### ISSUE TITLE
When I use the Multi-GPU in resnet50, it doesn't seem to work!

### ISSUE THREAD

**Issue by Gavince** [open-mmlab/mmclassification#10]
**commend**:  ./tools/dist_train.sh  configs/cifar10/resnet50.py  2

**Error**: subprocess.CalledProcessError: Command '['/home/xatu/anaconda2/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=14', 'configs/cifar10/resnet50.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by yl-1993** [comment]
Hi @Gavince , I suspect the true error is `ZeroDivisionError: integer division or modulo by zero`, which is raised by `torch.cuda.set_device(rank % num_gpus)` in mmcv.

Could you please post the full error message and check the CUDA setting?

**Comment by Gavince** [comment]
Thank you for your reply，I carefully found that the port was occupied. Now It run well when  I will post my the full error.

## ERROR:RuntimeError: Address already in use
