### ISSUE TITLE
How can I use information from layerCAM like if CAM show 4 dogs in the image I want to use this CAM information how can I do that?

### ISSUE THREAD

**Issue by noreenanwar** [open-mmlab/mmclassification#1006]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

\[here\]

### Post related information

1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
   \[here\]
2. Your config file if you modified it or created a new one.

```python
[here]
```

3. Your train log file if you meet the problem during training.
   \[here\]
4. Other code you modified in the `mmcls` folder.
   \[here\]

**Comment by Ezra-Yu** [comment]
please refer to [this doc](https://mmclassification.readthedocs.io/en/latest/tools/visualization.html#class-activation-map-visualization).

You have to know the dog id in your dataset.
```shell
python tools/visualizations/vis_cam.py \
    ${IMG} \
    ${CONFIG_FILE} \
    ${CHECKPOINT} \
    --method LayerCAM
    --target-category ${DOG_CATEGORY_INDEX_IN_YOUR_DATASET}
```

For example in ImageNet-1k dataset, '238' is the category of 'Greater Swiss Mountain dog'.

```shell
python tools/visualizations/vis_cam.py \
    demo/cat-dog.png configs/resnet/resnet50_8xb32_in1k.py \
    https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_batch256_imagenet_20200708-cfb998bf.pth \
    --method LayerCAM \
    --target-category 238
```

**Comment by noreenanwar** [comment]
But I want ID of all dogs in the image.I need image information like how many and where are these dogs in the image.

**Comment by Ezra-Yu** [comment]
> But I want ID of all dogs in the image. I need image information like how many and where are these dogs in the image. 

what does the 'ID' mean? CAM is just a tool to analyze the current model concerns. It can not help model to count and detect objects, which requires specific algorithms.

> How can I find the name of the category for the target layer ? 

I can not get the new issue question. If it is still about this question, I will close that and discuss in this issue.
