### ISSUE TITLE
[Feature] Accurate calculation of flops and parameters.

### ISSUE THREAD

**Issue by tonysy** [open-mmlab/mmclassification#1009]
### Describe the feature

Flops and paramters calculation 
- Backbone
- Overall 

### Motivation

A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when \[....\].
Ex2. There is a recent paper \[....\], which is very helpful for \[....\].

\[here\]

### Related resources

If there is an official code release or third-party implementation, please also provide the information here, which would be very helpful.

\[here\]

### Additional context

If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

\[here\]

**Comment by mzr1996** [comment]
Closed by #1000
