### ISSUE TITLE
Why the trained models are the same size with different input shape(train image size)?

### ISSUE THREAD

**Issue by wolfryu** [open-mmlab/mmclassification#1012]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

I have trained two models with different image size 80X80X3 and 80X160X3.
But the size of these trained models are the same.
I can not understand why, because the input image size is different, the layers' width of model should be different. 
So the model with image size  80X160X3 should be bigger than the model with image 80X80X3.
Is there any place fixed the image size, and resized each image input into model? 
How can I change the model to use raw image size without resize?   

### Post related information
the config file is:
```
_base_ = [
    '../_base_/models/mobilenet_v2_1x.py',
    '../_base_/schedules/imagenet_bs256_epochstep.py',
    '../_base_/default_runtime.py'
]

# ---- Model configs ----
# Here we use init_cfg to load pre-trained model.
# In this way, only the weights of backbone will be loaded.
# And modify the num_classes to match our dataset.

model = dict(
    backbone=dict(
        init_cfg = dict(
            type='Pretrained',
          checkpoint='https://download.openmmlab.com/mmclassification/v0/mobilenet_v2/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth',
            prefix='backbone')
    ),
    head=dict(
        num_classes=2,
        topk = (1, )
    ))

# ---- Dataset configs ----
# We re-organized the dataset as ImageNet format.
dataset_type = 'CustomDataset'


img_norm_cfg = dict(
     mean=[132.5028, 97.4147, 115.2442],
     std=[40.315, 62.0412, 33.2143],
     to_rgb=True)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]


```

**Comment by Ezra-Yu** [comment]
> I have trained two models with different image size 80X80X3 and 80X160X3. But the size of these trained models are the same.

Yes, the CNN models such as mobilenet and resnet, there are [GAP](https://github.com/open-mmlab/mmclassification/blob/90254a845540650bd03bc2b6108251825935c687/configs/_base_/models/resnet50.py#L10), a kind of neck. Take 2 examples:
If the input tensor is the shape of (3, 224, 224) and the output after the backbone is (1024, 7, 7), the GAP will flatten the last two dim and make the tensor to (1024, 1, 1);
If the input tensor is the shape of (3, 160, 1600) and the output after the backbone is (1024, 5, 50), the GAP will flatten the last two dim and make the tensor to (1024, 1, 1);

**YOU CAN ONLY NOT RESIZE DURING TEST(INFERENCE)!**

To Resize in the train and test, refer to [given example](https://github.com/open-mmlab/mmclassification/blob/master/configs/_base_/datasets/imagenet_bs32.py):
```
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomResizedCrop', size=224),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(256, -1)),  # not resize during the test
    dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
```

Not to Resize in test and resize in the train:
```
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomResizedCrop', size=224),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    # dict(type='Resize', size=(256, -1)),
    # dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]

```

**Comment by wolfryu** [comment]
> > I have trained two models with different image size 80X80X3 and 80X160X3. But the size of these trained models are the same.
> 
> Yes, the CNN models such as mobilenet and resnet, there are [GAP](https://github.com/open-mmlab/mmclassification/blob/90254a845540650bd03bc2b6108251825935c687/configs/_base_/models/resnet50.py#L10), a kind of neck. Take 2 examples: If the input tensor is the shape of (3, 224, 224) and the output after the backbone is (1024, 7, 7), the GAP will flatten the last two dim and make the tensor to (1024, 1, 1); If the input tensor is the shape of (3, 160, 1600) and the output after the backbone is (1024, 5, 50), the GAP will flatten the last two dim and make the tensor to (1024, 1, 1); Whether your input, the output of your result before GAP is (C, H, W), C is fixed. and H, W changes with the input, but after the GAP. the tensor will be the shape of (C, 1, 1), and then do the classification.
> 
> **YOU CAN ONLY NOT RESIZE DURING TEST(INFERENCE)!**
> 
> To Resize in the train and test, refer to [given example](https://github.com/open-mmlab/mmclassification/blob/master/configs/_base_/datasets/imagenet_bs32.py):
> 
> ```
> train_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='RandomResizedCrop', size=224),
>     dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='ImageToTensor', keys=['img']),
>     dict(type='ToTensor', keys=['gt_label']),
>     dict(type='Collect', keys=['img', 'gt_label'])
> ]
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='Resize', size=(256, -1)),  # not resize during the test
>     dict(type='CenterCrop', crop_size=224),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='ImageToTensor', keys=['img']),
>     dict(type='Collect', keys=['img'])
> ]
> ```
> 
> Not to Resize in test and resize in the train:
> 
> ```
> train_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='RandomResizedCrop', size=224),
>     dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='ImageToTensor', keys=['img']),
>     dict(type='ToTensor', keys=['gt_label']),
>     dict(type='Collect', keys=['img', 'gt_label'])
> ]
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     # dict(type='Resize', size=(256, -1)),
>     # dict(type='CenterCrop', crop_size=224),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='ImageToTensor', keys=['img']),
>     dict(type='Collect', keys=['img'])
> ]
> ```

Thank you so much for the detailed answers !!!
It helped a lot !!!
