### ISSUE TITLE
Can't reproduce the training log of Resnet18 for CIFAR10[Bug]

### ISSUE THREAD

**Issue by ThanatosShinji** [open-mmlab/mmclassification#1014]
### Describe the bug
As this [log](https://download.openmmlab.com/mmclassification/v0/resnet/resnet18_b16x8_cifar10_20210528-bd6371c8.log.json) shows,  after 20 epochs, the loss should be reduced to 0.2. 
And I tried to train ResNet18 with below cmd:
python .\tools\train.py .\configs\resnet\resnet18_8xb16_cifar10.py

Here is my training log: 
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 10000/10000, 2227.6 task/s, elapsed: 4s, ETA:     0s2022-09-05 18:26:37,203 - mmcls - INFO - Epoch(val) [68][625] accuracy_top-1: 83.7200, accuracy_top-5: 99.1100
2022-09-05 18:26:41,316 - mmcls - INFO - Epoch [69][100/3125]   lr: 1.000e-01, eta: 2:25:58, time: 0.041, data_time: 0.020, memory: 252, loss: 0.4175
2022-09-05 18:26:43,407 - mmcls - INFO - Epoch [69][200/3125]   lr: 1.000e-01, eta: 2:25:56, time: 0.021, data_time: 0.000, memory: 252, loss: 0.4350
2022-09-05 18:26:45,536 - mmcls - INFO - Epoch [69][300/3125]   lr: 1.000e-01, eta: 2:25:54, time: 0.021, data_time: 0.000, memory: 252, loss: 0.4165

That's way far from the 0.2 loss.

### To Reproduce

The command you executed.

```shell
python .\tools\train.py .\configs\resnet\resnet18_8xb16_cifar10.py
```

**Comment by Ezra-Yu** [comment]
this log is trained by using 8 GPUS, If you train in a single GPU, the log should be different.

**Comment by ThanatosShinji** [comment]
I don't get it. Will 8 GPUs backward 7 more times than a single GPU?

**Comment by Ezra-Yu** [comment]
No! But you can try to scale your batch_size

**Comment by ThanatosShinji** [comment]
Ok, I will try bs128.

**Comment by ThanatosShinji** [comment]
bs=128 1GPU produced a similar result. Thanks!
