### ISSUE TITLE
Hi, I just want to ask that can I get CAM results just for area where tracker is? like inside the Bounding box ?

### ISSUE THREAD

**Issue by noreenanwar** [open-mmlab/mmclassification#1021]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

\[here\]

### Post related information

1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
   \[here\]
2. Your config file if you modified it or created a new one.

```python
[here]
```

3. Your train log file if you meet the problem during training.
   \[here\]
4. Other code you modified in the `mmcls` folder.
   \[here\]

**Comment by Ezra-Yu** [comment]
It seems like a detection task.

If you know the box, just crop the area, vis the area, and put the vised picture in the ordinary image.
