### ISSUE TITLE
How to draw an accuracy chart？？

### ISSUE THREAD

**Issue by fakerlove1** [open-mmlab/mmclassification#1033]

**Comment by Ezra-Yu** [comment]
Can the `accuracy chart` be more specific?

**Comment by fakerlove1** [comment]
I want to map the accuracy rate through logs?

**Comment by fakerlove1** [comment]
> Can the `accuracy chart` be more specific?

I want to map the accuracy rate through logs?

**Comment by Ezra-Yu** [comment]
Is [this](https://mmclassification.readthedocs.io/en/latest/tools/analysis.html#log-analysis) what you want?

**Comment by fakerlove1** [comment]
> Is [this](https://mmclassification.readthedocs.io/en/latest/tools/analysis.html#log-analysis) what you want?

thank you.yes
