### ISSUE TITLE
Training model from scratch

### ISSUE THREAD

**Issue by AntonioVispi** [open-mmlab/mmclassification#1041]
Dear authors,
I'm trying to train a classification model from scratch, so I don't have to train only the head, but also the backbone. 
I tested your colab test code ( https://colab.research.google.com/github/open-mmlab/mmclassification/blob/master/docs/en/tutorials/MMClassification_python.ipynb ), in particular I tried to disable the 'pretrained' option of the backbone, initializing the weights in 'normal' mode, however even after tens of epochs, the model does not seem to improve. I have the impression that I have to insert a setting that makes the whole model train, not just the head. In the documentation I have found many examples on fine-tuning, but unfortunately I have not found much on complete scratch training, which is what I need.
Would you kindly have some advice for me?
Thanks in advance, have a nice day.

**Comment by Ezra-Yu** [comment]
just to remove this line in the collab tutorial:

```
# Load the pre-trained model's checkpoint.
cfg.model.backbone.init_cfg = dict(type='Pretrained', checkpoint=checkpoint_file, prefix='backbone')
```


in mmcls, we use `model.init_cfg` to specify how to init a model. if it is `None`, do torch default init; if it is a dict like [this link](https://github.com/open-mmlab/mmclassification/blob/8d1bc557ab25ad75c17091711629d684cbdba5b8/mmcls/models/backbones/resnet.py#L481), do custom init refer to [mmcv tutorial](https://mmcv.readthedocs.io/en/latest/understand_mmcv/cnn.html#weight-initialization); if it is a dict like  `dict(type='Pretrained', checkpoint=xxx_path, prefix='backbone')`, init from a checkpoint

**Comment by AntonioVispi** [comment]
Thank you so much; it worked! 

However, I had some problems in testing the trained model. I might ask what is the exact command to load the entire trained model, and then use it? it seems that when I reload my .pth file the weights are not trained. Could I have some clarification on this in terms of code?
Also, are there any differences between training a model with .png images versus .jpg images?
Thanks again.

**Comment by AntonioVispi** [comment]
Thank you very much.  Actually that's exactly what I did before you
answered me, I can also confirm that it worked.
