### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'pipeline'

### ISSUE THREAD

**Issue by root12321** [open-mmlab/mmclassification#1044]
`
    
    data = dict(
        shutil=True
        samples_per_gpu=32,#batch_size
        workers_per_gpu=8,
        train=dict(
    
            type='KFoldDataset',
            dataset=dict(
                type=dataset_type,
                data_prefix='/data/dataset/cifar/cifar-10-100n-main/',#***************
                ann_file='/data/dataset/cifar/cifar-10-100n-main/train_val_cifar100/test_all.txt',#****************
                pipeline=train_pipeline),
            fold=0,
            num_splits=5
            ),
        val=dict(
    
            type='KFoldDataset',
            dataset=dict(
                type=dataset_type,
                data_prefix='/data/dataset/cifar/cifar-10-100n-main/',#***************
                ann_file='/data/dataset/cifar/cifar-10-100n-main/train_val_cifar100/test_all.txt',#****************
                pipeline=test_pipeline),
            fold=0,
            num_splits=5),
        test=dict(
    
            type='KFoldDataset',
            dataset=dict(
                type=dataset_type,
                data_prefix='/data/dataset/cifar/cifar-10-100n-main/',#***************
                ann_file='/data/dataset/cifar/cifar-10-100n-main/train_val_cifar100/test_all.txt',#****************
                pipeline=test_pipeline),
            fold=0,
            num_splits=5))
`
这个是配置文件中数据的配置
运行交叉验证代码报错
`
python tools/kfold-cross-valid.py /home/leinao/zhangzhiyong/mmclassification-20220919/mmclassification-master/cifar100_Kfold/EfficientNetconfig.py --num-splits 5
`
报错讯息
![image](https://user-images.githubusercontent.com/28287748/190950891-79f6c353-3a66-4847-b256-a983c4b4c055.png)

**Comment by mzr1996** [comment]
To use `kfold-cross-valid.py`, you don't need to set `KFoldDataset` in the config file, refers to https://github.com/open-mmlab/mmclassification/pull/563

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
