### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by brilliant-soilder** [open-mmlab/mmclassification#1047]
一、训练完成，测试出错
When I test mine generated .pth, it shows an error as this "ValueError: need at least one array to concatenate", in File "F:\mmclassification-0.19.0\tools\test.py", line 199.

And I didn't find solution when search key words.

二、【测试时的报错信息】error information
(trt6) F:\mmclassification-0.19.0>python tools/test.py  configs/resnet/resnet50_cup.py  work_dirs/resnet50_cup/latest.pth --out work_dirs/results/result_resnet50_cup.json
load checkpoint from local path: work_dirs/resnet50_cup/latest.pth
completed: 0, elapsed: 0sTraceback (most recent call last):
  File "F:\mmclassification-0.19.0\tools\test.py", line 219, in <module>
    main()
  File "F:\mmclassification-0.19.0\tools\test.py", line 199, in main
    scores = np.vstack(outputs)
  File "<__array_function__ internals>", line 180, in vstack
  File "F:\anaconda\anzhuangweizhi\envs\trt6\lib\site-packages\numpy\core\shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

三、【环境信息】enviroments
sys.platform: win32
Python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: GeForce GTX 1650
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
NVCC: Not Available
GCC: n/a
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, 

TorchVision: 0.9.0
OpenCV: 4.6.0
MMCV: 1.4.0
MMCV Compiler: MSVC 192930145
MMCV CUDA Compiler: 10.2
MMClassification: 0.19.0+
------------------------------------------------------------

2022-09-20 16:24:31,998 - mmcls - INFO - Distributed training: False
2022-09-20 16:24:32,501 - mmcls - INFO - Config:
checkpoint_config = dict(interval=10)
log_config = dict(
    interval=50,
    hooks=[dict(type='TextLoggerHook'),
           dict(type='TensorboardLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1), ('val', 1)]
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(256, 256)),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(256, 256)),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
dataset_type = 'DATALOADER'
data = dict(
    samples_per_gpu=32,
    workers_per_gpu=2,
    train=dict(
        type='DATALOADER',
        data_prefix=
        'F:\mmcls\mmclassification\mmcls\datasets\data_apple\train\data',
        ann_file=
        'F:/mmcls/mmclassification/mmcls/datasets/data_apple/train/train_ann.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=(256, 256)),
            dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='ToTensor', keys=['gt_label']),
            dict(type='Collect', keys=['img', 'gt_label'])
        ]),
    val=dict(
        type='DATALOADER',
        data_prefix=
        'F:\mmcls\mmclassification\mmcls\datasets\data_apple\val\data',
        ann_file=
        'F:\mmcls\mmclassification\mmcls\datasets\data_apple\val\val_ann.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=(256, 256)),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ]),
    test=dict(
        type='DATALOADER',
        data_prefix=
        'F:\mmcls\mmclassification\mmcls\datasets\data_apple\test\data',
        ann_file=
        'F:\mmcls\mmclassification\mmcls\datasets\data_apple\test\test_ann.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=(256, 256)),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ]))
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNeSt',
        depth=50,
        num_stages=4,
        out_indices=(3, ),
        style='pytorch'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=2,
        in_channels=2048,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5)))
optimizer = dict(type='SGD', lr=0.001, momentum=1, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='cyclic',
    target_ratio=(10, 0.0001),
    cyclic_times=150,
    step_ratio_up=0.5)
momentum_config = dict(
    policy='cyclic',
    target_ratio=(0.85, 0.95),
    cyclic_times=150,
    step_ratio_up=0.5)
runner = dict(type='EpochBasedRunner', max_epochs=150)
evaluation = dict(
    interval=1,
    metric='accuracy',
    metric_options=dict(topk=(1, )),
    save_best='auto',
    start=1)
work_dir = 'F:/mmclassification-0.19.0/work_dirs/resnet50_cup'
gpu_ids = range(0, 1)

2022-09-20 16:24:32,503 - mmcls - INFO - Set random seed to 226849921, deterministic: False
2022-09-20 16:24:32,763 - mmcls - INFO - initialize ResNeSt with init_cfg [{'type': 'Kaiming', 'layer': ['Conv2d']}, {'type': 'Constant', 'val': 1, 'layer': ['_BatchNorm', 'GroupNorm']}]
2022-09-20 16:24:32,949 - mmcls - INFO - initialize LinearClsHead with init_cfg {'type': 'Normal', 'layer': 'Linear', 'std': 0.01}
Name of parameter - Initialization information

四、【配置】
I made self-dataset as "Filelist"
_base_ = ['../_base_/default_runtime.py']
#################################models_setting

# model settings
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(3, ),
        style='pytorch'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=2,
        in_channels=2048,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5),
    ))

####################################datasets

# dataset settings
# dataset_type = 'ImageNet'
dataset_type = "Filelist"
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomResizedCrop', size=224),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(256, -1)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
data = dict(
    samples_per_gpu=8,
    # workers_per_gpu=2,
    workers_per_gpu=1,
    train=dict(
        type=dataset_type,
        # data_prefix='data/imagenet/train',
        data_prefix=R'F:\mmclassification-0.19.0\mmcls\datasets\data_apple\Tiao_pian_out2\train',
        # data_prefix=R"F:\mmcls\mmclassification\mmcls\datasets\data_apple\train\data",
        ann_file=R'F:\mmclassification-0.19.0\mmcls\datasets\data_apple\Tiao_pian_out2\meta\train.txt',
        # ann_file="F:/mmcls/mmclassification/mmcls/datasets/data_apple/train/train_ann.txt",
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        data_prefix=R'F:\mmclassification-0.19.0\mmcls\datasets\data_apple\Tiao_pian_out2\val',
        ann_file=R'F:\mmclassification-0.19.0\mmcls\datasets\data_apple\Tiao_pian_out2\meta\val.txt',
        pipeline=test_pipeline),
    test=dict(
        # replace `data/val` with `data/test` for standard test
        type=dataset_type,
        data_prefix=R'F:\mmclassification-0.19.0\mmcls\datasets\data_apple\test\data',
        ann_file=R'F:\mmclassification-0.19.0\mmcls\datasets\data_apple\test\test_ann.txt',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='accuracy')

###################################schedules
# optimizer
optimizer = dict(
    type='SGD', lr=0.8, momentum=0.9, weight_decay=0.0001, nesterov=True)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=2500,
    warmup_ratio=0.25,
    step=[30, 60, 90])
runner = dict(type='EpochBasedRunner', max_epochs=100)

##############################default_runtime
# checkpoint saving
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=100,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable

dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]

**Comment by mzr1996** [comment]
It looks like it's because your dataset doesn't work. And the `tools/test.py` cannot read any samples to predict.

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
