### ISSUE TITLE
意思是不接受pr吗

### ISSUE THREAD

**Issue by Fei-Wang** [open-mmlab/mmclassification#1057]
### Prerequisite

- [X] I have searched related issues but cannot get the expected help.
- [X] I have read [the documentation](https://mmclassification.readthedocs.io/) and don't know what to do.

### Describe the question

提了pr根本没人看？？？
https://github.com/open-mmlab/mmclassification/pull/856
https://github.com/open-mmlab/mmclassification/pull/857

**Comment by tonysy** [comment]
Sorry for the late reply first. We appreciate your contributions sincerely.  We set the bot to remind the PR, which only be activated when assigned the Reviewers, and then we can receive the notification. We will follow these two PRs quickly and update the contribution guide. 

Thanks again.
