### ISSUE TITLE
FileList(Dataset)

### ISSUE THREAD

**Issue by ZhenYiRan** [open-mmlab/mmclassification#1060]
### 我已试图查询该问题

- [X] 我已经查阅了相关 issue，没有找到相关帮助。
- [X] 我已经查询了[官方文档](https://mmclassification.readthedocs.io/zh_CN/master/)，没有找到相关帮助。

### 描述该问题

1.在自定义数据集中，创建自己的数据集类FileList，需要提供filename, gt_label，但是在推理的时候仅能提供filename参数，会报错，请问应该怎么解决？
![Image 1](https://user-images.githubusercontent.com/114554897/192689524-45902ac1-687d-413a-9176-515165f6d6ac.png)
![Image 2](https://user-images.githubusercontent.com/114554897/192689564-cd336dcc-b783-4048-947a-3004029b5832.png)
![Image 3](https://user-images.githubusercontent.com/114554897/192689567-c4ee9dac-23b0-4368-a49b-5b6adb246a41.png)

**Comment by Ezra-Yu** [comment]
Does your test dataset have target information?

**Comment by ZhenYiRan** [comment]
> 

hi Yu，I guess my dataset have target info, here are my config file and my test data. 
Is it right? Thanks!!!
![Image 4](https://user-images.githubusercontent.com/114554897/192712287-1f7e8947-455b-43c5-bff9-1fdcf3f0f09d.png)
![Image 5](https://user-images.githubusercontent.com/114554897/192712390-4690e547-bda4-43a5-bda6-34af3356fb82.png)

**Comment by GoblinsWang** [comment]
> > 
> 
> hi Yu，I guess my dataset have target info, here are my config file and my test data. Is it right? Thanks!!! ![Image 4](https://user-images.githubusercontent.com/114554897/192712287-1f7e8947-455b-43c5-bff9-1fdcf3f0f09d.png) ![Image 5](https://user-images.githubusercontent.com/114554897/192712390-4690e547-bda4-43a5-bda6-34af3356fb82.png)
your annfile don't have target info, it's only filename.

**Comment by ZhenYiRan** [comment]
> 

hi wang, thanks for your commemt.
I want to ask what the target info should be.
Can you show me? Thanks!!!!!!

**Comment by Ezra-Yu** [comment]
in your `classes.txt`, should be 
```
Class_A 0
Class_B 1
.......
```

in your `ann_file.txt`, should be 
```
samper0.jpg 0  # it class label should be Class_A 
samper2.jpg 0
samper3.jpg 1  # it class label should be Class_B
samper4.jpg 0
xxxxxx
```

**Comment by Ezra-Yu** [comment]
The data format you use can use [`CustomDataset`](https://mmclassification.readthedocs.io/en/latest/tutorials/new_dataset.html#reorganize-dataset-to-existing-format) directly, you don't need to write data classes yourself.

**Comment by ZhenYiRan** [comment]
> 

Thanks Yu! My classes.txt just like these
Class_A
Class_B ...
I thought it may conbine with the index or something.
Thanks a lot! I would try again!
Have a nice day!!!

**Comment by ZhenYiRan** [comment]
> The data format you use can use [`CustomDataset`](https://mmclassification.readthedocs.io/en/latest/tutorials/new_dataset.html#reorganize-dataset-to-existing-format) directly, you don't need to write data classes yourself.

Hi, Yu. After receiving your advice, I change my classes.txt. But it still doesn't work.
When I try test a single img, it works! haha. 
I guess something wrong with the filelist. 
When the test file with label, it can work out, and with label it can't
![image](https://user-images.githubusercontent.com/114554897/192755461-b6b37c1b-ca27-42ee-85fc-aae5d4b75b19.png)

**Comment by mzr1996** [comment]
The `FileList` dataset is used for training and testing, which requires ground truth to calculate the loss or metrics.
To inference images without labels, using `mmcls.apis.inference_model` is the right way.
