### ISSUE TITLE
How to get inference time and FPS on v1.0.0?

### ISSUE THREAD

**Issue by okotaku** [open-mmlab/mmclassification#1069]
### Prerequisite

- [X] I have searched related issues but cannot get the expected help.
- [X] I have read [the documentation](https://mmclassification.readthedocs.io/) and don't know what to do.

### Describe the question

I ran tools/test.py on v1.0.0 and found progress bar was deleted.
But on [this PR](https://github.com/open-mmlab/mmclassification/pull/1064) inference time and FPS are shown.
So there is other way?

Related issue.
https://github.com/open-mmlab/mmclassification/issues/657

**Comment by mzr1996** [comment]
We are developing a benchmark repository to test the performance on various devices, but it's still a private repository.
Moreover, our [dev scripts](https://github.com/open-mmlab/mmclassification/blob/dev-1.x/.dev_scripts/benchmark_regression/1-benchmark_valid.py) support measuring the inference time. For example, you can measure all ShuffleNet inference time with batch size 16 by the below command:
```bash
python .dev_scripts/benchmark_regression/1-benchmark_valid.py --models shufflenet --inference-time --batch-size 16
```
and the output should be
![image](https://user-images.githubusercontent.com/26739999/194685345-efab802c-3ea3-45e7-8f5d-90e1f6fcfcba.png)

**Comment by okotaku** [comment]
@mzr1996 Thank you!

**Comment by wsy-yjys** [comment]
Each line of data below is the result of averaging 100 by using model inference, but the result still fluctuates. Which value should I take?
```
# {'fps': 63.5, 'time_mean': 15.7, 'time_std': 0.5}
# {'fps': 62.8, 'time_mean': 15.9, 'time_std': 0.1}
# {'fps': 64.9, 'time_mean': 15.4, 'time_std': 0.2}
# {'fps': 63.6, 'time_mean': 15.7, 'time_std': 0.1}
# {'fps': 64.5, 'time_mean': 15.5, 'time_std': 0.1}
# {'fps': 64.1, 'time_mean': 15.6, 'time_std': 0.2}
# {'fps': 61.2, 'time_mean': 16.3, 'time_std': 0.1}
# {'fps': 62.2, 'time_mean': 16.1, 'time_std': 0.1}
# {'fps': 63.7, 'time_mean': 15.7, 'time_std': 0.4}
# {'fps': 65.0, 'time_mean': 15.4, 'time_std': 0.1}
# {'fps': 63.9, 'time_mean': 15.7, 'time_std': 0.1}
# {'fps': 63.9, 'time_mean': 15.7, 'time_std': 0.1}
# {'fps': 61.1, 'time_mean': 16.4, 'time_std': 0.5}
# {'fps': 64.2, 'time_mean': 15.6, 'time_std': 0.7}
```
