### ISSUE TITLE
mim install mmengine "mmcv-full>=2.0rc0"

### ISSUE THREAD

**Issue by xingzhe996** [open-mmlab/mmclassification#1077]
### 我已试图查询该问题

- [X] 我已经查阅了相关 issue，没有找到相关帮助。
- [X] 我已经查询了[官方文档](https://mmclassification.readthedocs.io/zh_CN/master/)，没有找到相关帮助。

### 描述该问题

mim install mmengine "mmcv-full>=2.0rc0"

full版本并没有后2.0rc0，好好检查检查

**Comment by mzr1996** [comment]
抱歉，这里没有及时更新，已经修复了，https://github.com/open-mmlab/mmclassification/commit/f452e242a7b9038aaf87ed16f05c784e7c02950f

**Comment by xingzhe996** [comment]
感谢您的回复
