### ISSUE TITLE
输入为灰度图的时候，随机增强里面的Translate出错

### ISSUE THREAD

**Issue by xingzhe996** [open-mmlab/mmclassification#1079]
### 我已试图查询该问题

- [X] 我已经查阅了相关 issue，没有找到相关帮助。
- [X] 我已经查询了[官方文档](https://mmclassification.readthedocs.io/zh_CN/master/)，没有找到相关帮助。

### 描述该问题

输入为灰度图的时候，随机增强里面的Translate出错
#################以下是代码
img_norm_cfg = dict(
    mean=[11.0047], std=[18.3813])
train_pipeline = [
    dict(type='LoadImageFromFile', color_type=IMREAD_GRAYSCALE),
    # dict(type='RandomGrayscale', gray_prob=1),#灰度化
    # dict(type='RandomResizedCrop', size=224, backend='pillow', interpolation='bicubic'),
    dict(type='Resize', size=(224, -1), backend='pillow', interpolation='bicubic'),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(
            type='RandAugment',
            policies={{_base_.rand_increasing_policies}},
            num_policies=2,
            total_level=10,
            magnitude_level=6,
            magnitude_std=0.5,
            hparams=dict(
                pad_val=[round(x) for x in img_norm_cfg['mean'][::-1]],
                interpolation='bicubic')),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
###############################
运行后会有错误如下
AssertionError: Translate: pad_val as a tuple must have 3 elements, got 1 instead.
##################
请问应该如何处理这种情况？
另外用mmcls.datasets.pipelines.Rotate进行旋转增强时为什么angle只能输入一个值？torch里面可以输入一个范围啊？
例如使用dict(type='Rotate', angle=[-30.0, 30.0])，出现
Rotate: The angle type must be float, but got <class 'list'> instead.

**Comment by mzr1996** [comment]
看起来 Translate 在设计时仅考虑了三维图像，但其实是没有必要的，只需要把
https://github.com/open-mmlab/mmclassification/blob/91b85bb4a5df075ae2690273da32819b298e4395/mmcls/datasets/pipelines/auto_augment.py#L343-L351
这几行删掉
https://github.com/open-mmlab/mmclassification/blob/91b85bb4a5df075ae2690273da32819b298e4395/mmcls/datasets/pipelines/auto_augment.py#L360
这一行改成 `self.pad_val=pad_val`
就可以了。

另外 `Rotate` 和 `Translate` 这些变换操作在添加之初并不是独立存在的，他们都是作为 `RandAugment` 或者 `AutoAugment` 这种组合增强的一部分使用的。像是 RandAugment 本身就会每次生成不同的幅度，所以没有支持范围内随机幅度。

**Comment by xingzhe996** [comment]
非常感谢您的回答

**Comment by xingzhe996** [comment]
您好，我按照修改Translate 的方法修改了[auto_augment.py](https://github.com/open-mmlab/mmclassification/blob/91b85bb4a5df075ae2690273da32819b298e4395/mmcls/datasets/pipelines/auto_augment.py#L343-L351)中的Rotate 方法，传入灰度图，做随机增强的时候会出现如下的错误
ValueError: Invalid type <class 'list'> for `border_value`.
请问应该如何修改呢？
`        for key in results.get('img_fields', ['img']):
            img = results[key]
            img_rotated = mmcv.imrotate(
                img,
                angle,
                center=self.center,
                scale=self.scale,
                **border_value=self.pad_val,**
                interpolation=self.interpolation)
            results[key] = img_rotated.astype(img.dtype)
        return results`

**Comment by mzr1996** [comment]
我之前以为你的灰度图 pad_val 传的是一个数字，如果是个 list 的话，那就把
https://github.com/open-mmlab/mmclassification/blob/91b85bb4a5df075ae2690273da32819b298e4395/mmcls/datasets/pipelines/auto_augment.py#L360
这一行改回来

**Comment by xingzhe996** [comment]
非常感谢您的回答
