### ISSUE TITLE
how calculate the accuracy of different class?

### ISSUE THREAD

**Issue by xlgong** [open-mmlab/mmclassification#1085]
### 我已试图查询该问题

- [X] 我已经查阅了相关 issue，没有找到相关帮助。
- [X] 我已经查询了[官方文档](https://mmclassification.readthedocs.io/zh_CN/master/)，没有找到相关帮助。

### 描述该问题

I want to calculate the accuracy of different class, but I don't know how, I need help.

**Comment by mzr1996** [comment]
See https://github.com/open-mmlab/mmclassification/issues/598

**Comment by tonysy** [comment]
@mzr1996 Maybe we can convert these two issues to discussion?

**Comment by xlgong** [comment]
> 

Thank you。
