### ISSUE TITLE
A minor issue of non-ASCII character

### ISSUE THREAD

**Issue by caiqi** [open-mmlab/mmclassification#109]
It looks like there is a non-ASCII character in this Line

https://github.com/open-mmlab/mmclassification/blob/master/mmcls/models/backbones/lenet.py#L11

and it will cause an error in some cases. Would it be better to replace with a normal 'X'?

**Comment by wangruohui** [comment]
Hello, as this is an minor issue, you can submit a pull requests for it. Moreover, would you plase describe the error you met with?

**Comment by tonysy** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you still encounter this issue with the latest stable version. You can also contribute directly by creating a PR

Thank you!
