### ISSUE TITLE
[Feature] Support DaViT

### ISSUE THREAD

**Issue by okotaku** [open-mmlab/mmclassification#1096]
### Describe the feature

paper: https://arxiv.org/pdf/2204.03645.pdf
code: https://github.com/dingmyu/davit

### Will you implement it?

- [X] I would like to implement this feature and create a PR!

**Comment by Ezra-Yu** [comment]
Thank you for your suggestion. We will consider adding this backbone. Community contributions are also welcome.

**Comment by okotaku** [comment]
I plan to make a PR!
