### ISSUE TITLE
Test on imagenet

### ISSUE THREAD

**Issue by xiaozr** [open-mmlab/mmclassification#11]
How to generate val.txt for testing on imagenet dataset.
I get this from ILSVRC2012_validation_ground_truth.txt and subtract 1 from each class id，because 1000 is out of class range.

This is my val.txt,
![image](https://user-images.githubusercontent.com/25071151/88031018-95e6e680-cb6e-11ea-9bc6-0b01af2cbdfc.png)

The top acc is very low by using the pretrained model of mobilenet_v2_batch256_20200708-3d2dc3af.pth
![image](https://user-images.githubusercontent.com/25071151/88031798-b1062600-cb6f-11ea-9a7c-aefb74b8ebd3.png)

**Comment by yl-1993** [comment]
Hi @xiaozr , there are mainly two versions of ground-truth for ImageNet. Our model is currently trained with the version provided by BVLC. You can download the validation list through [get_ilsvrc_aux.sh](https://github.com/BVLC/caffe/blob/master/data/ilsvrc12/get_ilsvrc_aux.sh).

**Comment by xiaozr** [comment]
@yl-1993 thanks for your reply. I will try it.
