### ISSUE TITLE
[Feature] Pretrained model?

### ISSUE THREAD

**Issue by chen-del** [open-mmlab/mmclassification#1121]
### 分支

1.x 分支 (1.0.0rc2 或其他 1.x 版本)

### 描述该功能

I see that moblinetv3 only provides a pre-trained model of 1.0. Can you provide more pre-trained models with different scaling factors of 0.75 and 0.5?

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 MMClassification 贡献代码！

**Comment by yingfhu** [comment]
Sure, we will add more pretrains of 0.75 with priority, since official has only released 1.0 and 0.75. 
0.5 needs to trained from scratch, hence will be considered in the future.

**Comment by yingfhu** [comment]
refers to https://github.com/open-mmlab/mmclassification/pull/1154, update with branch dev-1.x for more pretrains,
