### ISSUE TITLE
[Bug] 404 docs

### ISSUE THREAD

**Issue by sanbuphy** [open-mmlab/mmclassification#1165]
### Branch

1.x branch (1.0.0rc2 or other 1.x version)

### Describe the bug

能不能干脆把所有还没指定跳转的 有跳转功能的（比如某个页面切换英文文档都重定向到英文文档的开头 省事也避免报错)
Can you simply all have not specified the jump jump function (such as a page switch to the English document are redirected to the beginning of the English document to save time and avoid reporting errors)

### Environment

like this : https://mmclassification.readthedocs.io/zh_CN/latest/install.html
if you use `read the docs` to change version to dev-1.x,you can see 404 error page.

**Comment by mzr1996** [comment]
Thanks for the suggestion! Now you can try your example again, and it should work.
I will configure all redirection from old docs to new docs later.

**Comment by sanbuphy** [comment]
> Thanks for the suggestion! Now you can try your example again, and it should work. I will configure all redirection from old docs to new docs later.

Thank you so much.

**Comment by mzr1996** [comment]
Solved by #1207
