### ISSUE TITLE
[Feature] Support Sub-center ArcFace

### ISSUE THREAD

**Issue by okotaku** [open-mmlab/mmclassification#1169]
### Branch

1.x branch (1.0.0rc2 or other 1.x version)

### Describe the feature

paper: https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123560715.pdf
github: https://github.com/deepinsight/insightface

### Will you implement it?

- [x] I would like to implement this feature and create a PR!

**Comment by Ezra-Yu** [comment]
I have implemented a version based on the current arcface, but due to some recent affairs, I need to wait some days to submit up, I hope you can review that. @okotaku

**Comment by okotaku** [comment]
@Ezra-Yu Thank you, I got it!

**Comment by Ezra-Yu** [comment]
I have tried to support `ArcFaceClsHeadAdaptiveMargin`. But I'm not sure that having the user generate and pass in a category-freq file is a friendly way to use it. Or is there another way to support that?

**Comment by okotaku** [comment]
@Ezra-Yu 
I have only used the method using category-freq file. So I don't know of any good way to do it.
How about `SetAdaptiveMarginHook` like following my dirty example.

```
class SetAdaptiveMarginHook(Hook):
    def before_train(self, runner):
        """Check whether the training dataset is compatible with head.
        Args:
            runner (obj: `IterBasedRunner`): Iter based Runner.
        """
        gt_labels = runner.train_dataloader.dataset. get_gt_labels()
        runner.model.head.set_margin(gt_labels)

class ArcFaceAdaptiveMarginClsHead(ArcFaceClsHead):
    def __init__(self):
        # margins = zeros num_classes  # dummy value for load state dict
        self.register_buffer('margins', margins)

    def set_margin(self, gt_labels):
        # margins = calculate from gt_labels
        self.register_buffer('margins', margins)
```

**Comment by Ezra-Yu** [comment]
:+1: This is an option worth considering

**Comment by okotaku** [comment]
@Ezra-Yu  Is there any plans to support other metric learning architecture like CurricularFace, AdaFace, CosFace, etc...?

**Comment by Ezra-Yu** [comment]
@okotaku  Frankly, it was not in our plan by the end of recent years; we plan to add some algorithms about the long-tail problem in the rest of the year.

**Comment by Ezra-Yu** [comment]
sub-center arcface has been supported in https://github.com/open-mmlab/mmclassification/pull/1181
