### ISSUE TITLE
[Bug] tools/dist_test.sh can't strat distributed test

### ISSUE THREAD

**Issue by xzh929** [open-mmlab/mmclassification#1185]
### 分支

master 分支 (0.24 或其他 0.x 版本)

### 描述该错误

when i launch this script after training finished, something happened.
this is my command:./tools/dist_test.sh vgg16/vgg16_b16x8_voc.py vgg16/epoch_40.pth 4 --metrics mAP --out vgg16_test2.json
the error shows: 
File "./tools/test.py", line 246, in <module>
    main()
  File "./tools/test.py", line 201, in main
        main()broadcast_buffers=False)
 File "/mmcls/utils/distribution.py", line 64, in wrap_distributed_model
    model.cuda(), *args, device_ids=[current_device()], **kwargs)
TypeError: ABCMeta object got multiple values for keyword argument 'device_ids'

### 环境信息

{   'CUDA available': True,
    'CUDA_HOME': '/usr/local/cuda',
    'GCC': 'gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0',
    'GPU 0,1,2,3': 'Tesla P40',
    'MMCV': '1.6.2',
    'MMCV CUDA Compiler': '10.2',
    'MMCV Compiler': 'GCC 7.3',
    'MMClassification': '0.24.1+',
    'NVCC': 'Cuda compilation tools, release 10.2, V10.2.8',
    'OpenCV': '4.6.0',
    'PyTorch': '1.10.1+cu102',
    'PyTorch compiling details': 'PyTorch built with:\n'
                                 '  - GCC 7.3\n'
                                 '  - C++ Version: 201402\n'
                                 '  - Intel(R) oneAPI Math Kernel Library '
                                 'Version 2021.2-Product Build 20210312 for '
                                 'Intel(R) 64 architecture applications\n'
                                 '  - Intel(R) MKL-DNN v2.2.3 (Git Hash '
                                 '7336ca9f055cf1bfa13efb658fe15dc9b41f0740)\n'
                                 '  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n'
                                 '  - LAPACK is enabled (usually provided by '
                                 'MKL)\n'
                                 '  - NNPACK is enabled\n'
                                 '  - CPU capability usage: AVX2\n'
                                 '  - CUDA Runtime 10.2\n'
                                 '  - NVCC architecture flags: '
                                 '-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70\n'
                                 '  - CuDNN 7.6.5\n'
                                 '  - Magma 2.5.2\n'
                                 '  - Build settings: BLAS_INFO=mkl, '
                                 'BUILD_TYPE=Release, CUDA_VERSION=10.2, '
                                 'CUDNN_VERSION=7.6.5, '
                                 'CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, '
                                 'CXX_FLAGS= -Wno-deprecated '
                                 '-fvisibility-inlines-hidden '
                                 '-DUSE_PTHREADPOOL -fopenmp -DNDEBUG '
                                 '-DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK '
                                 '-DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK '
                                 '-DSYMBOLICATE_MOBILE_DEBUG_HANDLE '
                                 '-DEDGE_PROFILER_USE_KINETO -O2 -fPIC '
                                 '-Wno-narrowing -Wall -Wextra '
                                 '-Werror=return-type '
                                 '-Wno-missing-field-initializers '
                                 '-Wno-type-limits -Wno-array-bounds '
                                 '-Wno-unknown-pragmas -Wno-sign-compare '
                                 '-Wno-unused-parameter -Wno-unused-variable '
                                 '-Wno-unused-function -Wno-unused-result '
                                 '-Wno-unused-local-typedefs '
                                 '-Wno-strict-overflow -Wno-strict-aliasing '
                                 '-Wno-error=deprecated-declarations '
                                 '-Wno-stringop-overflow -Wno-psabi '
                                 '-Wno-error=pedantic '
                                 '-Wno-error=redundant-decls '
                                 '-Wno-error=old-style-cast '
                                 '-fdiagnostics-color=always -faligned-new '
                                 '-Wno-unused-but-set-variable '
                                 '-Wno-maybe-uninitialized -fno-math-errno '
                                 '-fno-trapping-math -Werror=format '
                                 '-Wno-stringop-overflow, LAPACK_INFO=mkl, '
                                 'PERF_WITH_AVX=1, PERF_WITH_AVX2=1, '
                                 'PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, '
                                 'USE_CUDA=ON, USE_CUDNN=ON, '
                                 'USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, '
                                 'USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, '
                                 'USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, '
                                 'USE_OPENMP=ON, \n',
    'Python': '3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]',
    'TorchVision': '0.11.2+cu102',
    'sys.platform': 'linux'}

### 其他信息

i delete the parameter which is in tools/test.py line 200 :device_ids=[int(os.environ['LOCAL_RANK'])],then it can run.Because i find that the same function in train did not has this parameter

**Comment by mzr1996** [comment]
Get it, I will fix it soon.

**Comment by IncludeMathH** [comment]
I have the same problem. The code works properly when the parameter `device_ids` is commented out.

**Comment by mzr1996** [comment]
Closed by @1215
