### ISSUE TITLE
[Bug] resnet18 train error

### ISSUE THREAD

**Issue by jiangyangbo** [open-mmlab/mmclassification#1194]
### 分支

master 分支 (0.24 或其他 0.x 版本)

### 描述该错误

a resnet18 train error , 
the code is :  python tools/train.py configs/resnet/restnet18_b32x8_imagenet.py 
and a error is as following:

2022-11-12 20:13:13,052 - mmcls - INFO - Set random seed to 21485187, deterministic: False
Traceback (most recent call last):
  File "/home/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/workspace/Attention_project/mmclassification/mmcls/models/backbones/resnet.py", line 616, in __init__
    plugins=plugins)
  File "/home/workspace/Attention_project/mmclassification/mmcls/models/backbones/resnet.py", line 628, in make_res_layer
    return ResLayer(**kwargs)
  File "/home/workspace/Attention_project/mmclassification/mmcls/models/backbones/resnet.py", line 464, in __init__
    **kwargs))
TypeError: __init__() got an unexpected keyword argument 'plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/workspace/Attention_project/mmclassification/mmcls/models/classifiers/image.py", line 22, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/workspace/Attention_project/mmclassification/mmcls/models/builder.py", line 19, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: ResNet: __init__() got an unexpected keyword argument 'plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 203, in <module>
    main()
  File "tools/train.py", line 173, in main
    model = build_classifier(cfg.model)
  File "/home/workspace/Attention_project/mmclassification/mmcls/models/builder.py", line 38, in build_classifier
    return CLASSIFIERS.build(cfg)
  File "/home/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: ImageClassifier: ResNet: __init__() got an unexpected keyword argument 'plugins'

### 环境信息

{'sys.platform': 'linux', 'Python': '3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]', 'CUDA available': True, 'GPU 0,1,2,3': 'NVIDIA GeForce RTX 3080 Ti', 'CUDA_HOME': '/usr/local/cuda', 'NVCC': 'Build cuda_11.1.TC455_06.29069683_0', 'GCC': 'gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0', 'PyTorch': '1.8.2+cu111', 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.1\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86\n  - CuDNN 8.0.5\n  - Magma 2.5.2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, \n', 'TorchVision': '0.9.2+cu111', 'OpenCV': '4.5.5', 'MMCV': '1.4.5', 'MMCV Compiler': 'GCC 7.3', 'MMCV CUDA Compiler': '11.1', 'MMClassification': '0.23.0+7c5ddb1'}

**Comment by jiangyangbo** [comment]
but Resnet-50 and Resnet-101 are ok,not Resnet18 andResnet-34 are not.



---Original---
From: ***@***.***&gt;
Date: Mon, Nov 14, 2022 10:05 AM
To: ***@***.***&gt;;
Cc: "yangbo ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmclassification] [Bug] resnet18 train error (Issue#1194)




 
the Resnet in mmcls does not support 'plugins' now.

**Comment by Ezra-Yu** [comment]
Yes, Since the [BasicBlock](https://github.com/open-mmlab/mmclassification/blob/0eb3b61fc5a408b1e9fa3e6dcfb40a7628cd1dcb/mmcls/models/backbones/resnet.py#L17) for ResNet18 has not supported the 'plugins'. But the [BottleNeck](https://github.com/open-mmlab/mmclassification/blob/0eb3b61fc5a408b1e9fa3e6dcfb40a7628cd1dcb/mmcls/models/backbones/resnet.py#L136) for ResNet50 has supported the 'plugins'.

**Comment by jiangyangbo** [comment]
But mmcls with 0.24.1 , mmcv with 1.7.1 for Resnet18 is okay.



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 17, 2022 10:45 AM
To: ***@***.***&gt;;
Cc: "yangbo ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmclassification] [Bug] resnet18 train error (Issue#1194)




 
Yes, Since the BasicBlock for ResNet18 has not supported the 'plugins'. But the BottleNeck for ResNet50 has supported the 'plugins'.

**Comment by Ezra-Yu** [comment]
Can you show your config?

**Comment by Ezra-Yu** [comment]
I have checked the src code,  The [`ResNet`](https://github.com/open-mmlab/mmclassification/blob/0eb3b61fc5a408b1e9fa3e6dcfb40a7628cd1dcb/mmcls/models/backbones/resnet.py#L402) in mmcls does not support the  attribute 'plugins', And the [ResNet](https://github.com/open-mmlab/mmsegmentation/blob/180ad0882426f5721cb85978a6a01ba9d27e7795/mmseg/models/backbones/resnet.py#L311) in mmdet and mmseg only support the [BottleNeck](https://github.com/open-mmlab/mmsegmentation/blob/180ad0882426f5721cb85978a6a01ba9d27e7795/mmseg/models/backbones/resnet.py#L99) with 'plugins';

![image](https://user-images.githubusercontent.com/18586273/202351423-72f6770b-ef49-4887-b3dd-2fd731f0a847.png)

And I run these code in mmdet. Get ResNet18 have not support the  'plugins' and the ResNet50 with  'plugins'  is OK.

**Comment by jiangyangbo** [comment]
> I have checked the src code, The [`ResNet`](https://github.com/open-mmlab/mmclassification/blob/0eb3b61fc5a408b1e9fa3e6dcfb40a7628cd1dcb/mmcls/models/backbones/resnet.py#L402) in mmcls does not support the attribute 'plugins', And the [ResNet](https://github.com/open-mmlab/mmsegmentation/blob/180ad0882426f5721cb85978a6a01ba9d27e7795/mmseg/models/backbones/resnet.py#L311) in mmdet and mmseg only support the [BottleNeck](https://github.com/open-mmlab/mmsegmentation/blob/180ad0882426f5721cb85978a6a01ba9d27e7795/mmseg/models/backbones/resnet.py#L99) with 'plugins';
> 
> ![image](https://user-images.githubusercontent.com/18586273/202351423-72f6770b-ef49-4887-b3dd-2fd731f0a847.png)
> 
> And I run these code in mmdet. Get ResNet18 have not support the 'plugins' and the ResNet50 with 'plugins' is OK.

You are right.
