### ISSUE TITLE
how to do inference

### ISSUE THREAD

**Issue by GoldenAbel** [open-mmlab/mmclassification#12]
how to do inference with fine-tuned model

**Comment by yl-1993** [comment]
Hi @GoldenAbel , please refer to [getting_started.md](https://github.com/open-mmlab/mmclassification/blob/master/docs/getting_started.md#test-a-dataset) to checkout how to test a dataset.

**Comment by GoldenAbel** [comment]
> Hi @GoldenAbel , please refer to [getting_started.md](https://github.com/open-mmlab/mmclassification/blob/master/docs/getting_started.md#test-a-dataset) to checkout how to test a dataset.

thank for your reply. but not test, i got the fine-tuned model,  how to do reference?  i noticed the  functions in mmcls/apis/inference.py have not been implemented.

**Comment by yl-1993** [comment]
@GoldenAbel Good catch, thanks. We will implement the model inference through PR https://github.com/open-mmlab/mmclassification/pull/16
