### ISSUE TITLE
Add a new loss

### ISSUE THREAD

**Issue by Qingyuncookie** [open-mmlab/mmclassification#121]
I want to add a new loss, but got this problem: 
KeyError: 'XXLoss is not in the loss registry'
could you tell me how to add a new loss?

**Comment by Qingyuncookie** [comment]
solved
thank you

**Comment by y78h11b09** [comment]
Hi,I have the same problem too, and how did you soloved it?

**Comment by wangruohui** [comment]
Generally, you should remember to add the registry decorator, and trace the code to make sure the registry is extended BEFORE the configuration is parsed.
