### ISSUE TITLE
[Bug] Pin memory thread exited unexpectedly

### ISSUE THREAD

**Issue by Fei-Wang** [open-mmlab/mmclassification#1210]
### 分支

1.x 分支 (1.0.0rc2 或其他 1.x 版本)

### 描述该错误

使用最新的dev-1.x代码，和https://github.com/open-mmlab/mmclassification/issues/392 问题一样，训练过程中报```Pin memory thread exited unexpectedly```

### 环境信息

```python
{'sys.platform': 'linux',
 'Python': '3.8.4 (default, Jul 15 2020, 05:01:57) [GCC 4.8.5 20150623 (Red '
           'Hat 4.8.5-39)]',
 'CUDA available': True,
 'numpy_random_seed': 2147483648,
 'GPU 0,1': 'GeForce RTX 2080 Ti',
 'CUDA_HOME': '/usr/local/cuda-11.0',
 'NVCC': 'Cuda compilation tools, release 11.0, V11.0.194',
 'GCC': 'gcc (GCC) 7.3.0',
 'PyTorch': '1.7.0+cu110',
 'PyTorch compiling details': 'PyTorch built with:\n'
                              '  - GCC 7.3\n'
                              '  - C++ Version: 201402\n'
                              '  - Intel(R) Math Kernel Library Version '
                              '2020.0.0 Product Build 20191122 for Intel(R) 64 '
                              'architecture applications\n'
                              '  - Intel(R) MKL-DNN v1.6.0 (Git Hash '
                              '5ef631a030a6f73131c77892041042805a06064f)\n'
                              '  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n'
                              '  - NNPACK is enabled\n'
                              '  - CPU capability usage: AVX2\n'
                              '  - CUDA Runtime 11.0\n'
                              '  - NVCC architecture flags: '
                              '-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80\n'
                              '  - CuDNN 8.0.4\n'
                              '  - Magma 2.5.2\n'
                              '  - Build settings: BLAS=MKL, '
                              'BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated '
                              '-fvisibility-inlines-hidden -DUSE_PTHREADPOOL '
                              '-fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK '
                              '-DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK '
                              '-DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing '
                              '-Wall -Wextra -Werror=return-type '
                              '-Wno-missing-field-initializers '
                              '-Wno-type-limits -Wno-array-bounds '
                              '-Wno-unknown-pragmas -Wno-sign-compare '
                              '-Wno-unused-parameter -Wno-unused-variable '
                              '-Wno-unused-function -Wno-unused-result '
                              '-Wno-unused-local-typedefs -Wno-strict-overflow '
                              '-Wno-strict-aliasing '
                              '-Wno-error=deprecated-declarations '
                              '-Wno-stringop-overflow -Wno-psabi '
                              '-Wno-error=pedantic -Wno-error=redundant-decls '
                              '-Wno-error=old-style-cast '
                              '-fdiagnostics-color=always -faligned-new '
                              '-Wno-unused-but-set-variable '
                              '-Wno-maybe-uninitialized -fno-math-errno '
                              '-fno-trapping-math -Werror=format '
                              '-Wno-stringop-overflow, PERF_WITH_AVX=1, '
                              'PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, '
                              'USE_CUDA=ON, USE_EXCEPTION_PTR=1, '
                              'USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, '
                              'USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, '
                              'USE_NNPACK=ON, USE_OPENMP=ON, \n',
 'TorchVision': '0.8.0',
 'OpenCV': '4.6.0',
 'MMEngine': '0.3.1',
 'MMClassification': '1.0.0rc2+4ad8e88'}
```

### 其他信息

是否因为没有禁用pin_memory的缘故？
https://github.com/open-mmlab/mmclassification/blob/743ca2d602631856a971510090c386712d0eac32/tools/train.py#L117-L118

加上了```default_dataloader_cfg.pin_memory = False```后，可以正常训练，不报错

**Comment by Ezra-Yu** [comment]
这是一个pytorch 的bug，refers to https://github.com/pytorch/pytorch/commit/54ce171f16c8859f829dde09f87c364c8a6b4130. 

解决这个问题：
1. 升级你的 PyTorch>=1.8.0 
2.  set `pin_memory=False` or set `persistent_workers=False` in https://github.com/open-mmlab/mmclassification/blob/64bbed41f40ce41928a66e7a7b9817284c8a677f/mmcls/datasets/builder.py#L52-L53


refer to https://github.com/open-mmlab/mmclassification/issues/392

**Comment by Fei-Wang** [comment]
> 这是一个pytorch 的bug，refers to [pytorch/pytorch@54ce171](https://github.com/pytorch/pytorch/commit/54ce171f16c8859f829dde09f87c364c8a6b4130).

是的，由于我无法升级pytorch版本。而且mmcls dev1.x也支持1.7版本，是否应该在```if```中增加```default_dataloader_cfg.pin_memory = False```


> 是否因为没有禁用pin_memory的缘故？
> 
> https://github.com/open-mmlab/mmclassification/blob/743ca2d602631856a971510090c386712d0eac32/tools/train.py#L117-L118
> 
> 加上了`default_dataloader_cfg.pin_memory = False`后，可以正常训练，不报错

**Comment by mzr1996** [comment]
你在 config 中指定了 persistent_workers=True 吗？否则的话只指定 pin_memory=True 应该是可以工作的

**Comment by Fei-Wang** [comment]
> 你在 config 中指定了 persistent_workers=True 吗？否则的话只指定 pin_memory=True 应该是可以工作的

dev1.x版本不是默认为True吗，https://github.com/open-mmlab/mmclassification/blob/743ca2d602631856a971510090c386712d0eac32/tools/train.py#L117-L118
然后这边将```persistent_workers```置为```False```，我没有单独设置```no_pin_memory```和```no_persistent_workers```，也不知道怎么在config中指定persistent_workers。

**Comment by mzr1996** [comment]
> > 你在 config 中指定了 persistent_workers=True 吗？否则的话只指定 pin_memory=True 应该是可以工作的
> 
> dev1.x版本不是默认为True吗，
> 
> https://github.com/open-mmlab/mmclassification/blob/743ca2d602631856a971510090c386712d0eac32/tools/train.py#L117-L118
> 
> 然后这边将`persistent_workers`置为`False`，我没有单独设置`no_pin_memory`和`no_persistent_workers`，也不知道怎么在config中指定persistent_workers。

可以不是贴一下你使用的 config?

**Comment by Fei-Wang** [comment]
> > > 你在 config 中指定了 persistent_workers=True 吗？否则的话只指定 pin_memory=True 应该是可以工作的
> > 
> > 
> > dev1.x版本不是默认为True吗，
> > https://github.com/open-mmlab/mmclassification/blob/743ca2d602631856a971510090c386712d0eac32/tools/train.py#L117-L118
> > 
> > 然后这边将`persistent_workers`置为`False`，我没有单独设置`no_pin_memory`和`no_persistent_workers`，也不知道怎么在config中指定persistent_workers。
> 
> 可不可以贴一下你使用的 config?

我又检查了下config，果然设置了```persistent_workers=True```，删掉就OK了
谢谢
