### ISSUE TITLE
[Feature] Support Regression Task

### ISSUE THREAD

**Issue by okotaku** [open-mmlab/mmclassification#1228]
### Branch

1.x branch (1.0.0rc2 or other 1.x version)

### Describe the feature

・Regression Dataset
・Regression Loss
・Regression Head
・Regression batch_aug

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by Ezra-Yu** [comment]
We have no plans to support Regression Task for the time being. Although the Regression Task looks simple, it needs to add several parts and is very tedious.
