### ISSUE TITLE
[Bug] Notimplemented error:mmclassificiation doesn't support to train the distilled version efficientformer

### ISSUE THREAD

**Issue by Youngforever0911** [open-mmlab/mmclassification#1241]
### Branch

1.x branch (1.0.0rc2 or other 1.x version)

### Describe the bug

Notimplemented error:mmclassificiation doesn't support to train the distilled version efficientformer.

Is this because of mmcls version issue? or other? Thanks.

### Environment

GTX 3090

**Comment by Ezra-Yu** [comment]
> ```Notimplemented error:mmclassificiation doesn't support to train the distilled version efficientformer.```

The current mmcls do not support training models with knowledge distillation, and next year we plan to support this feature by using mmrazor or adding simple distillation methods.
