### ISSUE TITLE
[Bug] Incorrect link for VGG-16-BN model

### ISSUE THREAD

**Issue by Magnus1cheng** [open-mmlab/mmclassification#1247]
### Branch

master branch (0.24 or other 0.x version)

### Describe the bug

In https://github.com/open-mmlab/mmclassification/tree/master/configs/vgg#readme, the config file in row VGG-16-BN should not links to https://github.com/open-mmlab/mmclassification/blob/master/configs/vgg/vgg16_8xb32_in1k.py, instead, it should either links to https://github.com/open-mmlab/mmclassification/blob/master/configs/vgg/vgg16bn_8xb32_in1k.py or https://github.com/open-mmlab/mmclassification/blob/master/configs/vgg/vgg16bn_b32x8_imagenet.py.
If use vgg16_8xb32_in1k.py as config file to generate onnx model from given pth file, accuracy is really low Test Top1 0.11%     Top5 0.61%, but if I use vgg16bn_8xb32_in1k.py, onnx model gives expected accuracy.

### Environment

To generate onnx model,
```
python3 tools/deployment/pytorch2onnx.py configs/vgg/vgg16_8xb32_in1k.py --checkpoint ./vgg16_bn_batch256_imagenet_20210208-7e55cd29.pth --show --output-file vgg16.onnx --dynamic-export
```

**Comment by Ezra-Yu** [comment]
> In https://github.com/open-mmlab/mmclassification/tree/master/configs/vgg#readme, the config file in row VGG-16-BN should not links to https://github.com/open-mmlab/mmclassification/blob/master/configs/vgg/vgg16_8xb32_in1k.py, instead, it should either links to https://github.com/open-mmlab/mmclassification/blob/master/configs/vgg/vgg16bn_8xb32_in1k.py or https://github.com/open-mmlab/mmclassification/blob/master/configs/vgg/vgg16bn_b32x8_imagenet.py.

Yes, you are right. Could you propose a PR to re-link it `https://github.com/open-mmlab/mmclassification/blob/master/configs/vgg/vgg16bn_8xb32_in1k.py`

```text
| VGG-16-BN |  138.37   |  15.53   |   73.74   |   91.66   | [config](https://github.com/open-mmlab/mmclassification/blob/master/configs/vgg/vgg16bn_8xb32_in1k.py) | [model](https://download.openmmlab.com/mmclassification/v0/vgg/vgg16_bn_batch256_imagenet_20210208-7e55cd29.pth) \| [log](https://download.openmmlab.com/mmclassification/v0/vgg/vgg16_bn_batch256_imagenet_20210208-7e55cd29.log.json) |
```
