### ISSUE TITLE
About saving the weight with best accuracy

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmclassification#125]
Hello. I try training with tools/train.py, and it saves the checkpoints by intervals and also saves the last one. But when I want to save the weight separately with best accuracy, I found that the training logic has been integrated in mmcv. 
I wonder are there any apis to enable the runner to save a checkpoint with specified performance, such as lowest loss, highest top-1 accuracy, etc.

**Comment by CheungBH** [comment]
By the way, I notice that the file "tools/inference.py" is not available in master branch.

**Comment by ycxioooong** [comment]
Hi @CheungBH, these features are in our development plan.

**Comment by digantamisra98** [comment]
@ycxioooong any updates on this?

**Comment by mzr1996** [comment]
`save_best` has been supported in mmcv. Refers to https://github.com/open-mmlab/mmcv/blob/c3ddcf9d380b34a594ba78087b355dbd3b86398f/mmcv/runner/hooks/evaluation.py#L31-L39
You can use it by modify evaluation config like
```python
evaluation = dict(
    interval=1, metric='accuracy', metric_options={'topk': (1, )}, save_best='accuracy_top-1')
```
Then the checkpoint with the best `accuracy_top-1` score will be saved.

**Comment by dugudongfangshuo** [comment]
十分感谢

**Comment by 1713mz** [comment]
Does anyone know what key should I use to save the checkpoint (like 'accuracy_top-1' in the example by @mzr1996 ) when I use f1_score instead of accuracy as a metric?

**Comment by tctco** [comment]
@1713mz maybe refer to this [line](https://github.com/open-mmlab/mmclassification/blob/master/mmcls/datasets/base_dataset.py#L181) and this [line](https://github.com/open-mmlab/mmclassification/blob/master/mmcls/datasets/base_dataset.py#L154) in base_dataet.py?
