### ISSUE TITLE
[Bug] Chinese tutorial document: evaluation keyword:"save_best"

### ISSUE THREAD

**Issue by Tamiku** [open-mmlab/mmclassification#1268]
### 分支

master 分支 (0.24 或其他 0.x 版本)

### 描述该错误

In the Chinese tutorial document, it says `evaluation = dict(interval=1, save_best=True, metric='accuracy', metric_options={'topk': (1, )})` , however, the keyword `save_best` should be str instead of bool , like "auto" or 'accuracy_top-1'

### 环境信息

python=3.6

### 其他信息

Thanks for your tutorial documentation! However, I was confused when I met the keyword error. It would be appreciated if you can upgrade the tutorial documentation.

**Comment by Ezra-Yu** [comment]
try 
```save_best='accuracy_top-1'```
or 
```save_best='auto'```

**Comment by mzr1996** [comment]
Get it, I will fix it later.
