### ISSUE TITLE
[Bug] use gpu in customized pipeline, get error.

### ISSUE THREAD

**Issue by ChenJunzhi-buaa** [open-mmlab/mmclassification#1270]
### Branch

master branch (0.24 or other 0.x version)

### Describe the bug

use gpu in customized pipeline, get error.

### Environment

{'sys.platform': 'linux',
 'Python': '3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]',
 'CUDA available': True,
 'GPU 0,1,2,3,4,5,6,7': 'NVIDIA GeForce RTX 2080 Ti',
 'CUDA_HOME': None,
 'GCC': 'gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0',
 'PyTorch': '1.12.1+cu102',
 'PyTorch compiling details': 'PyTorch built with:\n'
                              '  - GCC 7.3\n'
                              '  - C++ Version: 201402\n'
                              '  - Intel(R) Math Kernel Library Version '
                              '2020.0.0 Product Build 20191122 for Intel(R) 64 '
                              'architecture applications\n'
                              '  - Intel(R) MKL-DNN v2.6.0 (Git Hash '
                              '52b5f107dd9cf10910aaa19cb47f3abf9b349815)\n'
                              '  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n'
                              '  - LAPACK is enabled (usually provided by '
                              'MKL)\n'
                              '  - NNPACK is enabled\n'
                              '  - CPU capability usage: AVX2\n'
                              '  - CUDA Runtime 10.2\n'
                              '  - NVCC architecture flags: '
                              '-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70\n'
                              '  - CuDNN 7.6.5\n'
                              '  - Magma 2.5.2\n'
                              '  - Build settings: BLAS_INFO=mkl, '
                              'BUILD_TYPE=Release, CUDA_VERSION=10.2, '
                              'CUDNN_VERSION=7.6.5, '
                              'CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, '
                              'CXX_FLAGS= -fabi-version=11 -Wno-deprecated '
                              '-fvisibility-inlines-hidden -DUSE_PTHREADPOOL '
                              '-fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM '
                              '-DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK '
                              '-DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE '
                              '-DEDGE_PROFILER_USE_KINETO -O2 -fPIC '
                              '-Wno-narrowing -Wall -Wextra '
                              '-Werror=return-type '
                              '-Wno-missing-field-initializers '
                              '-Wno-type-limits -Wno-array-bounds '
                              '-Wno-unknown-pragmas -Wno-unused-parameter '
                              '-Wno-unused-function -Wno-unused-result '
                              '-Wno-unused-local-typedefs -Wno-strict-overflow '
                              '-Wno-strict-aliasing '
                              '-Wno-error=deprecated-declarations '
                              '-Wno-stringop-overflow -Wno-psabi '
                              '-Wno-error=pedantic -Wno-error=redundant-decls '
                              '-Wno-error=old-style-cast '
                              '-fdiagnostics-color=always -faligned-new '
                              '-Wno-unused-but-set-variable '
                              '-Wno-maybe-uninitialized -fno-math-errno '
                              '-fno-trapping-math -Werror=format '
                              '-Wno-stringop-overflow, LAPACK_INFO=mkl, '
                              'PERF_WITH_AVX=1, PERF_WITH_AVX2=1, '
                              'PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, '
                              'USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, '
                              'USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, '
                              'USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, '
                              'USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n',
 'TorchVision': '0.13.1+cu102',
 'OpenCV': '4.6.0',
 'MMCV': '1.7.0',
 'MMCV Compiler': 'GCC 7.3',
 'MMCV CUDA Compiler': '10.2',
 'MMClassification': '0.24.0+e4a930f'}

### Other information

I try to customize a pipeline. In it，image is cropped by a network，which uses gpu.

However, this pipeline raise errors, about using gpu in multiprocessing, as below:
![image](https://user-images.githubusercontent.com/77711950/208019734-37853eeb-a586-4438-a9ce-5ea60d56158b.png)

I tried some method but failed.

What can I do?

**Comment by yingfhu** [comment]
The data pipeline will use multi-processing, you can try add these lines after `init_dist` in `tools/train.py`
```python
import torch.multiprocessing as mp
mp.set_start_method('spawn')
```
You can also refer to https://pytorch.org/docs/master/notes/multiprocessing.html for more information.

**Comment by ChenJunzhi-buaa** [comment]
> The data pipeline will use multi-processing, you can try add these lines after `init_dist` in `tools/train.py`
> 
> ```python
> import torch.multiprocessing as mp
> mp.set_start_method('spawn')
> ```
> 
> You can also refer to https://pytorch.org/docs/master/notes/multiprocessing.html for more information.

Thanks for your help !
It have  tried  your method as you suggest, but there still is a error.
The codes is changed as below: 
![image](https://user-images.githubusercontent.com/77711950/208564972-1c5d2f32-01fa-4776-a683-60a61cea9629.png)

The error is as below:
```
  File "/data/cjz/mtcls/mmcls/datasets/pipelines/crop_by_seg.py", line 44, in crop_by_seg
    input = torch.randn((2,3,32,32)).to(self.device)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

Is there any other way?

Thank you！

**Comment by yingfhu** [comment]
This is a OOM error, since you are using extra model to crop image, you could try to lower down the number of worker for dataloader, which is the `data.workers_per_gpu` in config file.
