### ISSUE TITLE
[Bug] F1 score seems not work for binary classification because of pytorch's one_hot

### ISSUE THREAD

**Issue by PT0X0E** [open-mmlab/mmclassification#1279]
### Branch

master branch (0.24 or other 0.x version)

### Describe the bug

I'm using mmcls 0.25.0 to do binary classification and I want to use F1 score as metric. 
In function `precision_recall_f1` (line 44 at mmcls/core/evaluation/eval_metrics.py), the prediction and target are converted to one-hot encoding by pytorch's nn.functional.one_hot. 
However, for binary classification, it will raise `RuntimeError: Class values must be smaller than num_classes.` The following code can reproduce it. 
```python
import torch
from torch.nn.functional import one_hot
target = torch.LongTensor([1,1,0])
one_hot(target, 1)
```
So I think this might be a bug? Maybe we should add an if-else. If the number of classes is 1, there is no need to convert because pred and target are already "one-hot".
Thanks.

### Environment

'sys.platform': 'linux',
 'Python': '3.8.15 (default, Nov 24 2022, 15:19:38) [GCC 11.2.0]',
 'CUDA available': True,
 'GPU 0': 'GeForce RTX 3090',
 'CUDA_HOME': '/usr/local/cuda',
 'NVCC': 'Cuda compilation tools, release 11.3, V11.3.58',
 'GCC': 'gcc (Ubuntu 8.4.0-3ubuntu2) 8.4.0',
 'PyTorch': '1.10.0+cu113',
'TorchVision': '0.11.1+cu113',
 'OpenCV': '4.6.0',
 'MMCV': '1.7.0',
 'MMCV Compiler': 'GCC 9.3',
 'MMCV CUDA Compiler': '11.3',
 'MMClassification': '0.25.0+'

**Comment by Ezra-Yu** [comment]
I think that `binary classification` can be treated as a special multi-label classification task, (only one label). You can try to use multi-label metrics. there is [an example](https://github.com/open-mmlab/mmclassification/tree/master/configs/csra), you have to modify something.

By the way, you can try to use the [`1.x` branch](https://github.com/open-mmlab/mmclassification/tree/dev-1.x).  It is more friendly to multi-tabbed categories as in https://mmclassification.readthedocs.io/en/1.x/advanced_guides/evaluation.html#use-metrics-in-mmclassification

**Comment by PT0X0E** [comment]
@Ezra-Yu Thanks for reply. Yes, I am using the `MultiLabelLinearClsHead`, but with `BaseDataset`. 
Found `MultiLabelDataset` in your example. It seems work for me.
Then I think adding an assertion would be better, to tell users what they should use if the model has only one output.
Will try 1.x branch. Thanks.

**Comment by Ezra-Yu** [comment]
@PT0X0E  Thank you for your suggestion, but for the current state of the master branch, we are not going to improve it in this place.  Because at the beginning of 2023, we swap 1.x with the master branch.
