### ISSUE TITLE
关于配置文件中 测试时输入的尺寸问题

### ISSUE THREAD

**Issue by ainndejj11** [open-mmlab/mmclassification#1299]
### Branch

master branch (0.24 or other 0.x version)

### Describe the feature

数据集中的这两个，请问哪个是测试是的输入大小？  想改小输入，修改哪个呢
dict(type='Resize', size=(256, -1), backend='pillow'),
    dict(type='CenterCrop', crop_size=224),

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by Ezra-Yu** [comment]
```
dict(type='Resize', size=(256, -1), backend='pillow'),
dict(type='CenterCrop', crop_size=224),
```

For ```dict(type='Resize', size=(256, -1), backend='pillow'),```  Short edge resize to 256 with constant aspect ratio, using PIL backend.

For ```dict(type='CenterCrop', crop_size=224),```,  Center crop a (224, 224) size image.

For a (600, 800) picture,  ```dict(type='Resize', size=(256, -1), backend='pillow'),``` would resize it to (256, 342); ```dict(type='CenterCrop', crop_size=224),``` would crop the (224, 224) area of the picture in the center.

> 数据集中的这两个，请问哪个是测试是的输入大小？ 想改小输入，修改哪个呢

同时相对应的修改，比如 

```
dict(type='Resize', size=(100, -1), backend='pillow'),
dict(type='CenterCrop', crop_size=96),
```

**Comment by ainndejj11** [comment]
您举例的这个&nbsp; &nbsp; 最终是输入尺寸96是吧？


@w
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmclassification"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月5日(星期四) 上午10:55
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmclassification] 关于配置文件中 测试时输入的尺寸问题 (Issue #1299)





 dict(type='Resize', size=(256, -1), backend='pillow'), dict(type='CenterCrop', crop_size=224),  
For dict(type='Resize', size=(256, -1), backend='pillow'),  Short edge resize to 256 with constant aspect ratio, using PIL backend.
 
For dict(type='CenterCrop', crop_size=224),,  Center crop a (224, 224) size image.
 
For a (600, 800) picture,  dict(type='Resize', size=(256, -1), backend='pillow'), would resize it to (256, 342); dict(type='CenterCrop', crop_size=224), would crop the (224, 224) area of the picture in the center.
  
数据集中的这两个，请问哪个是测试是的输入大小？ 想改小输入，修改哪个呢
  
同时相对应的修改，比如
 dict(type='Resize', size=(100, -1), backend='pillow'), dict(type='CenterCrop', crop_size=96),

**Comment by Ezra-Yu** [comment]
嗯嗯！

**Comment by wangcc123-dave** [comment]
I have a question.
If input image size is (w:128, h:100)，after dict(type='Resize', size=(256, -1), backend='pillow'), what is the output size?
