### ISSUE TITLE
[Bug] cannot reproduce top1 accuracy with resnet50 for cub dataset

### ISSUE THREAD

**Issue by jeannotes** [open-mmlab/mmclassification#1335]
### Branch

1.x branch (1.0.0rc2 or other 1.x version)

### Describe the bug

after clone mmcls, I try to reproduce cls with cub dataset, I have 4 2090ti, with default config "configs/resnet/resnet50_8xb8_cub.py", the best accuracy is 87.4%, which is still lower than your result(88.4%)
any suggestions for further improvement?
thanks

### Environment

not that matter

**Comment by Ezra-Yu** [comment]
The accuracy given is what we get using an 8GPU machine, and you need to be careful about scaling lr when reproducing it. In your case, please try a smaller `lr` or use a larger `batchsize` .
