### ISSUE TITLE
[Bug] 文档有误

### ISSUE THREAD

**Issue by bobo0810** [open-mmlab/mmclassification#1339]
### 分支

1.x 分支 (1.0.0rc2 或其他 1.x 版本)

### 描述该错误

![image](https://user-images.githubusercontent.com/26057879/215993527-c5aabd01-2da4-4366-97cd-1eeef119e72c.png)

### 环境信息

![image](https://user-images.githubusercontent.com/26057879/215993565-b8fabd73-a882-42ee-bdf7-322eb28c0ee7.png)

**Comment by Ezra-Yu** [comment]
@bobo0810  Welcome to create a PR and fix this typo refer to [contribution_guide](https://mmclassification.readthedocs.io/en/1.x/notes/contribution_guide.html).

**Comment by bobo0810** [comment]
> We recommend using English or English & Chinese for issues so that we could have broader discussion.

OK👌🏻

**Comment by bobo0810** [comment]
> @bobo0810 Welcome to create a PR and fix this typo refer to [contribution_guide](https://mmclassification.readthedocs.io/en/1.x/notes/contribution_guide.html).

👌🏻
