### ISSUE TITLE
[Feature] Support for multimodal training

### ISSUE THREAD

**Issue by bobo0810** [open-mmlab/mmclassification#1346]
### 分支

1.x 分支 (1.0.0rc2 或其他 1.x 版本)

### 描述该功能

At present, the multimodal orientation of image-text is concerned. Are there plans to support multimode? eg: CLIP

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 MMClassification 贡献代码！

**Comment by Ezra-Yu** [comment]
> At present, the multimodal orientation of image-text is concerned. Are there plans to support multimode?

We plan to support inference for multimodal models, but their training we will put in other repos.

**Comment by bobo0810** [comment]
> We plan to support inference for multimodal models, but their training we will put in other repos.

Does multimodal training create a new repo or plan to place it in the current repo?

**Comment by Ezra-Yu** [comment]
> Does multimodal training create a new repo or plan to place it in an existing repo?

a new repo.

**Comment by bobo0810** [comment]
> a new repo.
Ops! Can you tell me which directions the new repo will support? For example, text-based image generation.

**Comment by Ezra-Yu** [comment]
> Ops! Can you tell me which directions the new repo will support? For example, text-based image generation.

Not AIGC, it is like Vision-language task, like Clip, Blip

**Comment by bobo0810** [comment]
> Not AIGC, it is like Vision-language task, like Clip, Blip

Are there plans for AIGC repo in the future？

**Comment by Ezra-Yu** [comment]
> Are there plans for AIGC repo in the future？

 I am sorry, I don't know.
