### ISSUE TITLE
[Bug] Fixed input with different of output features from multiple runs

### ISSUE THREAD

**Issue by psychAo** [open-mmlab/mmclassification#1347]
### 分支

master 分支 (0.24 或其他 0.x 版本)

### 描述该错误

对于固定的输入，模型输出的特征多次运行的结果不同。产生该现象的原因是什么？
此外，如何让模型读取model zoo中下载的预训练权重，从而使输入固定时，输出的特征相同。

```python
import torch
from mmcv import Config
from mmcls.models import build_classifier

cfg = Config.fromfile('configs/swin_transformer/swin-tiny_16xb64_in1k.py').model
cfg.backbone.out_indices = (0, 1, 2, 3)  # Output multi-scale feature maps
model = build_classifier(cfg)
for i in range(3):
    outs = model.extract_feat(torch.ones(1, 3, 224, 224), stage='backbone')
    print(outs[-1][0,0,0,:])
```

输出结果
> tensor([-0.6767, -0.6767, -0.6767, -0.6767, -0.6767, -0.6767, -0.6767],
       grad_fn=<SliceBackward>)
tensor([-1.2091, -1.2091, -1.2091, -1.2091, -1.2091, -1.2091, -1.2091],
       grad_fn=<SliceBackward>)
tensor([-0.5349, -0.5349, -0.5349, -0.5349, -0.5349, -0.5349, -0.5349],
       grad_fn=<SliceBackward>)

### 环境信息

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'pprint' has no attribute 'pp'
```

**Comment by Ezra-Yu** [comment]
Need add ```model.eval()``` before inference.

```
import torch
from mmcv import Config
from mmcls.models import build_classifier

cfg = Config.fromfile('configs/swin_transformer/swin-tiny_16xb64_in1k.py').model
cfg.backbone.out_indices = (0, 1, 2, 3)  # Output multi-scale feature maps
model = build_classifier(cfg)
for i in range(3):
    outs = model.extract_feat(torch.ones(1, 3, 224, 224), stage='backbone')
    print(outs[-1][0,0,0,:])
```

**Comment by psychAo** [comment]
In `configs/swin_transformer/swin-tiny_16xb64_in1k.py`, I used pretrained model to initialize parameters.

However, the output is still changeable.

```python
model = dict(
    backbone=dict(
        init_cfg=dict(
            type='Pretrained',
            checkpoint='pretrained/swin_tiny_224_b16x64_300e_imagenet_20210616_090925-66df6be6.pth',
            prefix='backbone',
        )),
```

```python
import torch
from mmcv import Config
from mmcls.models import build_classifier

cfg = Config.fromfile('configs/swin_transformer/swin-tiny_16xb64_in1k.py').model
cfg.backbone.out_indices = (0, 1, 2, 3)  # Output multi-scale feature maps
model = build_classifier(cfg)
model.eval()
for i in range(2):
    outs = model.extract_feat(torch.ones(1, 3, 224, 224), stage='backbone')
    print(outs[-1][0,0,0,:])
model = build_classifier(cfg)
model.eval()
for i in range(2):
    outs = model.extract_feat(torch.ones(1, 3, 224, 224), stage='backbone')
    print(outs[-1][0,0,0,:])
```

output:
> tensor([-0.9712, -0.9712, -0.9712, -0.9712, -0.9712, -0.9712, -0.9712],
       grad_fn=<SliceBackward>)
tensor([-0.9712, -0.9712, -0.9712, -0.9712, -0.9712, -0.9712, -0.9712],
       grad_fn=<SliceBackward>)
tensor([-1.1643, -1.1643, -1.1643, -1.1643, -1.1643, -1.1643, -1.1643],
       grad_fn=<SliceBackward>)
tensor([-1.1643, -1.1643, -1.1643, -1.1643, -1.1643, -1.1643, -1.1643],
       grad_fn=<SliceBackward>)
