### ISSUE TITLE
[Bug] shape of multi-level feature maps in Swin Transformer

### ISSUE THREAD

**Issue by psychAo** [open-mmlab/mmclassification#1348]
### Branch

master branch (0.24 or other 0.x version)

### Describe the bug

run these codes:

```python
import torch
from mmcv import Config
from mmcls.models import build_classifier

cfg = Config.fromfile("configs/swin_transformer/swin-tiny_16xb64_in1k.py").model
cfg.backbone.out_indices = (0, 1, 2, 3)  # Output multi-scale feature maps
model = build_classifier(cfg)
outs = model.extract_feat(torch.ones(1, 3, 224, 224), stage='backbone')
for out in outs:
    print(out.shape)
```

output:
> torch.Size([1, 192, 28, 28])
torch.Size([1, 384, 14, 14])
torch.Size([1, 768, 7, 7])
torch.Size([1, 768, 7, 7])

However, shapes of features should be as follows according to the original paper:

![图片](https://user-images.githubusercontent.com/32694957/216649308-76ef60c9-1c4c-4969-a8a8-6460a2a0b25a.png)

for input with spatial size of (224, 224), features are supposed to be:

(1, 96, 56, 56)
(1, 192, 28, 28)
(1, 384, 14, 14)
(1, 768, 7, 7)

### Environment

mmclassification==0.23.2

**Comment by Ezra-Yu** [comment]
Our implementation is based on its source code and the released wights.

here is the source code of MSRA. https://github.com/microsoft/Swin-Transformer/blob/f92123a0035930d89cf53fcb8257199481c4428d/models/swin_transformer.py#L560
