### ISSUE TITLE
支持多模态的数据

### ISSUE THREAD

**Issue by Hellcat1005** [open-mmlab/mmclassification#1353]
### 分支

master 分支 (0.24 或其他 0.x 版本)

### 描述该功能

我是做医疗影像算法的。对于某一个病人，他可能有多种影像数据，同时还有一些其他信息，例如身高、体重、验血结果等等。把这些信息利用起来会对预测有一定的帮助。是否可以实现一个比较灵活的方式，可以让用户自定义提取特征的方式、损失函数的计算等等。目前这个版本，不太清楚该如何去修改，好像只支持输入单张图像。

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 MMClassification 贡献代码！

**Comment by Ezra-Yu** [comment]
首选推荐使用我们的新版本1.x， https://github.com/open-mmlab/mmclassification/tree/1.x。

> 是否可以实现一个比较灵活的方式，可以让用户自定义提取特征的方式、损失函数的计算等等。

因为目前```一个比较灵活的方式```,过于灵活，其他的额外信息编码后，可以直接作为bakcbone的输入，也可以其中某一层的输入，还可以图像编码后进行融合。没有固定的范式，所以目前没有计划支持这一功能。

目前将图像信息特征与额外信息的编码比较好实现，不知道你的想法是什么样的？

**Comment by Hellcat1005** [comment]
> 首选推荐使用我们的新版本1.x， [https://github.com/open-mmlab/mmclassification/tree/1.x。](https://github.com/open-mmlab/mmclassification/tree/1.x%E3%80%82)
> 
> > 是否可以实现一个比较灵活的方式，可以让用户自定义提取特征的方式、损失函数的计算等等。
> 
> 因为目前`一个比较灵活的方式`,过于灵活，其他的额外信息编码后，可以直接作为bakcbone的输入，也可以其中某一层的输入，还可以图像编码后进行融合。没有固定的范式，所以目前没有计划支持这一功能。
> 
> 目前将图像信息特征与额外信息的编码比较好实现，不知道你的想法是什么样的？

你好，我对这个框架的理解不是很深入，我目前的感觉是这样的：在mmcls中自定义一些特征融合、backbone、head等模块，都是很方便的。但是从dataloader中获取数据，再把数据输入到网络中，这部分好像并不是在mmcls中实现，而是在engine或者mmcv中？如果有这样一个场景：输入是一张图片和一个onehot之后的类别数据。但是现在的backbone部分，输入都是x，也就是图片，从dataloader拿出一个batch，然后获取batch中的图像部分，再然后输入进网络，这部分代码是不是并不属于mmcls？要想实现同时输入图片和一个类别的向量，需要自己去编码，通过batch['img']，batch['某个信息']去获得数据，再进行输入。这部分代码应该去哪里实现呢？

**Comment by Ezra-Yu** [comment]
如果想要完全支持这个，是需要设计一个新的[`mmcls.models.Classifier`](https://github.com/open-mmlab/mmclassification/blob/7e4502b0ac0f0c329a11c2f65c032303d4128973/mmcls/models/classifiers/image.py#L13), 目前的版本只支持一个input为Tensor的输入，可以改成dict。你的思路应该可以通过修改这里实现。

如果追求快速实现且你只是在最后分类中使用额外信息，可以将 额外信息放在[ClsDataSample.metainfo](https://github.com/open-mmlab/mmclassification/blob/7e4502b0ac0f0c329a11c2f65c032303d4128973/mmcls/datasets/transforms/formatting.py#L95)中，[mmcls.datasets.ClsDataSample](https://github.com/open-mmlab/mmclassification/blob/7e4502b0ac0f0c329a11c2f65c032303d4128973/mmcls/structures/cls_data_sample.py#L71).  这样你在自己的分类头中，可以进行编码，特征融合以及分类，这样只需要添加一个dataset,以及clshead类。

**Comment by Hellcat1005** [comment]
> 如果想要完全支持这个，是需要设计一个新的[`mmcls.models.Classifier`](https://github.com/open-mmlab/mmclassification/blob/7e4502b0ac0f0c329a11c2f65c032303d4128973/mmcls/models/classifiers/image.py#L13), 目前的版本只支持一个input为Tensor的输入，可以改成dict。你的思路应该可以通过修改这里实现。
> 
> 如果追求快速实现且你只是在最后分类中使用额外信息，可以将 额外信息放在[ClsDataSample.metainfo](https://github.com/open-mmlab/mmclassification/blob/7e4502b0ac0f0c329a11c2f65c032303d4128973/mmcls/datasets/transforms/formatting.py#L95)中，[mmcls.datasets.ClsDataSample](https://github.com/open-mmlab/mmclassification/blob/7e4502b0ac0f0c329a11c2f65c032303d4128973/mmcls/structures/cls_data_sample.py#L71). 这样你在自己的分类头中，可以进行编码，特征融合以及分类，这样只需要添加一个dataset,以及clshead类。

好的，非常感谢。
