### ISSUE TITLE
mmlab实战营三课tools/train报错

### ISSUE THREAD

**Issue by funwong** [open-mmlab/mmclassification#1358]
### 分支

master 分支 (0.24 或其他 0.x 版本)

### 描述该错误

![mmlabcls-01](https://user-images.githubusercontent.com/113315791/217731196-01e495a9-097c-4f92-aae5-c40b0c4097b5.png)

(pytorch18cuda111) E:\mmcv-1\mmclassification>python tools/train.py mobilenet-v2_8xb32_in1_copy.py
E:\IDE\conda\envs\pytorch18cuda111\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation mo
dule. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
e:\mmcv-1\mmclassification\mmcls\utils\setup_env.py:32: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optim
al performance in your application as needed.
  warnings.warn(
Traceback (most recent call last):
  File "E:\mmcv-1\mmclassification\tools\train.py", line 205, in <module>
    main()
  File "E:\mmcv-1\mmclassification\tools\train.py", line 154, in main
    env_info_dict = collect_env()
  File "e:\mmcv-1\mmclassification\mmcls\utils\collect_env.py", line 10, in collect_env
    env_info = collect_base_env()
  File "E:\IDE\conda\envs\pytorch18cuda111\lib\site-packages\mmcv\utils\env.py", line 72, in collect_env
    nvcc = subprocess.check_output(f'"{nvcc}" -V', shell=True)
  File "E:\IDE\conda\envs\pytorch18cuda111\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\IDE\conda\envs\pytorch18cuda111\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\IDE\conda\envs\pytorch18cuda111\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\IDE\conda\envs\pytorch18cuda111\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### 环境信息

 
![mmlabcls-02](https://user-images.githubusercontent.com/113315791/217732616-75ca3148-263c-460f-8251-27a0b9f9482f.png)
E:\IDE\conda\envs\pytorch18cuda111\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "E:\mmcv-1\main.py", line 14, in <module>
    print (pprint.pp(dict(mmcls.utils.collect_env())))
  File "e:\mmcv-1\mmclassification\mmcls\utils\collect_env.py", line 10, in collect_env
    env_info = collect_base_env()
  File "E:\IDE\conda\envs\pytorch18cuda111\lib\site-packages\mmcv\utils\env.py", line 72, in collect_env
    nvcc = subprocess.check_output(f'"{nvcc}" -V', shell=True)
  File "E:\IDE\conda\envs\pytorch18cuda111\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\IDE\conda\envs\pytorch18cuda111\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\IDE\conda\envs\pytorch18cuda111\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\IDE\conda\envs\pytorch18cuda111\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by funwong** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Ezra-Yu** [comment]
Can you run ```nvcc -V``` in your env.

please try to use 1.x branch https://github.com/open-mmlab/mmclassification/tree/dev-1.x.

**Comment by funwong** [comment]
&nbsp;


1162759693
***@***.***



&nbsp;

**Comment by funwong** [comment]
![mmlabcls-03](https://user-images.githubusercontent.com/113315791/217745165-aa66a20e-4a2d-46b3-9a5c-f52c4de4f950.png)

**Comment by funwong** [comment]
![image](https://user-images.githubusercontent.com/113315791/217787002-abafc21c-ea29-46cb-aa72-f2c6d4cce271.png)
更换到class1.0分支后依然报错，

**Comment by Ezra-Yu** [comment]
我们在自己的windows系统测试是没有问题的，这边无法复现你的错误。

请问一下这个验证是否能走通？https://mmclassification.readthedocs.io/zh_CN/1.x/get_started.html#id5

如果你能debug，可以查看
![image](https://user-images.githubusercontent.com/18586273/217788839-85589a63-8d2b-445d-a966-3e3546745700.png)
这里subprocess具体执行的指令是什么（print(f"{nvcc} -V"), {nvcc}应该是nvcc的具体路径）？在CMD中执行一下试一下。

**Comment by funwong** [comment]
![image](https://user-images.githubusercontent.com/113315791/217819102-3da19433-f6a9-4e0d-96ed-67f8026ac76d.png)
是否是步骤一和步骤二的测试。

**Comment by funwong** [comment]
![image](https://user-images.githubusercontent.com/113315791/217823315-f51a068c-2089-4b7a-ae9c-558f9ba0eb93.png)
![image](https://user-images.githubusercontent.com/113315791/217823420-39e8c78c-ac6a-4a20-8bb7-5c3da5db2ab9.png)
请问，图二这个闪电标志在pycharm中是否为问题。。是否为少库导致的。。。真诚的请教目前debug操作是否与要求一致

**Comment by funwong** [comment]
![image](https://user-images.githubusercontent.com/113315791/217831221-6a3e20d2-863c-47ef-8f07-c96dc54fd495.png)

**Comment by funwong** [comment]
![image](https://user-images.githubusercontent.com/113315791/217837101-8b1ef677-eae4-40db-8a41-3e0788da0e76.png)

**Comment by funwong** [comment]
我换了一台笔记本，款式新。这个问题没出现。应该是报错的电脑太老了。cpu已经跑起来了

![image](https://user-images.githubusercontent.com/113315791/217991582-deff67e4-e02a-4bfc-b2e6-36459ad6ac6e.png)
