### ISSUE TITLE
[WARNING] WARNING - The "model" registry in mmcls did not set import location. Fallback to call `mmcls.utils.register_all_modules` instead. 

### ISSUE THREAD

**Issue by learning1112** [open-mmlab/mmclassification#1362]
### Branch

master branch (0.24 or other 0.x version)

### Describe the bug

python：
```
from mmcls import get_model, inference_model

model = get_model('resnet18_8xb32_in1k', device='cuda:0')  # 或者 device='cuda:0'
img = r"F:\pythonProject\banana.jpg"
result = inference_model(model, img)
print(result)
```
then
```
02/09 20:27:46 - mmengine - WARNING - The "model" registry in mmcls did not set import location. Fallback to call `mmcls.utils.register_all_modules` instead. 
02/09 20:27:47 - mmengine - WARNING - The "transform" registry in mmcls did not set import location. Fallback to call `mmcls.utils.register_all_modules` instead.
```
So What dose it mean？

### Environment

{'sys.platform': 'win32',
 'Python': '3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]',
 'CUDA available': True,
 'numpy_random_seed': 2147483648,
 'GPU 0': 'NVIDIA GeForce MX450',
 'CUDA_HOME': 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7',
 'NVCC': 'Cuda compilation tools, release 11.7, V11.7.99',
 'MSVC': '用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.34.31937 版',
 'GCC': 'n/a',
 'PyTorch': '1.13.1',
 'PyTorch compiling details': 'PyTorch built with:\n'
                              '  - C++ Version: 199711\n'
                              '  - MSVC 192829337\n'
                              '  - Intel(R) Math Kernel Library Version '
                              '2020.0.2 Product Build 20200624 for Intel(R) 64 '
                              'architecture applications\n'
                              '  - Intel(R) MKL-DNN v2.6.0 (Git Hash '
                              '52b5f107dd9cf10910aaa19cb47f3abf9b349815)\n'
                              '  - OpenMP 2019\n'
                              '  - LAPACK is enabled (usually provided by '
                              'MKL)\n'
                              '  - CPU capability usage: AVX2\n'
                              '  - CUDA Runtime 11.7\n'
                              '  - NVCC architecture flags: '
                              '-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37\n'
                              '  - CuDNN 8.5\n'
                              '  - Magma 2.5.4\n'
                              '  - Build settings: BLAS_INFO=mkl, '
                              'BUILD_TYPE=Release, CUDA_VERSION=11.7, '
                              'CUDNN_VERSION=8.5.0, '
                              'CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, '
                              'CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w '
                              '/bigobj -DUSE_PTHREADPOOL -openmp:experimental '
                              '-IC:/cb/pytorch_1000000000000/work/mkl/include '
                              '-DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI '
                              '-DUSE_FBGEMM -DUSE_XNNPACK '
                              '-DSYMBOLICATE_MOBILE_DEBUG_HANDLE '
                              '-DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, '
                              'PERF_WITH_AVX=1, PERF_WITH_AVX2=1, '
                              'PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, '
                              'USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, '
                              'USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, '
                              'USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, '
                              'USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, \n',
 'TorchVision': '0.14.1',
 'OpenCV': '4.7.0',
 'MMEngine': '0.5.0',
 'MMClassification': '1.0.0rc5+unknown'}

**Comment by Ezra-Yu** [comment]
Update the code for the latest mmcls-dev-1.x and mmengine, then this warning will go away.

> ```
> 02/09 20:27:46 - mmengine - WARNING - The "model" registry in mmcls did not set import location. Fallback to call `mmcls.utils.register_all_modules` instead. 
> 02/09 20:27:47 - mmengine - WARNING - The "transform" registry in mmcls did not set import location. Fallback to call `mmcls.utils.register_all_modules` instead.
> ```
> So What dose it mean？

To avoid the need for the user to call `mmcls.utils.register_all_models` manually. The default register in [`mmcls.registry` ](https://github.com/open-mmlab/mmclassification/blob/dev-1.x/mmcls/registry.py) is now used with a hidden import of the folder to register corresponding classes, the folder is specified by location.

**Comment by learning1112** [comment]
> Update the code for the latest mmcls-dev-1.x and mmengine, then this warning will go away.
> 
> > ```
> > 02/09 20:27:46 - mmengine - WARNING - The "model" registry in mmcls did not set import location. Fallback to call `mmcls.utils.register_all_modules` instead. 
> > 02/09 20:27:47 - mmengine - WARNING - The "transform" registry in mmcls did not set import location. Fallback to call `mmcls.utils.register_all_modules` instead.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So What dose it mean？
> 
> To avoid the need for the user to call `mmcls.utils.register_all_models` manually. The default register in [`mmcls.registry` ](https://github.com/open-mmlab/mmclassification/blob/dev-1.x/mmcls/registry.py) is now used with a hidden import of the folder to register corresponding classes, the folder is specified by location.

mmcls and mmengine are the latest version,but the warning is still there
'MMEngine': '0.5.0',
'MMClassification': '1.0.0rc5+unknown'

**Comment by learning1112** [comment]
yes
![image](https://user-images.githubusercontent.com/97772488/218305903-da762424-2b96-4a44-bdfb-b40d34f6267d.png)
