### ISSUE TITLE
[Feature] What are some examples of image retrieval(image search image)？

### ISSUE THREAD

**Issue by roomeo** [open-mmlab/mmclassification#1372]
### 分支

1.x 分支 (1.0.0rc2 或其他 1.x 版本)

### 描述该功能

image search image

### 是否希望自己实现该功能？

- [ ] 我希望自己来实现这一功能，并向 MMClassification 贡献代码！

**Comment by Ezra-Yu** [comment]
here is an example, https://github.com/open-mmlab/mmclassification/tree/dev-1.x/configs/arcface
