### ISSUE TITLE
How to save the best checkpoints according to val results

### ISSUE THREAD

**Issue by sibet-lb** [open-mmlab/mmclassification#1373]
### Branch

1.x branch (1.0.0rc2 or other 1.x version)

### Describe the feature

hi，how to save only the optimal weight file, not every epoch? I am using the  dev 1.x branch.

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by Ezra-Yu** [comment]
```
default_hooks = dict(
    # save last three checkpoints
    checkpoint=dict(
        type='CheckpointHook',
        save_best='auto',    # svae the best, auto select the `Accuracy` to the first  metric in val_evalutor
        interval=1,
        max_keep_ckpts=3,  # only save the  latest 3 ckpts
        rule='greater'            # the greater the metric, the better the ckpt will be    
)
)
```
For more details, refer to [MMEngine Tutorial](https://mmengine.readthedocs.io/en/latest/tutorials/hook.html#loggerhook) and [API doc](https://mmengine.readthedocs.io/en/latest/api/generated/mmengine.hooks.CheckpointHook.html#mmengine.hooks.CheckpointHook).

**Comment by sibet-lb** [comment]
Hello, when I modified the default_hooks inside runner.py, I still can't save the optimal weights, nothing has changed, where do I have to modify?
![Snipaste_2023-02-23_12-26-26](https://user-images.githubusercontent.com/82500802/220821506-cb052781-b52e-4f81-8341-b6a2c2a185d3.png)

**Comment by Ezra-Yu** [comment]
![image](https://user-images.githubusercontent.com/18586273/220821965-809c09ee-49a0-45cd-b988-14b6a1621c88.png)

do you have this kind of dir?

**Comment by sibet-lb** [comment]
Hello, I have not received this type of file. But when I used version 0.x, I could get the file with unique weights directly. With the current version this is no longer the case. Here is a comparison between the old and the new version
![Snipaste_2023-02-23_13-36-19](https://user-images.githubusercontent.com/82500802/220829098-c4f5f3fe-bcc6-4ebd-8dc0-5cd8cdebe673.png)
![Snipaste_2023-02-23_13-37-01](https://user-images.githubusercontent.com/82500802/220829121-8bf5ead3-40e5-4d2e-867f-e419a5e9e77c.png)

**Comment by Ezra-Yu** [comment]
check your configuration in your log.

![image](https://user-images.githubusercontent.com/18586273/220831252-8732adaa-717e-48a4-884b-27dd129436c6.png)

![image](https://user-images.githubusercontent.com/18586273/220831113-22bf7b87-9b72-49d0-bf6d-2f20fa92f14a.png)

If it doesn't work, then it's not in effect

**Comment by sibet-lb** [comment]
Hello, I noticed that default_hooks did not change, but I changed the checkpoint in runner.py. Am I in the wrong place? I don't think there is anything to change in config.py or train.py
![image](https://user-images.githubusercontent.com/82500802/220832725-0c8f8dbb-1682-4124-baa9-379dfb89f61c.png)

**Comment by Ezra-Yu** [comment]
can you show your config?

**Comment by sibet-lb** [comment]
![image](https://user-images.githubusercontent.com/82500802/220834246-09359c00-3ecc-4a9a-87ef-3ea78297cf9b.png)

**Comment by Ezra-Yu** [comment]
add this in the file.
```
default_hooks = dict(
    # save last three checkpoints
    checkpoint=dict(
        type='CheckpointHook',
        save_best='auto',    # svae the best, auto select the `Accuracy` to the first  metric in val_evalutor
        interval=1,
        max_keep_ckpts=3,  # only save the  latest 3 ckpts
        rule='greater'            # the greater the metric, the better the ckpt will be    
)
)
```

**Comment by sibet-lb** [comment]
It works! thanks a lot!

**Comment by chenshen03** [comment]
I have a similar question, how to automatically select the checkpoint corresponding to the best val metric for inference on the test set?
