### ISSUE TITLE
[Bug] Rotate transformation does not behave as expected?

### ISSUE THREAD

**Issue by tctco** [open-mmlab/mmclassification#1392]
### Branch

1.x branch (1.0.0rc2 or other 1.x version)

### Describe the bug

Given `dict(type='Rotate', magnitude_range=[-180,180])`, the expected output should be images rotated with a random angle between [-180, 180] deg. However, the current code will only rotate the image with 2 specific angles: -180deg or 180deg.

In this [line](https://github.com/open-mmlab/mmclassification/blob/1.x/mmcls/datasets/transforms/auto_augment.py#L580), it shows that angle is generated by `random_magnitude()` in this [line](https://github.com/open-mmlab/mmclassification/blob/1.x/mmcls/datasets/transforms/auto_augment.py#L323).

```python
    def __init__(self,
                 magnitude_level: int = 10,
                 magnitude_range: Tuple[float, float] = None,
                 magnitude_std: Union[str, float] = 0.,
                 total_level: int = 10,
                 prob: float = 0.5,
                 random_negative_prob: float = 0.5):
        ...


    def random_magnitude(self):
        """Randomly generate magnitude."""
        magnitude = self.magnitude_level
        # if magnitude_std is positive number or 'inf', move
        # magnitude_value randomly.
        if self.magnitude_std == 'inf':
            magnitude = np.random.uniform(0, magnitude)
        elif self.magnitude_std > 0:
            magnitude = np.random.normal(magnitude, self.magnitude_std)
            magnitude = np.clip(magnitude, 0, self.total_level)

        val1, val2 = self.magnitude_range
        magnitude = (magnitude / self.total_level) * (val2 - val1) + val1
        return magnitude
```

The default `magnitude_std` is set to 0, which makes the code skip all if statements in function `random_magnitude`.

### Environment

None

### Other information

Perhaps the default value for `magnitude_std` should be set to 'inf' in this [line](https://github.com/open-mmlab/mmclassification/blob/1.x/mmcls/datasets/transforms/auto_augment.py#L557)?

```python
        super().__init__(
            prob=prob, random_negative_prob=random_negative_prob, magnitude_std='inf', **kwargs)
```

**Comment by Ezra-Yu** [comment]
We add this transformation as a component of `RandAug` originally. We have described it as the docstring: https://github.com/open-mmlab/mmclassification/blob/c7ec630c37dd2c7c997405a70b9fafa6a54e5f95/mmcls/datasets/transforms/auto_augment.py#L286-L294

So, you want a mode as following:
```
the magnitude obeys uniform distribution :math:`Uniform(min,max)`  
```
and the code should update this modification.

**Comment by tctco** [comment]
I see, but can I use `Rotate` as a standalone data augmenting protocol?

**Comment by Ezra-Yu** [comment]
use [`Albumentations`](https://mmclassification.readthedocs.io/en/dev-1.x/api/generated/mmcls.datasets.transforms.Albumentations.html#mmcls.datasets.transforms.Albumentations). such as following:

```
dict(type='Albumentations', transforms=[dict(type='Rotate', limit=180)])
```

**Comment by Ezra-Yu** [comment]
@tctco  Did this answer help you solve your problem? I will close this issue if it works.

**Comment by tctco** [comment]
Thanks for your help :)
