### ISSUE TITLE
How to output the classification results of each picture？

### ISSUE THREAD

**Issue by yaochengwen** [open-mmlab/mmclassification#14]
Hello, I can use MobilenetV2 to train my own data set, and I can output the ACC of the test set normally, but how do I output the prediction results of each picture in the test set?

**Comment by yl-1993** [comment]
Hi @yaochengwen , this is similar to https://github.com/open-mmlab/mmclassification/issues/12. For your information, we will implement the model inference to output prediction results via PR https://github.com/open-mmlab/mmclassification/pull/16
