### ISSUE TITLE
[Feature] Can I convert resnet50 mmcls model to torchvision?

### ISSUE THREAD

**Issue by yuanyuangoo** [open-mmlab/mmclassification#1411]
### Branch

master branch (0.24 or other 0.x version)

### Describe the feature

I trained a resnet50 model in mmcls, can I convert it to torchvision?

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by Ezra-Yu** [comment]
Yes, sure. You can convert your weight to torchvision style, by changing the weight's key. We provide the [torchvison2mmcls](https://github.com/open-mmlab/mmclassification/blob/master/tools/convert_models/torchvision_to_mmcls.py) script, you can refer to writing a reverse script
