### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpnlu1a1qo/tmpwfb0cuz4.yaml'[Bug] when training a custom dataset

### ISSUE THREAD

**Issue by ManuBN786** [open-mmlab/mmclassification#1432]
### Branch

master branch (0.24 or other 0.x version)

### Describe the bug

I checked for syntax error in the config file with a 'python config.yam' and there are no issues.
But I still get the error:

(dl4cv) Projects/mmclassification$   python tools/train.py resnet34_config.yaml

Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    main()
  File "tools/train.py", line 93, in main
    cfg = Config.fromfile(args.config)
  File "/home/manu/.virtualenvs/dl4cv/lib/python3.8/site-packages/mmcv/utils/config.py", line 337, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/home/manu/.virtualenvs/dl4cv/lib/python3.8/site-packages/mmcv/utils/config.py", line 220, in _file2dict
    cfg_dict = mmcv.load(temp_config_file.name)
  File "/home/manu/.virtualenvs/dl4cv/lib/python3.8/site-packages/mmcv/fileio/io.py", line 58, in load
    obj = handler.load_from_fileobj(f, **kwargs)
  File "/home/manu/.virtualenvs/dl4cv/lib/python3.8/site-packages/mmcv/fileio/handlers/yaml_handler.py", line 17, in load_from_fileobj
    return yaml.load(file, **kwargs)
  File "/home/manu/.virtualenvs/dl4cv/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/manu/.virtualenvs/dl4cv/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml/_yaml.pyx", line 674, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.parser.ParserError: did not find expected <document start>
  in "<file>", line 10, column 5
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f03edfeaf70>
Traceback (most recent call last):
  File "/usr/lib/python3.8/tempfile.py", line 579, in __del__
    self.close()
  File "/usr/lib/python3.8/tempfile.py", line 575, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpnlu1a1qo/tmpwfb0cuz4.yaml'

The config file for custom dataset is as belo
[resnet34_config.txt](https://github.com/open-mmlab/mmclassification/files/11039537/resnet34_config.txt)
w

### Environment

Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mmcls
>>> mmcls.__version__
'0.25.0'
>>> import torch
>>> torch.__version__
'1.11.0+cu113'

**Comment by Ezra-Yu** [comment]
Could you run  ```mim run mmcls print_config $YOUR_CONFIG_PATH```? It seem something wrong in you config.

in first line  of the config:
```
_base_ = 'resnet34_8xb32_in1k.py'  # resnet34_8xb32_in1k.py is a file path

....
```

**Comment by ManuBN786** [comment]
This is the result of running the 'print_config'

(dl4cv) manu@manu-System-Product-Name:~/PycharmProjects/mmclassification$ python tools/misc/print_config.py /home/manu/PycharmProjects/mmrazor/resnet34_config.yaml
Traceback (most recent call last):
  File "tools/misc/print_config.py", line 35, in <module>
    main()
  File "tools/misc/print_config.py", line 28, in main
    cfg = Config.fromfile(args.config)
  File "/home/manu/.virtualenvs/dl4cv/lib/python3.8/site-packages/mmcv/utils/config.py", line 337, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/home/manu/.virtualenvs/dl4cv/lib/python3.8/site-packages/mmcv/utils/config.py", line 220, in _file2dict
    cfg_dict = mmcv.load(temp_config_file.name)
  File "/home/manu/.virtualenvs/dl4cv/lib/python3.8/site-packages/mmcv/fileio/io.py", line 58, in load
    obj = handler.load_from_fileobj(f, **kwargs)
  File "/home/manu/.virtualenvs/dl4cv/lib/python3.8/site-packages/mmcv/fileio/handlers/yaml_handler.py", line 17, in load_from_fileobj
    return yaml.load(file, **kwargs)
  File "/home/manu/.virtualenvs/dl4cv/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/manu/.virtualenvs/dl4cv/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml/_yaml.pyx", line 674, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.parser.ParserError: did not find expected <document start>
  in "<file>", line 10, column 5
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f81e33c28b0>
Traceback (most recent call last):
  File "/usr/lib/python3.8/tempfile.py", line 579, in __del__
    self.close()
  File "/usr/lib/python3.8/tempfile.py", line 575, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpcjn7ll3w/tmpup6t2hyl.yaml'

**Comment by Ezra-Yu** [comment]
should be "_base_ = 'configs/resnet/resnet34_b32x8_imagenet.py"
not "base = 'configs/resnet/resnet34_b32x8_imagenet.py"

**Comment by ManuBN786** [comment]
It's actually                          _base_ = "configs/resnet/resnet34_b32x8_imagenet.py"

But it does not resolve the issue.

It still gives the same error.

Please tell me how to fix it ?

**Comment by Ezra-Yu** [comment]
But in my environment, using your config, as long as the path of _base_ is set correctly, there is no problem.


Could you try the [dev-1x](https://github.com/open-mmlab/mmclassification/tree/dev-1.x) branch， the master branch would no longer be maintained.

**Comment by ManuBN786** [comment]
I did a fresh installation from the dev-1x branch on a new environment.

But i still get the same error

![Screenshot from 2023-03-27 15-49-52](https://user-images.githubusercontent.com/16796765/227876559-4515cb0d-2efa-4143-980a-b4644c595099.png)

**Comment by Ezra-Yu** [comment]
This config can be used.
```
_base_ = 'mmcls::resnet/resnet34_8xb32_in1k.py'

# the same with the following:
# _base_ = [
#    '../_base_/models/resnet50.py',
#    '../_base_/datasets/cifar10_bs16.py', '../_base_/default_runtime.py'
# ]
# as https://mmclassification.readthedocs.io/en/latest/tutorials/finetune.html

# Model config
model = dict(
    backbone=dict(
        frozen_stages=2,
        init_cfg=dict(
            type='Pretrained',
            checkpoint='https://download.openmmlab.com/mmclassification/v0/resnet/resnet34_8xb32_in1k_20210831-f257d4e6.pth',
            prefix='backbone',
        )),
    head=dict(num_classes=10),
)

# Dataset config
img_norm_cfg = dict(
    mean=[125.307, 122.961, 113.8575],
    std=[51.5865, 50.847, 51.255],
    to_rgb=False,
)
train_pipeline = [
    dict(type='RandomCrop', size=32, padding=4),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Resize', size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label']),
]
test_pipeline = [
    dict(type='Resize', size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img']),
]
data = dict(
    train=dict(pipeline=train_pipeline),
    val=dict(pipeline=test_pipeline),
    test=dict(pipeline=test_pipeline),
)

# Training schedule config
# lr is set for a batch size of 128
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', step=[15])
runner = dict(type='EpochBasedRunner', max_epochs=200)
log_config = dict(interval=100)
```

It works in my environment.
![image](https://user-images.githubusercontent.com/18586273/227882573-7d22cd5e-e5d7-4961-a8ca-be6ebe0817f1.png)

**Comment by ManuBN786** [comment]
![Screenshot from 2023-03-27 17-27-31](https://user-images.githubusercontent.com/16796765/227901710-d0369f0c-7d1a-4643-a23f-939f94910bd9.png)

I tried this too. But somewhere along I get the same error.

The source of the error is  _base_ = 'mmcls::resnet/resnet34_8xb32_in1k.py'     or    _base_ = 'configs/resnet/resnet34_8xb32_in1k.py'

So I put all absolute paths in the 'resnet34_8xb32_in1k.py'

_base_ = [ '/home/manu/PycharmProjects/mmclassification/configs/_base_/models/resnet34.py', '/home/manu/PycharmProjects/mmclassification/configs/_base_/datasets/imagenet_bs32.py',    '/home/manu/PycharmProjects/mmclassification/configs/_base_/schedules/imagenet_bs256.py', '/home/manu/PycharmProjects/mmclassification/configs/_base_/default_runtime.py']

Despite that I get the same error.

During installation everything was very smooth.

But when running the config files, the error is coming from resnet34_8xb32_in1k.py

**Comment by Ezra-Yu** [comment]
Try to rename your `resnet34_config2.yaml` as `resnet34_config2.py`

**Comment by ManuBN786** [comment]
![Screenshot from 2023-03-27 17-49-24](https://user-images.githubusercontent.com/16796765/227907346-97b0a23d-43fd-4e54-9cfb-abee27376b47.png)

Renaming it into .py file did the magic !!!

I have a deadline and you just saved me !!

Thank you so much !!
