### ISSUE TITLE
efficientnet-b2 模型训练精度测试，得到的结果与预期不符

### ISSUE THREAD

**Issue by pedant235** [open-mmlab/mmclassification#1455]
### 分支

master 分支 (0.24 或其他 0.x 版本)

### 描述该错误

在8卡(v100)环境上进行训练，100个step之后得到的推理结果如下{"mode": "val", "epoch": 100, "iter": 196, "lr": 0.0001, "accuracy_top-1": 73.12801, "accuracy_top-5": 91.188}，根据 https://github.com/open-mmlab/mmclassification/tree/master/configs/efficientnet 页面显示的结果，精度应该达到79.64左右。另外发现我们的机器上得到的权重文件是71M大小，而该页面下载下来的权重文件是35M大小。
```shell
# 运行的命令是
bash ./tools/dist_train.sh ./configs/efficientnet/efficientnet-b2_8xb32_in1k.py 8 2>&1 | tee train.log
```

### 环境信息

{'sys.platform': 'linux', 'Python': '3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]', 'CUDA available': True, 'GPU 0,1,2,3,4,5,6,7': 'Tesla V100S-PCIE-32GB', 'CUDA_HOME': '/usr/local/cuda', 'NVCC': 'Cuda compilation tools, release 11.3, V11.3.109', 'GCC': 'gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0', 'PyTorch': '1.10.2+cu102', 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX512\n  - CUDA Runtime 10.2\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70\n  - CuDNN 7.6.5\n  - Magma 2.5.2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, \n', 'TorchVision': '0.11.3+cu102', 'OpenCV': '4.7.0', 'MMCV': '1.5.3', 'MMCV Compiler': 'n/a', 'MMCV CUDA Compiler': 'n/a', 'MMClassification': '0.25.0+unknown'}

### 其他信息

1. 我在train.py中加入了如下代码固定种子：
```python
import random
import numpy as np
def setup_seed(seed):
     torch.manual_seed(seed)
     torch.cuda.manual_seed_all(seed)
     np.random.seed(seed)
     random.seed(seed)
     torch.backends.cudnn.deterministic = True
# 设置随机数种子
setup_seed(20)
torch.backends.cudnn.benchmark = True
```
2. 我注意到这个模型的权重文件在该模型上传6天前产生，所以我怀疑，上述页面的权重文件与代码仓库中的配置有部分出入

**Comment by pedant235** [comment]
[20230331_112809.txt](https://github.com/open-mmlab/mmclassification/files/11147408/20230331_112809.txt)
[20230403_100013.txt](https://github.com/open-mmlab/mmclassification/files/11147409/20230403_100013.txt)
上传日志文件

**Comment by Ezra-Yu** [comment]
部分模型我们是从原repo转换而来，不保证其训练精度！
![image](https://user-images.githubusercontent.com/18586273/229766704-ea3dafc8-61ac-4fdb-9d3c-02d74f4526a7.png)。
` efficientnet-b2` 的模型权重是有谷歌使用tf且使用了额外的数据以及训练技巧训练的。

训练得到的checkpoint，包括了模型本身的权重，优化器信息，以及模型数据集meta信息，如果使用了ema，还包含了EMA模型。我们readme中给出的模型只有权重，所以小不少。

**Comment by pedant235** [comment]
> 部分模型我们是从原repo转换而来，不保证其训练精度！ ![image](https://user-images.githubusercontent.com/18586273/229766704-ea3dafc8-61ac-4fdb-9d3c-02d74f4526a7.png)。 ` efficientnet-b2` 的模型权重是有谷歌使用tf且使用了额外的数据以及训练技巧训练的。
> 
> 训练得到的checkpoint，包括了模型本身的权重，优化器信息，以及模型数据集meta信息，如果使用了ema，还包含了EMA模型。我们readme中给出的模型只有权重，所以小不少。

感谢解答
