### ISSUE TITLE
Low gpu utilization in test

### ISSUE THREAD

**Issue by penghaozhou** [open-mmlab/mmclassification#148]
Hi, I found the GPU utilization is very low (about 10%) in test time but about 90% in train time, which proves that the problem is not caused by preprocessing data.
Could you give any idea about improving the GPU utilization, Thank you!

**Comment by mzr1996** [comment]
Can you provide your environment information?
And you said "proves that the problem is not caused by preprocessing data", any more information about it?

**Comment by tonysy** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you still encounter this issue with the latest stable version. You can also contribute directly by creating a PR

Thank you!
