### ISSUE TITLE
TypeError: simple_test() got an unexpected keyword argument 'img_metas'

### ISSUE THREAD

**Issue by DreamerDoReMi** [open-mmlab/mmclassification#154]
here is my config information`model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=18,
        num_stages=4,
        out_indices=(3, ),
        style='pytorch'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=2,
        in_channels=512,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0)))
dataset_type = 'Fence'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomResizedCrop', size=224),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(256, -1)),
    dict(type='CenterCrop', crop_size=224),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
data = dict(
    samples_per_gpu=32,
    workers_per_gpu=1,
    train=dict(
        type='Fence',
        data_prefix=
        '/worker/wuyahui/workspace/dataset/fenceClassification/imgs',
        ann_file=
        '/worker/wuyahui/workspace/dataset/fenceClassification/meta/train.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=(256, -1)),
            dict(type='CenterCrop', crop_size=224),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='ToTensor', keys=['gt_label']),
            dict(type='Collect', keys=['img', 'gt_label'])
        ]),
    val=dict(
        type='Fence',
        data_prefix=
        '/worker/wuyahui/workspace/dataset/fenceClassification/imgs',
        ann_file=
        '/worker/wuyahui/workspace/dataset/fenceClassification/meta/val.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=(256, -1)),
            dict(type='CenterCrop', crop_size=224),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='ToTensor', keys=['gt_label']),
            dict(type='Collect', keys=['img', 'gt_label'])
        ]),
    test=dict(
        type='Fence',
        data_prefix=
        '/worker/wuyahui/workspace/dataset/fenceClassification/imgs',
        ann_file=
        '/worker/wuyahui/workspace/dataset/fenceClassification/meta/val.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=(256, -1)),
            dict(type='CenterCrop', crop_size=224),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='ToTensor', keys=['gt_label']),
            dict(type='Collect', keys=['img', 'gt_label'])
        ]))
evaluation = dict(interval=1, metric='accuracy')
optimizer = dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='step', step=[30, 60, 90])
runner = dict(type='EpochBasedRunner', max_epochs=100)
checkpoint_config = dict(interval=1)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1), ('val', 1)]
work_dir = './work_dirs/resnet18_b32x8_imagenet'
gpu_ids = range(0, 1)`

The training stage is normal. but when it comes to evaluation, I got this error.
'TypeError: simple_test() got an unexpected keyword argument 'img_metas''

Is this a mmcv version problem ?

Great thanks to anyone help me figurethis out.

**Comment by ycxioooong** [comment]
Hi @DreamerDoReMi, this bug is fixed by https://github.com/open-mmlab/mmclassification/pull/152, please update your mmclassification.

**Comment by DreamerDoReMi** [comment]
> Hi @DreamerDoReMi, this bug is fixed by #152, please update your mmclassification.

Hi @ycxioooong ， thanks for replying. I tried to update mmclassification, but I still met the same problem. Could you give some hints to fix this bug? Is it possible there is something wrong with configuration file?

**Comment by DreamerDoReMi** [comment]
@ycxioooong Thanks man. Your are right. I fixed it.
