### ISSUE TITLE
SeResnet50 pretrained model mismatch

### ISSUE THREAD

**Issue by zhangliukun** [open-mmlab/mmclassification#17]
- Question: I use the SeResnet config and the num_classes is 7.  My pretrained model is the  se-resnet50_batch256_20200708-657b3c36.pth download from this project's model zoo.  However, I get the following log, which has lots of unexpected key in source state_dict. why?

- log:
size mismatch for head.fc.weight: copying a param with shape torch.Size([1000, 2048]) from checkpoint, the shape in current model is torch.Size([7, 2048]).
size mismatch for head.fc.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape in current model is torch.Size([7]).
unexpected key in source state_dict: backbone.layer1.0.se_layer.conv1.weight, backbone.layer1.0.se_layer.conv1.bias, backbone.layer1.0.se_layer.conv2.weight, backbone.layer1.0.se_layer.conv2.bias, backbone.layer1.1.se_layer.conv1.weight, backbone.layer1.1.se_layer.conv1.bias, backbone.layer1.1.se_layer.conv2.weight, backbone.layer1.1.se_layer.conv2.bias, backbone.layer1.2.se_layer.conv1.weight, backbone.layer1.2.se_layer.conv1.bias, backbone.layer1.2.se_layer.conv2.weight, backbone.layer1.2.se_layer.conv2.bias, backbone.layer2.0.se_layer.conv1.weight, backbone.layer2.0.se_layer.conv1.bias, backbone.layer2.0.se_layer.conv2.weight, backbone.layer2.0.se_layer.conv2.bias, backbone.layer2.1.se_layer.conv1.weight, backbone.layer2.1.se_layer.conv1.bias, backbone.layer2.1.se_layer.conv2.weight, backbone.layer2.1.se_layer.conv2.bias, backbone.layer2.2.se_layer.conv1.weight, backbone.layer2.2.se_layer.conv1.bias, backbone.layer2.2.se_layer.conv2.weight, backbone.layer2.2.se_layer.conv2.bias, backbone.layer2.3.se_layer.conv1.weight, backbone.layer2.3.se_layer.conv1.bias, backbone.layer2.3.se_layer.conv2.weight, backbone.layer2.3.se_layer.conv2.bias, backbone.layer3.0.se_layer.conv1.weight, backbone.layer3.0.se_layer.conv1.bias, backbone.layer3.0.se_layer.conv2.weight, backbone.layer3.0.se_layer.conv2.bias, backbone.layer3.1.se_layer.conv1.weight, backbone.layer3.1.se_layer.conv1.bias, backbone.layer3.1.se_layer.conv2.weight, backbone.layer3.1.se_layer.conv2.bias, backbone.layer3.2.se_layer.conv1.weight, backbone.layer3.2.se_layer.conv1.bias, backbone.layer3.2.se_layer.conv2.weight, backbone.layer3.2.se_layer.conv2.bias, backbone.layer3.3.se_layer.conv1.weight, backbone.layer3.3.se_layer.conv1.bias, backbone.layer3.3.se_layer.conv2.weight, backbone.layer3.3.se_layer.conv2.bias, backbone.layer3.4.se_layer.conv1.weight, backbone.layer3.4.se_layer.conv1.bias, backbone.layer3.4.se_layer.conv2.weight, backbone.layer3.4.se_layer.conv2.bias, backbone.layer3.5.se_layer.conv1.weight, backbone.layer3.5.se_layer.conv1.bias, backbone.layer3.5.se_layer.conv2.weight, backbone.layer3.5.se_layer.conv2.bias, backbone.layer4.0.se_layer.conv1.weight, backbone.layer4.0.se_layer.conv1.bias, backbone.layer4.0.se_layer.conv2.weight, backbone.layer4.0.se_layer.conv2.bias, backbone.layer4.1.se_layer.conv1.weight, backbone.layer4.1.se_layer.conv1.bias, backbone.layer4.1.se_layer.conv2.weight, backbone.layer4.1.se_layer.conv2.bias, backbone.layer4.2.se_layer.conv1.weight, backbone.layer4.2.se_layer.conv1.bias, backbone.layer4.2.se_layer.conv2.weight, backbone.layer4.2.se_layer.conv2.bias

**Comment by zhangliukun** [comment]
checkpoint['state_dict']['backbone.layer3.4.se_layer.conv1.conv.bias'] 
I find that the model's state_dict is not match when the key is related to the 'se_layer'.  there has a 'conv' following every se_layer.conv1 which leads to the mismatch. 

How to fix it ?

**Comment by yl-1993** [comment]
Hi @zhangliukun , thanks for reporting. @xiaojieli0903 will help update the pretrained SEResNet with correct keys.

**Comment by xiaojieli0903** [comment]
Hi @zhangliukun, the corrected SEResNet models have been uploaded in the latest version.

**Comment by liweizhong666** [comment]
How to solve this problem? The pre-training model is 1000 categories, I want to train 5 categories, the categories are not consistent.
How to modify the weights that only load the first few layers of the model, not the fully connected layer? Where is the relevant code?
Thanks

**Comment by xiaojieli0903** [comment]
You can specify the  `pretrained` when you write the config of the head. For example, you can replace `pretrained=None` to `pretrained=path_to_your_pretrained_model` in https://github.com/open-mmlab/mmclassification/blob/master/docs/tutorials/finetune.md#modify-head. 
But you have to replace `backbone.*` to `*` in keys of the pretrained model downloaded from https://github.com/open-mmlab/mmclassification/blob/master/docs/model_zoo.md.
