### ISSUE TITLE
multiple images test

### ISSUE THREAD

**Issue by jacktkk** [open-mmlab/mmclassification#170]
Sorry to bother you, I wonder how to perform multiple images testing?
Thanks for your reply.

**Comment by LXXXXR** [comment]
Hi,
You may use `tools/test.py`. And you can find a detailed tutorial here:https://github.com/open-mmlab/mmclassification/blob/master/docs/getting_started.md . Pls let me know if you have any further questions.

**Comment by jacktkk** [comment]
Thanks for your answer and it works~
