### ISSUE TITLE
Incorrect order of samples in distributed test

### ISSUE THREAD

**Issue by mzr1996** [open-mmlab/mmclassification#173]
When use distributed cluster test checkpoint, the test results is different with local test. That should be caused by incorrect samples' order.
I tried outputting the samples' order in `evaluate` function of `BaseDataset`, and get results as below (`-gres=gpu:8` and `samples_per_gpu=32`):
![深度截图_选择区域_20210309141846](https://user-images.githubusercontent.com/26739999/110427297-7d6a1300-80e2-11eb-8b7a-8a945b6f4448.png)
After `results=np.vstack(results)`, its order won't still match gt_label's order.

**Comment by LXXXXR** [comment]
Hi,
Thank you for the feedback. 
I am not quite sure how you obtained the "samples order". I assume you were running `test.py` and intended to examine if the order of results matches that of gt_labels. In this case, I suggest dumping the output after gpu collect and check if you could get what you want.

**Comment by mzr1996** [comment]
> Hi,
> Thank you for the feedback.
> I am not quite sure how you obtained the "samples order". I assume you were running `test.py` and intended to examine if the order of results matches that of gt_labels. In this case, I suggest dumping the output after gpu collect and check if you could get what you want.

Well, I add a key `index` in `load_annotation` function, and collect it in pipelines.
Then, I modified `ImageClassifier`-`simple_test` function to return this index.
Finally, I output `results` in `BaseDataset`--`evaluate` function item by item.
So I think this output is after gpu collect

**Comment by mzr1996** [comment]
Ok, I have found what causes it.
https://github.com/open-mmlab/mmclassification/blob/affb39fe07309bb1ce27e0f727d92a49dc65da61/mmcls/apis/test.py#L100-L103
Here, if the return value of the head's `simple_test` is not a list, `results` will append it. 
However, the return value usually includes a batch of results.
Assume there are two gpu, and the batch size is 3.
```
# if result is list:
results = [1,3,5,7,9,11]     # gpu 0
results = [2,4,6,8,10,12]    # gpu 1
# if result is not list, is an array for example:
results = [array([1, 3, 5]), array([7, 9, 11])]     # gpu 0
results = [array([2, 4, 6]), array([8, 10, 12])]    # gpu 1
```
After `collect_results_gpu`, results will become:
```
# if result is list:
results = [1,2,3,4,5,6,7,8,9,10,11]
# if result is not list, is an array for example:
results = [array([1, 3, 5]), array([2, 4, 6]), array([ 7,  9, 11]), array([ 8, 10, 12])]
```
Therefore, I think we need `assert isinstance(result, list)` or to show a warning if the `result` is not a list.
