### ISSUE TITLE
Training Val is not working (Precision recall and f1 at 50 always)

### ISSUE THREAD

**Issue by aina1997** [open-mmlab/mmclassification#174]
I have a dataset of two classes and in the training the values are not coherent. They are the same. The dataset is unbalanced and I don't know if it could be a problem in this case. The values of validation do not change during the training but the values of the training does. This is the output:

{'accuracy_top-1': 100.0, 'accuracy_top-5': 100.0, 'support': 15.0, 'precision': 50.0, 'recall': 50.0, 'f1_score': 50.0}

**Comment by LXXXXR** [comment]
Hi,
Thank you for the feedback. 
I am not sure how unbalanced your dataset is. Does the validation dataset at least contain sample from both classes?
It seems that your dataset is quite small. I would suggest that you could run a test and examine the outputs for each sample to see what went wrong.

**Comment by tonysy** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you still encounter this issue with the latest stable version. You can also contribute directly by creating a PR

Thank you!
