### ISSUE TITLE
unexpected key in source state_dict: backbone.conv1.weight, backbone.bn1.weight，and missing keys in source state_dict: conv1.weight, bn1.weight, bn1.bias, bn1.running_mean, bn1.running_var, layer1.0.conv1.weight,

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmclassification#18]
I think your pretrained model have a 'backbone' prefix for the key, how to fix it ? Will the weights loaded to the model ?

**Comment by xiaojieli0903** [comment]
Hi @clw5180 , Please tell me which pretrained model do you load when you encounter this problem. And can you provide the running code?
