### ISSUE TITLE
no tools/inference.py

### ISSUE THREAD

**Issue by Williamlizl** [open-mmlab/mmclassification#185]
There is no file : tools/inference.py

**Comment by LXXXXR** [comment]
Hi, 
You may use tools/test.py to perform inference.

**Comment by Williamlizl** [comment]
> Hi,
> You may use tools/test.py to perform inference.

I try to save the result with the argument "--out" , '--out', help='output result file'。out is the path?
`TypeError: Unsupported format: /home/lbc/mmclassification/results/3_25`

**Comment by LXXXXR** [comment]
Yes, pls specify a valid output result file. Supported formats include json or pkl.

**Comment by Williamlizl** [comment]
> Hi,
> You may use tools/test.py to perform inference.

I try to save the result with the argument "--out" , '--out', help='output result file'。out is the path?
`TypeError: Unsupported format: /home/lbc/mmclassification/results/3_25`

> Yes, please specify a valid output result file. Supported formats include json and pkl.

If I want to see which picture is classified wrong, is there easy way?

**Comment by LXXXXR** [comment]
You could compare the predicted labels with the gts. Or you could try tools/analyze_results.py to get visualized results.

**Comment by Williamlizl** [comment]
> You could compare the predicted labels with the gts. Or you could try tools/analyze_results.py to get visualized results.

Yep, I mean which file  I could see the predicted results?

**Comment by LXXXXR** [comment]
In the --out you specified.

**Comment by Williamlizl** [comment]
> In the `--out` you specified.

In the '--out', it just shows the precision, maybe something else is wrong, I check

**Comment by LXXXXR** [comment]
Have you specified the `--metrics`? Please remove it.

**Comment by Williamlizl** [comment]
> Have you specified the `--metrics`? Please remove it.

I see the right result, thank u

**Comment by LXXXXR** [comment]
My pleasure.
