### ISSUE TITLE
How to show the feature vectors while inference image?

### ISSUE THREAD

**Issue by ryan994** [open-mmlab/mmclassification#195]
Hello, 
Due to some researches and curious, I tried to print out some feature vectors during inferencing image.
I only find this command when model inferences image:
scores = model(return_loss=False, **data),
which returns a list :
[array([1.2522009e-02, 9.9847050e-08, 9.8747790e-01], dtype=float32)].
what if I want to see the feature vectors of fc layer whild model inferences an image ,how should I do? Not weights in pretrain model file .pth.

Thanks

**Comment by mzr1996** [comment]
I think you need to use breakpoint or add log output where you want to output feature vector.
For example, if you use `LinearClsHead`, you need to add it before final fc layer.
https://github.com/open-mmlab/mmclassification/blob/ace09510f700d3f8583e19c993113491cfd10ce4/mmcls/models/heads/linear_head.py#L37-L39

**Comment by mzr1996** [comment]
Closed by #593
