### ISSUE TITLE
data loading in each epoch starting is slow!

### ISSUE THREAD

**Issue by wanghao9610** [open-mmlab/mmclassification#196]
Hi, did anyone got stuck in the issue that data loading for ImageNet is slow in each epoch starting, how to fix it in open-mmlab repository(the same issue also exists in mmseg, mmdet et al.)?

**Comment by mzr1996** [comment]
Hello, I think that's a PyTorch issue refers to https://discuss.pytorch.org/t/enumerate-dataloader-slow/87778.
You can try to modify dataloader by setting `persistent_workers=True`to get epochs starting faster (except the first).
https://github.com/open-mmlab/mmclassification/blob/09597e5a4c7a995c4cd81fc5396f56a6a0f43e37/mmcls/datasets/builder.py#L89-L98
However, this param is added in PyTorch 1.7 and now we cannot add it to this repo for compatibility.

**Comment by mzr1996** [comment]
Now, `persistent_workers=True` will be used if available.
