### ISSUE TITLE
Training freezes

### ISSUE THREAD

**Issue by digantamisra98** [open-mmlab/mmclassification#199]
Training any config on adequate compute is just freezing for some reason. The progress bar just gets stuck, with no error trace. This for a ResNet-50 CIFAR model with batch size 128 and using a P100, T4 and even a Quadro M4000 GPU. 
<img width="1060" alt="Screenshot 2021-04-03 at 11 50 08 AM" src="https://user-images.githubusercontent.com/34192716/113470388-c491bc80-9472-11eb-89b6-18fe3b33c3d8.png">

**Comment by ycxioooong** [comment]
Could you please also report the environment you are using? (e.g., system version, PyTorch version, CUDA version, etc)?

**Comment by digantamisra98** [comment]
Machine Specifications:

##### `nvcc --version`: 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
```
##### GPU: NVIDIA P100

##### CPU: 8 vCPUs, 30 GB RAM

##### PyTorch version: 1.8.0+cu111

##### Storage: 100 GB


However, this is happening in all my instances and not just the one reported above

**Comment by ZwwWayne** [comment]
30GB RAM might not be  sufficient. You may try to use smaller batch size and set the workers_per_gpu=0 and see the outcomes? Furthermore, does the program stuck at a similar place every time?

**Comment by digantamisra98** [comment]
@ZwwWayne This is for CIFAR-10 and it was working fine for the same config a week ago but suddenly started freezing for all my runs last week. Additionally, no they don't get stuck at the same epoch, one got stuck at 195th epoch.

**Comment by ZwwWayne** [comment]
Did you pull the code? If not, it means that the program stuck using a similar code. We are not able to do much help here.

**Comment by digantamisra98** [comment]
Ah okay, I guess, it's some issue on my end
