### ISSUE TITLE
HOW TO USE AUTO AUG POLICES？

### ISSUE THREAD

**Issue by rhythm-A** [open-mmlab/mmclassification#205]

**Comment by LXXXXR** [comment]
Hi @rhythm-A,
You may add AutoAugment in the train pipeline,
``` python
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='AutoAugment', policies=policies),
    dict(type='RandomResizedCrop', size=224),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
```
and specify the policies in the format of `list[list[dict]]`, such as:
``` python
policies = [
    [
        dict(type='Posterize', bits=4, prob=0.4),
        dict(type='Rotate', angle=30., prob=0.6)
    ],
    [
        dict(type='Solarize', thr=256 / 9 * 4, prob=0.6),
        dict(type='AutoContrast', prob=0.5)
    ]]
```
Unfortunately we currently do not support searching the policy yet.

**Comment by d-li14** [comment]
@LXXXXR Could you please provide the config of AutoAug applied to ImageNet? Thanks.

**Comment by LXXXXR** [comment]
Hi @d-li14 ,
We will release the config with ViT training config, which shall also be in this month release version.

**Comment by d-li14** [comment]
Hi @LXXXXR 
I notice most recent ViT variants are trained with RandAug, following the training recipe of [DeiT](https://arxiv.org/abs/2012.12877). So which AutoAug policy will you use? Is it exactly the one provided in the original paper https://arxiv.org/abs/1805.09501? Thanks.

**Comment by LXXXXR** [comment]
Hi @d-li14,
Sorry for the late reply.
We are still experimenting on the training recipe. We currently use the policy from original paper. Unfortunately the code was not released with the paper, so we follow the widely adopted third party implementation: https://github.com/DeepVoltaire/AutoAugment and it seems to give the performance an increase of 0.98%. The only difference is that we use cv2 as backend instead of pillow.

**Comment by d-li14** [comment]
Hi @LXXXXR 
Thanks, I see it. It is also interesting to see that the ViT's accuracy is clearly improved with AutoAug instead of the officially suggested RandAug.

**Comment by mzr1996** [comment]
The question looks solved.
