### ISSUE TITLE
How to train a custom multi-label dataset? 

### ISSUE THREAD

**Issue by Kyuuki93** [open-mmlab/mmclassification#215]

**Comment by LXXXXR** [comment]
Hi @Kyuuki93 ,
First, you need to convert your dataset to existing dataset format, e.g. VOC format or implement a new Dataset class inherited from `BaseDataset`. Pls refer to [Tutorial 2: Adding New Dataset](https://github.com/open-mmlab/mmclassification/blob/master/docs/tutorials/new_dataset.md) for more info.
Then, you can write a config as [config for VGG](https://github.com/open-mmlab/mmclassification/blob/master/configs/vgg/vgg16_b16x8_voc.py).

**Comment by Kyuuki93** [comment]
> Hi @Kyuuki93 ,
> First, you need to convert your dataset to existing dataset format, e.g. VOC format or implement a new Dataset class inherited from `BaseDataset`. Pls refer to [Tutorial 2: Adding New Dataset](https://github.com/open-mmlab/mmclassification/blob/master/docs/tutorials/new_dataset.md) for more info.
> Then, you can write a config as [config for VGG](https://github.com/open-mmlab/mmclassification/blob/master/configs/vgg/vgg16_b16x8_voc.py).

Thanks for ur quick reply, I have prepared a toy `FileList` dataset , the anno_file looks like
```
001.jpg 0
002.jpg 1
003.jpg 0 1
``` 
And then created a `TestDataset` which modified from `mmcls\datasets\multi_label.py`,  use mobilenet as backbone,
then I got 
```
TypeError: ImageClassifier: MultiLabelClsHead: __init__() got an unexpeted keywork argument 'num_classes'
TypeError: ImageClassifier: MultiLabelClsHead: __init__() got an unexpeted keywork argument 'in_channels'
```

Does `multi-label task` only support `vgg` for now?

**Comment by LXXXXR** [comment]
For your dataset, it seems like imagenet format, which is not supported for multi-label classification task. You might need to convert it to VOC format.
For VGG backbone, we put the final fc layer inside the backbone rather than put it in the head. So `MultiLabelClsHead` does not expect argument `num_classes` and `in_channels`. If you want use other backbones, you might need to use `MultiLabelLinearClsHead`. Thank you.

**Comment by ccxi1008** [comment]
> For your dataset, it seems like imagenet format, which is not supported for multi-label classification task. You might need to convert it to VOC format. For VGG backbone, we put the final fc layer inside the backbone rather than put it in the head. So `MultiLabelClsHead` does not expect arguments `num_classes` and `in_channels`. If you want use other backbones, you might need to use `MultiLabelLinearClsHead`. Thank you.

Hi, I want to train multi-label on my own dataset, how should I organize my data folder and train use the config file? I found these 2 templates seem to be like multi-label:

<img width="1344" height="788" alt="Image" src="https://github.com/user-attachments/assets/5887e439-71e6-46af-8d77-5a0e09d76683" />

<img width="1142" height="1272" alt="Image" src="https://github.com/user-attachments/assets/b00268f8-6347-4fe5-b39b-68ca756aed83" />
Can I directly use them like this?:(how should I prepare anno files?) Or I should use the MultilabelDataset class? And how?

<img width="1034" height="382" alt="Image" src="https://github.com/user-attachments/assets/c24df465-1645-4336-acf2-90e7abd8e147" />
