### ISSUE TITLE
The annotation of AlexNet has some error

### ISSUE THREAD

**Issue by RishengDeng** [open-mmlab/mmclassification#23]
I believe that the annotation of AlexNet is incorrect. The input of AlexNet should be 224*224 RGB image, rather than 256*256 according to the classifier.

**Comment by yl-1993** [comment]
@RishengDeng Thanks for reporting. The model is alright but the docstring of AlexNet should be revised to 224x224.

**Comment by hellock** [comment]
Fixed in #26
