### ISSUE TITLE
[Refactor]: Use MMCV model registry

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmclassification#234]
To enable MMDet and MMSeg to use the backbones supported in MMClassification, MMClassification should update their model registry and inherit them from MMCV.

related PR https://github.com/open-mmlab/mmcv/pull/760, https://github.com/open-mmlab/mmdetection/pull/5059

**Comment by mzr1996** [comment]
https://github.com/open-mmlab/mmclassification/pull/252 has been merged, anything else needed to do?
