### ISSUE TITLE
Compatibility of MMClassificationwith older MMCV versions

### ISSUE THREAD

**Issue by Hrayo712** [open-mmlab/mmclassification#235]
Hi,

I have some legacy code that is working on MMCV 0.2.10. I'd like to use MMClassification without having to update MMCV. Is there a MMClassification version compatible with MMCV 0.2.10 ?

My use case is limited to training mobilenetv2-like architectures.

Thanks a lot in advance for the input

Regards

**Comment by LXXXXR** [comment]
Hi @Hrayo712,
Sorry about the inconvenience, but I am afraid our initial release was based on MMCV 1.1.4, as the [documentation](https://github.com/open-mmlab/mmclassification/blob/master/docs/install.md) indicates.

**Comment by Hrayo712** [comment]
Thanks for the input!
