### ISSUE TITLE
Reuse of the inverted residual module

### ISSUE THREAD

**Issue by RangiLyu** [open-mmlab/mmclassification#246]
Hi mmcls team, I notice that the implementations of MobileNetV2 and V3 use two different inverted residual modules. 
Since the MobileNet series and EfficientNet series share the same basic block, is there any plan to reuse the inverted residual implementation?

**Comment by ZwwWayne** [comment]
Kindly ping @ycxioooong

**Comment by ycxioooong** [comment]
Thanks for your suggestion. Actually, we are also working on this issue. New MobileNet implementation is expected in the next release.

**Comment by ycxioooong** [comment]
And we will fix this after providing updated MobileNet models.

**Comment by tonysy** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you still encounter this issue with the latest stable version. You can also contribute directly by creating a PR

Thank you!
