### ISSUE TITLE
RegNet and MobileNetV3 Pretrain Model Download

### ISSUE THREAD

**Issue by flyingTan** [open-mmlab/mmclassification#261]
Could u provide regnet and mobilnetv3 pretrain model  download link?

**Comment by mzr1996** [comment]
Hello, the pretrain model of mobilenet v3 is still in training, we are trying to improve the training recipe to get higher accuracy.
Please refer to #193 
As for RegNet, I'm sorry that we don't have training configs for now. And we will add it later.

**Comment by mzr1996** [comment]
Hello, we have supported the RegNet pretrain model, which refers to https://github.com/open-mmlab/mmclassification/tree/master/configs/regnet

**Comment by mzr1996** [comment]
Hello, we have supported the MobilenetV3 pretrain model, which refers to https://github.com/open-mmlab/mmclassification/tree/master/configs/mobilenet_v3#pretrain-model
