### ISSUE TITLE
ImportError: cannot import name 'MODELS' from 'mmcv.cnn'

### ISSUE THREAD

**Issue by freepoet** [open-mmlab/mmclassification#263]
when i implemnet  `python demo/image_demo.py demo/demo.JPEG configs/resnet/resnet50_b32x8_imagenet.py checkpoints/resnet50-19c8e357.pth`
it reported a error:

> ImportError: cannot import name 'MODELS' from 'mmcv.cnn' (/home/n/anaconda3/envs/pytorch160/lib/python3.7/site-packages/mmcv/cnn/__init__.py)

Here are the details：

> (pytorch160) root@Ubuntu20:/home/n/Github/mmclassification0110/mmclassification# python demo/image_demo.py demo/demo.JPEG configs/resnet/resnet50_b32x8_imagenet.py checkpoints/resnet50-19c8e357.pth
> Traceback (most recent call last):
>   File "demo/image_demo.py", line 3, in<module
>     from mmcls.apis import inference_model, init_model, show_result_pyplot
>   File "/home/n/Github/mmclassification0110/mmclassification/mmcls/apis/__init__.py", line 1, in module
>   from .inference import inference_model, init_model, show_result_pyplot
>   File "/home/n/Github/mmclassification0110/mmclassification/mmcls/apis/inference.py", line 10, in modulefrom mmcls.datasets.pipelines import Compose
>   File "/home/n/Github/mmclassification0110/mmclassification/mmcls/datasets/__init__.py", line 1, in module from .base_dataset import BaseDataset
>   File "/home/n/Github/mmclassification0110/mmclassification/mmcls/datasets/base_dataset.py", line 9, in module from mmcls.models.losses import accuracy
>   File "/home/n/Github/mmclassification0110/mmclassification/mmcls/models/__init__.py", line 1, in module from .backbones import *  # noqa: F401,F403
>   File "/home/n/Github/mmclassification0110/mmclassification/mmcls/models/backbones/__init__.py", line 1, in modulefrom .alexnet import AlexNet
>   File "/home/n/Github/mmclassification0110/mmclassification/mmcls/models/backbones/alexnet.py", line 3, in module from ..builder import BACKBONES
>   File "/home/n/Github/mmclassification0110/mmclassification/mmcls/models/builder.py", line 1, in module  from mmcv.cnn import MODELS as MMCV_MODELS
> ImportError: cannot import name 'MODELS' from 'mmcv.cnn' (/home/n/anaconda3/envs/pytorch160/lib/python3.7/site-packages/mmcv/cnn/__init__.py)

my env:
python:3.7
torch:1.6.0
mmcls:0.11.0
mmcv:1.3.0
it seems meet  the requirements in the install document.

btw, my conda env name is **pytorch160**, this env also include **mmdet 2.11.0**package. it will influence **mmcls 0.11.0**?

**Comment by freepoet** [comment]
I solved this problem by create anothor env ,it includes:
**python:3.7
torch:1.3.0
mmcls:0.11.0
mmcv:1.3.4** 
it seems torch's version shouldn't be too higher

**Comment by mzr1996** [comment]
I think that's not because of torch's version, should because of mmcv version.
`MODELS` in `mmcv.cnn` is added recently.

**Comment by freepoet** [comment]
> I think that's not because of torch's version, should because of mmcv version.
> `MODELS` in `mmcv.cnn` is added recently.

 Yes,you are right. I find this [commit in Apr 10,2021](https://github.com/open-mmlab/mmcv/commit/375605fba8f89f40eb1b6b67b4aab83fbe769098#diff-a5d58c22b815eafb2e4c39b11e0c596df245976bb8256351514f111d3a203667),it add MODELS
