### ISSUE TITLE
[Feature Request] CPU Testing

### ISSUE THREAD

**Issue by kennymckormick** [open-mmlab/mmclassification#277]
Since CPU training is already supported in PR #219, what about also adding the feature of CPU testing. 

Besides, it seems there are still some problems with the CPU training feature @wangruohui : 
When we set `--device CPU`, the expected behavior is using CPU for training, no matter if there exist GPUs on this machine. However, mmcls will use GPU for training if it exists, even if we set `--device CPU`.

**Comment by wangruohui** [comment]
https://github.com/open-mmlab/mmclassification/pull/286

**Comment by wangruohui** [comment]
https://github.com/open-mmlab/mmclassification/pull/286
