### ISSUE TITLE
wanna load tfrecord style dataset

### ISSUE THREAD

**Issue by cww97** [open-mmlab/mmclassification#281]
when train on imagenet, using multple GPUs
some efficient nets such as mobilenet or resnet50
I find more than 90% time is spent on data, and the GPU usage is less than 10%, while in one GPU this nubmer is about 50%.
so tfrecord, u know what I mean

**Comment by Ezra-Yu** [comment]
We are going to support  tfrecord backend.

By default, LoadImageFromFile loads images from disk but it may lead to IO bottleneck for efficient small models. Various backends are supported by mmcv to accelerate this process.

Both tfrecord and memcache are key-value pair data reading methods.For example, if the training machines have setup memcached, we can revise the config as follows.
`
memcached_root = '/mnt/xxx/memcached_client/'
train_pipeline = [
    dict(
        type='LoadImageFromFile',
        file_client_args=dict(
            backend='memcached',
            server_list_cfg=osp.join(memcached_root, 'server_list.conf'),
            client_cfg=osp.join(memcached_root, 'client.conf'))),
]
`

More supported backends can be found in [https://github.com/open-mmlab/mmcv/blob/master/mmcv/fileio/file_client.py](mmcv.fileio.FileClient) , including HardDiskBackend, CephBackend,MemcachedBackend,LmdbBackend,PetrelBackend, HTTPBackend.

**Comment by Ezra-Yu** [comment]
We are going to support tfrecord backend.

By default, LoadImageFromFile loads images from disk but it may lead to IO bottleneck for efficient small models. Various backends are supported by mmcv to accelerate this process.

For example, if the training machines have setup memcached.Both tfrecord and memcache are key-value pair data reading methods. We can revise the config as follows.

```
memcached_root = '/mnt/xxx/memcached_client/'      
  train_pipeline = [  
    dict(  
        type='LoadImageFromFile',   
        file_client_args=dict(   
            backend='memcached',  
            server_list_cfg=osp.join(memcached_root, 'server_list.conf'),  
            client_cfg=osp.join(memcached_root, 'client.conf'))),  
]  
```

More supported backends can be found in [mmcv/fileio/file_client](https://github.com/open-mmlab/mmcv/blob/master/mmcv/fileio/file_client.py) , including HardDiskBackend, CephBackend,MemcachedBackend,LmdbBackend,PetrelBackend, HTTPBackend.
