### ISSUE TITLE
How to input 3D dataset？Such as *.npy

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#294]
Hi, dear authors!
Sorry to bother you.
Could you tell me how to input 3D dataset(such as *.npy)？Because I want to do 3D classification with `mmcls`.
And does `mmcls` support 3D classification?

Thank you!

**Comment by mzr1996** [comment]
MMClassification only supports 2D image classification by now.
Considering 3D point clouds need quite different pipelines comparing with 2D images, it's hard to support 3D classification recently.
However, it's much simpler to support 3D classification in [mmdet3d](https://github.com/open-mmlab/mmdetection3d), and you can create an issue in the mmdet3d repo.

**Comment by zhongqiu1245** [comment]
Thank you！
