### ISSUE TITLE
Can we also compute validation loss ?

### ISSUE THREAD

**Issue by hasanirtiza** [open-mmlab/mmclassification#296]
My question is, given the current architecture, can we also compute validation loss. I know, by default we compute the accuracy, but is there a way to also compute validation loss; besides modifying the code ?

**Comment by Ezra-Yu** [comment]
I am sorry. In current architecture, we can not compute validation loss, besides modifying the code.
In https://github.com/open-mmlab/mmclassification/blob/master/mmcls/apis/test.py, line 26.
Modify `return_loss=False` to  `return_loss=True`.

We will evaluate whether to add this feature in the repo.
