### ISSUE TITLE
Freeze the network mmclassification (frozen_satage in mmdetection)

### ISSUE THREAD

**Issue by hasanirtiza** [open-mmlab/mmclassification#300]
Hello,
I am exploring mmclassification in detail; I want to know, if there is a way to freeze the network layers completely and train only the last fully connected or classification layer, I know how to do it in PyTorch; but I was wondering if one can do it, like it is in mmdetection `frozen_stages`.

**Comment by mzr1996** [comment]
Hello, we have `frozen_stages` in many backbones, you can simply use it by the config file.
For example, in ResNet:
https://github.com/open-mmlab/mmclassification/blob/5e1a02103f0f1f41d92477e6c352ec0c33e40d27/mmcls/models/backbones/resnet.py#L409-L410

**Comment by hasanirtiza** [comment]
Thanks, my bad did not check out the code.
