### ISSUE TITLE
Feature Request: Pre-training weight file of  Defromable Convolutional Networks

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#317]
Hi, dear authors!
Sorry to bother you.
Could you release the pre-training weight file of  Defromable Convolutional Networks?
I see that you only have the technique of turning on DCN without training files, and using the original non-DCN(such as resnet50, resnet 101) weights will result in slightly worse performance.
Please forgive my bad English.
Thank you!

**Comment by mzr1996** [comment]
Thx for your suggestion! We will evaluate it and notify you if we added it.
And if you are more familiar with Chinese, you can use Chinese.

**Comment by zhongqiu1245** [comment]
谢谢！
