### ISSUE TITLE
支持的数据增强方法有哪些呢？

### ISSUE THREAD

**Issue by cvstudy0** [open-mmlab/mmclassification#323]

**Comment by Ezra-Yu** [comment]
https://github.com/open-mmlab/mmclassification/blob/master/mmcls/datasets/pipelines/__init__.py
这个文件中显示了目前所支持的所有数据预处理方式。
对应代码在的mmcls/datasets/pipelines路径下的文件中

**Comment by mzr1996** [comment]
常规数据增强方法（参考`mmcls/datasets/pipeline/transforms.py`）：
- Random Crop
- Random Resized Crop
- Random Grayscale
- Random Flip
- Random Erasing
- Resize
- Center Crop
- Normalize
- Color Jitter
- Lighting
- Albu
组合数据增强方法（参考`mmcls/datasets/pipeline/auto_augment.py`）：
- Auto Augment
- Random Augment
