### ISSUE TITLE
请问se模块中为何没有sigmoid函数

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#327]
您好，亲爱的作者！
很抱歉打扰您一下
我看到mmcls中se模块(mmcls/models/utils/se_layer.py)中与官方的se模块有区别，mmcls中的se模块没有最后的sigmoid的函数
请问为何删去了sigmoid函数？这个是属于bug还是出于某种原因把它删去了呢？
请您赐教
谢谢！

**Comment by mzr1996** [comment]
sigmoid 作为激活函数，包含在ConvModule里
