### ISSUE TITLE
请问你们有没有尝试过在backbone中加入新模块，但不是从头训练？

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#328]
您好
抱歉打扰您一下
请问请问你们有没有尝试过在backbone中加入一个新模块，但不是从头训练，而是加载原有的权重？
比如，我在resnet18中的每个block中加入SE模块，但是我仍然利用torchvision://resnet18的原始权重初始化所有resnet18层(不包括SE)，SE则采用默认的kaiming init，这样的效果好吗？（我查看了mmcls的权重加载模式，发现即使加入新模块，mmcls也能正确的引导权重文件正确的加载在原有的层上，而新模块的初始化则是默认的kaiming init）
谢谢！

**Comment by mzr1996** [comment]
欢迎使用本框架进行实验 :smile: 
如果是功能方面的需求，欢迎提出请求。至于模型设计的效果，还请自行测试。

**Comment by zhongqiu1245** [comment]
谢谢
