### ISSUE TITLE
imagenet 的元数据一直下载不了，有别的办法获取吗？

### ISSUE THREAD

**Issue by WanglifuCV** [open-mmlab/mmclassification#329]
imagenet 的元数据一直下载不了，有别的办法获取吗？训练模型显示错误：data/imagenet/meta/val.txt 找不到

**Comment by mzr1996** [comment]
你是按照 [教程](https://github.com/open-mmlab/mmclassification/blob/master/docs_zh-CN/getting_started.md) 里的说明下载ImageNet元数据的吗？

**Comment by mzr1996** [comment]
Long time no response.
