### ISSUE TITLE
Does the weight file download do not match?

### ISSUE THREAD

**Issue by bingpo1314** [open-mmlab/mmclassification#334]
![image](https://user-images.githubusercontent.com/81397357/124053771-682f4080-da53-11eb-944d-afd560aa4e40.png)

**Comment by mzr1996** [comment]
Hello, please post the entire config file and train log

**Comment by bingpo1314** [comment]
sorry，I sent it in the wrong，it is mmocr，not mmcls。
I will resend in mmocr.



---Original---
From: "Ma ***@***.***&gt;
Date: Thu, Jul 1, 2021 10:21 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmclassification] Does the weight file download do not match? (#334)




 
Hello, please post the entire config file and train log
