### ISSUE TITLE
The epoch number of ResNet and SeResNet are different

### ISSUE THREAD

**Issue by Jun-jieChen** [open-mmlab/mmclassification#344]
Hey, author!
I found the epoch number of ResNet and SeResNet are different in `resnet50_b32x8_imagenet.py` and  `seresnet50_b32x8_imagenet.py`.

the following code in `resnet50_b32x8_imagenet.py` is:
```
_base_=[
...
    '../_base_/schedules/imagenet_bs256.py'
...
]
```
 it has 100 epochs 
, however in `seresnet50_b32x8_imagenet.py`:

```
_base_=[
...
    '../_base_/schedules/imagenet_bs256_140e.py',
...
]
```
 it has 140 epochs.
The two models with different epoch number can be compared equally?

**Comment by mzr1996** [comment]
Different networks need different epochs to converge. And usually, we only concern with the final performance of the model.
