### ISSUE TITLE
KeyError: '`cfg` or `default_args` must contain the key "type", but got 

### ISSUE THREAD

**Issue by Z-zturn** [open-mmlab/mmclassification#345]
I can normally train on mnist dataset, but fail on cifar10 and cifar100 datasets.
No matter if try ' python tools/train.py configs/resnet/resnet50_b16x8_cifar10.py' or 'python tools/train.py configs/resnet/resnet50_b16x8_cifar100.py' , it always report the error below:
![QQ图片20210706115354](https://user-images.githubusercontent.com/85380956/124539944-060a7d00-de51-11eb-8259-3842667a1c14.png)
I'm pretty sure I don't change any code, So how can I fix this problem?Thanks!
Other useful information as below:
[20210706_031801.log](https://github.com/open-mmlab/mmclassification/files/6767199/20210706_031801.log)

**Comment by mzr1996** [comment]
Please update your mmcls to the latest version and try again, thx

**Comment by mzr1996** [comment]
No update for a long time, closed.
If the problem is not solved, please open a new issue.

**Comment by kevinlikai1213** [comment]
I reinstalled the mmcls, but the problem is not solved

**Comment by batman47steam** [comment]
I have got this error too, and fixed it by check the config file

```
train_dataloader = dict(
    batch_size=32,
    num_workers=2,
    dataset=dict(
        _delete_=True,
        type=dataset_type,
        data_root='data',
        data_prefix='train',
        pipeline={{_base_.train_pipeline}}
    ),
)
```

I used `_delete_=True` in the dataset dict, but I forgot `type=dataset_type`. so that the `type` in the dict has no `value`. and got this config error, after add `type=dataset_type` the error is fixed

**Comment by daxiongpro** [comment]
> I have got this error too, and fixed it by check the config file
> 
> ```
> train_dataloader = dict(
>     batch_size=32,
>     num_workers=2,
>     dataset=dict(
>         _delete_=True,
>         type=dataset_type,
>         data_root='data',
>         data_prefix='train',
>         pipeline={{_base_.train_pipeline}}
>     ),
> )
> ```
> 
> I used `_delete_=True` in the dataset dict, but I forgot `type=dataset_type`. so that the `type` in the dict has no `value`. and got this config error, after add `type=dataset_type` the error is fixed

有用！
