### ISSUE TITLE
How can I use FPN in mmcls.

### ISSUE THREAD

**Issue by Chen94yue** [open-mmlab/mmclassification#348]
How can I use FPN in mmcls?

**Comment by mzr1996** [comment]
Are you trying to use FPN for object detection?

**Comment by Chen94yue** [comment]
I want to use FPN for multi-stage classification.

**Comment by mzr1996** [comment]
Sorry, we haven't support FPN by now.
If you're willing to implement it by yourself, you can refer to [mmdetection code](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/necks/fpn.py) and the [document](https://mmclassification.readthedocs.io/en/latest/tutorials/new_modules.html#add-new-necks). If that, we welcome you to create a Pull Request.
Or we will implement it in the future, and we will notify you that time.

**Comment by tonysy** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you still encounter this issue with the latest stable version. You can also contribute directly by creating a PR

Thank you!
