### ISSUE TITLE
dist train slow: GPU and CPU can not be fully used

### ISSUE THREAD

**Issue by YonghaoHe** [open-mmlab/mmclassification#350]
I train resnet50 on imagenet with 4 RTX 2080TI (dist train). I found that one GPU is always in very low usage, meanwhile, the utilization rate of CPU decreases too. Detailed info is listed below:
![image](https://user-images.githubusercontent.com/28685653/124849933-4ba28380-dfd2-11eb-9ba5-1652b13f9c21.png)
Typical GPU info in training:
![image](https://user-images.githubusercontent.com/28685653/124850067-92907900-dfd2-11eb-8929-0b36d03d99bc.png)

Sometimes, in the first few iters, everything works fine and 4 GPU can reach 95%+ utilization, but later, one GPU may slow down.

What I have tried:
1, increase workers per gpu (not work)
2, set env OMP_NUM_THREADS=[a large value, say 20] (not work)
3, I run mmdetection with the same environment, everything works fine (4 GPU can reach ~95% usage al the time)

Anyone have ideas?

The same code works fine in another machine (V100 x 4)

**Comment by mzr1996** [comment]
We will check it recently.

**Comment by YonghaoHe** [comment]
> We will check it recently.

It seems dataloader can not provide data in time.

**Comment by YonghaoHe** [comment]
> We will check it recently.

After many trials, I realized that when the network is light (say resnet18/34/50), the dataloader can not catch up with the batch consumption. Although dataloader is implemented using multi-processing, it can not fully use multi-core CPU. Or something wrong with my configuration?

**Comment by mzr1996** [comment]
> > We will check it recently.
> 
> After many trials, I realized that when the network is light (say resnet18/34/50), the dataloader can not catch up with the batch consumption. Although dataloader is implemented using multi-processing, it can not fully use multi-core CPU. Or something wrong with my configuration?

Maybe it's a disk problem. The random read speed of your disk cannot cover the need for Dataloader?

**Comment by YonghaoHe** [comment]
> > > We will check it recently.
> > 
> > 
> > After many trials, I realized that when the network is light (say resnet18/34/50), the dataloader can not catch up with the batch consumption. Although dataloader is implemented using multi-processing, it can not fully use multi-core CPU. Or something wrong with my configuration?
> 
> Maybe it's a disk problem. The random read speed of your disk cannot cover the need for Dataloader?

I tried with two machines (RTX TITAN x 4; RTX 2080TI x 4), the same problem remains. Indeed, my disks are HDD. I found that the ratio of CPU utilization is low. Before I use mmcls, I train resnet50 on imagenet with my own code, which can fully use all GPUs (95%+ utilization). In my own code, multi-threading is adopted for dataloader. 
So I wonder if some triggers for dataloader are off?

**Comment by mzr1996** [comment]
> > > > We will check it recently.
> > > 
> > > 
> > > After many trials, I realized that when the network is light (say resnet18/34/50), the dataloader can not catch up with the batch consumption. Although dataloader is implemented using multi-processing, it can not fully use multi-core CPU. Or something wrong with my configuration?
> > 
> > 
> > Maybe it's a disk problem. The random read speed of your disk cannot cover the need for Dataloader?
> 
> I tried with two machines (RTX TITAN x 4; RTX 2080TI x 4), the same problem remains. Indeed, my disks are HDD. I found that the ratio of CPU utilization is low. Before I use mmcls, I train resnet50 on imagenet with my own code, which can fully use all GPUs (95%+ utilization. so I think HDD is not the problem). In my own code, multi-threading is adopted for dataloader.
> So I wonder if some triggers for dataloader are off?
> 
> （This problem is very strange. If we can contact using WeChat or DingDing? I can should you something more）

The `pin_memory` option is off. If you want to change it, refers to https://github.com/open-mmlab/mmclassification/blob/1a7cebe4b90cf72e730a7066267b75561864e811/mmcls/datasets/builder.py#L95

**Comment by YonghaoHe** [comment]
> > > > > We will check it recently.
> > > > 
> > > > 
> > > > After many trials, I realized that when the network is light (say resnet18/34/50), the dataloader can not catch up with the batch consumption. Although dataloader is implemented using multi-processing, it can not fully use multi-core CPU. Or something wrong with my configuration?
> > > 
> > > 
> > > Maybe it's a disk problem. The random read speed of your disk cannot cover the need for Dataloader?
> > 
> > 
> > I tried with two machines (RTX TITAN x 4; RTX 2080TI x 4), the same problem remains. Indeed, my disks are HDD. I found that the ratio of CPU utilization is low. Before I use mmcls, I train resnet50 on imagenet with my own code, which can fully use all GPUs (95%+ utilization. so I think HDD is not the problem). In my own code, multi-threading is adopted for dataloader.
> > So I wonder if some triggers for dataloader are off?
> > （This problem is very strange. If we can contact using WeChat or DingDing? I can should you something more）
> 
> The `pin_memory` option is off. If you want to change it, refers to
> 
> https://github.com/open-mmlab/mmclassification/blob/1a7cebe4b90cf72e730a7066267b75561864e811/mmcls/datasets/builder.py#L95

The problem ramains.

**Comment by tonysy** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you still encounter this issue with the latest stable version. You can also contribute directly by creating a PR

Thank you!
