### ISSUE TITLE
请问能识别多标签分类吗

### ISSUE THREAD

**Issue by prio158** [open-mmlab/mmclassification#353]

**Comment by mzr1996** [comment]
可以的，请参考 VOC 数据类，以及相应的 [config 文件](https://github.com/open-mmlab/mmclassification/blob/1a7cebe4b90cf72e730a7066267b75561864e811/configs/vgg/vgg16_b16x8_voc.py)

**Comment by mzr1996** [comment]
如果没有什么疑问，就关闭这个issue了

**Comment by prio158** [comment]
好的，谢谢解答
