### ISSUE TITLE
[Bug] The ckpt of VGG19 is same as the ckpt of VGG19_BN

### ISSUE THREAD

**Issue by sennnnn** [open-mmlab/mmclassification#362]
### Describe the bug
Hello, mmcls developers. When I need to use VGG19 and VGG19_BN ckpt, I find that the ckpt of VGG19 is same as VGG19_BN. The ckpt of VGG19 also contains batch normalization parameters. So, the ckpt of VGG19 actually isn't the real ckpt. The current ckpt of VGG19 is just the no-BN version ckpt of VGG19_BN.

* VGG19 URL: [ckpt](https://download.openmmlab.com/mmclassification/v0/vgg/vgg19_bn_batch256_imagenet_20210208-da620c4f.pth)
* VGG19_BN URL: [ckpt](https://download.openmmlab.com/mmclassification/v0/vgg/vgg19_bn_batch256_imagenet_20210208-da620c4f.pth)

Can you benchmark VGG19 on ImageNet again? THX

**Comment by mzr1996** [comment]
Sorry, I think that's a typo, please use [this link](https://download.openmmlab.com/mmclassification/v0/vgg/vgg19_batch256_imagenet_20210208-e6920e4a.pth).
And we will fix it ASAP, thanks for your reminding.

**Comment by sennnnn** [comment]
Thanks for the reply.
