### ISSUE TITLE
[Bug]pytorch2torchscript对ResNeSt进行编译错误，ModuleAttributeError: 'ResNeSt' object has no attribute 'norm1'

### ISSUE THREAD

**Issue by Rheelt** [open-mmlab/mmclassification#366]
环境：pytorch1.6.0 mmcv 1.3.8 mmcls 0.13.0
因为resnest没有使用norm1参数，但是resnet中使用了norm1作为property

Traceback如下
ModuleAttributeError Traceback (most recent call last)
in
----> 1 scripted = torch.jit.trace(script_model, example)

/usr/local/lib/python3.6/dist-packages/torch/jit/init.py in trace(func, example_inputs, optimize, check_trace, check_inputs, check_tolerance, strict, _force_outplace, _module_class, _compilation_unit)
953 return trace_module(func, {'forward': example_inputs}, None,
954 check_trace, wrap_check_inputs(check_inputs),
--> 955 check_tolerance, strict, _force_outplace, _module_class)
956
957 if (hasattr(func, 'self') and isinstance(func.self, torch.nn.Module) and

/usr/local/lib/python3.6/dist-packages/torch/jit/init.py in trace_module(mod, inputs, optimize, check_trace, check_inputs, check_tolerance, strict, _force_outplace, _module_class, _compilation_unit)
1101 register_submods(mod, '__module')
1102
-> 1103 module = make_module(mod, _module_class, _compilation_unit)
1104
1105 for method_name, example_inputs in inputs.items():

/usr/local/lib/python3.6/dist-packages/torch/jit/init.py in make_module(mod, _module_class, _compilation_unit)
785 if _module_class is None:
786 _module_class = TopLevelTracedModule
--> 787 return _module_class(mod, _compilation_unit=_compilation_unit)
788
789 def wrap_check_inputs(check_inputs):

/usr/local/lib/python3.6/dist-packages/torch/jit/init.py in init(self, orig, id_set, _compilation_unit)
2232
2233 for name, submodule in orig._modules.items():
-> 2234 tmp_module._modules[name] = make_module(submodule, TracedModule, _compilation_unit=None)
2235
2236 script_module = torch.jit._recursive.create_script_module(tmp_module, lambda module: (), share_types=False)

/usr/local/lib/python3.6/dist-packages/torch/jit/init.py in make_module(mod, _module_class, _compilation_unit)
785 if _module_class is None:
786 _module_class = TopLevelTracedModule
--> 787 return _module_class(mod, _compilation_unit=_compilation_unit)
788
789 def wrap_check_inputs(check_inputs):

/usr/local/lib/python3.6/dist-packages/torch/jit/init.py in init(self, orig, id_set, _compilation_unit)
2232
2233 for name, submodule in orig._modules.items():
-> 2234 tmp_module._modules[name] = make_module(submodule, TracedModule, _compilation_unit=None)
2235
2236 script_module = torch.jit._recursive.create_script_module(tmp_module, lambda module: (), share_types=False)

/usr/local/lib/python3.6/dist-packages/torch/jit/init.py in make_module(mod, _module_class, _compilation_unit)
768 if isinstance(mod, ScriptModule):
769 return mod
--> 770 elif torch._jit_internal.module_has_exports(mod):
771 def make_stubs_from_exported_methods(mod):
772 exported = []

/usr/local/lib/python3.6/dist-packages/torch/_jit_internal.py in module_has_exports(mod)
474 def module_has_exports(mod):
475 for name in dir(mod):
--> 476 item = getattr(mod, name)
477 if callable(item):
478 if get_torchscript_modifier(item) is FunctionModifiers.EXPORT:

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in getattr(self, name)
770 return modules[name]
771 raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
--> 772 type(self).name, name))
773
774 def setattr(self, name: str, value: Union[Tensor, 'Module']) -> None:

ModuleAttributeError: 'ResNeSt' object has no attribute 'norm1'

**Comment by mzr1996** [comment]
感谢您的提醒，我们会尽快检查这个问题

**Comment by mzr1996** [comment]
Hello, TorchScript has supported property after 1.7.0, refers to https://github.com/pytorch/pytorch/pull/42389
So please try to update your PyTorch and try again.
