### ISSUE TITLE
如何可视化pipeline

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#367]
作者你好！
很抱歉打扰你。
我想可视化 config.py 中的pipeline(因为我想在 config.py 中看到图像增强方法的效)果。
请问该如何可视化pipeline吗？
谢谢！

**Comment by Ezra-Yu** [comment]
目前，你可以在pipeline的最后增加一个显示图片的数据增强，并且在配置文件中注释掉ToTensor和Normalization，再参考tools/test.py写一个build_cfg以及迭代dataloader的调用工具。

后期我们会考虑将可视化pipeline的feature添加进来。

**Comment by zhongqiu1245** [comment]
谢谢
