### ISSUE TITLE
For the results in Model Zoo, how many GPUs were they run on?

### ISSUE THREAD

**Issue by damonmaria** [open-mmlab/mmclassification#371]
I know the mini-batch size has an impact on the results. The configs linked to in the Model Zoo have in them `samples_per_gpu` but there's no info about the number of gpus used to get the results listed. So I can't figure out what the mini-batch size is. 

In the logs linked from Model Zoo results I can see mention of 8x V100, so is it correct when `sampels_per_gpu=32` that the mini-batch size was 32 x 8 = 256?

For example, mmsegmentation [explicitly mentions the GPU configuration](https://mmsegmentation.readthedocs.io/en/latest/model_zoo.html) of its Model Zoo results.

**Comment by Ezra-Yu** [comment]
Yes, your understanding is correct.By default, the models of mmcls are derived under the condition of 8 GPUs.

Thank you for your suggestion, we are going to make it clear in the document.

**Comment by mzr1996** [comment]
Hello, we usually use config name to mark GPU numbers, for example, `mobilenet_v2_b32x8_imagenet.py` means we use `samples_per_gpu=32` and 8 GPUs.
And thanks for your suggestion,  I think explicit mention is a good idea. We will try to make it easier to understand.

**Comment by damonmaria** [comment]
Ah, I see, and then in `_base_/schedules` the `bs` number is the batch size. 

So SwimTransformer was really trained on 64 gpus? `swin_base_224_b16x64_300e_imagenet.py` -> `imagenet_bs1024_adamw_swin.py`

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
