### ISSUE TITLE
[Feature]weight bias of each class support

### ISSUE THREAD

**Issue by noahc1510** [open-mmlab/mmclassification#379]
### Describe the feature

weight bias of each class in training.

### Motivation
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

This function is very useful in MMDetection but I cannot found it in MMClassification.

### Related resources
If there is an official code release or third-party implementation, please also provide the information here, which would be very helpful.

https://github.com/open-mmlab/mmdetection/blob/ba286696eb1fee2e02f3aae04164f4e79296ea80/mmdet/models/losses/cross_entropy_loss.py#L201

### Additional context
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

None.

**Comment by Ezra-Yu** [comment]
Thank you for your suggestion,  We are going to add this feature.

**Comment by mzr1996** [comment]
Should have been solved by #388
