### ISSUE TITLE
[Feature] add some new backbone 

### ISSUE THREAD

**Issue by zkloveai** [open-mmlab/mmclassification#394]
thanks for your work !!
hope add res2net，or other backbone to use!
thanks again!

**Comment by mzr1996** [comment]
Sorry but a new backbone is a heavy job, we have to spend some time migrating it from mmdet, and it doesn't have the highest priority.
We welcome contributors from the community to help us with this work.

**Comment by mzr1996** [comment]
Closed by https://github.com/open-mmlab/mmclassification/pull/465
