### ISSUE TITLE
Why fp16 is slower than fp32 in ResNet-50

### ISSUE THREAD

**Issue by edwardyehuang** [open-mmlab/mmclassification#415]
The FP16 training log 
https://download.openmmlab.com/mmclassification/v0/fp16/resnet50_batch256_fp16_imagenet_20210320-b3964210.log.json

shows the its speed is slower than fp32

https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_batch256_imagenet_20200708-cfb998bf.log.json

**Comment by mzr1996** [comment]
Hello, the main difference between both logs is `data_time`. I think it's caused by different file clients in `LoadImageFromFile`. When training the fp32 version, we used `memcache`, while when training the fp16 version, we use `disk`.

**Comment by edwardyehuang** [comment]
Thanks!

**Comment by huoguangdiandian** [comment]
@edwardyehuang 问一下，你的resnet50训练imagenet的配置文件是用官方的吗？为啥我训练出来的精度比官方提供的少6个点
