### ISSUE TITLE
[Feature] MLP architecture implementation

### ISSUE THREAD

**Issue by c-liangyu** [open-mmlab/mmclassification#416]
### Describe the feature

MLP architecture implementation

### Motivation
It has been months since Google reported the progress with MLP realted vision research. There is a potential that MLP will be dominant arch for various tasks.

### Related resources

lucidrains/mlp-mixer-pytorch: An All-MLP solution for Vision, from Google AI
https://github.com/lucidrains/mlp-mixer-pytorch

**Comment by Ezra-Yu** [comment]
There is a PR #405  about MLP-Mixer. We are reviewing this code. It looks like it is not completely finished.

You can use that code and complete it, or just review that and tell us  if there are any shortcomings.

**Comment by Ezra-Yu** [comment]
we have added MLP-Mixer in #528
