### ISSUE TITLE
请问最后的score是概率吗？

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#423]
作者您好！
请问图像最后显示的score是概率吗？
比如输入一张蛇的图片，显示结果为score=0.82， 那么代表该图是蛇的概率是0.82吗？
如果不是，请问score和最终概率直接转转换公式是什么？
谢谢您

**Comment by Ezra-Yu** [comment]
模型inference后得到是一个向量[scores](https://github.com/open-mmlab/mmclassification/blob/6a0a76af0c176f381c8534097333f37a9e65a6bf/mmcls/apis/inference.py#L85)，向量长度为C（类别）维，表示该图像为对应的类别概率。
[score](https://github.com/open-mmlab/mmclassification/blob/6a0a76af0c176f381c8534097333f37a9e65a6bf/mmcls/apis/inference.py#L86)便是scores向量中最大值，即概率最大值；
label维最大概率score对应的index。

**Comment by zhongqiu1245** [comment]
明白了，谢谢您的指点
