### ISSUE TITLE
How to set the dtype of image data as uint8?

### ISSUE THREAD

**Issue by reclusezz** [open-mmlab/mmclassification#430]
Hello, via the disscussion with you in the latest issue, I have found that the dtype of image array wil affect the output of op A.

Op A:
pipeline_cfg = [
    dict(type='Normalize', mean=NORM_MEAN, std=NORM_STD, to_rgb=False),
    dict(type='ImageToTensor', keys=['img']),
]

Op B:
transform1 = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=NORM_MEAN, std=NORM_STD)   
    ])

I think that if  i want to infer with op B, the dtype of image array (before op A) should be uint8 while training. So, How to set the dtype of image data as uint8 to keep the consistency of traning phase and inference?

**Comment by Ezra-Yu** [comment]
the dtype of image array (before op A) has been uint8.
[LoadImageFromFile Pipeline](https://github.com/open-mmlab/mmclassification/blob/729c6c11923dad1a03ec4e01d685cb6cb4e64a53/mmcls/datasets/pipelines/loading.py#L11) have pararm `to_float32`(default is False). So the img from `LoadImageFromFile` is uint8.

**Comment by mzr1996** [comment]
Should have been solved, if have other question, please open a new issue.
