### ISSUE TITLE
vgg config

### ISSUE THREAD

**Issue by QiangZhu123** [open-mmlab/mmclassification#442]
### Describe the bug
Maybe you should fix the vgg config,because the 'num_classes' is  'cfg.model.backbone.num_classes' ,but the pytorch2onnx needs 'model.head.num_classes' to get 'num_classes',so if I select the vgg model to deploy , pytorch2onnx  can't work.

[here]

### To Reproduce
The command you executed.

```shell
[here]
```

### Post related information
1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
[here]
2. Your config file if you modified it or created a new one.
```python
[here]
```
3. Your train log file if you meet the problem during training.
[here]
4. Other code you modified in the `mmcls` folder.
[here]

### Additional context

[here]

**Comment by mzr1996** [comment]
Thanks for your reminder, we will try to fix it recently.
And to keep backward compatibility, I think a more intelligent `tools/deployment/pytorch2onnx.py` is a better way.

**Comment by mzr1996** [comment]
Should have been solved.
