### ISSUE TITLE
Why site-package/mmcls works but mmclassification/mmcls do not work?

### ISSUE THREAD

**Issue by ykk648** [open-mmlab/mmclassification#443]
Hi there, I'm trying to add 'filelist.py' into 'mmcls/datasets/' ,but when I running demo codes, It seems like 'PYTHONPATH/site-package/mmcls' works but not 'mmclassification/mmcls', is this some kind design or my mistake?

Waiting for the reply, thx.

**Comment by mzr1996** [comment]
Hello, how do you install mmcls? Did you obey the [develop version installation](https://github.com/open-mmlab/mmclassification/blob/master/docs/install.md#develop-version)?
Please provide the output of the following command:
```shell
pip list | grep mmcls
```

**Comment by ykk648** [comment]
output:

`mmcls                   0.15.0`

fully obey the installation instruction.

when I uninstall mmcls in conda env, it shows:

`ModuleNotFoundError: No module named 'mmcls.apis'`

**Comment by mzr1996** [comment]
Sorry, but I think you used [release version installation](https://github.com/open-mmlab/mmclassification/blob/master/docs/install.md#release-version), instead of [develop version installation](https://github.com/open-mmlab/mmclassification/blob/master/docs/install.md#develop-version).
