### ISSUE TITLE
[Bug]TypeError: set_providers() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by uniyushu** [open-mmlab/mmclassification#448]
### Describe the bug
I try to test onnx model,  but meet set_providers bugs, anyone meet the same problem before? Please help me, thanks.
### To Reproduce
```shell
python tools/deployment/test.py configs/mobilenet_v3/mobilenet_v3_small_cifar.py  work_dirs/mobilenet_v3_small_cifar/latest.onnx --backend onnxruntime --out outs/output.pkl --metrics "accuracy"
```
```shell
['CUDAExecutionProvider', 'CPUExecutionProvider'] [{'device_id': 0}, {}]
Traceback (most recent call last):
  File "tools/deployment/test.py", line 116, in <module>
    main()
  File "tools/deployment/test.py", line 77, in main
    args.model, class_names=dataset.CLASSES, device_id=0)
  File "/data/mmclassification/mmcls/core/export/test.py", line 25, in __init__
    sess.set_providers(providers, options)
TypeError: set_providers() takes 2 positional arguments but 3 were given
```

**Comment by mzr1996** [comment]
Hello, can you provide the version of your `onnxruntime`?

**Comment by mzr1996** [comment]
I notice that `onnxruntime` updated their API in https://github.com/microsoft/onnxruntime/pull/4205, maybe you can try to update your `onnxruntime` and try again.

**Comment by uniyushu** [comment]
> I notice that `onnxruntime` updated their API in [microsoft/onnxruntime#4205](https://github.com/microsoft/onnxruntime/pull/4205), maybe you can try to update your `onnxruntime` and try again.

Thanks for the reply. I update onnxruntime, resize the image and change the batchsize, it starts testing.
