### ISSUE TITLE
importing _ext: 找不到指定的模块。

### ISSUE THREAD

**Issue by dugudongfangshuo** [open-mmlab/mmclassification#451]
离线环境下把mmcv从本地复制到了服务器，之后就报这个错，我该怎么处理一下呢

**Comment by Ezra-Yu** [comment]
Hello, please use English or Chinese & English to open an issue in the future, so that your issue can help more people.

please run `MMCV_WITH_OPS=1 pip install -e .` in the mmcv dir, refer to [mmcv doc](https://mmcv.readthedocs.io/en/latest/get_started/build.html)
