### ISSUE TITLE
[Feature] Knowledge Distillation module

### ISSUE THREAD

**Issue by xiangn95** [open-mmlab/mmclassification#452]
### Describe the feature

Knowledge Distillation module

### Motivation

Knowledge distillation has always been a very important to the research community. Since MMDetection has one (Localization Distillation), I think MMClassification should have some modules as well, which may be useful for future research.

### Related resources

Consider the paper Distilling the Knowledge in a Neural Network by Geoffrey Hinton et al. for a straightforward implementation as a start.

https://github.com/xiangn95/mmclassification/tree/master/mmcls/models

**Comment by Ezra-Yu** [comment]
Thank you for your suggestion. Our plan is to put knowledge distillation and other model compression methods in another repository which is under development, and it will be released soon, so stay tuned.
