### ISSUE TITLE
Resize maintaining aspect ratio

### ISSUE THREAD

**Issue by Charlyo** [open-mmlab/mmclassification#453]
Dear mmclassification developers.

I want to resize an image in the pipeline  by resizing the bigger side and adapting the smaller one maintaining the aspect ratio of the image, but it seems that this behavior is not possible (-1, 224)?

Am I missing something?

Thanks in advance

**Comment by Ezra-Yu** [comment]
use `Resize((224, -1))`, refer to [the docstring](https://github.com/open-mmlab/mmclassification/blob/8f68779cc61bdf1dfbfe03cb7da636eae1bc9c27/mmcls/datasets/pipelines/transforms.py#L619)

**Comment by mzr1996** [comment]
Right, the `Resize` pipeline only supports resizing the shorter side and adapting the longer side.
So is this your need? If so, please reply to me and we will support it in the future. Moreover, you can implement it and contribute to this repo, and it's really helpful for us.

**Comment by Charlyo** [comment]
Similar to mmdetection, it would be interesting to resize an image to a desired size (e.g 224, 224) whilst maintaining aspect ratio by adding black border. That would be a nice feature.

**Comment by dadada101** [comment]
yes , @mzr1996   when I set the resizing configuration to (-1, 224) for example, it reports the resized image size in a batch not consistent error , how to solve it? I think it is needed the transformation in maskrcnn in mmdet.

**Comment by dadada101** [comment]
@Charlyo yes right,have you implemented it?

**Comment by Charlyo** [comment]
I would rather see the 2nd one done (2.). However, if you think it through, the first option will already be included in the second one if done properly.
