### ISSUE TITLE
Specify percentage of data used for training 

### ISSUE THREAD

**Issue by hasanirtiza** [open-mmlab/mmclassification#456]
Is there anyway through the configs or by minor modifications to specify the percentage of data to be used in training. What I mean is, say I have 100 images for training and I only want to use randomly sampled 80 images for training.

**Comment by mzr1996** [comment]
Hello, let me confirm your need.
We will use the dataset to train the model for multiple epochs, do you want to randomly select 80% data in each epoch, or randomly select 80% data and use them in all epochs.

**Comment by hasanirtiza** [comment]
Randomly select 80% data and use this 80% data in all epochs. I know perhaps you can do it through 
`mmclassification/mmcls/datasets/imagenet.py` file and in this function  `get_samples(root, folder_to_idx, extensions):`, when returning the list samples you extract randomly 80% (is it correct ?). Is there any other nice way of doing it.

**Comment by mzr1996** [comment]
I think that's the best way by now.
If you want a more elegant implementation, a dataset wrapper like `RepeatDataset` may meet your need. You can add a new dataset wrapper, like `RandomSubsetDataset` in [`mmcls/datasets/dataset_wrappers.py`](https://github.com/open-mmlab/mmclassification/blob/master/mmcls/datasets/dataset_wrappers.py), and you also need to modify [`mmcls/datasets/__init__.py`](https://github.com/open-mmlab/mmclassification/blob/master/mmcls/datasets/__init__.py) and the `build_dataset` function in [`mmcls/datasets/builder.py`](https://github.com/open-mmlab/mmclassification/blob/master/mmcls/datasets/builder.py) to enable it.

**Comment by hasanirtiza** [comment]
Thanks.
