### ISSUE TITLE
[Feature] Transform / use mmdetection object detection dataset into mmclassification 

### ISSUE THREAD

**Issue by Charlyo** [open-mmlab/mmclassification#460]
Is there any script  / feature that allows to use each of the object detections from an image in a mmdetection dataset directly on mmclassification as different images? Maybe that's a feature that could be interesting to have.

Thanks in advance

**Comment by mzr1996** [comment]
interesting feature, we will discuss with mmdet developers about it.

**Comment by mzr1996** [comment]
Thanks for your suggestion. This is actually a good feature and currently, we are considering supporting it.
For now, if you want to implement it by yourself, you need a wrapper that contains a detector and a classifier and implement the forward logic including the detector forward, image cropping & pre-processing, the classifier forward.

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
