### ISSUE TITLE
Publish model to mmdetection

### ISSUE THREAD

**Issue by yanlongbinluck** [open-mmlab/mmclassification#462]
I have found that the published model using ``` tools/model_converters/publish_model.py``` has the key ``` backbone.layer1.xxx```, it  is not same with the official model with ``` layer1.xxx```.
Can it be loaded correctly in mmdetection?

**Comment by mzr1996** [comment]
Hello, the models of `mmdet` also have fields like `backbone`, so it should match if you load the entire model.
However, if you just want to use the pretrained backbone, please use configs like the following:
```python
backbone=dict(
    type='MobileNetV2',
    widen_factor=1.0,
    init_cfg=dict(
        type='Pretrained',
        checkpoint='checkpoints/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth',
        prefix='backbone')  # <-- To tell the initialization function to remove `backbone` prefix.
),
```

**Comment by yanlongbinluck** [comment]
I see. 
Thanks for your prompt reply.
