### ISSUE TITLE
Does it support reading and writing in HDF5 format of Imagenet dataset

### ISSUE THREAD

**Issue by JackeyGHD1** [open-mmlab/mmclassification#476]
Due to the limitation of my server on the number of files (the maximum number can not exceed 1 million), I generate Imagenet data into HDF5 format. How can I input this data format！Thanks a lot！

**Comment by mzr1996** [comment]
Hello, by now we haven't provided HDF5 format support. However, you can simply support it by modifying the ImageNet dataset class.
```python
import h5py
from .imagenet import ImageNet
from .builder import DATASETS

@DATASETS.register_module()
class ImageNetHDF5(ImageNet):
    def load_annotations(self):
        # Use ann_file to get the hdf5 file
        assert self.ann_file is not None
        with h5py.File(self.ann_file, "r") as f:
            # Load your dataset here
            imgs = ...        # A sequence of np.ndarray
            gt_labels = ...   # A sequence of int

        data_infos = []
        for img, gt_label in zip(imgs, gt_labels):
            gt_label = np.array(gt_label, ddtype=np.int64)
            info = {'img': img, 'gt_label': gt_label}
            data_infos.append(info)
        return data_infos
```
And then, refers to [the docs](https://mmclassification.readthedocs.io/en/latest/tutorials/new_dataset.html#an-example-of-customized-dataset) to register the new dataset class.

Here is what your config file should look like (assume you are using [`configs/resnet/resnet50_b32x8_imagenet.py`](https://github.com/open-mmlab/mmclassification/blob/master/configs/resnet/resnet50_b32x8_imagenet.py)):
```python
_base_ = [
    '../_base_/models/resnet50.py',
    '../_base_/schedules/imagenet_bs256.py', '../_base_/default_runtime.py'
]

# dataset settings
dataset_type = 'ImageNetHDF5'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    # Since you have read the images in memory, you don't need to load images from file.
    # dict(type='LoadImageFromFile'),
    dict(type='RandomResizedCrop', size=224),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    # dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(256, -1)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
data = dict(
    samples_per_gpu=32,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        data_prefix='data/imagenet',
        ann_file='your training hdf5 file',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        data_prefix='data/imagenet',
        ann_file='your test hdf5 file',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        data_prefix='data/imagenet',
        ann_file='your test hdf5 file',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='accuracy')

```

**Comment by JackeyGHD1** [comment]
I so appreciate it！Thank you your reply！I will try it！

**Comment by qiuzhongwei-USTB** [comment]
> > Thank you very much for your reply! "Please note, this will load the entire imagenet dataset in your memory, please confirm you have enough memory." Because the training set of imagenet dataset is about 140Gb. Does that mean my device needs 140Gb of memory？
> 
> Well, since you save the entire dataset to a file, all data will be loaded into memory when building the dataset. If you want to load the dataset by streaming, you may need to create an [iterable-style datasets](https://pytorch.org/docs/stable/data.html#iterable-style-datasets). Another alternative method is using a pipeline to load it. For example, modify the dataset as:
> 
> ```python
> from .imagenet import ImageNet
> from .builder import DATASETS
> 
> @DATASETS.register_module()
> class ImageNetHDF5(ImageNet):
>     def load_annotations(self):
>         # Use ann_file to get the hdf5 file
>         assert self.ann_file is not None
>         with h5py.File(self.ann_file, "r") as f:
>             # Load your dataset here
>             img_indices = range(len(data))
>             gt_labels = ...   # A sequence of int
> 
>         data_infos = []
>         for img_index, gt_label in zip(img_indices, gt_labels):
>             info = {'data_file': self.ann_file}
>             info['img_info'] = {'index': img_index}
>             info['gt_label'] = np.array(gt_label, ddtype=np.int64)
>             data_infos.append(info)
>         return data_infos
> ```
> 
> In this situation, the `data_info` won't include the entire image data but include the index of the image. And create a new data pipeline to load it by streaming. For example:
> 
> ```python
> @PIPELINES.register_module()
> class LoadImageFromHDF5(object):
>     def __init__(self, group_key, to_float32=False):
>         self.group_key = group_key
>         self.to_float32 = to_float32
> 
>     def __call__(self, results):
>         hdf5_file = results['data_file']
>         with h5py.File(hdf5_file, "r") as f:
>             # Load your image data here
>             img = ...  # np.ndarray
> 
>         if self.to_float32:
>             img = img.astype(np.float32)
> 
>         results['img'] = img
>         results['img_shape'] = img.shape
>         results['ori_shape'] = img.shape
>         num_channels = 1 if len(img.shape) < 3 else img.shape[2]
>         results['img_norm_cfg'] = dict(
>             mean=np.zeros(num_channels, dtype=np.float32),
>             std=np.ones(num_channels, dtype=np.float32),
>             to_rgb=False)
>         return results
> 
>     def __repr__(self):
>         repr_str = (f'{self.__class__.__name__}('
>                     f'group_key={self.group_key}, '
>                     f'to_float32={self.to_float32})')
>         return repr_str
> ```
> 
> And then, refers to [the docs](https://mmclassification.readthedocs.io/en/latest/tutorials/data_pipeline.html#extend-and-use-custom-pipelines) to register the new data pipeline. Finally, replace the `LoadImageFromFile` in the data pipeline to `LoadImageFromHDF5`

hi, where can we find the original load_annotations() because we overwrite it?

**Comment by ericzw** [comment]
Is it the def load_data_list(self): function in the current version?
