### ISSUE TITLE
[Bug]RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling

### ISSUE THREAD

**Issue by RainFrost1** [open-mmlab/mmclassification#477]
推荐使用英语模板 Bug report，以便你的问题帮助更多人。

### 描述 bug
简单地描述一下遇到了什么 bug
When training swintransformer
[填写这里]

### 复现流程
在命令行中执行的详细操作
python tools/train.py configs/swin_transformer/swin_tiny_224_b16x64_300e_imagenet.py
```shell
[填写这里]
```

### 相关信息
1. `pip list | grep "mmcv\|mmcls\|^torch"` 命令的输出
mmcls==0.15.0
mmcv-full==1.3.13
torch==1.9.0
2. 如果你修改了，或者使用了新的配置文件，请在这里写明
```python
[填写这里]
```
3. 如果你是在训练过程中遇到的问题，请填写完整的训练日志和报错信息
[填写这里]
4. 如果你对 `mmcls` 文件夹下的代码做了其他相关的修改，请在这里写明
[填写这里]

### 附加内容
任何其他有关该 bug 的信息、截图等
![图片](https://user-images.githubusercontent.com/11568925/136645907-d8004695-fcc5-41be-b6e5-02d0312373f4.png)

[填写这里]

**Comment by canghaiyunfan** [comment]
@mzr1996 I faced the same issue, maybe a bug for pytorch1.8

**Comment by 459737087** [comment]
I also met this question, maybe a bug for pytorch 1.9.
when I ran it in pytorch1.8, this question disappeared!

**Comment by Ezra-Yu** [comment]
Make sure that the PyTorch version matches the Cuda version, refer to [PyTorch installation guide](https://pytorch.org/get-started/previous-versions/).
