### ISSUE TITLE
如何自定义配置

### ISSUE THREAD

**Issue by zj837578609** [open-mmlab/mmclassification#484]
### 首先确认以下内容
- 我已经查询了相关的 issue，但没有找到需要的帮助。
- 我已经阅读了相关文档，但仍不知道如何解决。

### 描述你遇到的问题

我想自定义配置一些选项，比如优化器，比如学习率下降策略，但我不知道该如何填写配置文件。
比如我想知道有哪些优化器可供选择，有哪些学习率策略可供选择。

**Comment by Ezra-Yu** [comment]
1. 目前支持[pytorch的所有优化器](https://blog.csdn.net/u011995719/article/details/88988420)，构造是传类名，type=''XXX", 如‘SGD'，’Adam' 等
```
optimizer = dict(
    type='AdamW',
    lr=5e-4 * 128 * 8 / 512,
    weight_decay=0.05,
    eps=1e-8,
    betas=(0.9, 0.999),
    paramwise_cfg=paramwise_cfg)
```
2. 不同的学习率曲线，有cos, step等, 参考相关[mmcvAPI文档](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/lr_updater.py),
```
lr_config = dict(
    policy='CosineAnnealing',
    min_lr=0,
    warmup='linear',
    warmup_iters=25025,
    warmup_ratio=0.25)
```
3. 不同网络参数设置不同的学习率，参考[mmcv相关文档](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/optimizer/default_constructor.py)
```
optimizer = dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0001, paramwise_cfg=paramwise_cfg)
paramwise_cfg = dict(
    norm_decay_mult=0.0,
    bias_decay_mult=0.0,
    custom_keys={
        '.absolute_pos_embed': dict(decay_mult=0.0),
        '.relative_position_bias_table': dict(decay_mult=0.0)
    })
```

**Comment by zj837578609** [comment]
好的好的  希望文档能早日出来。。 那文档出来之前只能看源码么，实在不确定的来提issue？

**Comment by zj837578609** [comment]
好的好的 我试试看  感谢您的答复

**Comment by zj837578609** [comment]
好的 感谢   还有旋转任意角度的数组增强方式mmclass支持吗  我好像只看到了随机裁剪类和色彩变幻类的增强方式

**Comment by mzr1996** [comment]
> 好的 感谢 还有旋转任意角度的数组增强方式mmclass支持吗 我好像只看到了随机裁剪类和色彩变幻类的增强方式

Rotate 在 RandAugment 中提供了，可以用 RandAugment 增强，在 policy 中指定 rotate

**Comment by zj837578609** [comment]
如何测试模型耗时呢  默认数据pipline和模型预测是一体的   代码比较菜，拆不开。。有统计耗时的接口吗

**Comment by Ezra-Yu** [comment]
目前需要 统计 https://github.com/open-mmlab/mmclassification/blob/72cffac7b50a556824907721665e6705fd5045fb/mmcls/apis/inference.py#L84~87 计算时间，再多余求平均。

不是很理解 `默认数据pipline和模型预测是一体的,拆不开` 为什么需要拆开？

关于在api.inference 中增加统计时间、传入多个图片的功能我们会考虑添加进去。

**Comment by zj837578609** [comment]
已经解决我的问题了  感谢

**Comment by zj837578609** [comment]
模型转onnx时遇到了一些问题，我仅仅使用了最简单的结构，还是转换失败。（使用默认的mobilenetv2可以转换成功）pytorch1.9  onnx
我的网络结构是：
@BACKBONES.register_module()
class Simple(BaseBackbone):

    def __init__(self, num_classes=-1):
        super(Simple, self).__init__()
        self.num_classes = num_classes
        self.features = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, stride=1, padding='same'),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),

            nn.Conv2d(64, 128, kernel_size=3, stride=1, padding='same'),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),

            nn.Conv2d(128, 128, kernel_size=3, stride=1, padding='same'),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )

        if self.num_classes > 0:
            self.classifier = nn.Sequential(
                nn.Linear(128 * 8 * 8, 64),
                nn.ReLU(inplace=True),
                # nn.BatchNorm1d(64),
                nn.Linear(64, num_classes),
            )

    def forward(self, x):
        # print(x.shape)
        x = self.features(x)
        if self.num_classes > 0:
            # x = x.view(x.size(0), 128 * 8 * 8)
            x=x.flatten(1)
            # print(x.shape)
            x = self.classifier(x)

        return (x, )
模型设置为：
# model settings
model = dict(
    type='ImageClassifier',
    backbone=dict(type='Simple', num_classes=21),
    neck=None,
    head=dict(
        type='ClsHead',
        cal_acc=True,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
    ))

转换报错为：
RuntimeError: Exporting the operator _convolution_mode to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

**Comment by zj837578609** [comment]
问题已解决

**Comment by Ezra-Yu** [comment]
是算子版本的问题吗？

**Comment by zj837578609** [comment]
是pytorch转onnx不支持  “same”模式的padding   “same”改为1就可以了

**Comment by MARUIHAN123** [comment]
> > mmcalss 支持提前停止吗 比如跌倒一定次数后 loss不再降低时提前终止训练 以及 不再降低时降低学习率
> 
> loss不再降低时降低学习率相关的PR可以参见，[open-mmlab/mmcv#1183](https://github.com/open-mmlab/mmcv/pull/1183)
为什么我训练的时候不显示loss,学习率等参数，写入tensorboard的时候也没有
