### ISSUE TITLE
Is the parameter of `get_root_logger` in train.py a bug?

### ISSUE THREAD

**Issue by tansor** [open-mmlab/mmclassification#485]
https://github.com/open-mmlab/mmclassification/blob/6fba1078403b9ccf551361609e9614f7a52ae46d/mmcls/apis/train.py#L59

while the first param is log_file in 

https://github.com/open-mmlab/mmclassification/blob/6fba1078403b9ccf551361609e9614f7a52ae46d/mmcls/utils/logger.py#L7

**Comment by Ezra-Yu** [comment]
go to the defintion of [mmcv.util.get_root_logger](https://mmcv.readthedocs.io/en/latest/api.html#mmcv.utils.get_logger)


> Initialize and get a logger by name.
> If the logger has not been initialized, this method will initialize the logger by adding one or two handlers, otherwise the  initialized logger will be directly returned. During initialization, a StreamHandler will always be added. If log_file is specified and the process rank is 0, a FileHandler will also be added.

more detail can refer to [source code](https://mmcv.readthedocs.io/en/latest/_modules/mmcv/utils/logging.html#get_logger)
