### ISSUE TITLE
image load erro

### ISSUE THREAD

**Issue by CruiseShao** [open-mmlab/mmclassification#5]
![image](https://user-images.githubusercontent.com/38639098/87428547-12307580-c615-11ea-894c-3d431cef9141.png)

![image](https://user-images.githubusercontent.com/38639098/87428632-3be99c80-c615-11ea-9a51-f96b358e6891.png)

The following error occurs when loading the non-standard format image, but it is ok when reading it using PIL library

**Comment by CruiseShao** [comment]
What function is called inside this function to read the image?
img_bytes = **self.file_client.get**(filename)
And thank you very much for your contribution.

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmcv/blob/master/mmcv/fileio/file_client.py

**Comment by JiayuXu0** [comment]
![微信截图_20220701182208](https://user-images.githubusercontent.com/84259897/176878289-53ffed1f-c7e6-411f-a5dd-cfd72ca4f25f.png)
