### ISSUE TITLE
backbone request：RMNet

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#517]
Hi, dear authors!
Thank you for your amazing job!
Could you support RMNet?
It like RepVgg but stronger than RepVgg. This network can convert Resnet( or other Resnet style Networks,for example, Mobilenet) to Vgg-style, which gets rid of the limitation of ReLU.

Paper & Code:
arXiv:https://arxiv.org/abs/2111.00687
code: https://github.com/fxmeng/RMNet

**Comment by mzr1996** [comment]
Of course, but the time is hard to guarantee with only our force. We welcome any interested community contributors to work on it to accelerate adding new models.

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
