### ISSUE TITLE
Class names in checkpoint's meta data

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmclassification#520]
How to save the class names of my custom dataset in the checkpoint's metadata?

I don't see any option in `train.py` or from skimming the tutorial on config [here](https://mmclassification.readthedocs.io/en/latest/tutorials/config.html).

**Comment by Ezra-Yu** [comment]
You can pass in the dictionary of class name information in checkpoint-config, refer to [MMCV CheckpointHook](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/checkpoint.py#L11).

The CheckpointHook is constructed in [this file](https://github.com/open-mmlab/mmclassification/blob/master/configs/_base_/default_runtime.py#L2) by [this line](https://github.com/open-mmlab/mmclassification/blob/dc35eb62b61ab17decedb93c4d83ec6da5f93eff/configs/_base_/default_runtime.py#L2). 

for example.
```
checkpoint_config = dict(interval=1, CLASSES=['cat', 'dog'])
```

**Comment by Ezra-Yu** [comment]
By the way, we are going to add some documentation about Hook in #499, which includes CheckPointHook, and it is under review.
Maybe you can read that and give us some suggestions.

**Comment by rlleshi** [comment]
Just tried this and it didn't work out like that in `mmcv-full==1.3.16`. Maybe that `mmcv` version that you refer to hasn't been released yet?

I added them instead in the `data` config. Like so:

data = dict(
    samples_per_gpu=32,
    workers_per_gpu=2,
    classes=[
       'cat',
       'dog'],
 )
 
also, your test [files](https://github.com/open-mmlab/mmclassification/blob/dc35eb62b61ab17decedb93c4d83ec6da5f93eff/tests/test_data/test_datasets/test_common.py#L53) are referring to it like that.

**Comment by Ezra-Yu** [comment]
It does not work when you add `CLASSES` in the field  [`data`](https://github.com/open-mmlab/mmclassification/blob/dc35eb62b61ab17decedb93c4d83ec6da5f93eff/configs/_base_/datasets/imagenet_bs32.py#L22), you must add `CLASSES` to the field [`checkpoint_config`](https://github.com/open-mmlab/mmclassification/blob/dc35eb62b61ab17decedb93c4d83ec6da5f93eff/configs/_base_/default_runtime.py#L2), if you want to save `CLASSES` in your checkpoint.

**Comment by mzr1996** [comment]
Well, in the `tools/train.py`, we will automatically add the `CLASSES` attribute of the dataset to the checkpoint's `meta` argument.
Usually, you only need to add the `classes` in the dataset configuration.
