### ISSUE TITLE
Why the `init_cfg` isn't sent into `InvertedResidual` Module in MobileNetV2?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#521]
Hi, dear authors!
Thank you for your amazing job!
I have a small question about MobileNetV2.
I find the `init_cfg` is only sent into `class MobileNetV2`, but not into `class InvertedResidual` Module.
If we do like that, the init of `InvertedResidual` Module will follow the `init_cfg`?
Thank you!

**Comment by mzr1996** [comment]
This weight initialization process is controlled by `BaseModule` in mmcv, please refers to https://mmcv.readthedocs.io/en/latest/understand_mmcv/cnn.html#initializers-and-configs

**Comment by zhongqiu1245** [comment]
Thank you！
