### ISSUE TITLE
How to init the backbone which is mixed with custom module?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#522]
Hi, dear authors!
Thank you for your amazing job!
I have a small question about init.
I mixed the ResNet 18 with my custom module, which looks like as follow:
![屏幕截图 2021-11-07 144148](https://user-images.githubusercontent.com/48090608/140635299-29e51ab0-722b-40e4-a035-3d4213ec0d34.jpg)
I want to initialize all ResNet layers with ResNet 18 pre-trained file, and initialize all custom layers with:
```
custom_init_cfg=[dict(type='Kaiming', layer=['Conv2d']),
                 dict(type='Constant', val=1, layer=['_BatchNorm', 'GroupNorm'])])
```
or can describe like this:
```
# for all resnet layers
resnet_init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet18')
 
# for all custom layers
custom_init_cfg=[dict(type='Kaiming', layer=['Conv2d']),
                 dict(type='Constant', val=1, layer=['_BatchNorm', 'GroupNorm'])])
```
How do I initialize this "mix backbone" in this way?
Thank you!

**Comment by mzr1996** [comment]
Please refer to https://mmcv.readthedocs.io/en/latest/understand_mmcv/cnn.html#initializers-and-configs

**Comment by zhongqiu1245** [comment]
@mzr1996 Hi, thank you for your reply!
But I still confuse about how to initialize this mix_backbone with init_cfg.
If I use `override`, how do I need to make the network know the override part is to initialize all resnet layers? 
I mean this :
```
init_cfg=[dict(type='Kaiming', layer=['Conv2d']),
                 dict(type='Constant', val=1, layer=['_BatchNorm', 'GroupNorm']),
                 override=dict(type='Pretrained', name='????', checkpoint='torchvision://resnet18')
]
```
 What should I fill in `name`? Do I need to specify those resnet layers one by one? Like `name=['stem', 'layer1', 'layer2', 'layer3', 'layer4']`?
Thank you!

**Comment by mzr1996** [comment]
Well, if you're confused about the `init_cfg` or your initialization process is complex, you can also just override the `init_weights` functions, which refers to the [resnet](https://github.com/open-mmlab/mmclassification/blob/dc35eb62b61ab17decedb93c4d83ec6da5f93eff/mmcls/models/backbones/resnet.py#L596). This function has the highest priority, and you can also access the `init_cfg` in this function.

**Comment by zhongqiu1245** [comment]
Thank you！
