### ISSUE TITLE
how to load pretrained weight for swin transformer.

### ISSUE THREAD

**Issue by XuKun2424** [open-mmlab/mmclassification#524]
推荐使用英语模板 General question，以便你的问题帮助更多人。

### 首先确认以下内容
- 我已经查询了相关的 issue，但没有找到需要的帮助。
- 我已经阅读了相关文档，但仍不知道如何解决。

### 描述你遇到的问题

self = SwinTransformer(**extra_config)
self._load_from_state_dict()

### 相关信息
1. `pip list | grep "mmcv\|mmcls\|^torch"` 命令的输出
[填写这里]
2. 如果你修改了，或者使用了新的配置文件，请在这里写明
```python
[填写这里]
```
3. 如果你是在训练过程中遇到的问题，请填写完整的训练日志和报错信息
[填写这里]
4. 如果你对 `mmcls` 文件夹下的代码做了其他相关的修改，请在这里写明
[填写这里]

**Comment by Ezra-Yu** [comment]
refer to this [article](https://blog.csdn.net/yuzh_/article/details/120842087?spm=1001.2014.3001.5501)


```
    backbone=dict(
        init_cfg = dict(
            type='Pretrained', 
            checkpoint="https://download.openmmlab.com/mmclassification/v0/swin-transformer/swin_tiny_224_b16x64_300e_imagenet_20210616_090925-66df6be6.pth", 
            prefix='backbone')
    )
```

**Comment by XuKun2424** [comment]
> refer to this [article](https://blog.csdn.net/yuzh_/article/details/120842087?spm=1001.2014.3001.5501)
> 
> Inherit a base swin-transformer configuration file, and add this.
> 
> ```
> _base_ = ['../_base_/models/swin_transformer/tiny_224.py']
> 
>   backbone=dict(
>       init_cfg = dict(
>           type='Pretrained', 
>           checkpoint="https://download.openmmlab.com/mmclassification/v0/swin-transformer/swin_tiny_224_b16x64_300e_imagenet_20210616_090925-66df6be6.pth", 
>           prefix='backbone')
>   )
> ```

Haha, thank my brother
