### ISSUE TITLE
how to assign different optimizer(or with different parameters) for different part of origin model

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmclassification#536]
for example 
adam optimizer -> model.backbone
sgd optimizer -> model.neck
or 
sgd optimizer (lr=0.2)-> model.neck
sgd optimizer (lr=0.1)-> model.backbone

**Comment by Ezra-Yu** [comment]
1. different optimizer is not supported now in mmcls.
2. you can refer to this [tutorial](https://github.com/Ezra-Yu/mmclassification/blob/schedule/docs/tutorials/schedule.md#parameter-wise-finely-configuration), which is still in review. Using `paramwise_cfg` as below:
```
optimizer = dict(type='SGD', lr=0.1, weight_decay=0.0001)

paramwise_cfg = dict(
    custom_keys={
        '.backbone': dict(lr_mult=1),
        '.neck': dict(lr_mult=2)
    })
```
