### ISSUE TITLE
How to train the networks with multi_scale?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#537]
Hi, dear authors!
Thank you for your amazing job!
I want to train the ResNet50 in multi-scale pattern, but i don't know how.
Could you tell me how to  train the ResNet50 in multi-scale?
Thank you!

**Comment by Ezra-Yu** [comment]
does `multi-scale` mean multi-scale inputs? eg. inputs have shape 224*224, 250*300, and so on.

**Comment by zhongqiu1245** [comment]
Yes
But how to write this into `config.py`?
In `train_pipeline`?

**Comment by Ezra-Yu** [comment]
Currently `mmcls` supports dynamic size input. 

However, we train a network batch by batch. You need to consider how to merge pictures of different input sizes, otherwise, you would only train a network one by one.

**Comment by Ezra-Yu** [comment]
Maybe you can use padding.

**Comment by zhongqiu1245** [comment]
Thank you！
 By the way, does the mmcls support the TTA?

**Comment by Ezra-Yu** [comment]
No, yet.

**Comment by zhongqiu1245** [comment]
thank you!

**Comment by okideal** [comment]
> 

where can I find the sample config/settings for dynamic size input?

**Comment by IT-five** [comment]
> Hi, dear authors! Thank you for your amazing job! I want to train the ResNet50 in multi-scale pattern, but i don't know how. Could you tell me how to train the ResNet50 in multi-scale? Thank you!

Is there a solution, is there a specific example for reference?
