### ISSUE TITLE
update RepVGG block 

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmclassification#538]
我想基于 MMclassification这个项目实现 [RepVGG](https://github.com/DingXiaoH/RepVGG/blob/main/repvgg.py)这个repo里面的[`the get_custom_L2 `](https://github.com/Kylin9511/mmclassification/blob/144db46a5d14148fc2dceb9598e46480bf507362/mmcls/models/losses/online_label_smooth_loss.py#L40:9)函数 ,直接的想法就是在`backbone`里面为每一个`epblock build_loss`，但是 这种方法感觉不太好实现 有没有类似的例子或者方法来完成这个呢？

**Comment by Ezra-Yu** [comment]
Hello, please use English or Chinese & English and an issue template to open an issue in the future, so that your issue can help more people.

关于RepVGG的这个L2正则我们近期也考虑支持，推荐使用 Hook 机制去实现这类损失函数。可以参考 [MMCV Hook 简介](https://zhuanlan.zhihu.com/p/355272220)。一些细节实现可以直接通过我github上留的邮箱联系到我，或者加群联系小助手联系上我们。

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
