### ISSUE TITLE
请问你们是否有对imagenet21k做过评估?

### ISSUE THREAD

**Issue by daixiangzi** [open-mmlab/mmclassification#540]
### Checklist
- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

[here]

### Post related information
1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
[here]
2. Your config file if you modified it or created a new one.
```python
[here]
```
3. Your train log file if you meet the problem during training.
[here]
4. Other code you modified in the `mmcls` folder.
[here]

**Comment by Ezra-Yu** [comment]
Does it mean `evaluation`?

No, the original ImgaNet21k dataset does not have 'val' or 'test' set.  Before you evaluate, you must split the dataset into 'train' and 'val'. There is currently no generally acknowledged method of the split for the ImgaNet21k dataset.

**Comment by daixiangzi** [comment]
> Does it mean `evaluation`?
> 
> No, the original ImgaNet21k dataset does not have 'val' or 'test' set. Before you evaluate, you must split the dataset into 'train' and 'val'. There is currently no generally acknowledged method of the split for the ImgaNet21k dataset.

嗯,那你们有做过下游任务的评估吗?比如在imagenet21k train 在imagenet上fine turn

**Comment by Ezra-Yu** [comment]
not, yet.
