### ISSUE TITLE
除了CELoss以外的Loss都不能在训练中使用

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#541]
您好，作者！
首先非常感谢您的work！
我用resnet50我训练自己的数据集，4类，数据格式是Imagenet格式
但是总是报错：`pred and target should be in the same shape.`
其中pred.shape=(6， 4)， target.shape=(6)
除了CELoss以外，其余的所有Loss都会报这个错误
请问该如何解决？谢谢！

**Comment by zhongqiu1245** [comment]
数据集总共内含3个文件夹，分别是 train， val和meta
其中train文件夹内有四个文件夹，分别是0， 1， 2， 3；
val文件夹内全是图片；
meta文件夹是val.txt, 其格式为 
```
......
xxxx.jpg 0
xxxx.jpg 1
xxxx.jpg 2
xxxx.jpg 3
......
```

**Comment by zhongqiu1245** [comment]
这个Error和这个Error一样，看样子不仅仅FcoalLoss有这个问题
https://github.com/open-mmlab/mmclassification/issues/533

**Comment by mzr1996** [comment]
The `FocalLoss` and `AsymmetricLoss` only support binary classification by now. If you want to use it in single-label tasks, please convert your labels to one-hot labels manually.

**Comment by zhongqiu1245** [comment]
@mzr1996 您好，二分类的也不行，我试了

**Comment by zhongqiu1245** [comment]
请问Imagenet的数据格式如何转one-hot？

**Comment by mzr1996** [comment]
> @mzr1996 您好，二分类的也不行，我都试了

Please post your config file and other information according to the issue template

**Comment by zhongqiu1245** [comment]
# type: ignore
model = dict(
    type="ImageClassifier",
    backbone=dict(
        type="ResNet",
        depth=50),
    neck=dict(type="GlobalAveragePooling"),
    head=dict(
        type="LinearClsHead",
        num_classes=2,
        in_channels=2048,
        loss=dict(type="FocalLoss", loss_weight=1.0),
        topk=(1, ),
    ))

**Comment by zhongqiu1245** [comment]
By the way, if I want to save the best `F1_score`, how do I set the `evaluation`?

**Comment by liluhu0** [comment]
> 
evaluation = dict(save_best='F1_score')

**Comment by liluhu0** [comment]
> 



> 顺便说一句，如果我想保存最好的`F1_score`，我该如何设置`evaluation`？

evaluation = dict(save_best='accuracy')

**Comment by mzr1996** [comment]
> By the way, if I want to save the best `F1_score`, how do I set the `evaluation`?

It depends on the detailed key of the evaluation results.
For basic F1 score, the result key is `f1_score`, then just modify the `evaluation` field in the config file as 
```python
# The `rule` field means how to compare the value.
# For "accuracy", mmcv can auto infer the rule, while for "f1_score", you need to specify it.
evaluation = dict(interval=1, metric=['accuracy', 'f1_score'], save_best='f1_score', rule='greater')
```
Or if you want only F1 score metric, just using "auto" is enough. ('auto' means automatically select the first metric to compare.)
```python
evaluation = dict(interval=1, metric='f1_score', save_best='auto', rule='greater')
```
If you also want set multiple thresholds, the key of F1 score will change.
```python
evaluation = dict(
    interval=1,
    metric=['accuracy', 'f1_score'],
    metric_options=dict(thrs=(0.2, 0.4)),
    save_best='f1_score_thr_0.20',
    rule='greater',
)
```

**Comment by zhongqiu1245** [comment]
Thank you!

**Comment by maoyuanpeng** [comment]
@XinyueZ  I have the same issue when use binary_cross_entropy
