### ISSUE TITLE
Extend NumClassCheckHook from mmdet to mmcls

### ISSUE THREAD

**Issue by elopezz** [open-mmlab/mmclassification#545]
### Describe the feature

Extend and adapt `NumClassCheckHook` for working with mmcls library.

### Motivation
The hook is very convenient for checking if your model classes number is equal to the dataset classes number and detect early mistakes in the training pipeline.

### Related resources
If there is an official code release or third-party implementation, please also provide the information here, which would be very helpful.

https://github.com/open-mmlab/mmdetection/blob/c76ab0eb3c637b86c343d8454e07e00cfecc1b78/mmdet/datasets/utils.py#L116

### Additional context
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

I would like to create a PR and implement the feature, but I have a question beforehand: for all the considered models/heads in the mmcls repository, which ones don't have a suitable layer configuration for checking this? For example, in the mmdet case a few heads are excluded in the hook check: https://github.com/open-mmlab/mmdetection/blob/c76ab0eb3c637b86c343d8454e07e00cfecc1b78/mmdet/datasets/utils.py#L141.

**Comment by Ezra-Yu** [comment]
heads in this [line](https://github.com/open-mmlab/mmdetection/blob/c76ab0eb3c637b86c343d8454e07e00cfecc1b78/mmdet/datasets/utils.py#L141 ) that can not use NumClassesCheckHook may have different classes-number with dataset classes-number. For example, the RPN head's classes-number is always set to be 2, positive and negative.

The classes-number of heads in `mmcls` are all included in the hook check.  We are very grateful If you could create a PR and implement the feature. Always welcome your contribution.
