### ISSUE TITLE
mmcls/datasets/pipelines/compose.py下的Compose似乎不需要注册

### ISSUE THREAD

**Issue by zranguai** [open-mmlab/mmclassification#550]
https://github.com/open-mmlab/mmclassification/blob/49cbfd776a47e77dacde3428f8014f829b85c5c4/mmcls/datasets/pipelines/compose.py#L9
这里的Compose并不在dataset的配置文件中，似乎不需要进行注册，注释后训练和测试都可跑通。

**Comment by mzr1996** [comment]
Right, `Compose` is a helper transform, and we usually call it directly in `BaseDataset`.
However, it's still a transform, and after registering into `PIPELINES`, you can call it by the following steps:
```python
>>> from mmcls.datasets import PIPELINES
>>> cfg = dict(
...     type='Compose',
...     transforms=[dict(type='LoadImageFromFile'), dict(type='Resize', size=(224, 224))]
... )
>>> pipeline = PIPELINES.build(cfg)
>>> print(pipeline)
Compose(
    LoadImageFromFile(to_float32=False, color_type='color', file_client_args={'backend': 'disk'})
    Resize(size=(224, 224), interpolation=bilinear)
)
```
Although this method is not used in mmcls repo, it may be useful in some situations.
