### ISSUE TITLE
Multiple dataset during training 

### ISSUE THREAD

**Issue by AyeshaNirma** [open-mmlab/mmclassification#551]
Hello,

I have two datasets, of course with same classes and I want to train the network on this datasets combined. I am trying to put path of both datasets in the config file like this.

`data_prefix=('data/dataset_1', 'data/dataset_2')`. However I get this error. I know you can do multiple dataset training in mmdetection so wondering if it is possible to do it in mmclassifictaion through configs. Of course I can merge the dataset in one folder. 

``` shell
 File "tools/train.py", line 156, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/ubuntu/workspace/mmclassification/mmcls/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: ImageNet: listdir: path should be string, bytes, os.PathLike, integer or None, not list

```

**Comment by Ezra-Yu** [comment]
you can use [ConcatDataset](https://mmclassification.readthedocs.io/en/latest/api.html#mmcls.datasets.ConcatDataset).

in cfg, for example

```
data = dict(
    samples_per_gpu=32,
    workers_per_gpu=2,
    train=[
        dict(
            type=dataset_type,
            data_prefix='data/imagenet/train',
            pipeline=train_pipeline),
        dict(
            type=dataset_type,
            data_prefix='data/imagenet/train',
            pipeline=train_pipeline),
        ],
    val=....,
    test=....,
```

change  `train`  dict  to a List[dict]
