### ISSUE TITLE
Is it possible to classify vary-size images without resizing them to fixed size? 

### ISSUE THREAD

**Issue by newforrestgump001** [open-mmlab/mmclassification#553]
For vary-size images, it is possible to classify them without resizing them to same size. Thank you a lot!

**Comment by Ezra-Yu** [comment]
Yes, you can just remove the Resize and Crop transforms in pipeline.

**Comment by 0x4f5da2** [comment]
Maybe you should also set batch size to 1 when testing.

**Comment by newforrestgump001** [comment]
@Ezra-Yu Is there some problem when sending multiple vary-sized images as a mini-batch. Is it permitted by cuda or cudnn? Thank you a lot for your quick reply!

**Comment by newforrestgump001** [comment]
@0x4f5da2 Can I set batch size greater than 1 when training?

**Comment by Ezra-Yu** [comment]
No, it is not permitted by cuda or cudnn.

but you can pad them to the same size before forward

**Comment by newforrestgump001** [comment]
@Ezra-Yu I got it. Thank you a lot!
