### ISSUE TITLE
[Feature] Option to include intermediate images in visualization by tools/visualizations/vis_pipeline.py

### ISSUE THREAD

**Issue by Minyus** [open-mmlab/mmclassification#561]
### Describe the feature

[tools/visualizations/vis_pipeline.py](https://github.com/open-mmlab/mmclassification/blob/master/tools/visualizations/vis_pipeline.py) is an awesome tool to design the preprocessing pipeline. (Thank you!)
Currently, [mode="concat"](https://github.com/open-mmlab/mmclassification/blob/715a80b09c62b6ccdd46e1735525ba56476e1e66/tools/visualizations/vis_pipeline.py#L47-L54) option can generate image including the original image and the output image, but I would like to request a new option (perhaps mode="concat_intermediates" or something) to include all the intermediate images (image after 1st transform step, image after 2nd transform step, ...) except for the ones set by [skip_type](https://github.com/open-mmlab/mmclassification/blob/715a80b09c62b6ccdd46e1735525ba56476e1e66/tools/visualizations/vis_pipeline.py#L22-L26) argument.

### Motivation

When I find the output image is not expected, sometimes it is not obvious that which transform step is problematic, and need to rerun vis_pipeline.py with skip_type argument set. 

### Related resources

https://github.com/open-mmlab/mmclassification/blob/master/tools/visualizations/vis_pipeline.py

**Comment by Ezra-Yu** [comment]
Thank you for your feedback and suggestion, we will consider adding that feature in the future. We also encourage users to implement by themselves and actively participate in the development of `MMClassification`.
