### ISSUE TITLE
download Vit-base  pretrained model but not existed.

### ISSUE THREAD

**Issue by devin-coder** [open-mmlab/mmclassification#562]
### questions
download vit pretrained model by clicked on url，but gived the following info:
*This XML file does not appear to have any style information associated with it. The document tree is shown below.*

**Comment by Ezra-Yu** [comment]
yes, it is a broken link in the model zoo, we will fix it soon.

you can get the weights from https://github.com/open-mmlab/mmclassification/tree/master/configs/vision_transformer

**Comment by mzr1996** [comment]
Closed by #564

**Comment by mzr1996** [comment]
Closed by #564
