### ISSUE TITLE
请问输出的pkl文件中pred_score，pred_label等指标的排序是什么？

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#565]
您好，作者！
首先非常感谢您的工作！
请问我在输出val-set的预测结果时，输出的pkl文件中pred_score，pred_label等预测结果的排序是什么？它们的排序是和meta/val.txt中图像名字的排序一一对应的吗？
谢谢！

**Comment by zhongqiu1245** [comment]
以及在没有答案的情况下，我想让mmcls预测图像，该如何去办到呢？

**Comment by Ezra-Yu** [comment]
you can refer to the [documentation](https://mmclassification.readthedocs.io/en/latest/getting_started.html#inference-and-test-a-dataset)

For example:
```
python tools/test.py configs/resnet/resnet50_8xb16_cifar10.py \
  https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_b16x8_cifar10_20210528-f54bfad9.pth \
  --out result.pkl \
  --out-items pred_score pred_labe
```

for more details please refer to `tools/test.py`, or run `python tools/test.py -h` for more help.

**Comment by zhongqiu1245** [comment]
Thank you!
