### ISSUE TITLE
The implementation of focalloss

### ISSUE THREAD

**Issue by zhijiejia** [open-mmlab/mmclassification#579]
I see the implementation of focal loss in `mmcls/models/losses/focal_loss.py`. Why does the sigmoid focal loss calculate the `pt` by the predicted class prob but not by the true class(**ground truth**) prob as in focal loss paper?

![image](https://user-images.githubusercontent.com/43838913/144557212-c7dae4ed-3ee0-41db-bc24-1b096a6a685d.png)

**Comment by mzr1996** [comment]
The original paper should calculate the `Pt` by the predicted class prob.
![图片](https://user-images.githubusercontent.com/26739999/144558952-c99b6fe0-18eb-4f39-90d6-3bd63ab8c623.png)

**Comment by zhijiejia** [comment]
`p ∈ [0, 1] is the model’s estimated probability for the class with label y = 1`
label y = 1 why not is the ground truth?

**Comment by mzr1996** [comment]
> `p ∈ [0, 1] is the model’s estimated probability for the class with label y = 1` label y = 1 why not is the ground truth?

y is the ground truth, is `target` in the program.

**Comment by zhijiejia** [comment]
oo, thanks, i get it, haha.
![image](https://user-images.githubusercontent.com/43838913/144562092-1a2d803a-5ab3-46a2-ba84-3eb01370d861.png)

**Comment by zhijiejia** [comment]
And Why the pt = p when target=0, not as the pt = (1 - p) when target = 0
![image](https://user-images.githubusercontent.com/43838913/144566527-a2d6331a-d487-490d-b526-90504d9e5058.png)
![image](https://user-images.githubusercontent.com/43838913/144566555-592c43b8-e0be-4b3e-912a-ac1bf3e357d7.png)

**Comment by zhijiejia** [comment]
oo,sorry, I understand
