### ISSUE TITLE
[Feature] Expose runner object to dataset's evaluate method in EvalHook

### ISSUE THREAD

**Issue by Minyus** [open-mmlab/mmclassification#581]
### Describe the feature

I would like to request to feed `runner` itself in addition to `runner.logger` in EvalHook at:

https://github.com/open-mmlab/mmclassification/blob/c090d3f7fd2a2a08b79d4dffb86591350c4ee063/mmcls/core/evaluation/eval_hooks.py#L45-L46

Currently, dataset's `evaluate` method can be customized to each user's dataset, but attributes of `runner` (e.g. epoch, iter, max_epochs, max_iters, model_name, model, timestamp, work_dir, etc.) cannot be accessed.

I tried to use the modified EvalHook as a custom cook:
```python
custom_imports = dict(imports=['ModifiedEvalHook'], allow_failed_imports=False)
```
but it did not work because `results` arg is not passed to custom hooks. 

### Motivation

By exposing `runner` to dataset's `evaluate` method, users can customize dataset's evaluate method more flexibly, for example, generate visualization plot of confusion matrix and save as a png/html file named with the epoch number (inaccessible now) under the training working directory (inaccessible now).

**Comment by Ezra-Yu** [comment]
Actually， we use EvalHook in `mmcv.runner.hooks` due to this line 
https://github.com/open-mmlab/mmclassification/blob/c090d3f7fd2a2a08b79d4dffb86591350c4ee063/mmcls/apis/train.py#L17-L23

and the `mmcls.core.EvalHook` will be deprecated in the future.  Since `EvalHook`  is default training hooks refer to [Tutorial 7](https://mmclassification.readthedocs.io/en/latest/tutorials/runtime.html#hooks), your modification will not effect.

Because downstream libraries in Openmmalb all rely on `mmcv`, this modification will cause BC breaking. I will ask what mmcv team think about this. 

I suggest you use an `AnalyseLogHook` after every eval epoch.

**Comment by Minyus** [comment]
Thank you, @Ezra-Yu 

The requested modification to the [code](https://github.com/open-mmlab/mmcv/blob/72182747a17231075b26768d37694781bd992daf/mmcv/runner/hooks/evaluation.py#L361) is just adding `runner=runner` like this:

```python
        eval_res = self.dataloader.dataset.evaluate(
            results, logger=runner.logger, runner=runner, **self.eval_kwargs)
```

This modification should be backward compatible (unless users add their own argument "runner" to their customized dataset's evaluate method or use positional arguments).

Is your suggestion adding a custom hook named `AnalyseLogHook`?
Is it possible to pass any data type (e.g. numpy array, html text, dict, list, etc.) other than simple numeric to a custom hook?

**Comment by Ezra-Yu** [comment]
but the code of other repo. such `mmdet.dataset.evaluate`, `mmseg.dataset.evaluate` and etc. would be modified too.
https://github.com/open-mmlab/mmclassification/blob/c090d3f7fd2a2a08b79d4dffb86591350c4ee063/mmcls/datasets/base_dataset.py#L117-L121
a arg `runner` should be added here. 

My suggestion is that you can log some import metrics, then read the log and get runner information in a custom hook, do your actions in this hook. Or just save the eval data in a new file, which meets your requirements for saving special data, remove them in the later.

**Comment by Minyus** [comment]
Ok, understood.
I'll write to a temporary file in evaluate method as a workaround.
Thank you!
