### ISSUE TITLE
请问如何对两张输入的图像做相同的aug操作？

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#582]
您好，作者！
首先非常感谢您的工作！
请问如何对两张输入的图像做相同的aug操作？
具体来说，我将两张3通道的图像concat成了6通道图像(上头要求的)，之后我想对这种6通道图像进行aug操作，比如autoaug，albu等。但是这些aug只支持3通道图像，不支持6通道图像。
所以我想到先把这6通道图像拆成两张3通道图像，之后对这两张3通道图像进行相同的aug操作（mmcv.xxxx），之后再把它们重新合并成6通道图像。
可是我该如何对这两张3通道的图像做相同的aug操作？
比如：
```
    def __call__(self, results):
        if np.random.rand() > self.prob:
            return results
        for key in results.get('img_fields', ['img']):
            img = results[key]
            img_contrasted = mmcv.auto_contrast(img)
            results[key] = img_contrasted.astype(img.dtype)
        return results
```
假设现在result[“img”]就是6通道图像，我现在把它拆成result[“img_1”]和result[“img_2”]，请问我该如何对result[“img_1”]和result[“img_2”]施加相同的mmcv.auto_contrast操作？
如果我用到Albu，请问我该如何对result[“img_1”]和result[“img_2”]施加相同的Albu操作？
(因为autoaug和Albu中有一些操作具有随机性，比如RandomBrightnessContrast， ChannelShuffle，RadomCrop等，所以要确保result[“img_1”]和result[“img_2”]也要受到**一模一样**的随机操作。
如果我写成类似：
```
result[“img_1”] = Albu.RandomBrightnessContrast(result[“img_1”])
result[“img_2”] = Albu.RandomBrightnessContrast(result[“img_2"])
```
则不能保证result[“img_1”]和result[“img_2”]受到相同的RandomBrightnessContrast操作，因为RandomBrightnessContrast有随机性，result[“img_1”]和result[“img_2”]收到的Random是不一致的。
一模一样的意思是比如result[“img_1”]被RadomCrop为224，则result[“img_2”]也必须被crop成224，且其crop的位置必须和result[“img_1”]的**一模一样**)
谢谢您！期待您的回复！

**Comment by Ezra-Yu** [comment]
maybe you can try to use `set_random_seed` before calling aug refer to [set_random_seed](https://github.com/open-mmlab/mmclassification/blob/c090d3f7fd2a2a08b79d4dffb86591350c4ee063/mmcls/apis/train.py#L67)

```
set_random_seed(0)
result[“img_1”] = Albu.RandomBrightnessContrast(result[“img_1”])
set_random_seed(0)
result[“img_2”] = Albu.RandomBrightnessContrast(result[“img_2"])
assert np.allclose(result[“img_1”], result[“img_2”])
```

**Comment by zhongqiu1245** [comment]
@Ezra-Yu 您好，感谢您的回复！
请问在mmcls的autoaug中也是用set_random_seed(0)吗？

**Comment by Ezra-Yu** [comment]
没有，

**Comment by zhongqiu1245** [comment]
@Ezra-Yu 您好，感谢您的回复！
抱歉临时增添了一些问题，请您重新看一下

**Comment by zhongqiu1245** [comment]
> @Ezra-Yu 您好，感谢您的回复！
> 请问在mmcls的autoaug(mmcv.xxxx)中也是用set_random_seed(0)吗？
> 如果设置set_random_seed(0)，那么读取相邻的两张6通道图像所采取的操作(比如RandomCrop)所裁剪的位置和大小是不是就成完全一样的了？
> 我想的是每张6通道图像采取的aug方式可以不一样，但是对于一张6通道图像而言，其内部的两张3通道图像的aug必须一模一样。

**Comment by Ezra-Yu** [comment]
我是希望你去尝试一下，看看结果是否一致。因为这类需求比较少，而且验证一下应该不难。

`Albu.RandomBrightnessContrast`**可能引入其他随机参数**。`set_random_seed`会固定一些随机种子包括 `np` , `torch` , `python.random` 等。我不是很确定这些已经完全包括了`Albu.RandomBrightnessContrast`引入的所有随机性。

**Comment by zhongqiu1245** [comment]
@Ezra-Yu 谢谢您！我稍后试一下，结果我会在这里反馈

**Comment by mzr1996** [comment]
Well, I think the easiest method is to write a new dataset and override the `load_annotation` and `prepare_data` methods.
For example
```python
class SixChannelDataset(BaseDataset):
    ...
    def prepare_data(self, idx):
        seed = np.random.randint(1 << 31)
        set_random_seed(seed)
        results = copy.deepcopy(self.data_infos[idx])
        data1 = self.pipelines({**results, 'prev_three_channel': True})

        set_random_seed(seed)
        results = copy.deepcopy(self.data_infos[idx])
        data2 = self.pipelines({**results, 'prev_three_channel': False})

        data1['img'] = torch.concat((data1['img'], data2['img']))
        return data1
```
And then, you can select which image to do augmentation by `prev_three_channel` field in `LoadImageFromFile`

**Comment by zhongqiu1245** [comment]
@mzr1996 谢谢您！我稍后试一下，结果我会在这里反馈

**Comment by zhongqiu1245** [comment]
@mzr1996 请问prev是什么意思？

**Comment by mzr1996** [comment]
> @mzr1996 请问prev是什么意思？

previous

**Comment by zhongqiu1245** [comment]
Thank you to all! It works!
