### ISSUE TITLE
How to transform the fine-tuned mmclassification of my datasets to torchscript model?

### ISSUE THREAD

**Issue by Williamlizl** [open-mmlab/mmclassification#585]
推荐使用英语模板 General question，以便你的问题帮助更多人。

### 首先确认以下内容
- 我已经查询了相关的 issue，但没有找到需要的帮助。
- 我已经阅读了相关文档，但仍不知道如何解决。

### 描述你遇到的问题

[填写这里]

### 相关信息
1. `pip list | grep "mmcv\|mmcls\|^torch"` 命令的输出
[填写这里]
2. 如果你修改了，或者使用了新的配置文件，请在这里写明
```python
[填写这里]
```
3. 如果你是在训练过程中遇到的问题，请填写完整的训练日志和报错信息
[填写这里]
4. 如果你对 `mmcls` 文件夹下的代码做了其他相关的修改，请在这里写明
[填写这里]

**Comment by mzr1996** [comment]
Here are the docs to convert models to TorchScript: https://mmclassification.readthedocs.io/en/latest/tools/pytorch2torchscript.html
