### ISSUE TITLE
Issue in running /demo/image_demo.py from spyder environment

### ISSUE THREAD

**Issue by tk2github** [open-mmlab/mmclassification#589]
Hi, I am interested to contribute in mmclassification lib. As a starting point,  I was trying exploring library and try to run /demo/image_demo.py from spyder  environment.  For the first time code is running fine but for the second time i am always getting the following error: 
AssertionError: scope mmcls exists in model registry

Any hints why it is occurring.

Please let me know also what are the procedures I need to follow to contribute.

**Comment by mzr1996** [comment]
Hello, can you provide the entire error info?

**Comment by tk2github** [comment]
Thank you very much.

First time importing library is fine
from mmcls.apis import inference_model, init_model, show_result_pyplot
When second time I am importing,  the exception is throwing like this

AssertionError: scope mmcls exists in model registry

**Comment by tk2github** [comment]
The error is getting only when running through spyder, but not in console

**Comment by mzr1996** [comment]
Got it, it may be caused by some features of Spyder. We didn't use it and need some time to check it.

**Comment by mzr1996** [comment]
Please try again after disabling the `UMR` in Spyder:
```
Tools -> Preferences -> Python interpreter -> Enable UMR
```

**Comment by tk2github** [comment]
Excellent !!! its working now
