### ISSUE TITLE
where is shufflnetv2-0.5x pretrained model?

### ISSUE THREAD

**Issue by Senwang98** [open-mmlab/mmclassification#590]
### Checklist
- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet
I am using mmdet2 to do some work, in backbone item:
```
backbone=dict(
        type='mmcls.ShuffleNetV2',
        widen_factor=0.5,
        out_indices=(0, 1, 2),
        norm_cfg=dict(type='BN'),
        act_cfg=dict(type='LeakyReLU', negative_slope=0.1),
        init_cfg=dict(type='Pretrained', checkpoint='mmcls://shufflenet_v2')
    ),
```
But, 1.0x and 1.5x work well, 0.5x will report shape mismatch....
it seems that when I set 0.5 in backbone, the model used to load is still shufflenetv2-1.0x!!!
So I want to set pretrained model path by myself, but now I can't find mmcls's shufflnetv2 pretrained model.

**Comment by Ezra-Yu** [comment]
Sorry that we don't provide that pretrained model.

**Comment by Senwang98** [comment]
@Ezra-Yu 
Okay, thanks for your reply!
