### ISSUE TITLE
Inference results don't match test results

### ISSUE THREAD

**Issue by gabrielpan147** [open-mmlab/mmclassification#596]
### Checklist
- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

Hello, I trained Resnet-101 on my custom dataset. Then I tested the model with the official test tool on my test set and got an accuracy of 91.44%. However, when I try to inference the test set image one by one, I found the model can't classify images correctly. Almost all the images are misclassified.  My data set has 3 labels '3h','5h' and '8h', The model will classify everything into ''8h'. But when I reload the model, it might predict everything into '5h'. 

To control, I tried different models on different dataset and this issue still existed. Which result should I believe?
Thank you!

### Post related information
1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`

mmcls                         0.18.0
mmcv-full                     1.4.0
torch                         1.8.1
torchaudio                    0.8.0a0+e4e171a
torchvision                   0.9.1

2. Your config file if you modified it or created a new one.
```python
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=101,
        num_stages=4,
        out_indices=(3, ),
        style='pytorch'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=3,
        in_channels=2048,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5)))
dataset_type = 'ImageNet'
img_norm_cfg = dict(
    mean=[420.57, 683.84, 1104.41], std=[100.3, 50.3, 150.6], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile', color_type='unchanged', to_float32=True),
    dict(type='RandomResizedCrop', size=224),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(
        type='Normalize',
        mean=[420.57, 683.84, 1104.41],
        std=[100.3, 50.3, 150.6],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile', color_type='unchanged', to_float32=True),
    dict(type='Resize', size=(256, -1)),
    dict(type='CenterCrop', crop_size=224),
    dict(
        type='Normalize',
        mean=[420.57, 683.84, 1104.41],
        std=[100.3, 50.3, 150.6],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
data = dict(
    samples_per_gpu=32,
    workers_per_gpu=4,
    train=dict(
        type='ImageNet',
        data_prefix='/mnt/data/processed/microglia/ImageNet_merge/train',
        pipeline=[
            dict(
                type='LoadImageFromFile',
                color_type='unchanged',
                to_float32=True),
            dict(type='RandomResizedCrop', size=224),
            dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
            dict(
                type='Normalize',
                mean=[420.57, 683.84, 1104.41],
                std=[100.3, 50.3, 150.6],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='ToTensor', keys=['gt_label']),
            dict(type='Collect', keys=['img', 'gt_label'])
        ],
        classes='/mnt/data/processed/microglia/ImageNet_merge/classes.txt'),
    val=dict(
        type='ImageNet',
        data_prefix='/mnt/data/processed/microglia/ImageNet_merge/test',
        ann_file='/mnt/data/processed/microglia/ImageNet_merge/test/test.txt',
        pipeline=[
            dict(
                type='LoadImageFromFile',
                color_type='unchanged',
                to_float32=True),
            dict(type='Resize', size=(256, -1)),
            dict(type='CenterCrop', crop_size=224),
            dict(
                type='Normalize',
                mean=[420.57, 683.84, 1104.41],
                std=[100.3, 50.3, 150.6],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ],
        classes='/mnt/data/processed/microglia/ImageNet_merge/classes.txt'),
    test=dict(
        type='ImageNet',
        data_prefix='/mnt/data/processed/microglia/ImageNet_merge/test',
        ann_file='/mnt/data/processed/microglia/ImageNet_merge/test/test.txt',
        pipeline=[
            dict(
                type='LoadImageFromFile',
                color_type='unchanged',
                to_float32=True),
            dict(type='Resize', size=(256, -1)),
            dict(type='CenterCrop', crop_size=224),
            dict(
                type='Normalize',
                mean=[420.57, 683.84, 1104.41],
                std=[100.3, 50.3, 150.6],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ],
        classes='/mnt/data/processed/microglia/ImageNet_merge/classes.txt'))
evaluation = dict(interval=10, metric='accuracy', metric_options=dict(topk=1))
optimizer = dict(type='Adam', lr=0.0001, weight_decay=0.001, amsgrad=False)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='step', step=[20, 50, 70], gamma=0.1)
runner = dict(type='EpochBasedRunner', max_epochs=100)
checkpoint_config = dict(interval=10)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
work_dir = 'merge_resnet_100e_128'
gpu_ids = range(0, 1)
```

**Comment by Ezra-Yu** [comment]
you can use more args in `test.py` to find where is the problem, for example,`--out`, `--out-items`, `--show-dir`. for more details please refer to the [code](https://github.com/open-mmlab/mmclassification/blob/188aa6ed5dae184024818a6c3a72e5b0c733888d/tools/test.py#L28)

Maybe, your gt_label is wrong when training,you can use tool [vis_pipeline](https://github.com/open-mmlab/mmclassification/blob/master/tools/visualizations/vis_pipeline.py) to check, refer to [doc](https://mmclassification.readthedocs.io/en/latest/tools/visualization.html#pipeline-visualization).

**Comment by gabrielpan147** [comment]
Hello, as I have already reproduced the problem on different data set (in my case, different cell types data), it might not be the gt_label problem. I will follow your advice and try to find out the reason.

Thank you!

**Comment by mzr1996** [comment]
> The model will classify everything into ''8h'. But when I reload the model, it might predict everything into '5h'.
It looks like you failed to load the checkpoint, how do you load it?

**Comment by gabrielpan147** [comment]
Hello, I use the command below:

config_file='/home/gabriel/algorithm/tasks/microglia/classification/merge_resnet_100e_128/resnet_config.py'
checkpoint_file ='/home/gabriel/algorithm/tasks/microglia/classification/merge_resnet_100e_128/epoch_100.pth'
device = 'cuda'
model = init_model(config_file, checkpoint_file, device=device)

And the output is:

/home/gabriel/anaconda3/envs/mmlab/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
load checkpoint from local path: /home/gabriel/algorithm/tasks/microglia/classification/merge_resnet_100e_128/epoch_100.pth

**Comment by mzr1996** [comment]
So how do you "inference the test set image one by one"?

**Comment by gabrielpan147** [comment]
result={'8h':0,'5h':0,'3h':0}
for img in img_list:
    image_seg = TIFF.open(img,'r').read_image().astype(np.int16)
    res = inference_model(model, image_seg)
    result[res['pred_class']] +=1

I also tried to check individual inference on notebook, and one of the result is:
{'pred_label': 2, 'pred_score': 1.0, 'pred_class': '8h'}.

**Comment by mzr1996** [comment]
Looks like no problem, can you provide your dataset class?

**Comment by gabrielpan147** [comment]
It's simply 3h, 5h and 8h. I just tried to use tools/test.py, the accuracy is 91.44%, the recall is 91.51%. 
But If I inference the test/5h/*.tif, the result would be {'8h': 10620, '5h': 8, '3h': 2}

**Comment by mzr1996** [comment]
> It's simply 3h, 5h and 8h. I just tried to use tools/test.py, the accuracy is 91.44%, the recall is 91.51%. But If I inference the test/5h/*.tif, the result would be {'8h': 10620, '5h': 8, '3h': 2}

Can you provide your dataset class?

**Comment by gabrielpan147** [comment]
> > It's simply 3h, 5h and 8h. I just tried to use tools/test.py, the accuracy is 91.44%, the recall is 91.51%. But If I inference the test/5h/*.tif, the result would be {'8h': 10620, '5h': 8, '3h': 2}
> 
> Can you provide your dataset class?

Sorry I don't get it, you mean the dataset config file or something?

**Comment by mzr1996** [comment]
Well, I get it,
Can you try it with:
```python
import mmcv
from mmcls.apis import inference_model, init_model, show_result_pyplot
import glob,random
import glob, os
from libtiff import TIFF,TIFFimage
import matplotlib.pyplot as plt
import numpy as np
import random


config_file='/home/gabriel/algorithm/tasks/microglia/classification/merge_resnet_100e_128/resnet_config.py'
checkpoint_file ='/home/gabriel/algorithm/tasks/microglia/classification/merge_resnet_100e_128/epoch_100.pth'
device = 'cuda'
model = init_model(config_file, checkpoint_file, device=device)

img_list=glob.glob('/mnt/data/processed/microglia/ImageNet_merge/test/5h/*.tif')

result={'8h':0,'5h':0,'3h':0}
for img in img_list:
    res = inference_model(model, img)
    result[res['pred_class']] +=1

print(result)
print(res)
```

**Comment by gabrielpan147** [comment]
> Well, I get it, Can you try again with:
> 
> ```python
> import mmcv
> from mmcls.apis import inference_model, init_model, show_result_pyplot
> import glob,random
> import glob, os
> from libtiff import TIFF,TIFFimage
> import matplotlib.pyplot as plt
> import numpy as np
> import random
> 
> 
> config_file='/home/gabriel/algorithm/tasks/microglia/classification/merge_resnet_100e_128/resnet_config.py'
> checkpoint_file ='/home/gabriel/algorithm/tasks/microglia/classification/merge_resnet_100e_128/epoch_100.pth'
> device = 'cuda'
> model = init_model(config_file, checkpoint_file, device=device)
> 
> img_list=glob.glob('/mnt/data/processed/microglia/ImageNet_merge/test/5h/*.tif')
> 
> result={'8h':0,'5h':0,'3h':0}
> for img in img_list:
>     res = inference_model(model, img)
>     result[res['pred_class']] +=1
> 
> print(result)
> print(res)
> ```

Surprisingly it works! It seems to be some data type problem, and I will follow your pipeline in the future. I really appreciate your help!

BTW, could you please tell me why it works with a file path rather than an array?

**Comment by mzr1996** [comment]
It's simple, here is the original code in mmcv to read the image
```python
        if backend == 'turbojpeg':
            with open(img_or_path, 'rb') as in_file:
                img = jpeg.decode(in_file.read(),
                                  _jpegflag(flag, channel_order))
                if img.shape[-1] == 1:
                    img = img[:, :, 0]
            return img
        elif backend == 'pillow':
            img = Image.open(img_or_path)
            img = _pillow2array(img, flag, channel_order)
            return img
        elif backend == 'tifffile':
            img = tifffile.imread(img_or_path)
            return img
        else:
            flag = imread_flags[flag] if is_str(flag) else flag
            img = cv2.imread(img_or_path, flag)
            if flag == IMREAD_COLOR and channel_order == 'rgb':
                cv2.cvtColor(img, cv2.COLOR_BGR2RGB, img)
            return img
```
Since you didn't specify the backend, mmcv use the `cv2` as the backend to load images in the `LoadImageFromFile` pipeline.
I think the outputs of different loading backends are different.
```python
img_path = 'tiff_img_file'
img1 = TIFF.open(img_path,'r').read_image().astype(np.int16)
img2 = cv2.imread(img_path, 'unchanged').astype(np.float32)
```

**Comment by mzr1996** [comment]
BTW, if you directly pass the file path to `inference_model`, it will use `LoadImageFromFile` in your pipeline to load the image

**Comment by gabrielpan147** [comment]
I got it, thanks a lot!!
