### ISSUE TITLE
How do I add GradCAM

### ISSUE THREAD

**Issue by 6sz** [open-mmlab/mmclassification#599]
How can I implemented Class Activation Map methods

**Comment by Ezra-Yu** [comment]
You could use `GradCAM` by using this [PR](https://github.com/open-mmlab/mmclassification/pull/577). Here is the [documentation link](https://mmclassification--577.org.readthedocs.build/en/577/tools/visualization.html#class-activation-map-visualization).

But if you want implemented Class Activation Map methods by yourself, please refer to this 3rd package src code, [grad-cam](https://github.com/jacobgil/pytorch-grad-cam), test your code by replacing the Classes.

**Comment by 6sz** [comment]
Thank you very much for your help, but the tools/visualizations/vis_cam.py file was deleted from the master branch, why was it deleted?Do I need to go back to the previous version to use it?

**Comment by Ezra-Yu** [comment]
No, it is still under review, but it is currently functionally implemented, so if you are in a hurry, you can use it now. We will modify it based on the review comments in the near future and then merge it on the master.

You can find it in the project branch of my personal fork, [branch link](https://github.com/Ezra-Yu/mmclassification/tree/cam), [tortuial documentation](https://github.com/Ezra-Yu/mmclassification/blob/cam/docs/tools/visualization.md)

**Comment by 6sz** [comment]
Wow, thank you very much
