### ISSUE TITLE
A error in tutorials/new_dataset.md

### ISSUE THREAD

**Issue by wxh928408225** [open-mmlab/mmclassification#6]
In this markdown,
`We can create a new dataset in mmdet/datasets/filelist.py to load the data.`
But this project does not have mmdet. I think it should be `mmcls/datasets`. 

Please updata this markdown.
Thanks!

**Comment by yl-1993** [comment]
Thanks. It will be updated via PR https://github.com/open-mmlab/mmclassification/pull/8.
