### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Jokoe66** [open-mmlab/mmclassification#60]
The argument **bboxes** of mmcv.imcrop should be in (xmin, ymin, xmax, ymax) format.
https://github.com/open-mmlab/mmclassification/blob/52d8ea462182872ac8801254298eeacbc0fd9757/mmcls/datasets/pipelines/transforms.py#L121-L124

**Comment by ycxioooong** [comment]
Thanks for your report and we'll submit a pull request to fix it.
