### ISSUE TITLE
何如降低数据memory的使用

### ISSUE THREAD

**Issue by liwang0621** [open-mmlab/mmclassification#601]
推荐使用英语模板 General question，以便你的问题帮助更多人。

### 首先确认以下内容
- 我已经查询了相关的 issue，但没有找到需要的帮助。
- 我已经阅读了相关文档，但仍不知道如何解决。

### 描述你遇到的问题
当我的workers_per_gpu给的比较大的时候，memory使用很大，workers_per_gpu=8大概占用五六十GB memory，但是workers_per_gpu=2的话，训练又太慢，data_time从原来的0.00x增长为0.xxx

### 相关信息
samples_per_gpu=128,
workers_per_gpu=2,

使用的是lmdb

**Comment by 0x4f5da2** [comment]
You may consider to:
* Put the files on a Solid State Drive or system memory(under the `/dev/shm` directory)
* Check if the Dataset with lmdb is implemented properly. [link](https://codeslake.github.io/research/pytorch/How-to-use-LMDB-with-PyTorch-DataLoader/)

**Comment by encichou** [comment]
你解决这问题了吗？我也是相同的问题，网络结构改动一下速度就下降了。data_time从原来的0.00x增长为0.xxx

**Comment by mzr1996** [comment]
@liwang0621 @encichou 
Maybe it's related to https://github.com/open-mmlab/mmdetection/pull/6867
You can try to modify according to the PR.

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
