### ISSUE TITLE
[Feature]training timm model with frozen_stages and norm eval tricks

### ISSUE THREAD

**Issue by Bo396543018** [open-mmlab/mmclassification#605]
I found use frozen_stages&norm eval may improve transfer learning performance. 
Currently，the timm wrapper not support these tricks.

**Comment by Ezra-Yu** [comment]
Yes, they do not implement related functions. Every backbone has a different implement. Currently, there is no way to modify this in general.

what backbone do you want to use?

**Comment by Bo396543018** [comment]
I use timm's resnet50 model to compare 21k &1k pretrained improvement.

**Comment by mzr1996** [comment]
So why don't just use mmcls ResNet implementation

**Comment by Bo396543018** [comment]
Use timm warpper could avoid the problem for 21k pretrained weights inconsistent naming.

**Comment by mzr1996** [comment]
Well, the freeze stages function depends on the detailed network and we cannot provide a unified API except timm provides it.

**Comment by Bo396543018** [comment]
Ok，Thank you for your reply，I'll try to convert weights for comparison.

**Comment by Ezra-Yu** [comment]
@Bo396543018  We are considering adding relevant pre-trained models to mmcls, and we will thank you if you complete the relevant work, put relevant weights or scripts in mmcls.

**Comment by Bo396543018** [comment]
@ Ezra-Yu OK，When I complete，I'll share the converted weights
