### ISSUE TITLE
PYTHONPATH="$(dirname $0)/..":$PYTHONPATH

### ISSUE THREAD

**Issue by shaoshuaidu** [open-mmlab/mmclassification#606]
### PYTHONPATH="$(dirname $0)/..":$PYTHONPATH
in dist_train.sh file, there is a line ''PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \'', what does it mean?  I have konwn that it is about PYTHONPATH. But how it works?  It is different from "export PYTHONPATH=###'. Could anyone explain it to me? Thanks! I am a new beginner.

**Comment by mzr1996** [comment]
The `$(dirname $0)/..` means the parent folder of `tools`, it's the root directory of mmclassification.
By adding this line, the `dist_train.sh` can automatically add the root directory of mmclassification in the PYTHONPATH, wherever you call this script.

**Comment by shaoshuaidu** [comment]
I so appreciate your reply. And I still don't understand the grammer of the "PYTHONPATH = "mmclassification/":$PYTHONPATH", which looks like a shell script. But I don't find the relevant shell grammer that explain how it works. Cound you provide some reference or guidebook?

**Comment by mzr1996** [comment]
`PYTHONPATH = "mmclassification/":$PYTHONPATH` is an assignment to `PYTHONPATH`. It's like `export` but a little different.
This method only affects the program in this line, for example:
```shell
$ export VAR=hello
$ VAR=world bash -c "echo \$VAR"
world
$ echo $VAR
hello
```

**Comment by shaoshuaidu** [comment]
> `PYTHONPATH = "mmclassification/":$PYTHONPATH` is an assignment to `PYTHONPATH`. It's like `export` but a little different. This method only affects the program in this line, for example:
> 
> ```shell
> $ export VAR=hello
> $ VAR=world bash -c "echo \$VAR"
> world
> $ echo $VAR
> hello
> ```

thank you very much.  It's very enlighting.
