### ISSUE TITLE
How to train my model(designed by me or provided by mmcls) on my dataset based on the package mmcls installed by pip?

### ISSUE THREAD

**Issue by lartpang** [open-mmlab/mmclassification#608]
### Checklist
- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

How to train my model (designed by me or provided by `mmcls`) on my dataset based on the package `mmcls` installed by `pip`?

The current introduction about them is only based on the develop version of `mmcls`:
- https://mmclassification.readthedocs.io/en/latest/tutorials/new_modules.html
- https://mmclassification.readthedocs.io/en/latest/tutorials/new_dataset.html

**Comment by Ezra-Yu** [comment]
You can try [mim](https://github.com/open-mmlab/mim).

before you use mim, please add model setting, dataset setting, runtime setting, and schedule setting in your config file refer to tutorial [finetune models](https://mmclassification.readthedocs.io/en/latest/tutorials/finetune.html)

**Comment by lartpang** [comment]
@Ezra-Yu Thanks!
