### ISSUE TITLE
How to remove EvalOnly

### ISSUE THREAD

**Issue by ioir123ju** [open-mmlab/mmclassification#616]
I don't have LR information when I train.
config: tnt_s_patch16_224_evalonly_imagenet.py
![image](https://user-images.githubusercontent.com/14951957/147305907-38e7a781-eae2-459f-9d81-e3807ec9b80d.png)

**Comment by Ezra-Yu** [comment]
Are there a few pictures in your dataset?

I guess that your config has a big log_interval in [line](https://github.com/open-mmlab/mmclassification/blob/131d8c6296caf56cfb3928632b35a80380e4ce98/configs/_base_/default_runtime.py#L4)

try a small log_interval :
```
log_config = dict(
    interval=5,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])

```

**Comment by ioir123ju** [comment]
> 

thanks, I solved~
