### ISSUE TITLE
vgg16 python2onnx.py 在打开dynamic-export时出现：'ClsHead' object has no attribute 'num_classes' [Bug]

### ISSUE THREAD

**Issue by Beichen-Wang** [open-mmlab/mmclassification#618]
### 描述 bug

[vgg16 python2onnx.py 在打开dynamic-export时出现：'ClsHead' object has no attribute 'num_classes' [Bug]]

### 附加内容
bug信息
 File "tools/deployment/pytorch2onnx.py", line 236, in <module>
    verify=args.verify)
  File "tools/deployment/pytorch2onnx.py", line 150, in pytorch2onnx
    input_shape[3] * 2), model.head.num_classes)
  File "/home/wangbeichen/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'ClsHead' object has no attribute 'num_classes'

[填写这里]

**Comment by mzr1996** [comment]
Hello, can you provide your mmcls version?

**Comment by Beichen-Wang** [comment]
> Hello, can you provide your mmcls version?

0.18.0

**Comment by mzr1996** [comment]
Ok, it's a bug in verification.
Please modify the script's 150 line
https://github.com/open-mmlab/mmclassification/blob/d1d9ebfc67c1cdb02af8edb8d13a311ec713cd3a/tools/deployment/pytorch2onnx.py#L150
to 
```python
 input_shape[3] * 2), num_classes) 
```
And we will fix it later.

**Comment by Beichen-Wang** [comment]
OK
