### ISSUE TITLE
打开dynamic-export时，pytorch2onnx.py中 mobilenetv2模型报错[Bug]

### ISSUE THREAD

**Issue by Beichen-Wang** [open-mmlab/mmclassification#619]
推荐使用英语模板 Bug report，以便你的问题帮助更多人。

### 描述 bug
报错原因是因为：
采用np.allclose默认精度误差太小，会在这个位置报错：“The outputs are different between Pytorch and ONNX”

**Comment by mzr1996** [comment]
Hello, what's the specific difference between PyTorch output and ONNX output?

**Comment by Beichen-Wang** [comment]
> Hello, what's the specific difference between PyTorch output and ONNX output?

主要是因为：Pytorch and ONNX 结果中有部分参数相差大小为e -6，而np.allclose在这个精度范围内会报错。

**Comment by mzr1996** [comment]
> 

Ok, we will check the detailed difference and increase the tolerance of `np,allclose`. Thank you.

**Comment by okideal** [comment]
Encountered the same problem when trying to convert the efficientNet, try not to expand the input shape by 2 of dummy input solvedt this temporarily , could anybody explain the reason.

**Comment by Ezra-Yu** [comment]
@Beichen-Wang  Currently, all deployment tools are no longer maintained, and all deployment-related work can try [mmdeploy](https://github.com/open-mmlab/mmdeploy).
