### ISSUE TITLE
Can I load pretrained weights from the model trained by torchvision?

### ISSUE THREAD

**Issue by hunto** [open-mmlab/mmclassification#620]
Thanks for your excellent work.

I'm trying to load the weights of ResNet-34 trained by torchvision, following other projects like mmdet, I've added an `init_cfg` into the model setting as follows,

```python
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=34,
        num_stages=4,
        out_indices=(3, ),
        style='pytorch'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=1000,
        in_channels=512,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5),
    ),
    init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet34')
)
```

but the weights in torchvision and mmcls are not matched and mmcls produces warnings below

```
2021-12-27 16:11:59,588 - mmcv - WARNING - The model and loaded state dict do not match exactly
unexpected key in source state_dict: conv1.weight, bn1.running_mean, ...
missing keys in source state_dict: backbone.conv1.weight, backbone.bn1.weight, backbone.bn1.bias, backbone.bn1.running_mean, ...
```

It seems that the weights in mmcls has a prefix `backbone` or `head` (defined by `ImageClassifier`), which makes the misalignment of names of weights in these two projects.

A solution is to load the weights inside the `backbone` and `head`, like

```python
model = dict(
    type='mmcls.ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=34,
        num_stages=4,
        out_indices=(3, ),
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet34')),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=1000,
        in_channels=512,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5),
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet34')
    ))
```
then the weights seems to be properly loaded.

However, this also produces warnings below (though the weights are loaded correctly)

```
2021-12-27 16:11:59,163 - mmcls - INFO - initialize ResNet with init_cfg [{'type': 'Kaiming', 'layer': ['Conv2d']}, {'type': 'Constant', 'val': 1, 'layer': ['_BatchNorm', 'Group
Norm']}]2021-12-27 16:11:59,298 - mmcls - INFO - initialize LinearClsHead with init_cfg {'type': 'Normal', 'layer': 'Linear', 'std': 0.01}
2021-12-27 16:11:59,318 - mmcls - INFO - initialize ResNet with init_cfg {'type': 'Pretrained', 'checkpoint': 'torchvision://resnet34'}2021-12-27 16:11:59,318 - mmcv - INFO - load model from: torchvision://resnet34
2021-12-27 16:11:59,318 - mmcv - INFO - Use load_from_torchvision loader2021-12-27 16:11:59,588 - mmcv - WARNING - The model and loaded state dict do not match exactly
unexpected key in source state_dict: fc.weight, fc.bias
2021-12-27 16:11:59,620 - mmcls - INFO - initialize LinearClsHead with init_cfg {'type': 'Pretrained', 'checkpoint': 'torchvision://resnet34'}
2021-12-27 16:11:59,621 - mmcv - INFO - load model from: torchvision://resnet342021-12-27 16:11:59,621 - mmcv - INFO - Use load_from_torchvision loader
2021-12-27 16:11:59,787 - mmcv - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: conv1.weight, bn1.running_mean, bn1.running_var, bn1.weight, bn1.bias, layer1.0.conv, ...
```

# Question
**Is there any better way to load the weights trained by torchvision without warnings?**

**Comment by Ezra-Yu** [comment]
Yes, but before you use the weights from  torchvision, you must convert the key names of weight refer to the scripts like [convert vgg weight script](https://github.com/open-mmlab/mmclassification/blob/master/tools/convert_models/vgg_to_mmcls.py).

what model are you training?

**Comment by hunto** [comment]
> Yes, but before you use the weights from torchvision, you must convert the key names of weight refer to the scripts like [convert vgg weight script](https://github.com/open-mmlab/mmclassification/blob/master/tools/convert_models/vgg_to_mmcls.py).
> 
> what model are you training?

Thanks for your reply.

The model I used is `ResNet-34`.

**If the checkpoints trained by torchvision must be converted, can mmcls provide the converted checkpoints so that we can easily load it through url?**

One reason of not using the weights trained by mmcls is that, I find the mmcls-trained models have higher accuracies compared to the torchvision's, while the papers I need to reproduce uses the torchvision's weights.

For instance, the timm provides converted torchvision ckpts (https://github.com/rwightman/pytorch-image-models/blob/07eb2f12005f75be3ed6c2394f3512e7a8ac640a/timm/models/resnet.py#L835), and we can easily build the pretrained models in timm with the same settings (accuracies) as other papers for fair comparisons.

**Comment by mzr1996** [comment]
Here is a simple script to convert the torchvision ResNet checkpoint to mmcls checkpoint:
```python
import torch
import torchvision
from collections import OrderedDict

model = torchvision.models.resnet34(pretrained=True)
state_dict = OrderedDict()

for k, v in model.state_dict().items():
    if not k.startswith('fc'):
        state_dict['backbone.' + k] = v
    else:
        state_dict['head.' + k] = v

torch.save(state_dict, './resnet34.pth')
