### ISSUE TITLE
Which `config.py` use `RandAugment`?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#621]
Hi, dear authors!
Thank you for your amazing job!
Could you tell me which `config.py` use `RandAugment`?
Thank you!

**Comment by Ezra-Yu** [comment]
No, there is no train config using `RandAugment`.

you can use `RandAugment` as `AutoAugment` in [this file](https://github.com/open-mmlab/mmclassification/blob/master/configs/_base_/datasets/imagenet_bs64_autoaug.py).
just modify the first line to :
```
_base_ = ['./pipelines/rand_aug.py']
```

**Comment by mzr1996** [comment]
https://github.com/open-mmlab/mmclassification/blob/master/configs/swin_transformer/swin-small_16xb64_in1k.py

**Comment by zhongqiu1245** [comment]
@Ezra-Yu @mzr1996 Thank you!
