### ISSUE TITLE
KeyError: 'auto_increasing_policies'

### ISSUE THREAD

**Issue by lingchensimon** [open-mmlab/mmclassification#627]
Checklist
I have searched related issues but cannot get the expected help.
I have read related documents and don't know what to do.
Describe the question you meet
Hi mmcls team,

I have upgraded mmcls v0.18.0 and mmcv 1.4.2，When I train the resnet50 model, error will be reported .
The error information and configuration file is pasted below.I would appreciate it if someone could provide any suggestions or solutions for implementation.

Thank you,

error information:(python37) jingxiaotong@GPU3:/media/lingmy/new_mmclassification$ python tools/train.py configs/resnet/resnet50_b32x1_voc.py
/home/jingxiaotong/anaconda3/envs/python37/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py:32: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/home/jingxiaotong/anaconda3/envs/python37/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/jingxiaotong/anaconda3/envs/python37/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
Traceback (most recent call last):
  File "tools/train.py", line 181, in <module>
    main()
  File "tools/train.py", line 90, in main
    cfg = Config.fromfile(args.config)
  File "/home/jingxiaotong/anaconda3/envs/python37/lib/python3.7/site-packages/mmcv/utils/config.py", line 335, in fromfile
    use_predefined_variables)
  File "/home/jingxiaotong/anaconda3/envs/python37/lib/python3.7/site-packages/mmcv/utils/config.py", line 248, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/jingxiaotong/anaconda3/envs/python37/lib/python3.7/site-packages/mmcv/utils/config.py", line 262, in _file2dict
    base_cfg_dict)
  File "/home/jingxiaotong/anaconda3/envs/python37/lib/python3.7/site-packages/mmcv/utils/config.py", line 160, in _substitute_base_vars
    v, base_var_dict, base_cfg)
  File "/home/jingxiaotong/anaconda3/envs/python37/lib/python3.7/site-packages/mmcv/utils/config.py", line 168, in _substitute_base_vars
    for c in cfg
  File "/home/jingxiaotong/anaconda3/envs/python37/lib/python3.7/site-packages/mmcv/utils/config.py", line 168, in <listcomp>
    for c in cfg
  File "/home/jingxiaotong/anaconda3/envs/python37/lib/python3.7/site-packages/mmcv/utils/config.py", line 156, in _substitute_base_vars
    new_v = new_v[new_k]
KeyError: 'auto_increasing_policies'

configuration file：
```
_base_ = [
    '../_base_/datasets/voc_bs32.py',
    '../_base_/default_runtime.py',
]
# optimizer
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
# learning policy
# lr_config = dict(policy='step', step=[30, 60, 90])
lr_config = dict(
    policy='CosineAnnealing',
    min_lr=0,
    warmup='linear',
    warmup_iters=5,
    warmup_ratio=1e-6,
    warmup_by_epoch=True)
runner = dict(type='EpochBasedRunner', max_epochs=100)
# fp16 = dict(loss_scale='dynamic')
fp16 = dict(loss_scale=512.)
# use different head for multilabel task
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,       
        out_indices=(3, ),   
        style='pytorch'),    
    neck=dict(type='GlobalAveragePooling'),    
    head=dict(
        type='MultiLabelLinearClsHead',
        num_classes=8,
        in_channels=2048,    
        # loss=dict(type='CrossEntropyLoss', loss_weight=1.0, use_soft=True),   
        loss=dict(type='LabelSmoothLoss', label_smooth_val=0.1, loss_weight=1.0)
    ),
    train_cfg=dict(
            # augments=dict(type='BatchMixup', alpha=0.2, num_classes=8,
            #               prob=1.)
            augments=dict(
                        type='BatchCutMix', alpha=1.0, num_classes=8, prob=1.0)
    )
)
```

**Comment by Ezra-Yu** [comment]
What is the content of the 'configs/_base_/datasets/voc_bs32.py' file？
Is there any modification relative to the  'configs/_base_/datasets/voc_bs32.py'  file？

**Comment by lingchensimon** [comment]
yes,It is a custom file reference the 'configs/base/datasets/voc_bs16.py',and the data enhancement section reference the  'configs/base/datasets/Imagenet_ bs64_ autoaug. py'

the voc_bs32.py
_base_ = ['./pipelines/auto_aug.py']

# dataset settings
dataset_type = 'ImageNet'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomResizedCrop', size=224),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='AutoAugment', policies={{_base_.auto_increasing_policies}}),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(256, -1)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
data = dict(
    samples_per_gpu=64,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        data_prefix='data/imagenet/train',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        data_prefix='data/imagenet/val',
        ann_file='data/imagenet/meta/val.txt',
        pipeline=test_pipeline),
    test=dict(
        # replace `data/val` with `data/test` for standard test
        type=dataset_type,
        data_prefix='data/imagenet/val',
        ann_file='data/imagenet/meta/val.txt',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='accuracy')

**Comment by Ezra-Yu** [comment]
use
```
dict(type='AutoAugment', policies={{_base_.policy_imagenet}}),
```

**Comment by lingchensimon** [comment]
Thank you very much for all your help.
