### ISSUE TITLE
Training got stuck on CPU

### ISSUE THREAD

**Issue by robbine** [open-mmlab/mmclassification#630]
I followed the tutorial to train a resnet-cifar model. 
Since I don't have a gpu on my macbook, here is the command I used:
python tools/train.py configs/tutorial/resnet50_finetune_cifar.py --device=cpu

2022-01-06 10:13:35,745 - mmcls - INFO - workflow: [('train', 1)], max: 2 iters
2022-01-06 10:13:35,745 - mmcls - INFO - Checkpoints will be saved to /Users/xxx/GitProjects/mmclassification/work_dirs/resnet50_finetune_cifar by HardDiskBackend.
[W ParallelNative.cpp:214] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
[W ParallelNative.cpp:214] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)

I noticed that it has printed 'Checkpoints will be saved to ' in the log, which means before_run hook has been called.
Actually I think IterBasedRunner.train has been executed as well, because some cplusplus log also appeared in the log.
I'm not sure whether it's a dataset issue or the model is too big to fit in memory.
I wonder if 'data_batch = next(data_loader)' failed to fetch data. Is there any way to verify it ?
Here is the config which is basically the same as the one on the website with some minor tweaks.
```
`_base_ = [
    '../_base_/models/resnet50.py',
    '../_base_/datasets/cifar10_bs16.py', '../_base_/default_runtime.py'
]

# 模型设置
model = dict(
    backbone=dict(
        frozen_stages=2,
        init_cfg=dict(
            type='Pretrained',
            checkpoint='https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth',
            prefix='backbone',
        )),
    head=dict(num_classes=10),
)

# 数据集设置
img_norm_cfg = dict(
    mean=[125.307, 122.961, 113.8575],
    std=[51.5865, 50.847, 51.255],
    to_rgb=False,
)
train_pipeline = [
    dict(type='RandomCrop', size=32, padding=4),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Resize', size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label']),
]
test_pipeline = [
    dict(type='Resize', size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img']),
]
data = dict(
    train=dict(pipeline=train_pipeline),
    val=dict(pipeline=test_pipeline),
    test=dict(pipeline=test_pipeline),
)

# 训练策略设置
# 用于批大小为 128 的优化器学习率
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
# 学习率衰减策略
lr_config = dict(policy='step', step=[15])
runner = dict(type='IterBasedRunner', max_iters=2)
log_config = dict(interval=1)`
```

**Comment by mzr1996** [comment]
Hello, I have tested your config file on my computer and I cannot reproduce the problem.
Did you modify any files? And please provide your mmcls version.

**Comment by robbine** [comment]
I didn't modify any files. As I googled on the internet and set an env variable like this,
OMP_NUM_THREADS=1 python tools/train.py configs/tutorial/resnet50_finetune_cifar.py --device=cpu, the problem is solved.
But I think it's a temporary solution. The mmcls version is master branch in a development mode.

**Comment by mzr1996** [comment]
Maybe modification like https://github.com/open-mmlab/mmdetection/pull/6974 can final solve it. And we will do it later

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
