### ISSUE TITLE
关于如何开启自动混合精度训练

### ISSUE THREAD

**Issue by xiaoachen98** [open-mmlab/mmclassification#636]
推荐使用英语模板 General question，以便你的问题帮助更多人。

### 首先确认以下内容
- 我已经查询了相关的 issue，但没有找到需要的帮助。
- 我已经阅读了相关文档，但仍不知道如何解决。

### 描述你遇到的问题

请问一下，使用mmclassification怎么开启自动混合精度训练呀。
在mmsegmentation中，是在config中进行如下配置：
# fp16 settings
optimizer_config = dict(type='Fp16OptimizerHook', loss_scale=512.)
# fp16 placeholder
fp16 = dict()
我目前在mmclassification的config中只加入了第一行，加入第二行会报错。
并且请问一下，在classification任务中从头开始训练，使用自动混合精度的话性能大概会drop多少阿

### 相关信息
1. `pip list | grep "mmcv\|mmcls\|^torch"` 命令的输出
[填写这里]
2. 如果你修改了，或者使用了新的配置文件，请在这里写明
```python
[填写这里]
```
3. 如果你是在训练过程中遇到的问题，请填写完整的训练日志和报错信息
[填写这里]
4. 如果你对 `mmcls` 文件夹下的代码做了其他相关的修改，请在这里写明
[填写这里]

**Comment by RangiLyu** [comment]
refer to

https://github.com/open-mmlab/mmclassification/blob/5232965b17b6c050f9b328b3740c631ed4034624/configs/resnet/resnet50_8xb32-fp16-dynamic_in1k.py#L4
