### ISSUE TITLE
Should we convert the image to RGB before feeding it to the `Albu` class?

### ISSUE THREAD

**Issue by MendelXu** [open-mmlab/mmclassification#637]
### Checklist
- [x] I have searched related issues but cannot get the expected help.
- [x] I have read related documents and don't know what to do.

### Describe the question you meet
I am trying to use `albumentations` package to involve more augmentations in the pipeline. The `albumentations` takes an RGB image as input. However, as the output of `LoadImageFromFile` is an image in BGR order, shouldn't we convert it to RGB before feeding it to the `Albu` class? Do I understand it wrong?

### Post related information
No experiments are executed.

**Comment by Ezra-Yu** [comment]
yes, your understanding is correct, if you want to implement a new pipeline class, which uses `Albu`.

you can refer to [Lighting](https://github.com/open-mmlab/mmclassification/blob/5232965b17b6c050f9b328b3740c631ed4034624/mmcls/datasets/pipelines/transforms.py#L965), which adds a param of `to_rgb`.
when you use it, set `to_rgb=True` like https://github.com/open-mmlab/mmclassification/blob/5232965b17b6c050f9b328b3740c631ed4034624/configs/regnet/regnetx-400mf_8xb128_in1k.py#L44

**Comment by MendelXu** [comment]
Thanks for your clarification.
