### ISSUE TITLE
Any chance I can transfer model from mmseg to mmcls

### ISSUE THREAD

**Issue by ChengHan111** [open-mmlab/mmclassification#638]
I am pretty interested in the performance of Bit_b0 model in image classification task. But mmcls has not supported that yet. However I noticed that there is mit_b0 backbone supported in mmseg. Any chance I can transfer the backbone to classification task?

Thanks

**Comment by Ezra-Yu** [comment]
We strongly encourage such actions. We greatly appreciate community contributions to mmcls.

 I noticed that there is mit_b0 backbone supported in mmseg, the link is [here](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/mit.py) . This backbone is the implementation of `SegFormer: Simple and Efficient Design for Semantic Segmentation with Transformers <https://arxiv.org/abs/2105.15203>`. It seems to be a seg backbone. 

And the `bit` is the [BeiT](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/beit.py) and [this PR](https://github.com/open-mmlab/mmsegmentation/pull/1164) in mmseg?  I am sorry that your abbreviation confuses me a bit. Can you tell me the link between `bit` and `mit`？

**Comment by ChengHan111** [comment]
Sorry it is a typo, I mean Mit_b0! But thank you, I am trying to build a bridge between them. I notice that there are some connections between mmcls and mmdet by using scope in mmcv. Any chance I can take advantage of that and apply this between mmcls and mmseg?
Thanks

**Comment by Ezra-Yu** [comment]
Yes, you can use the backbones from mmseg in mmcls. refer to [this article](https://zhuanlan.zhihu.com/p/436865195). Just replace the `mmdet` to `mmseg`. This way you can quickly start your experiments without migrating the backbone

**Comment by ChengHan111** [comment]
Thanks! I successfully implemented this
