### ISSUE TITLE
Differences between Swin Transformer in mmcls/mmdet/mmseg

### ISSUE THREAD

**Issue by DianCh** [open-mmlab/mmclassification#640]
Hi! Thanks for maintaining such a wonderful framework. I want to pre-train my own Swin Transformers for other tasks but found that `mmcls`, `mmdet`, `mmseg` all have their `swin` folder. Are there any differences? What should be careful about after training using `mmcls`'s version?

**Comment by Ezra-Yu** [comment]
`Swin Transformers` in `mmcls`, `mmdet` , `mmseg` are all the same. the weight of mmcls  `Swin Transformers` can be load into model in mmdet. you can use mmcls or mmselfsup to train your pre-train model. 

By the way, you can use `mmdet`'s backbones in mmcls, you can also use `mmcls`'s backbone in mmdet, refer to [this Chinese article](https://zhuanlan.zhihu.com/p/436865195)  if you understand Chinese.

**Comment by DianCh** [comment]
Thank you! This is very helpful.
