### ISSUE TITLE
Why does the use of AutoAugment lead to the failure of mixed accuracy training acceleration

### ISSUE THREAD

**Issue by lingchensimon** [open-mmlab/mmclassification#643]
Checklist
I have searched related issues but cannot get the expected help.
I have read related documents and don't know what to do.
Describe the question you meet
Hi mmcls team,
     I did a series of experiments to improve the accuracy of the model.Under the existing datasets and training mode, fp16 can shorten the training time and improve the accuracy. However, when comparing the training results, it is found that the AutoAugment of data will invalidate fp16. Why does this happen?
The result of this experiment is pasted below.I would appreciate it if someone could provide any suggestions or solutions for implementation.

Thank you,

![image](https://user-images.githubusercontent.com/92513876/149074508-5a4ba730-4ce3-4ce0-9297-e71c7d1c55e3.png)

**Comment by Ezra-Yu** [comment]
Thanks for your report, and I will check it later.

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
