### ISSUE TITLE
How could I test on multiple datasets in one run?

### ISSUE THREAD

**Issue by EdyQiu** [open-mmlab/mmclassification#648]
Hello! Just want to ask a general question.
I have trained a model and want to test its performance on multiple datasets (dataset are in different folders, but images have the same name and annotation for datasets). 
Is there an easy way to write information for all datasets in the config file (e.g. val.data_prefix and val.ann_file ), so that I can run the code once and get all results? 
If it is not possible, any suggestions to modify the code are also welcome!

**Comment by Ezra-Yu** [comment]
use [ConcatDataWapper](https://github.com/open-mmlab/mmclassification/blob/32d606e1a110188eb050e2d579120a3277b76957/mmcls/datasets/dataset_wrappers.py#L13),
```
data = dict(
val=[val_cfg1, val_cfg2, val_cfg3...........,  ])
```

for example:
```
data = dict(
    samples_per_gpu=32,
    workers_per_gpu=2,
    train=dict(...................),
    val=[dict(
        type=dataset_type,
        data_prefix='data/imagenet/val',
        ann_file='data/imagenet/meta/val.txt',
        pipeline=test_pipeline),
        dict(
        type=dataset_type,
        data_prefix='data/imagenet/val',
        ann_file='data/imagenet/meta/val.txt',
        pipeline=test_pipeline),],
    test=dict(.......................)
```

**Comment by EdyQiu** [comment]
> 

Thanks for your quick reply!
I have tried your approach, while found the following problem:

  **File "/data2/qiuxinkuan/mmclassification-master/tools/test.py", line 126, in main
    cfg.data.test.test_mode = True
AttributeError: 'list' object has no attribute 'test_mode'_**

This line is before "building dataset and dataloader", so the program got confused by the list format because it does not has the arribute "test_mode"

**I also tried to delete this line, and another problem occurred :
  File "/data2/qiuxinkuan/mmclassification-master/tools/test.py", line 188, in main
    eval_results = dataset.evaluate(outputs, args.metrics,
AttributeError: 'ConcatDataset' object has no attribute 'evaluate'**

It seems I need to modify more code.

Do you know where I got wrong? 
My modification is the following(I simply copy the original test dict and put them in the list):

    **test=[
        dict(
        type='ImageNet_16x4_overall_coarsegrained',
        data_prefix=
        '/data2/qiuxinkuan/mmclassification-master/data/imagenet/val',
        ann_file=
        '/data2/qiuxinkuan/mmclassification-master/data/imagenet/meta/overall_4_coarsegrained_val.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=(256, -1)),
            dict(type='CenterCrop', crop_size=224),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ]),
        dict(
        type='ImageNet_16x4_overall_coarsegrained',
        data_prefix=
        '/data2/qiuxinkuan/mmclassification-master/data/imagenet/val',
        ann_file=
        '/data2/qiuxinkuan/mmclassification-master/data/imagenet/meta/overall_4_coarsegrained_val.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=(256, -1)),
            dict(type='CenterCrop', crop_size=224),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
        ]**

**Comment by EdyQiu** [comment]
> use [ConcatDataWapper](https://github.com/open-mmlab/mmclassification/blob/32d606e1a110188eb050e2d579120a3277b76957/mmcls/datasets/dataset_wrappers.py#L13),
> 
> ```
> data = dict(
> val=[val_cfg1, val_cfg2, val_cfg3...........,  ])
> ```
> 
> for example:
> 
> ```
> data = dict(
>     samples_per_gpu=32,
>     workers_per_gpu=2,
>     train=dict(...................),
>     val=[dict(
>         type=dataset_type,
>         data_prefix='data/imagenet/val',
>         ann_file='data/imagenet/meta/val.txt',
>         pipeline=test_pipeline),
>         dict(
>         type=dataset_type,
>         data_prefix='data/imagenet/val',
>         ann_file='data/imagenet/meta/val.txt',
>         pipeline=test_pipeline),],
>     test=dict(.......................)
> ```

Thanks for your quick reply!
I have tried your approach, while found the following problem:

File "/data2/qiuxinkuan/mmclassification-master/tools/test.py", line 126, in main
cfg.data.test.test_mode = True
AttributeError: 'list' object has no attribute 'test_mode'_

This line is before "building dataset and dataloader", so the program got confused by the list format because it does not has the arribute "test_mode"

I also tried to delete this line, and another problem occurred :
File "/data2/qiuxinkuan/mmclassification-master/tools/test.py", line 188, in main
eval_results = dataset.evaluate(outputs, args.metrics,
AttributeError: 'ConcatDataset' object has no attribute 'evaluate'

It seems I need to modify more code.

Do you know where I got wrong?
My modification is the following(I simply copy the original test dict and put them in the list):

**test=[
    dict(
    type='ImageNet_16x4_overall_coarsegrained',
    data_prefix=
    '/data2/qiuxinkuan/mmclassification-master/data/imagenet/val',
    ann_file=
    '/data2/qiuxinkuan/mmclassification-master/data/imagenet/meta/overall_4_coarsegrained_val.txt',
    pipeline=[
        dict(type='LoadImageFromFile'),
        dict(type='Resize', size=(256, -1)),
        dict(type='CenterCrop', crop_size=224),
        dict(
            type='Normalize',
            mean=[123.675, 116.28, 103.53],
            std=[58.395, 57.12, 57.375],
            to_rgb=True),
        dict(type='ImageToTensor', keys=['img']),
        dict(type='Collect', keys=['img'])
    ]),
    dict(
    type='ImageNet_16x4_overall_coarsegrained',
    data_prefix=
    '/data2/qiuxinkuan/mmclassification-master/data/imagenet/val',
    ann_file=
    '/data2/qiuxinkuan/mmclassification-master/data/imagenet/meta/overall_4_coarsegrained_val.txt',
    pipeline=[
        dict(type='LoadImageFromFile'),
        dict(type='Resize', size=(256, -1)),
        dict(type='CenterCrop', crop_size=224),
        dict(
            type='Normalize',
            mean=[123.675, 116.28, 103.53],
            std=[58.395, 57.12, 57.375],
            to_rgb=True),
        dict(type='ImageToTensor', keys=['img']),
        dict(type='Collect', keys=['img'])
    ])
    ]**

**Comment by Ezra-Yu** [comment]
This is a bug of `DatasetWrapper`. Here's a temporary modification to run. We will fix this in an elegant way later.

in [`tools/test.py#L126`](https://github.com/open-mmlab/mmclassification/blob/master/tools/test.py)
```
    if isinstance(cfg.data.test, (list, tuple)):
        for test_dataset_cfg in cfg.data.test:
            test_dataset_cfg.test_mode = True
    else:
        cfg.data.test.test_mode = True
```

in [`mmcls.datasets.dataset_wrappers.py#L13`](https://github.com/open-mmlab/mmclassification/blob/master/mmcls/datasets/dataset_wrappers.py#L13)
```
@DATASETS.register_module()
class ConcatDataset(_ConcatDataset):
    """A wrapper of concatenated dataset.

    Same as :obj:`torch.utils.data.dataset.ConcatDataset`, but
    add `get_cat_ids` function.

    Args:
        datasets (list[:obj:`Dataset`]): A list of datasets.
    """

    def __init__(self, datasets):
        _ConcatDataset.__init__(self, datasets)
        self.CLASSES = datasets[0].CLASSES

    def get_gt_labels(self):
        return np.concatenate([dataset.get_gt_labels() for dataset in self.datasets], axis=0)

    def get_cat_ids(self, idx):
        if idx < 0:
            if -idx > len(self):
                raise ValueError(
                    'absolute value of index should not exceed dataset length')
            idx = len(self) + idx
        dataset_idx = bisect.bisect_right(self.cumulative_sizes, idx)
        if dataset_idx == 0:
            sample_idx = idx
        else:
            sample_idx = idx - self.cumulative_sizes[dataset_idx - 1]
        return self.datasets[dataset_idx].get_cat_ids(sample_idx)


    def evaluate(self,
            results,
            metric='accuracy',
            metric_options=None,
            logger=None):
        """Evaluate the dataset.

        Args:
            results (list): Testing results of the dataset.
            metric (str | list[str]): Metrics to be evaluated.
                Default value is `accuracy`.
            metric_options (dict, optional): Options for calculating metrics.
                Allowed keys are 'topk', 'thrs' and 'average_mode'.
                Defaults to None.
            logger (logging.Logger | str, optional): Logger used for printing
                related information during evaluation. Defaults to None.
        Returns:
            dict: evaluation results
        """
        if metric_options is None:
            metric_options = {'topk': (1, 5)}
        if isinstance(metric, str):
            metrics = [metric]
        else:
            metrics = metric
        allowed_metrics = [
            'accuracy', 'precision', 'recall', 'f1_score', 'support'
        ]
        eval_results = {}
        results = np.vstack(results)
        gt_labels = self.get_gt_labels()
        num_imgs = len(results)
        assert len(gt_labels) == num_imgs, 'dataset testing results should '\
            'be of the same length as gt_labels.'

        invalid_metrics = set(metrics) - set(allowed_metrics)
        if len(invalid_metrics) != 0:
            raise ValueError(f'metric {invalid_metrics} is not supported.')

        topk = metric_options.get('topk', (1, 5))
        thrs = metric_options.get('thrs')
        average_mode = metric_options.get('average_mode', 'macro')

        if 'accuracy' in metrics:
            if thrs is not None:
                acc = accuracy(results, gt_labels, topk=topk, thrs=thrs)
            else:
                acc = accuracy(results, gt_labels, topk=topk)
            if isinstance(topk, tuple):
                eval_results_ = {
                    f'accuracy_top-{k}': a
                    for k, a in zip(topk, acc)
                }
            else:
                eval_results_ = {'accuracy': acc}
            if isinstance(thrs, tuple):
                for key, values in eval_results_.items():
                    eval_results.update({
                        f'{key}_thr_{thr:.2f}': value.item()
                        for thr, value in zip(thrs, values)
                    })
            else:
                eval_results.update(
                    {k: v.item()
                     for k, v in eval_results_.items()})

        if 'support' in metrics:
            support_value = support(
                results, gt_labels, average_mode=average_mode)
            eval_results['support'] = support_value

        precision_recall_f1_keys = ['precision', 'recall', 'f1_score']
        if len(set(metrics) & set(precision_recall_f1_keys)) != 0:
            if thrs is not None:
                precision_recall_f1_values = precision_recall_f1(
                    results, gt_labels, average_mode=average_mode, thrs=thrs)
            else:
                precision_recall_f1_values = precision_recall_f1(
                    results, gt_labels, average_mode=average_mode)
            for key, values in zip(precision_recall_f1_keys,
                                   precision_recall_f1_values):
                if key in metrics:
                    if isinstance(thrs, tuple):
                        eval_results.update({
                            f'{key}_thr_{thr:.2f}': value
                            for thr, value in zip(thrs, values)
                        })
                    else:
                        eval_results[key] = values

        return eval_results

    def __getitem__(self, idx):
        if idx < 0:
            if -idx > len(self):
                raise ValueError(
                    'absolute value of index should not exceed dataset length')
            idx = len(self) + idx
        dataset_idx = bisect.bisect_right(self.cumulative_sizes, idx)
        if dataset_idx == 0:
            sample_idx = idx
        else:
            sample_idx = idx - self.cumulative_sizes[dataset_idx - 1]
        return self.datasets[dataset_idx][sample_idx]
```

**Comment by mzr1996** [comment]
Hello, we have implemented the evaluation on a concat dataset, refers to https://github.com/open-mmlab/mmclassification/pull/650

**Comment by EdyQiu** [comment]
That is great! Thank so much!
