### ISSUE TITLE
How can I get the pretainted model of  SE-ResNeXt-101?

### ISSUE THREAD

**Issue by baibaidedongdong** [open-mmlab/mmclassification#65]
I find  the model zoo,but it didn't have the pretained model of  SE-ResNeXt-101?Can you tell me how can I get it?Thank you very much!

**Comment by baibaidedongdong** [comment]
Can someone give me a help?

**Comment by hellock** [comment]
There is currently no such pretrained model.

**Comment by baibaidedongdong** [comment]
ok，thank you!



---Original---
