### ISSUE TITLE
Running into error with `test.py`

### ISSUE THREAD

**Issue by zunction** [open-mmlab/mmclassification#652]
### Checklist
- I have searched related issues but cannot get the expected help. yes
- I have read related documents and don't know what to do. yes

### Describe the question you meet

When running the following test command

```
! python tools/test.py \
         ./work_dirs/perception-absposition-resnet34-mask-120-40-40--D16-01-2022--T08-34-32/perception-absposition-resnet34-mask-120-40-40.py \
         ./work_dirs/perception-absposition-resnet34-mask-120-40-40--D16-01-2022--T08-34-32/latest.pth \
         --out result.pkl \
         --out-items class_scores
```
it returns the following error message

```
load checkpoint from local path: ./work_dirs/perception-absposition-resnet34-mask-120-40-40--D16-01-2022--T08-34-32/latest.pth
[>>>>>>>>>>>>>>>>>>>>>>>>] 11247/11247, 675.9 task/s, elapsed: 17s, ETA:     0sTraceback (most recent call last):
  File "tools/test-cls.py", line 219, in <module>
    main()
  File "tools/test-cls.py", line 202, in main
    pred_class = [CLASSES[lb] for lb in pred_label]
  File "tools/test-cls.py", line 202, in <listcomp>
    pred_class = [CLASSES[lb] for lb in pred_label]
TypeError: 'NoneType' object is not subscriptable
```

### Post related information
1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
mmcls                         0.19.0
mmcv-full                     1.4.2
torch                         1.7.0
torchvision                   0.8.1

2. Your config file if you modified it or created a new one.
```python
NA
```
3. Your train log file if you meet the problem during training.
NA
4. Other code you modified in the `mmcls` folder.
NA

**Comment by Ezra-Yu** [comment]
your `dataset.CLASSES` has not been saved in your checkpoint.

Maybe the same problem in https://github.com/open-mmlab/mmclassification/pull/641
