### ISSUE TITLE
Does mmcv support reading .rec file for image classification ?

### ISSUE THREAD

**Issue by robbine** [open-mmlab/mmclassification#653]
I'm trying to load a .rec file from my previous project which use mxnet for training & testing.
It can be seen as a assemble file which contains all images in one file.
mmclassifcation has a LoadImageFromFile method to read multiple images by a data loader  .
Is there a way to support loading a rec file in mmcv ?
Thanks a lot !

**Comment by Ezra-Yu** [comment]
Now, `mmcv` support `PetrelBackend`, `MemcachedBackend`, `LmdbBackend`, `HardDiskBackend`, `HTTPBackend`
refer to [mmcv code](https://github.com/open-mmlab/mmcv/blob/86ed509a8bc783cdd0617efeba257375d5aa6658/mmcv/fileio/file_client.py?_pjax=%23repo-content-pjax-container#L767). 
I am sorry that I'm not familiar with “.rec ” file.

**Comment by mzr1996** [comment]
We haven't supported loading .rec files.
However, you can implement it simply by adding a pipeline, which refers to https://mmclassification.readthedocs.io/en/latest/tutorials/data_pipeline.html
