### ISSUE TITLE
[Bug]vis_cam.py类别激活图可视化时报一个错 TypeError: __call__() got an unexpected keyword argument 'target_category'

### ISSUE THREAD

**Issue by xiefeifeihu** [open-mmlab/mmclassification#654]
推荐使用英语模板 Bug report，以便你的问题帮助更多人。

### 描述 bug
简单地描述一下遇到了什么 bug

vis_cam.py类别激活图可视化时报一个错
TypeError: __call__() got an unexpected keyword argument 'target_category'

### 复现流程
在命令行中执行的详细操作

```shell
python tools/visualizations/vis_cam.py data/test.jpg project/resnet50_b32x8_cls_test.py work_dirs/test/latest.pth 
指定目标分类也错：
python tools/visualizations/vis_cam.py data/test.jpg project/resnet50_b32x8_cls_test.py work_dirs/test/latest.pth --device cuda --target-category 0 
```

### 相关信息
1. `pip list | grep "mmcv\|mmcls\|^torch"` 命令的输出

mmcls                         0.19.0              /home/damon/open-mmlab/mmclassification-v0.19.0
mmcv-full                     1.3.16
torch                         1.10.1
torchvision                   0.11.2

2. 如果你修改了，或者使用了新的配置文件，请在这里写明
```python

model = dict(
    head=dict(
        num_classes=8,
        in_channels=2048,
        topk=(1,5),
    ))
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=224),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    # dict(type='Resize', size=(256, -1)),
    dict(type='Resize', size=224),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]

```
3. 如果你是在训练过程中遇到的问题，请填写完整的训练日志和报错信息
[填写这里]
4. 如果你对 `mmcls` 文件夹下的代码做了其他相关的修改，请在这里写明
[填写这里]

### 附加内容
任何其他有关该 bug 的信息、截图等

[填写这里]

**Comment by mzr1996** [comment]
It's an upstream issue that Pytorch-grad-cam modified their API.
Please install pytorch-grad-cam 1.3.6 by `pip install grad-cam==1.3.6` and try again.

**Comment by mzr1996** [comment]
Closed by #656
