### ISSUE TITLE
How to test inference time

### ISSUE THREAD

**Issue by dreamer121121** [open-mmlab/mmclassification#657]
推荐使用英语模板 General question，以便你的问题帮助更多人。

### 首先确认以下内容
- 我已经查询了相关的 issue，但没有找到需要的帮助。
- 我已经阅读了相关文档，但仍不知道如何解决。

### 描述你遇到的问题

如何测量推理速度

### 相关信息
1. `pip list | grep "mmcv\|mmcls\|^torch"` 命令的输出
[填写这里]
2. 如果你修改了，或者使用了新的配置文件，请在这里写明
```python
[填写这里]
```
3. 如果你是在训练过程中遇到的问题，请填写完整的训练日志和报错信息
[填写这里]
4. 如果你对 `mmcls` 文件夹下的代码做了其他相关的修改，请在这里写明
[填写这里]

**Comment by mzr1996** [comment]
Please use `tools/test.py` and it will provide a progress bar with how many tasks are finished per second.

**Comment by dreamer121121** [comment]
> Please use `tools/test.py` and it will provide a progress bar with how many tasks are finished per second.

I found that the multi-gpu-test will use batch_size=32, so the task/s how to be transfered to fps?

**Comment by Ezra-Yu** [comment]
you can set `samples_per_gpu=1`. Add `--cfg-options data.samples_per_gpu=1` in the end of command.

eg. 
```
python ./tools/test.py configs/resnet/resnet18_8xb32_in1k.py https://download.openmmlab.com/mmclassification/v0/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pthhttps://download.openmmlab.com/mmclassification/v0/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pth --metrics accuracy --cfg-options data.samples_per_gpu=1
```

then `fps = img_pre_second / num_GPUs`. but, it is better to use only one GPU when testing inference time.

**Comment by dreamer121121** [comment]
> you can set `samples_per_gpu=1`. Add `--cfg-options data.samples_per_gpu=1` in the end of command.
> 
> eg.
> 
> ```
> python ./tools/test.py configs/resnet/resnet18_8xb32_in1k.py https://download.openmmlab.com/mmclassification/v0/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pthhttps://download.openmmlab.com/mmclassification/v0/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pth --metrics accuracy --cfg-options data.samples_per_gpu=1
> ```
> 
> then `fps = img_pre_second / num_GPUs`. but, it is better to use only one GPU when testing inference time.

what's mean img_pre_second? Its mean task/s ?

**Comment by Ezra-Yu** [comment]
Frames Per Second or Images Per Second.

**Comment by dreamer121121** [comment]
> Frames Per Second or Images Per Second. the same as task/s if your task is picture.
[https://user-images.githubusercontent.com/35915584/151101769-5e24c950-2558-49bb-a7c8-1446d559214f.png)

**Comment by Ezra-Yu** [comment]
a task = `read data` + `pre-process` + `forward` + `post-process` + `ProgressBar display & print`

the `ProgressBar display & print` will also affect the speed.
