### ISSUE TITLE
[Bug] Exception when calcute train time

### ISSUE THREAD

**Issue by xiefeifeihu** [open-mmlab/mmclassification#661]
推荐使用英语模板 Bug report，以便你的问题帮助更多人。

### 描述 bug

统计训练时间时，抛出异常“AttributeError: 'Namespace' object has no attribute 'window_size'”

### 复现流程
在命令行中执行的详细操作

```shell
python tools/analysis_tools/analyze_logs.py cal_train_time work_dirs/some_exp/20200422_153324.log.json
```

### 相关信息
1. `pip list | grep "mmcv\|mmcls\|^torch"` 命令的输出
mmcls                         0.19.0              /home/damon/open-mmlab/mmclassification-v0.19.0
mmcv-full                     1.4.3
torch                         1.10.1
torchvision                   0.11.2

2. 如果你修改了，或者使用了新的配置文件，请在这里写明
```python
[填写这里]
```
3. 如果你是在训练过程中遇到的问题，请填写完整的训练日志和报错信息
[填写这里]
4. 如果你对 `mmcls` 文件夹下的代码做了其他相关的修改，请在这里写明
[填写这里]

### 附加内容
任何其他有关该 bug 的信息、截图等

[填写这里]

**Comment by Ezra-Yu** [comment]
Thank you for your report and contribution,  we have noticed your PR. Please sign the CLA so that we can merge that.

**Comment by Ezra-Yu** [comment]
Fix in #662
