### ISSUE TITLE
[Feature] Support features_only in TIMMBackbone

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmclassification#665]
### Describe the feature

Support 'features_only' option in TIMMBackbone.

### Motivation
See the discussion in https://github.com/open-mmlab/mmdetection/pull/7020. In MMDet, MMSeg, and other downstream repos, we wish to directly use backbones supported by TIMM in MMCls. Therefore, it is necessary to support this option for downstream tasks.

### Related resources
https://github.com/open-mmlab/mmdetection/pull/7020

**Comment by shinya7y** [comment]
I will create a PR.

**Comment by mzr1996** [comment]
Closed by #668
