### ISSUE TITLE
Does this code base support ray distributed training  

### ISSUE THREAD

**Issue by sivaguru-pat** [open-mmlab/mmclassification#669]
thank you for your amazing work! 
just curious about training in the multiple devices with this codebase
does this support ray
https://github.com/ray-project/ray

**Comment by mzr1996** [comment]
Sorry, we don't support ray by now.
To train models in multiple devices, we support using slurm, which refer to the https://github.com/open-mmlab/mmclassification/blob/master/tools/slurm_train.sh

**Comment by sivaguru-pat** [comment]
is it possible to integrate ray distributed training in this codebase

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
