### ISSUE TITLE
Finetune from MobilenetV2 Wrong

### ISSUE THREAD

**Issue by hwenjun18** [open-mmlab/mmclassification#67]
RuntimeError: size mismatch, m1: [160 x 1280], m2: [320 x 256] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290

**Comment by hwenjun18** [comment]
pretrained model download from Model Zoo (MobileNet V2) and config file 


____________
model = dict(
    type='ImageMultiTaskClassifier',
    backbone=dict(type='MobileNetV2'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='MultiTaskHead',
        num_classes=7,
        in_channels=320,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 2),
    ))

**Comment by xiaojieli0903** [comment]
Hi @hwenjun18, it seems that the way you loaded your pretrained model is not correct. Please refer to https://github.com/open-mmlab/mmclassification/issues/17.

**Comment by hwenjun18** [comment]
@xiaojieli0903 thanks for your response,  in my config file, i don't use pretrained , but set use load_from  to the pretrained model path, it seems that https://github.com/open-mmlab/mmclassification/blob/master/docs/tutorials/finetune.md#modify-head says the same, or should I just set pretrained=MODEL_PATH as https://github.com/open-mmlab/mmclassification/issues/17#issuecomment-674665893 here you response in #17 ? thank you

**Comment by xiaojieli0903** [comment]
I recommend the latter method because the first method will load the parameters of both the backbone and the linear from the pretrained model. While the shape of the linear's weight is different from your current one. The second method will only load the weight of the backbone. We will update the finetune tutorial later. Thanks for your feedback.

**Comment by xiaojieli0903** [comment]
@hwenjun18 Hi, have you loaded the pretrained model successfully?

**Comment by hwenjun18** [comment]
> @hwenjun18 Hi, have you loaded the pretrained model successfully?

yes, sorry about late reply, thanks for your help

**Comment by songsonggithub** [comment]
> I recommend the latter method because the first method will load the parameters of both the backbone and the linear from the pretrained model. While the shape of the linear's weight is different from your current one. The second method will only load the weight of the backbone. We will update the finetune tutorial later. Thanks for your feedback.

please, now have the way to update backbone only?
