### ISSUE TITLE
How to set the  load_from params to load a trained model by myself for finetune train

### ISSUE THREAD

**Issue by dreamer121121** [open-mmlab/mmclassification#673]
推荐使用英语模板 General question，以便你的问题帮助更多人。

### 首先确认以下内容
- 我已经查询了相关的 issue，但没有找到需要的帮助。
- 我已经阅读了相关文档，但仍不知道如何解决。

### 描述你遇到的问题

[填写这里]

### 相关信息
1. `pip list | grep "mmcv\|mmcls\|^torch"` 命令的输出
[填写这里]
2. 如果你修改了，或者使用了新的配置文件，请在这里写明
```python
[填写这里]
```
3. 如果你是在训练过程中遇到的问题，请填写完整的训练日志和报错信息
[填写这里]
4. 如果你对 `mmcls` 文件夹下的代码做了其他相关的修改，请在这里写明
[填写这里]

**Comment by Ezra-Yu** [comment]
modify the `init_cfg` in `model.backbone` refer to [collab notebook tutorial](https://colab.research.google.com/github/open-mmlab/mmclassification/blob/master/docs/en/tutorials/MMClassification_tools.ipynb).

for example:
```
model = dict(
    backbone=dict(
        type='ResNet',
        init_cfg = dict(
            type='Pretrained', 
            checkpoint='you-checkpoint, 
            prefix='backbone')
    ),
    head=dict(
        num_classes=xxx,
        topk = (1, )
    ))
```
usually only load the `backbone` pre-trained weight

**Comment by dreamer121121** [comment]
> usually only load the `backbone` pre-trained weight

if i want to load pretrained model not only backbone but also head, can i use the load_from params? and how should i set it ?

**Comment by Ezra-Yu** [comment]
Yes!
```
load_from = "path_to_your_checkpoint"
```

**Comment by dreamer121121** [comment]
> 

which config file should i set the load_from param?

**Comment by Ezra-Yu** [comment]
the fine-tune config file.
