### ISSUE TITLE
Conformer model does not support different input image sizes

### ISSUE THREAD

**Issue by Balakumaran789** [open-mmlab/mmclassification#680]
The conformer model backbone gives error when tries to give input image size like (241x241) or (242x242) ,but works fine with some image sizes and also changes in  hyperparameters patch_size gives the error in tensor size matching . It is better if it has hyperparameter like img_size like other models

**Comment by mzr1996** [comment]
Sounds like a bug, we will fix it later

**Comment by Balakumaran789** [comment]
> Sounds like a bug, we will fix it later

Thanks

**Comment by Balakumaran789** [comment]
> Sounds like a bug, we will fix it later

Thanks
