### ISSUE TITLE
For init_cfg of different models , where can i get the list of layers of any model ?

### ISSUE THREAD

**Issue by Balakumaran-kandula** [open-mmlab/mmclassification#682]
Every model contains a list of layers like ("Conv2d" , "linear" , etc) , if i want to initialize weights for different layers of a particular model, is there anywhere i can search and get the list of layers for that model instead of going deep in the builded model ?

**Comment by Ezra-Yu** [comment]
you can refer to [mmcv doc](https://mmcv.readthedocs.io/en/latest/understand_mmcv/cnn.html#weight-initialization) and some examples in `configs/_base_/models/` such as [these lines](https://github.com/open-mmlab/mmclassification/blob/e0edffb353e5ac3176140429a32688c64e55ac88/configs/_base_/models/swin_transformer/base_224.py#L15)
