### ISSUE TITLE
Could you release pretrain weights of ConvNeXt and Efficientnet

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#684]
Hi, dear authors!
Thank you for your amazing job!
Could you release pretrain weights of ConvNeXt and Efficientnet?
Thank you in advance!

**Comment by Ezra-Yu** [comment]
we have provided ConvNeXt and Efficientnet pre-trained weights, you can reach them here : [fficientnet](https://github.com/open-mmlab/mmclassification/tree/master/configs/efficientnet) and [convnext](https://github.com/open-mmlab/mmclassification/tree/master/configs/convnext)
