### ISSUE TITLE
How to set the size of CAM output picture

### ISSUE THREAD

**Issue by 6sz** [open-mmlab/mmclassification#690]
Please help me.
When I used the visualization function, I found that the size of the test result picture I saved was 224*224, and the result picture was cut out from the original picture instead of changing the size(resize). May I ask how to set the size or keep the original size?
The following command is used:
```python
python tools/visualizations/vis_cam.py data/CAM_data/test.png \
./configs/resne`t/resnet18_8xb32_in1k.py \
./work_dirs/data_0613_3/resnet18_8xb32_in1k/epoch_250.pth \
--method GradCAM \
--save-path ./work_dirs/cam_result/
```

**Comment by Ezra-Yu** [comment]
you can modify the [`test.pipeline`](https://github.com/open-mmlab/mmclassification/blob/a7f8e96b31c10ab3e9c133293ca406e6e548475b/configs/_base_/datasets/imagenet_bs32.py#L14) in config.

Remove the `CenterCrop` in `test.pipeline` and set the Resize size.

for example:
```
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(400, 500)),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
```


notice that some models only support specific image size such `mlp-mixer`.

**Comment by 6sz** [comment]
Wow, great, I made it. Thank you very much for your help
