### ISSUE TITLE
Return code should not be zero if scripts run failed.

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmclassification#693]
https://github.com/open-mmlab/mmclassification/blob/f9eb9b409b65361167446c7c28e240f64aa7cf18/tools/deployment/test.py#L83

https://github.com/open-mmlab/mmclassification/blob/fc8adbc1490efa158cce66f4d0ed3a981a8a8d3b/tools/convert_models/mlpmixer_to_mmcls.py#L52

**Comment by Ezra-Yu** [comment]
Is any number except zero OK?

**Comment by del-zhenwu** [comment]
> Is any number except zero OK?

This would be fine.

**Comment by Ezra-Yu** [comment]
@del-zhenwu Can you review the PR#694  and leave comments
