### ISSUE TITLE
In tutorial - ClassBalancedDataset  

### ISSUE THREAD

**Issue by Randomless** [open-mmlab/mmclassification#70]
How can i instantiate function self.get_cat_ids(idx) ?
can i just copy get_cat_ids(idx) from ConcatDataset for my custom dataset? 
https://github.com/open-mmlab/mmclassification/blob/784987fe9f20c475e2b0ed3c8edc909a65dec4b2/mmcls/datasets/dataset_wrappers.py#L26

**Comment by yl-1993** [comment]
@Randomless Good catch. We create a PR https://github.com/open-mmlab/mmclassification/pull/72 to fix this. After it is merged, you don't have to worry about `get_cat_ids` if you inherit from `BaseDataset`.
