### ISSUE TITLE
请问配置的详细文档在哪里可以找到

### ISSUE THREAD

**Issue by liuzhihengg** [open-mmlab/mmclassification#700]
### 首先确认以下内容
- 我已经查询了相关的 issue，但没有找到需要的帮助。
- 我已经阅读了相关文档，但仍不知道如何解决。

**Comment by Ezra-Yu** [comment]
你可以查看[这个文档](https://mmclassification.readthedocs.io/zh_CN/latest/tutorials/schedule.html),文档中已经给了一些简单的例子，相关collab的教程也在我们的计划中，
