### ISSUE TITLE
Frozen_stages feature

### ISSUE THREAD

**Issue by Rtut654** [open-mmlab/mmclassification#701]
Hi everyone! Thanks for such a useful framework. I have a question regarding frozen_stages feature which many backbones have. I can't  completely get what these stages consists of. For example, if I train resnet-50 and after want to tune it on another dataset to train only last FC layer, I would freeze all the layers except the last one. Does frozen_stages=3 (out of 4) mean that? I recently trained a swin-transformer which also has 4 stages to freeze and I saw almost no difference on validation after training with frozen_stages=3 and frozen_stages=1 which is confusing. I wonder if there is any chance to freeze exact layers in the model - by one, not by stages. Could you please shed some light on that?

**Comment by Ezra-Yu** [comment]
> Does frozen_stages=3 (out of 4) mean that? 
Yes， but frozen_stages would be 4 in some modesl, we are tring to unify this setting.

>  wonder if there is any chance to freeze exact layers in the model - by one, not by stages
No。 Sorry that we do not support this currently. you need to implement that by yourself.

**Comment by Rtut654** [comment]
I got it thanks!
