### ISSUE TITLE
Swin-Transformer,VGG等模型在微调时设置frozen_stages不为-1时，使用多个gpu训练会产生错误，报告显示forward输出部分没有参与到loss计算

### ISSUE THREAD

**Issue by liuzhihengg** [open-mmlab/mmclassification#702]
### 复现流程
bash tools/dist_train.sh configs/tutorial/vgg19-finetune-cifar.py 4       *****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
/export/lzh/open_mmlab/mmclassification/mmcls/utils/setup_env.py:42: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/export/lzh/open_mmlab/mmclassification/mmcls/utils/setup_env.py:42: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/export/lzh/open_mmlab/mmclassification/mmcls/utils/setup_env.py:42: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/export/lzh/open_mmlab/mmclassification/mmcls/utils/setup_env.py:42: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
2022-02-20 22:53:11,998 - mmcls - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3: TITAN RTX
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 9.0, V9.0.176
GCC: gcc (GCC) 6.1.0
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.1, CUDNN_VERSION=7.6.3, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.9.0
OpenCV: 4.5.5
MMCV: 1.4.4
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMClassification: 0.20.1+a7f8e96
------------------------------------------------------------

2022-02-20 22:53:11,999 - mmcls - INFO - Distributed training: True
2022-02-20 22:53:12,129 - mmcls - INFO - Config:
dataset_type = 'CIFAR10'
img_norm_cfg = dict(
    mean=[125.307, 122.961, 113.8575],
    std=[51.5865, 50.847, 51.255],
    to_rgb=False)
train_pipeline = [
    dict(type='RandomCrop', size=32, padding=4),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Resize', size=224),
    dict(
        type='Normalize',
        mean=[125.307, 122.961, 113.8575],
        std=[51.5865, 50.847, 51.255],
        to_rgb=False),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='Resize', size=224),
    dict(
        type='Normalize',
        mean=[125.307, 122.961, 113.8575],
        std=[51.5865, 50.847, 51.255],
        to_rgb=False),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
data = dict(
    samples_per_gpu=64,
    workers_per_gpu=2,
    train=dict(
        type='CIFAR10',
        data_prefix='data/cifar10',
        pipeline=[
            dict(type='RandomCrop', size=32, padding=4),
            dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
            dict(type='Resize', size=224),
            dict(
                type='Normalize',
                mean=[125.307, 122.961, 113.8575],
                std=[51.5865, 50.847, 51.255],
                to_rgb=False),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='ToTensor', keys=['gt_label']),
            dict(type='Collect', keys=['img', 'gt_label'])
        ]),
    val=dict(
        type='CIFAR10',
        data_prefix='data/cifar10',
        pipeline=[
            dict(type='Resize', size=224),
            dict(
                type='Normalize',
                mean=[125.307, 122.961, 113.8575],
                std=[51.5865, 50.847, 51.255],
                to_rgb=False),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ],
        test_mode=True),
    test=dict(
        type='CIFAR10',
        data_prefix='data/cifar10',
        pipeline=[
            dict(type='Resize', size=224),
            dict(
                type='Normalize',
                mean=[125.307, 122.961, 113.8575],
                std=[51.5865, 50.847, 51.255],
                to_rgb=False),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ],
        test_mode=True))
checkpoint_config = dict(interval=1)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='VGG',
        depth=19,
        num_classes=10,
        frozen_stages=2,
        out_indices=(-1, ),
        init_cfg=dict(
            type='Pretrained',
            checkpoint=
            'checkpoints/vgg19_batch256_imagenet_20210208-e6920e4a.pth',
            prefix='backbone')),
    neck=None,
    head=dict(
        type='ClsHead',
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5)))
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='step', step=[15])
runner = dict(type='EpochBasedRunner', max_epochs=20)
work_dir = './work_dirs/vgg19-finetune-cifar'
gpu_ids = range(0, 4)

2022-02-20 22:53:15,406 - mmcls - INFO - Set random seed to 1195651349, deterministic: False
2022-02-20 22:53:16,825 - mmcls - INFO - initialize VGG with init_cfg {'type': 'Pretrained', 'checkpoint': 'checkpoints/vgg19_batch256_imagenet_20210208-e6920e4a.pth', 'prefix': 'backbone'}
2022-02-20 22:53:16,825 - mmcv - INFO - load backbone in model from: checkpoints/vgg19_batch256_imagenet_20210208-e6920e4a.pth
load checkpoint from local path: checkpoints/vgg19_batch256_imagenet_20210208-e6920e4a.pth
load checkpoint from local path: checkpoints/vgg19_batch256_imagenet_20210208-e6920e4a.pth
load checkpoint from local path: checkpoints/vgg19_batch256_imagenet_20210208-e6920e4a.pth
load checkpoint from local path: checkpoints/vgg19_batch256_imagenet_20210208-e6920e4a.pth
2022-02-20 22:53:17,337 - mmcv - WARNING - The model and loaded state dict do not match exactly

size mismatch for classifier.6.weight: copying a param with shape torch.Size([1000, 4096]) from checkpoint, the shape in current model is torch.Size([10, 4096]).
size mismatch for classifier.6.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape in current model is torch.Size([10]).
2022-02-20 22:53:19,785 - mmcls - INFO - Start running, host: lzh@dellt630b, work_dir: /export/lzh/open_mmlab/mmclassification/work_dirs/vgg19-finetune-cifar
2022-02-20 22:53:19,785 - mmcls - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook
(NORMAL      ) CheckpointHook
(LOW         ) DistEvalHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_train_epoch:
(VERY_HIGH   ) StepLrUpdaterHook
(NORMAL      ) DistSamplerSeedHook
(LOW         ) IterTimerHook
(LOW         ) DistEvalHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_train_iter:
(VERY_HIGH   ) StepLrUpdaterHook
(LOW         ) IterTimerHook
(LOW         ) DistEvalHook
 --------------------
after_train_iter:
(ABOVE_NORMAL) DistOptimizerHook
(NORMAL      ) CheckpointHook
(LOW         ) IterTimerHook
(LOW         ) DistEvalHook
(VERY_LOW    ) TextLoggerHook
 --------------------
after_train_epoch:
(NORMAL      ) CheckpointHook
(LOW         ) DistEvalHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_val_epoch:
(NORMAL      ) DistSamplerSeedHook
(LOW         ) IterTimerHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_val_iter:
(LOW         ) IterTimerHook
 --------------------
after_val_iter:
(LOW         ) IterTimerHook
 --------------------
after_val_epoch:
(VERY_LOW    ) TextLoggerHook
 --------------------
after_run:
(VERY_LOW    ) TextLoggerHook
 --------------------
2022-02-20 22:53:19,786 - mmcls - INFO - workflow: [('train', 1)], max: 20 epochs
2022-02-20 22:53:19,786 - mmcls - INFO - Checkpoints will be saved to /export/lzh/open_mmlab/mmclassification/work_dirs/vgg19-finetune-cifar by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 194, in <module>
    main()
  File "tools/train.py", line 182, in main
    train_model(
  File "/export/lzh/open_mmlab/mmclassification/mmcls/apis/train.py", line 208, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 42, in train_step
    and self.reducer._rebuild_buckets()):
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Traceback (most recent call last):
  File "tools/train.py", line 194, in <module>
    main()
  File "tools/train.py", line 182, in main
    train_model(
  File "/export/lzh/open_mmlab/mmclassification/mmcls/apis/train.py", line 208, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 42, in train_step
    and self.reducer._rebuild_buckets()):
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Traceback (most recent call last):
  File "tools/train.py", line 194, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 194, in <module>
    main()
  File "tools/train.py", line 182, in main
    main()
  File "tools/train.py", line 182, in main
    train_model(
  File "/export/lzh/open_mmlab/mmclassification/mmcls/apis/train.py", line 208, in train_model
    train_model(
  File "/export/lzh/open_mmlab/mmclassification/mmcls/apis/train.py", line 208, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    runner.run(data_loaders, cfg.workflow)
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    epoch_runner(data_loaders[i], **kwargs)
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 42, in train_step
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    and self.reducer._rebuild_buckets()):
    outputs = self.model.train_step(data_batch, self.optimizer,RuntimeError
: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 42, in train_step

    and self.reducer._rebuild_buckets()):
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Killing subprocess 21215
Killing subprocess 21216
Killing subprocess 21217
Killing subprocess 21218
Traceback (most recent call last):
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/export/lzh/anaconda3/envs/open-mmlab-four/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/export/lzh/anaconda3/envs/open-mmlab-four/bin/python', '-u', 'tools/train.py', '--local_rank=3', 'configs/tutorial/vgg19-finetune-cifar.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by Ezra-Yu** [comment]
thank you for your report, 
the PR https://github.com/open-mmlab/mmclassification/pull/634 is  about it, you can try it

we are still discussing what `frozen_stages` means

**Comment by mzr1996** [comment]
Sorry for the late reply.
I have reproduced the problem, and find that it's caused by the missing call of `_freeze_stages` in the initialization method.
Just add a line at the end of the `__init__` method in `SwinTransformer` class:
```python
self._freeze_stages()
```
We will fix it soon
