### ISSUE TITLE
Multi-GPU training with mmcls

### ISSUE THREAD

**Issue by robbine** [open-mmlab/mmclassification#719]
I've tried to train an image classification model with the tools/dist_train.sh script.
Although there are 4 gpus installed on my machine, only one of them is used during training.
I tried to specify devices with options like " --gpu-ids 0 1 2 3". It doesn't work.
It seems that the world_size value returned by the get_dist_info function determines number of gpus visible by the program.
Is there some example settings which I can refer to ?
Thanks !

**Comment by Ezra-Yu** [comment]
Try to use this [tool](https://github.com/open-mmlab/mmclassification/blob/master/tools/dist_train.sh) to train.

have you added `-m torch.distributed.launch --nproc_per_node=$GPUS` in your command.

**Comment by robbine** [comment]
Yes, I pasted my command as below
python -m torch.distributed.launch --nproc_per_node=1
Perhaps proc_per_node needs to be set to 2 in order to run on 2 gpus

**Comment by Ezra-Yu** [comment]
It is recommended to use
```
CUDA_VISIBLE_DEVICES=0,1 ./tools/dis_train.sh $CFG_PATH
```

**Comment by robbine** [comment]
Thanks ! 
This is very helpful !
