### ISSUE TITLE
[Bug] Vision-Transformer-Base model not support dynamic shape due to hard-coded Reshape node input shape

### ISSUE THREAD

**Issue by sammysun0711** [open-mmlab/mmclassification#724]
### Describe the bug
I notice that PR #706 was merged in master, which target to support dynamic input shape for ViT-based algorithms. However, when I trained a dummy model with ImageNet dataset, then export Pytorch model with tools/deployment/pytorch2onnx.py with onnx simplifier, following error occurs: 
```
  File "/home/xsun/anaconda3/envs/mmcls/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'ime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:41 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&, bool) e.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,768,28,28}, requested shape:{1,768,196}
```
When I visualize intermediate generated ONNX model vit-p16-base.onnx before simplify, I found that Node reshape_5 has hard-coded input shape [1,768,196], which can not be reshape for ONNX runtime, so vit-p16-base.onnx is not support dynamic shape input. Could you please have a look?
![Screenshot 2022-03-07 215006](https://user-images.githubusercontent.com/22404054/157047100-c23e01b8-6563-4ec4-b628-3c7409a30bc9.png)

### To Reproduce
You may follow following step to reproduce the error in github master with commit ```2037260```
```shell
conda create -n mmcls python=3.6
conda activate mmcls
conda install pytorch==1.5.1 torchvision==0.6.1 -c pytorch
pip install openmim protobuf onnxruntime onnx-simplifier
git clone https://github.com/open-mmlab/mmclassification.git
cd mmclassification
mim install -e .
python tools/train.py configs/vision_transformer/vit-base-p16_pt-64xb64_in1k-224.py
python tools/deployment/pytorch2onnx.py \
configs/vision_transformer/vit-base-p16_pt-64xb64_in1k-224.py \
--checkpoint work_dirs/vit-base-p16_pt-64xb64_in1k-224/latest.pth \
--output-file vit-base-p16.onnx  --dynamic-export --simplify
```

### Post related information
1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
```
mmcls              0.21.0          /home/xsun/mmclassification
mmcv-full          1.4.6
torch              1.5.1
torchvision        0.6.0a0+35d732a
```
2. config file modified it or created a new one.
I just use dummy 200 imagenet images, and change max_epochs as 1 for training, you may find trainig.log and pytorch2onnx.log as follow: [train.log](https://github.com/open-mmlab/mmclassification/files/8198252/train.log), [python2onnx.log](https://github.com/open-mmlab/mmclassification/files/8198251/python2onnx.log)

**Comment by mzr1996** [comment]
Thanks for your report, and I will check it later

**Comment by sammysun0711** [comment]
@mzr1996 Thanks for you quick response, I found Twins-Svt-Base model has similar issue, I created a separate issue #726 for detailed info, could you please also have a look. Thanks!

**Comment by zhentaoyu** [comment]
I also had this issue. But it succeed when I upgrade the torch to 1.11. Seems a bug of `torch.onnx.export`.

**Comment by sammysun0711** [comment]
> I also had this issue. But it succeed when I upgrade the torch to 1.11. Seems a bug of `torch.onnx.export`.

@zhentaoyu, thanks for your advice, I upgrade torch to 1.11.0,  export ONNX model now does not have hard-coded reshape node:
![Screenshot 2022-03-15 112840](https://user-images.githubusercontent.com/22404054/158300524-68da9f2d-ec0d-4b0f-91eb-7d621f7d3fde.png)

But when I ran following command, another runtime error raised: 
python tools/deployment/pytorch2onnx.py configs/vision_transformer/vit-base-p16_pt-64xb64_in1k-224.py --checkpoint work_dirs/vit-base-p16_pt-64xb64_in1k-224/latest.pth --output-file vit-base-p16.onnx  --dynamic-export --simplify
```
2022-03-15 09:48:21.911159557 [E:onnxruntime:, sequential_executor.cc:346 Execute] Non-zero status code returned while running Add node. Name:'Add_25' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:505 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 197 by 785

Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 226, in <module>
    pytorch2onnx(
  File "tools/deployment/pytorch2onnx.py", line 131, in pytorch2onnx
    model_opt, check_ok = onnxsim.simplify(
  File "/home/xsun/anaconda3/envs/py38/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 492, in simplify
    model = fixed_point(model, infer_shapes_and_optimize, constant_folding)
  File "/home/xsun/anaconda3/envs/py38/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 393, in fixed_point
    x = func_b(x)
  File "/home/xsun/anaconda3/envs/py38/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 482, in constant_folding
    res = forward_for_node_outputs(model,
  File "/home/xsun/anaconda3/envs/py38/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 229, in forward_for_node_outputs
    res = forward(model,
  File "/home/xsun/anaconda3/envs/py38/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 215, in forward
    res = OrderedDict(zip(outputs, sess.run(
  File "/home/xsun/anaconda3/envs/py38/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'Add_25' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:505 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 197 by 785
```
I use following python package `pip list | grep "mmcv\|mmcls\|onnx\|^torch"`:
```
mmcls              0.21.0          /home/xsun/mmclassification
mmcv-full          1.4.6
onnx               1.11.0
onnx-simplifier    0.3.7
onnxoptimizer      0.2.6
onnxruntime        1.10.0
torch              1.11.0
torchvision        0.6.0a0+35d732a
``` 

It seems that new error is related to onnx-simplifier. Can same issue be reproduceable in your environment?

Thanks,
Xiake

**Comment by zhentaoyu** [comment]
@sammysun0711, the input shape when do simplify is like it in the script:
![image](https://user-images.githubusercontent.com/84065714/158303253-7bb9b833-f230-4b3a-8ace-aab61c9f166c.png)
I don't understand why, so I change it to line 125, it can simplify successfully. It may help.
Besides, onnx-simplifier has not much help to simplify onnx model with dynamic input. So, if you add `--simplify`, the result may has no much different.
Hope it helps, Thanks.

**Comment by mzr1996** [comment]
Well, it looks an upstream issue about PyTorch and onnxsim.
