### ISSUE TITLE
Efficientnet Flops

### ISSUE THREAD

**Issue by 3huo** [open-mmlab/mmclassification#725]
请问，mmclassification 统计的efficientnet flops 为什么和官方论文统计的不一样呢

**Comment by 3huo** [comment]
Hi, the Efficientnet Flops computed in mmclassification are quite different from the official paper. Why is it

**Comment by Ezra-Yu** [comment]
Thank you for your report.
We use the [tool](https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/utils/flops_counter.py) in mmcv to get_flops, it can not calculate flops of `Conv2dAdaptivePadding`.
![image](https://user-images.githubusercontent.com/18586273/157214092-038ea68e-4a45-4e55-8d72-6e31c7d2f6f4.png)

We will fix later.

**Comment by 3huo** [comment]
yea, I also found it. I added the Conv2dAdaptivePadding to the 'get_modules_mapping()' function.

**Comment by Ezra-Yu** [comment]
Have you gotten the relatively correct flops of Efficientnet?

**Comment by 3huo** [comment]
> Have you gotten the relatively correct flops of Efficientnet?

yes, I got the relatively correct flops, but I'm not very sure if it's precise enough.

**Comment by Ezra-Yu** [comment]
Yep, Can you create a PR and modify the flops num in [readme.md](https://github.com/open-mmlab/mmclassification/tree/master/configs/efficientnet) in Efficientnet?

**Comment by 3huo** [comment]
> 

Hi, I just modified the efficientnet flops results in README.md as well as the model_zoo.md on my repo.

**Comment by Ezra-Yu** [comment]
you can create a PR refer to this [doc](https://mmclassification.readthedocs.io/en/latest/community/CONTRIBUTING.html). welcome your contribution to MMClassification.

**Comment by 3huo** [comment]
> you can create a PR refer to this [doc](https://mmclassification.readthedocs.io/en/latest/community/CONTRIBUTING.html). welcome your contribution to MMClassification.

I created it just now

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
