### ISSUE TITLE
[Bug] Twins-Svt-Base model not support dynamic shape due to hard-coded Reshape node input shape

### ISSUE THREAD

**Issue by sammysun0711** [open-mmlab/mmclassification#726]
### Describe the bug
Similar as #724, Twins-Svt-Base Pytorch model can not be exported as simplified ONNX model with dynamic shape via pytorch2onnx.py
The root cause is Reshape_11 node with hard-coded input shape [1,96,3136] in ONNX model as follow: 

![Screenshot 2022-03-08 214413](https://user-images.githubusercontent.com/22404054/157250379-195477c4-b651-4a50-9129-dac2a2b77a20.png)

### To Reproduce
You may follow following step to reproduce the error in github master with commit 2037260

```shell
conda create -n mmcls python=3.6
conda activate mmcls
conda install pytorch==1.5.1 torchvision==0.6.1 -c pytorch
pip install openmim protobuf onnxruntime onnx-simplifier
git clone https://github.com/open-mmlab/mmclassification.git
cd mmclassification
mim install -e .
python tools/train.py configs/twins/twins-svt-base_8xb128_in1k.py
python tools/deployment/pytorch2onnx.py configs/twins/twins-svt-base_8xb128_in1k.py \
--checkpoint work_dirs/twins-svt-base_8xb128_in1k/latest.pth \
--output-file twin-svt-base-p16.onnx  --dynamic-export --simplify
```

### Post related information
1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
```
mmcls              0.21.0          /home/xsun/mmclassification
mmcv-full          1.4.6
torch              1.5.1
torchvision        0.6.0a0+35d732a
```
2. config file modified it or created a new one.
I just use dummy 200 imagenet images, and change max_epochs as 1 for training, you may find detailed info as follow:[twins-svt-base-p16-train.log](https://github.com/open-mmlab/mmclassification/files/8206652/twins-svt-base-p16-train.log), [twins-svt-base-p16-pytorch2onnx.log](https://github.com/open-mmlab/mmclassification/files/8206655/twins-svt-base-p16-pytorch2onnx.log)

**Comment by mzr1996** [comment]
Closed according to #724
