### ISSUE TITLE
test problem on single gpu

### ISSUE THREAD

**Issue by chenhongming** [open-mmlab/mmclassification#736]
### Checklist
- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### 
run python tools/test.py configs/tutorial/resnet18_4xb64_finetune_priv.py ./work_dirs/resnet18_4xb64_finetune_priv/epoch_77.pth --metrics accuracy precision recall f1_score **--show-dir ./work_dirs/**

With the --show-dir parameter added, the test speed on a single gpu became extremely slow.
Don't know which parameter will affect this speed. Thank you for your answer.
![issue2](https://user-images.githubusercontent.com/29920966/158950707-f51b49ea-05a0-4a5b-88d3-953eb66b87b8.PNG)

### Post related information
1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
mmcls              0.21.0        
mmcv-full          1.4.5
torch              1.7.0
torchaudio         0.7.0a0+ac17b64
torchvision        0.8.0

**Comment by Ezra-Yu** [comment]
have you tried testing without `--show-dir`, Is the time required normal?

**Comment by chenhongming** [comment]
Without --show-dir, the test speed is normal.

![issue3](https://user-images.githubusercontent.com/29920966/158952352-4fac9a2a-1940-47dc-809c-2d190348a8cf.PNG)

**Comment by Ezra-Yu** [comment]
here we use `matplotlib` to show the result, it inits a figure and saves a picture for every image. So it may slow down the speed.

for instead, you can use `--out` when test and get xxx.pkl result file. and then use `tools/analysis_tools/analyze_results.py` to show the result, here is [the doc](https://mmclassification.readthedocs.io/en/latest/tools/analysis.html#result-analysis), please notice the arg `--topk`.

**Comment by chenhongming** [comment]
I'll give it a try.  Thanks
