### ISSUE TITLE
Dose ResNeST have pretraining checkpoints?

### ISSUE THREAD

**Issue by imaginistLi** [open-mmlab/mmclassification#737]
I want to make a fine-tune training for ResNeST, so dose ResNeST have pretraining checkpoints?

**Comment by Ezra-Yu** [comment]
Sorry that we do not have pre-trained checkpoints, there are some checkpoints in the[ official repo](https://github.com/zhanghang1989/ResNeSt/blob/master/ablation.md). you can convert those to use.

you can refer to the [convert scripts](https://github.com/open-mmlab/mmclassification/tree/master/tools/convert_models) and modify them towards `ResNeSt`, If you have done that job, we are welcome your PR.

**Comment by imaginistLi** [comment]
> 

ok, thanks
