### ISSUE TITLE
fail to load some latest checkpoints with torch<1.6.

### ISSUE THREAD

**Issue by Jokoe66** [open-mmlab/mmclassification#74]
I notice some latest checkpoints in the model_zoo cannot be loaded by torch<1.6.
For example
```python
from torch.utils import model_zoo

ckpt = model_zoo.load_url('https://openmmlab.oss-cn-hangzhou.aliyuncs.com/mmclassification'
                          '/v0/imagenet/resnest50_converted-1ebf0afe.pth')
```
Pytorch will report `RuntimeError: Only one file(not dir) is allowed in the zipfile`.
The probable reason is that the latest checkpoints are saved by torch>=1.6 with different serialization protocol.

**Comment by Jokoe66** [comment]
`torch.load` works well to load the downloaded checkpoint.

**Comment by ycxioooong** [comment]
Hi @Jokoe66. Thanks for reporting this issue. The problem is caused since ``torch.save`` in Pytorch 1.6 switches to use zip format as the default format. The current workaround is to use ``torch.load`` and we'll submit PR to fix this issue.

**Comment by mzr1996** [comment]
Should have been solved. In the new `publish_model.py`, we use Pytorch<1.6 format, refers to https://github.com/open-mmlab/mmclassification/pull/439
