### ISSUE TITLE
demo problem

### ISSUE THREAD

**Issue by Byronnar** [open-mmlab/mmclassification#75]
I have run python demo/image_demo.py demo/demo.JPEG configs/imagenet/vgg19bn.py weights/9c_b7ns_1e_640_ext_15ep_best_fold4.pth.

but get the error blow:
File "demo/image_demo.py", line 29, in <module>
    main()
  File "demo/image_demo.py", line 21, in main
    model = init_model(args.config, args.checkpoint, device=args.device)
  File "/home/byronnar/bigfile/projects/mmclassification/mmcls/apis/inference.py", line 35, in init_model
    checkpoint = load_checkpoint(model, checkpoint, map_location=map_loc)
  File "/home/byronnar/anaconda3/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 259, in load_checkpoint
    state_dict = {k[7:]: v for k, v in checkpoint['state_dict'].items()}
KeyError: 'state_dict'

How should I do?
my env :
torch                              1.7.0
torchvision                        0.8.1
tornado                            6.0.2
tqdm                               4.27.0
traitlets                          4.3.2
transaction                        3.0.0
translationstring                  1.3

torch-1.5.1 torchvision-0.6.1 get the same error

**Comment by mzr1996** [comment]
It looks like your `9c_b7ns_1e_640_ext_15ep_best_fold4.pth` doesn't have `state_dict` key, where does it come from?

**Comment by mzr1996** [comment]
No response for a long time.
This issue will be closed. If you have other questions, please open a new issue.
