### ISSUE TITLE
how can i build a network with multi-head branch?

### ISSUE THREAD

**Issue by flywheel1412** [open-mmlab/mmclassification#751]
## Description
I want to build a classification network with 2 or 3 head, and I don't know how to write the config file.

## Example

training a ResNet18 with two head, head1 predict object is cat or dog; and head2 predict object's color is white, black, orange or other.

the original ResNet18 network define as fellow in config, and how to modifiy it?

```python
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=18,
        num_stages=4,
        out_indices=(3, ),
        style='pytorch'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=1000,
        in_channels=512,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5),
    ))
```

**Comment by Ezra-Yu** [comment]
This feature is currently under development, here is the PR #675

**Comment by flywheel1412** [comment]
ok, tkx for your reply.
