### ISSUE TITLE
[Bug] OOM killed during unit testing

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmclassification#758]
推荐使用英语模板 Bug report，以便你的问题帮助更多人。

### 描述 bug
`tests/test_models/test_backbones/test_swin_transformer.py`
run failed caused by OOM
```
tests/test_models/test_backbones/test_shufflenet_v2.py ..                [ 74%]
tests/test_models/test_backbones/test_swin_transformer.py .Killed
```
![image](https://user-images.githubusercontent.com/56623710/161229373-b1593f2a-4a6d-4d94-bbc6-cd8b29eb06ca.png)
[填写这里]

### 复现流程
在命令行中执行的详细操作

```shell
[填写这里]
```

### 相关信息
1. `pip list | grep "mmcv\|mmcls\|^torch"` 命令的输出
base image:
`ubuntu_1804_py_37_cuda_101_cudnn_7_torch_160_mmcv_v1.4.6`
branch:
dev
3. 如果你修改了，或者使用了新的配置文件，请在这里写明
```python
[填写这里]
```
4. 如果你是在训练过程中遇到的问题，请填写完整的训练日志和报错信息
[填写这里]
5. 如果你对 `mmcls` 文件夹下的代码做了其他相关的修改，请在这里写明
[填写这里]

### 附加内容
任何其他有关该 bug 的信息、截图等

[填写这里]

**Comment by del-zhenwu** [comment]
> Well, looks the batch size in unit test is too large. I have created a pull request and you can test if it can solve your problem.

CI will be triggered after this pr merged.

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
