### ISSUE TITLE
Visualization Technique for weights in the model

### ISSUE THREAD

**Issue by Balakumaran-kandula** [open-mmlab/mmclassification#763]
The visualization like gradcam is available , but to visualize the weights of the layers like ( guided-gradcam) is available in mmclassification ? , if not will it be added ?

**Comment by Balakumaran-kandula** [comment]
> Do you mean visualize the `gradcam` map of a specific layer in a given model? In deed, [`--target-layers`](https://github.com/open-mmlab/mmclassification/blob/5a67bc8a1aefd5493732b8f6ab10ee8c04839773/tools/visualizations/vis_cam.py#L67) can specify a target layer in the visualization model.
> 
> But in my experiments, Its visual effect is not satisfactory.


No , this kind of visualization moreover tells where the activation happens for the given image , but i would like to look at the saliency maps e.g( guided backpropogation ) , there is something called guided gradcam which will give results in combination of Grad-CAM and Guided Backprop.

Because for some classification datasets (e.g: same object with and without defect) the results of activation visualization doesn't make much sense (even if the metrics are good ) , if i can visualize the saliency maps i guess it would make some sense

**Comment by Ezra-Yu** [comment]
Can you attach some `guided-gradcam` links to papers and codes?

We are very sorry that we currently have no such plans.
