### ISSUE TITLE
When I use pdb.set_trace() in the code, the procedure never stop.

### ISSUE THREAD

**Issue by rainylt** [open-mmlab/mmclassification#769]
I'd like to learn the code by debugging, but when I use pdb in the code, the procedure never stops.
eg. I set a breakpoint in the 94 lines of mmcls/models/backbones/convnext.py.  But when I run the training procedure with a single gpu, it never stops.
I'm confused that how can I use pdb successfully in the procedure. Please give me some suggestions.

**Comment by mzr1996** [comment]
Pdb works in my environment, I think you need to provide more information about your debugging.
![图片](https://user-images.githubusercontent.com/26739999/162151065-a810d928-42d1-4e1a-a48c-4e8fd36e7671.png)

**Comment by rainylt** [comment]
> Pdb works in my environment, I think you need to provide more information about your debugging. ![图片](https://user-images.githubusercontent.com/26739999/162151065-a810d928-42d1-4e1a-a48c-4e8fd36e7671.png)

Thanks for your reply. I have found the problem. Maybe because I have token some redundant operations when I install misclassification, resulting in that the mmcls version doesn't match the code. So after I reinstalled the mmcls by "pip3 install -e .", the pdb can work successfully.
