### ISSUE TITLE
[Feature] add some feature for learning extremely un-balanced datasets

### ISSUE THREAD

**Issue by flywheel1412** [open-mmlab/mmclassification#775]
### Describe the feature

**Re-sampling**
- in mini-batch, every class is balanced (class-balanced sampling);
- gradually transition from sample-balanced sampling(current sampling stategy) to class-balanced sampling in training time;

**Re-weighting**
- set difference class with difference weight;

### Motivation

in the industrial, more attention is focus on training a model on class un-balanced datasets, bellow is some methods to better learning un-balanced dataset.

### Related resources
[Deep Long-Tailed Learning: A Survey](https://arxiv.org/abs/2110.04596)

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
