### ISSUE TITLE
Can't use gpu

### ISSUE THREAD

**Issue by EstherJinyan** [open-mmlab/mmclassification#777]
Hello, I can't use gpu when training the model, the details are as follows:

It can be trained with gpu at the beginning, "python tools/train.py --gpu-id=0"
Then I changed to cpu for debugging code, "python tools/train.py --gpu-id=-1"
Then change to gpu and find that it is unavailable, "python tools/train.py --gpu-id=0"

The prompt "No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'", how to solve this?
Thanks.

**Comment by mzr1996** [comment]
Strange error, will this error still exist if you retry it after starting a new shell?

**Comment by EstherJinyan** [comment]
I reopened a shell and found that there is no problem. It seems that the restart is yyds.
Thanks.
