### ISSUE TITLE
vis pipeline error

### ISSUE THREAD

**Issue by EstherJinyan** [open-mmlab/mmclassification#780]
Hello, I have the following error when I use vis_pipline.py to view the pipline result according to the tutorial, what is the problem?
Traceback (most recent call last):
  File "tools/visualizations/vis_pipeline.py", line 337, in <module>
    main()
  File "tools/visualizations/vis_pipeline.py", line 303, in main
    dataset, pipelines = build_dataset_pipelines(cfg, args.phase)
  File "tools/visualizations/vis_pipeline.py", line 151, in build_dataset_pipelines
    if len(data_cfg.pipeline
  File "/dockerdata/weimei/env/miniconda3/envs/py37/lib/python3.7/site-packages/mmcv/utils/config.py", line 49, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'pipeline' 

The command is: python tools/visualizations/vis_pipeline.py configs/resnet/resnet50_augment_roof6.py --number 100 --mode pipeline --output-dir tmp_pipline_vis --adaptive

The pipline in config is:
img_norm_cfg = dict(mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomFlip', flip_prob=0.3, direction='vertical'),
    dict(type='RandomFlip', flip_prob=0.3, direction='horizontal'),
    dict(type='RandomResizedCrop', size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label']),
]

**Comment by mzr1996** [comment]
Can you provide the entire config?

**Comment by EstherJinyan** [comment]
base_ = [
    '../_base_/models/resnet50.py', '../_base_/default_runtime.py'
]

# 模型设置
model = dict(
    backbone=dict(
        #frozen_stages=None,
        in_channels = 3,
        init_cfg=dict(
            type='Pretrained',
            checkpoint='/run/ljy/data/pretrained/resnet50_8xb32_in1k_20210831-ea4938fc.pth',
            prefix='backbone',
        )),
    head=dict(num_classes=6,
        topk=(1, 2)),
)

# 数据集设置
dataset_type = 'GtWithContour_Cls6'
img_norm_cfg = dict(mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomFlip', flip_prob=0.3, direction='vertical'),
    dict(type='RandomFlip', flip_prob=0.3, direction='horizontal'),
    dict(type='RandomResizedCrop', size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label']),
]
test_pipeline = [
    dict(type='LoadImageWIthContour', crop_flag=False, mask_flag=False, add_mask_flag=False),
    dict(type='Resize', size=(256, -1)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img']),
]

data_root_path = '/run/ljy/data/building_roof/1-2'
data = dict( 
    samples_per_gpu=128,
    workers_per_gpu=1,
    train=dict(
        type='ClassBalancedDataset',
        oversample_thr=0.1,
        dataset =dict(
            type=dataset_type,
            data_prefix='{}/images'.format(data_root_path),
            ann_file='{}/train.txt'.format(data_root_path),
            pipeline=train_pipeline)),
    val=dict(
        type=dataset_type,
        data_prefix='{}/images'.format(data_root_path),
        ann_file='{}/test.txt'.format(data_root_path),
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        data_prefix='{}/images'.format(data_root_path),
        ann_file='{}/test.txt'.format(data_root_path),
        pipeline=test_pipeline))
# 优化策略
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)

# 学习率衰减策略
lr_config = dict(policy='step', step=[15])
runner = dict(type='EpochBasedRunner', max_epochs=200)
log_config = dict(interval=100)

# 运行设置
evaluation = dict(interval=1, metric='accuracy')
checkpoint_config = dict(interval=10)  # checkpoint saving
load_from = None
resume_from = None


**LoadImageWIthContour** is a class I implemented myself, in test_pipline, I think it should have nothing to do with this error.

**Comment by mzr1996** [comment]
Get it, the vis pipeline tool doens't support `ClassBalancedDataset` by now. I think you can change it to the original dataset temporarily.

**Comment by EstherJinyan** [comment]
Ok,thanks.
