### ISSUE TITLE
Question about DistOptHook

### ISSUE THREAD

**Issue by HarborYuan** [open-mmlab/mmclassification#786]
### Checklist
- I have searched related issues but cannot get the expected help. done.
- I have read related documents and don't know what to do. done.

### Describe the question you meet

Hi, 

I want to check the grad norm info when training. However, the current implementation of [DistOptHook](https://github.com/open-mmlab/mmclassification/blob/6beac5060f0c1d57141642dba77c19c9ed6b3873/mmcls/core/utils/dist_utils.py#L47) prevent the textlogger from priting gradnorm.

I can circumvent it by myself, but does the DistOptHook has its functionality? Can we move to mmcv OptHook?

I can raise a PR if neccessary.

Thanks.

**Comment by mzr1996** [comment]
Looks it's a legacy problem. Welcome to change it to the `OptimizerHook` in mmcv, and we will test it.

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
