### ISSUE TITLE
How to eval

### ISSUE THREAD

**Issue by IT-five** [open-mmlab/mmclassification#788]
I call mmcls.model from the outside, but it can only be trained, not verified, how can I verify it?
This is my code:
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='SwinTransformer', arch='base', img_size=224, drop_path_rate=0.5),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=8,
        in_channels=1024,
        init_cfg=None,  # suppress the default init_cfg of LinearClsHead.
        loss=dict(
            type='LabelSmoothLoss', label_smooth_val=0.1, mode='original'),
        cal_acc=False),
    init_cfg=[
        dict(type='TruncNormal', layer='Linear', std=0.02, bias=0.),
        dict(type='Constant', layer='LayerNorm', val=1., bias=0.),
        dict(type='Pretrained', checkpoint='https://download.openmmlab.com/mmclassification/v0/swin-transformer/swin_tiny_224_b16x64_300e_imagenet_20210616_090925-66df6be6.pth')
    ])
net = build_classifier(model)

**Comment by Ezra-Yu** [comment]
you can refer to the [get_started docs](https://mmclassification.readthedocs.io/en/latest/getting_started.html#inference-with-pretrained-models) to learn about the `test.py` tools.

If you want to learn about the mmcls python test\eval API, you can refer to [notebook](https://colab.research.google.com/github/open-mmlab/mmclassification/blob/master/docs/en/tutorials/MMClassification_tools.ipynb).
