### ISSUE TITLE
The pre-train model performance of ResNet-50 doesn't match with the document

### ISSUE THREAD

**Issue by XingtongGe** [open-mmlab/mmclassification#789]
Hi, I use the pre-train model of resnet50_8xb32_in1k and inference on the ILSVRC2012_img_val set, but the result is worse than the document.

I tried another config file resnet50_8xb32-fp16_in1k.py and its pre-train model, the result is also worse.

the command: 
python tools/test.py \
    configs/resnet/resnet50_b32x8_imagenet.py \
    checkpoints/mmclassification/resnet50_8xb32_in1k_20210831-ea4938fc.pth  --metrics accuracy precision recall

![image](https://user-images.githubusercontent.com/58927343/163852174-35cfdb05-c668-4650-bf22-23898064e509.png)

I selected 1000 images of the val set to accelerate it, the result using the full val set was about the same.

Plus, I used the same command on last December(12.2021) and the result was correct, so was something in data pipeline changed during this time or did I just use the wrong config file?

Appriciate it if you could help!

**Comment by mzr1996** [comment]
Sorry but I cannot reproduce your problem.
![image](https://user-images.githubusercontent.com/26739999/163905107-0d012aa6-d465-4349-99a8-734f2e8480f3.png)

**Comment by XingtongGe** [comment]
Thanks a lot! I finally found out that it was because I had changed an api in mmcv before, and it returned to normal after the modification.
