### ISSUE TITLE
[Bug] metafile info of `ShuffleNetV1` and `ShuffleNetV2` missing 

### ISSUE THREAD

**Issue by PeterH0323** [open-mmlab/mmclassification#800]
### Describe the bug
Can not find any info from metafile of below model config file:

- `shufflenet_v1_1x_b64x16_linearlr_bn_nowd_imagenet.py`
- `shufflenet_v2_1x_b64x16_linearlr_bn_nowd_imagenet.py`

We need it when process mmdeploy regression test.

Thx

**Comment by Ezra-Yu** [comment]
[shufflenet_v2_1x_b64x16_linearlr_bn_nowd_imagenet.py](https://github.com/open-mmlab/mmclassification/blob/master/configs/shufflenet_v2/shufflenet_v2_1x_b64x16_linearlr_bn_nowd_imagenet.py) is equal with [shufflenet-v2-1x_16xb64_in1k.py](https://github.com/open-mmlab/mmclassification/blob/master/configs/shufflenet_v2/shufflenet-v2-1x_16xb64_in1k.py).

and the `shufflenet_v2_1x_b64x16_linearlr_bn_nowd_imagenet.py` will be deprecated in nearly future. As you open the  `shufflenet_v2_1x_b64x16_linearlr_bn_nowd_imagenet.py` file, you can see:
```
_base_ = 'shufflenet-v2-1x_16xb64_in1k.py'

_deprecation_ = dict(
    expected='shufflenet-v2-1x_16xb64_in1k.py',
    reference='https://github.com/open-mmlab/mmclassification/pull/508',
)
```

The same as the `shufflenet_v1_1x_b64x16_linearlr_bn_nowd_imagenet.py`.
