### ISSUE TITLE
ClsHead  update request [Feature]

### ISSUE THREAD

**Issue by GitHubChrischen** [open-mmlab/mmclassification#804]
### Describe the feature

在ClsHead初始化函数里面不要限制参数loss 只能是 dict
cls_head.py 
line 32:
assert isinstance(loss, dict)

### Motivation
我可能会写一个loss 传入进去，希望兼容直接传入loss或者传入dict在里面build这两种模式，3Q

[here]

### Related resources
If there is an official code release or third-party implementation, please also provide the information here, which would be very helpful.

[here]

### Additional context
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

[here]

**Comment by Ezra-Yu** [comment]
you can directly modify the source code in your own project.
