### ISSUE TITLE
How to change classes number while training?

### ISSUE THREAD

**Issue by lvbohui** [open-mmlab/mmclassification#806]
###  Related info
1. `pip list | grep "mmcv\|mmcls\|^torch"` output:
mmcls                             0.22.1    /home/xiaojiu/gitlab-pro/mmclassification
mmcv-full                         1.5.0
torch                             1.10.2
torchvision                       0.11.3

2. Training
I want to change the **classes number** from 1000 to 4, within ImageNet format.<br>
I use this config file: **configs/mobilenet_v3/mobilenet-v3-small_8xb32_in1k.py**, and I have changed related *model* file:
![image](https://user-images.githubusercontent.com/31612613/165694738-835295a1-2636-4b83-8036-ba12f454e0f0.png)
As shown above, the line 8 has been changed, but I still got the error:<br> 
Traceback (most recent call last):
  File "/home/xiaojiu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/xiaojiu/gitlab-pro/mmclassification/mmcls/datasets/imagenet.py", line 1052, in __init__
    super().__init__(
  File "/home/xiaojiu/gitlab-pro/mmclassification/mmcls/datasets/custom.py", line 165, in __init__
    super().__init__(
  File "/home/xiaojiu/gitlab-pro/mmclassification/mmcls/datasets/base_dataset.py", line 51, in __init__
    self.data_infos = self.load_annotations()
  File "/home/xiaojiu/gitlab-pro/mmclassification/mmcls/datasets/custom.py", line 211, in load_annotations
    samples = self._find_samples()
  File "/home/xiaojiu/gitlab-pro/mmclassification/mmcls/datasets/custom.py", line 190, in _find_samples
    assert len(self.CLASSES) == len(classes), \
AssertionError: The number of subfolders (4) doesn't match the number of specified classes (1000). Please check the data folder.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "tools/train.py", line 200, in <module>
    main()
  File "tools/train.py", line 170, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/xiaojiu/gitlab-pro/mmclassification/mmcls/datasets/builder.py", line 50, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/xiaojiu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: ImageNet: The number of subfolders (4) doesn't match the number of specified classes (1000). Please check the data folder.

So, **shall I change anyother config file?** Thanks anyway

**Comment by Ezra-Yu** [comment]
It seems that your modification is not successful. try to print your model before training.

you can refer to [the collab tutorial](https://colab.research.google.com/github/open-mmlab/mmclassification/blob/master/docs/en/tutorials/MMClassification_tools.ipynb).

**Comment by lvbohui** [comment]
> It seems that your modification is not successful. try to print your model before training.
> 
> you can refer to [the collab tutorial](https://colab.research.google.com/github/open-mmlab/mmclassification/blob/master/docs/en/tutorials/MMClassification_tools.ipynb).

Thanks for your reply, I have printed the model, but it's too long, I put it into a file:
[model.log](https://github.com/open-mmlab/mmclassification/files/8580482/model.log)

**Comment by Ezra-Yu** [comment]
Your log is correct.

I get the problem, We recently had an update to datasets, including ImageNet and CustomDataset, but no updates to previous tutorials. Your error cause by [this line](https://github.com/open-mmlab/mmclassification/blob/6beac5060f0c1d57141642dba77c19c9ed6b3873/mmcls/datasets/custom.py#L189), the ImageNet has default `Classes`.

To slove the error:
chage  `class_type`  to  'CustomDataset', such as [this line](https://github.com/open-mmlab/mmclassification/blob/6beac5060f0c1d57141642dba77c19c9ed6b3873/configs/_base_/datasets/imagenet_bs64.py#L2) to ```dataset_type = 'CustomDataset'```

Or change the classes value in config through [`ImageNet.classes`](https://github.com/open-mmlab/mmclassification/blob/6beac5060f0c1d57141642dba77c19c9ed6b3873/mmcls/datasets/imagenet.py#L20) like:
```
dataset_type = 'ImageNet'
data = dict(
    samples_per_gpu=64,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        classes=['a', 'b', 'c', 'd'],
        data_prefix='data/imagenet/train',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        classes=['a', 'b', 'c', 'd'],
        data_prefix='data/imagenet/val',
        ann_file='data/imagenet/meta/val.txt',
        pipeline=test_pipeline),
    test=dict(
        # replace `data/val` with `data/test` for standard test
        type=dataset_type,
        classes=['a', 'b', 'c', 'd'],
        data_prefix='data/imagenet/val',
        ann_file='data/imagenet/meta/val.txt',
        pipeline=test_pipeline))

```

**Comment by lvbohui** [comment]
If I chage `class_type` to 'CustomDataset', do I need to write another dedicated py file for it?

**Comment by mzr1996** [comment]
> 

No, Just use it as the [instruction here](https://mmclassification.readthedocs.io/en/master/api/datasets.html#mmcls.datasets.CustomDataset).

**Comment by lvbohui** [comment]
Thanks, I fix this problem through changeing the classes value, so maybe I can close this issue.

**Comment by Chenhaolin6** [comment]
注意：若使用imagenet的数据格式需修改官方代码 [[#报错issues](https://github.com/open-mmlab/mmpretrain/issues/806)](https://github.com/open-mmlab/mmpretrain/issues/806)

修改目录：mmpretrain/datasets/custom.py
修改行数：234

```
if self.CLASSES is not None:
    assert len(self.CLASSES) == len(classes), \
        f"The number of subfolders ({len(classes)}) doesn't " \
        f'match the number of specified classes ' \
        f'({len(self.CLASSES)}). Please check the data folder.'
else:
    self._metainfo['classes'] = tuple(classes)
```

改为：

```
self._metainfo['classes'] = tuple(classes)
```
