### ISSUE TITLE
Unable to download cats_dogs_dataset，Can you upload this dataset to Baidu online disk?

### ISSUE THREAD

**Issue by daigang896** [open-mmlab/mmclassification#807]
Hello，https://www.dropbox.com/s/wml49yrtdo53mie/cats_dogs_dataset_reorg.zip?dl=0，it unable to download. Can you upload this dataset to Baidu online disk?

**Comment by Ezra-Yu** [comment]
链接：https://pan.baidu.com/s/1NnVprB_niP-XL9gdo42QiQ 
提取码：phza

**Comment by daigang896** [comment]
Thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmclassification"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 下午4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmclassification] Unable to download cats_dogs_dataset，Can you upload this dataset to Baidu online disk? (Issue #807)





 
链接：https://pan.baidu.com/s/1NnVprB_niP-XL9gdo42QiQ
 提取码：phza
