### ISSUE TITLE
always in eval state 

### ISSUE THREAD

**Issue by yuanpengcheng** [open-mmlab/mmclassification#81]
I train resnet50 in distributed mode on imagenet-1k, in train phase, everything is Ok, however, in eval phase, the process is pending all time.
![image](https://user-images.githubusercontent.com/8765191/98189565-2f84a900-1f50-11eb-80b6-16ae8e45abf6.png)

**Comment by mzr1996** [comment]
Hello, is this problem exists with the latest version?

**Comment by tonysy** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you still encounter this issue with the latest stable version. You can also contribute directly by creating a PR

Thank you!
