### ISSUE TITLE
[Bug] RunTimeError: selected index k out of range

### ISSUE THREAD

**Issue by fdh0** [open-mmlab/mmclassification#810]
### 描述
An error will be reported when the 2 classification （<5）

```
RunTimeError: selected index k out of range
```

### 附加内容
修改处：

mmclassification\mmcls\models\losses\accuracy.py
Line:57
```
    # if num_classes < 5, will error
    maxk = min(max(topk), pred.size(1))

```

**Comment by Ezra-Yu** [comment]
We have an example in 2-category classification task, [link](https://github.com/open-mmlab/mmclassification/blob/master/docs/en/tutorials/MMClassification_python.ipynb). There is no error.

**Comment by fdh0** [comment]
@Ezra-Yu I think code below works.

`
# Modify the evaluation metric
cfg.evaluation['metric_options']={'topk': (1, )}
`

it just get the top 1 result.
