### ISSUE TITLE
how i can save model in mmclassification?

### ISSUE THREAD

**Issue by vothaianh1997** [open-mmlab/mmclassification#814]
推荐使用英语模板 General question，以便你的问题帮助更多人。

### 首先确认以下内容
- 我已经查询了相关的 issue，但没有找到需要的帮助。
- 我已经阅读了相关文档，但仍不知道如何解决。

### 描述你遇到的问题

[填写这里]

### 相关信息
1. `pip list | grep "mmcv\|mmcls\|^torch"` 命令的输出
[填写这里]
2. 如果你修改了，或者使用了新的配置文件，请在这里写明
```python
[填写这里]
```
3. 如果你是在训练过程中遇到的问题，请填写完整的训练日志和报错信息
[填写这里]
4. 如果你对 `mmcls` 文件夹下的代码做了其他相关的修改，请在这里写明
[填写这里]

**Comment by Ezra-Yu** [comment]
modify CheckpointHook in [`configs/_base_/runtime.py`](https://github.com/open-mmlab/mmclassification/blob/7c5ddb1e5bee68d52ff8b5622cdbd75c02792c07/configs/_base_/default_runtime.py#L2)

here is the docstring:

```
class CheckpointHook(Hook):
    """Save checkpoints periodically.
    Args:
        interval (int): The saving period. If ``by_epoch=True``, interval
            indicates epochs, otherwise it indicates iterations.
            Default: -1, which means "never".
        by_epoch (bool): Saving checkpoints by epoch or by iteration.
            Default: True.
        save_optimizer (bool): Whether to save optimizer state_dict in the
            checkpoint. It is usually used for resuming experiments.
            Default: True.
        out_dir (str, optional): The directory to save checkpoints. If not
            specified, ``runner.work_dir`` will be used by default.
        max_keep_ckpts (int, optional): The maximum checkpoints to keep.
            In some cases we want only the latest few checkpoints and would
            like to delete old ones to save the disk space.
            Default: -1, which means unlimited.
    """
```

**Comment by vothaianh1997** [comment]
pls give me file code example. i don't find runtime.py in  base

**Comment by vothaianh1997** [comment]
pls give me file code example.

**Comment by Ezra-Yu** [comment]
For CheckPointHook, such as:
```
checkpoint_config = dict(interval=10, max_keep_ckpts=10)
# save checkpoint every 10 epochs
# save 10 checkpoints as most.
```

If you want to save the best checkpoint, you can refer to this [example](https://github.com/open-mmlab/mmclassification/blob/7c5ddb1e5bee68d52ff8b5622cdbd75c02792c07/configs/_base_/datasets/imagenet_bs64_t2t_224.py#L71).

**Comment by fedllanes** [comment]
I usually run this code before inference.

if not os.path.isdir(cfg['work_dir']):
  os.mkdir(cfg['work_dir'])
  
with open(cfg['work_dir'] + "/config.py", "w") as f:
    f.write(cfg.dump())
    
   It'll save the config file alongside the logs, it's useful because then you can just load this file when doing inference.
