### ISSUE TITLE
how to train my own dataset

### ISSUE THREAD

**Issue by JennieDD** [open-mmlab/mmclassification#815]
[我在使用代码训练自己的数据的时候，修改了相关配置文件之后，运行的时候仍会报错]
修改了以下：

修改类别：将 1000 类改为 2 类

修改topk = (1,5)变成topk = (1,)

修改数据路径：data

修改数据类别：classes='/data/dataset_81/cats_dogs_dataset/classes.txt'

运行命令
```python
python tools/train.py configs/resnet/resnet34_8xb32_in1k.py --work-dir my_workdir
```

报错如下：
'RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)'
![image](https://user-images.githubusercontent.com/104477720/166855557-93e26d1a-51a2-4c01-8408-d1e713d93313.png)

**Comment by Ezra-Yu** [comment]
I have never encountered such a problem, maybe you [this question](https://stackoverflow.com/questions/66600362/runtimeerror-cuda-error-cublas-status-execution-failed-when-calling-cublassge) in StackOverflow can help you.

**Comment by Ezra-Yu** [comment]
have you ever solved your problem?

**Comment by Ezra-Yu** [comment]
closed since no reply.
