### ISSUE TITLE
Question about K-Fold config

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#816]
Hi, dear authors!
Thank you for your amazing job!

I have a question about K-Fold config.
In K-Fold, can the `val` and the `test` be the same? 
Like follow:
```
    train=dict(
        type='KFoldDataset',
        num_splits=5,
        dataset=dict(
            type='RepeatDataset',
            times=15,
            dataset=dict(
                type=dataset_type,
                data_prefix='data/my_data/train',
                pipeline=train_pipeline))),
    val=dict(
        type=dataset_type,
        data_prefix='data/my_data/val',
        ann_file='data/my_data/meta/val.txt',
        pipeline=test_pipeline),
    test=dict(
        # replace `data/val` with `data/test` for standard test
        type=dataset_type,
        data_prefix='data/my_data/val',
        ann_file='data/my_data/meta/val.txt',
        pipeline=test_pipeline))
```
Thank you!

------------------------------------------------------------------------------
您好：
非常感谢您的工作！
我有一个关于 K-Fold 配置的问题。请问在 K-Fold 中，`val` 的配置和 `test` 的配置可以相同吗？（就是`val` 和 `test`公用一套图像）
就像下面这样:
```
    train=dict(
        type='KFoldDataset',
        num_splits=5,
        dataset=dict(
            type='RepeatDataset',
            times=15,
            dataset=dict(
                type=dataset_type,
                data_prefix='data/my_data/train',
                pipeline=train_pipeline))),
    val=dict(
        type=dataset_type,
        data_prefix='data/my_data/val',
        ann_file='data/my_data/meta/val.txt',
        pipeline=test_pipeline),
    test=dict(
        # replace `data/val` with `data/test` for standard test
        type=dataset_type,
        data_prefix='data/my_data/val',
        ann_file='data/my_data/meta/val.txt',
        pipeline=test_pipeline))
```
谢谢！

**Comment by Ezra-Yu** [comment]
For K-Fold cross-validation, all images should be placed in the same folder.

You can refer to  [the K-fold PR](https://github.com/open-mmlab/mmclassification/pull/563), there is a detailed example config in PR desciption and a [tool](https://github.com/open-mmlab/mmclassification/blob/master/tools/kfold-cross-valid.py).

**Comment by zhongqiu1245** [comment]
Thank you!

**Comment by zhongqiu1245** [comment]
Hi, sorry to bother you again. 
If I use `Repeatdataset(times=15)` in `k-fold` of `train_cfg`, should I also use `Repeatdataset(times=15)` in `val_cfg` and `test_cfg`?
Like this?
```
train=dict(
        type='KFoldDataset',
        dataset=dict(
            type='RepeatDataset',
            times=15,
            dataset=dict(
                type=dataset_type,
                data_prefix='data/my_data/train',
                pipeline=train_pipeline)),
        fold=0,
        num_splits=5),
    val=dict(
        type='KFoldDataset',
        dataset=dict(
            type=dataset_type,
            data_prefix='data/my_data/train',
            pipeline=train_pipeline),
        fold=0,
        num_splits=5),
    test=dict(
        type='KFoldDataset',
        dataset=dict(
            type=dataset_type,
            data_prefix='data/my_data/train',
            pipeline=train_pipeline),
        fold=0,
        num_splits=5))
```

**Comment by zhongqiu1245** [comment]
And if I really want to use "data/my_data/val" to be test_set, how can I change the cfg？

**Comment by Ezra-Yu** [comment]
1.
Yes.

2.
Just as the settings in a normal configuration file, such as [link](https://github.com/open-mmlab/mmclassification/blob/7c5ddb1e5bee68d52ff8b5622cdbd75c02792c07/configs/_base_/datasets/cifar10_bs16.py#L31).

**Comment by zhongqiu1245** [comment]
You mean this?
```
train=dict(
        type='KFoldDataset',
        dataset=dict(
            type='RepeatDataset',
            times=15,
            dataset=dict(
                type=dataset_type,
                data_prefix='data/my_data/train',
                pipeline=train_pipeline)),
        fold=0,
        num_splits=5),
    val=dict(
        type='KFoldDataset',
        dataset=dict(
            type='RepeatDataset',
            times=15,
            dataset=dict(
                type=dataset_type,
                data_prefix='data/my_data/train',
                pipeline=train_pipeline)),
        fold=0,
        num_splits=5),
    test=dict(
        type=dataset_type,
        data_prefix='data/my_data/val',
        ann_file='data/my_data/meta/val.txt',
        pipeline=test_pipeline))
```

That is to say, in the case of K-Fold, only train_cfg and val_cfg need to comply with the same `KFolddataset` operation (including `Repeatdataset` nested in `KFolddataset` and other sub-operations), but test_cfg can not comply?
也就是说，用K-Fold的情况下，只有train_cfg和val_cfg需要遵从相同的`KFolddataset`操作(包括`KFolddataset`里面嵌套的`Repeatdataset`等子操作)， 但是test_cfg可以不遵从？

**Comment by zhongqiu1245** [comment]
For 1， NO
There is an error:
![image](https://user-images.githubusercontent.com/48090608/167153808-ed80d13b-9a25-4310-a39f-f3bcb37081a4.png)

config:
train=dict(
        type='KFoldDataset',
        dataset=dict(
            type='RepeatDataset',
            times=15,
            dataset=dict(
                type=dataset_type,
                data_prefix='data/my_data/train',
                pipeline=train_pipeline)),
        fold=0,
        num_splits=5),
    val=dict(
        type='KFoldDataset',
        dataset=dict(
            type='RepeatDataset',
            times=15,
            dataset=dict(
                type=dataset_type,
                data_prefix='data/my_data/train',
                pipeline=train_pipeline)),
        fold=0,
        num_splits=5),
    test=dict(
        type=dataset_type,
        data_prefix='data/my_data/val',
        ann_file='data/my_data/meta/val.txt',
        pipeline=test_pipeline))

**Comment by Ezra-Yu** [comment]
> That is to say, in the case of K-Fold, only train_cfg and val_cfg need to comply with the same `KFolddataset` operation (including `Repeatdataset` nested in `KFolddataset` and other sub-operations), but test_cfg can not comply? 也就是说，用K-Fold的情况下，只有train_cfg和val_cfg需要遵从相同的`KFolddataset`操作(包括`KFolddataset`里面嵌套的`Repeatdataset`等子操作)， 但是test_cfg可以不遵从？

The principle is to use what is specified in the config file. val_cfg specify another dataset, then the runner will use another dataset too. But there is no the meaning of k-folder Dataset

**Comment by zhongqiu1245** [comment]
> For 1， NO There is an error: ![image](https://user-images.githubusercontent.com/48090608/167153808-ed80d13b-9a25-4310-a39f-f3bcb37081a4.png)
> 
> config:
> 
> ```
> train=dict(
>         type='KFoldDataset',
>         dataset=dict(
>             type='RepeatDataset',
>             times=15,
>             dataset=dict(
>                 type=dataset_type,
>                 data_prefix='data/my_data/train',
>                 pipeline=train_pipeline)),
>         fold=0,
>         num_splits=5),
>     val=dict(
>         type='KFoldDataset',
>         dataset=dict(
>             type='RepeatDataset',
>             times=15,
>             dataset=dict(
>                 type=dataset_type,
>                 data_prefix='data/my_data/train',
>                 pipeline=train_pipeline)),
>         fold=0,
>         num_splits=5),
>     test=dict(
>         type=dataset_type,
>         data_prefix='data/my_data/val',
>         ann_file='data/my_data/meta/val.txt',
>         pipeline=test_pipeline))
> ```

@Ezra-Yu 
Thank you for your reply
But I have a question, how to use repeatdataset in K-fold
I used RepeatDataset in K-fold but it got this error ('casue my dataset is small, so I have to use Repeatdataset to improve performance).
Could you tell me how to solve it? Thank you!

**Comment by zhongqiu1245** [comment]
或者说我想在K-fold的情况下，仅在train中使用repeatdataset，然后在val中就不使用了，请问这种该如何办到？

**Comment by Ezra-Yu** [comment]
There is no way to use it at present. If the data is relatively small, it is not recommended to use K-fold

**Comment by zhongqiu1245** [comment]
“If the data is relatively small, it is not recommended to use K-fold.” why？

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
