### ISSUE TITLE
densenet121_4xb256_in1k.py A100 training result is a little bit lower than expected

### ISSUE THREAD

**Issue by KimmiShi** [open-mmlab/mmclassification#818]
On A100-80GB, 8 gpus,  got:

```
{"mode": "val", "epoch": 90, "iter": 25, "lr": 0.001, "accuracy_top-1": 72.718, "accuracy_top-5": 91.04601}

```

which is loewer than `DenseNet121* | 7.98 | 2.88 | 74.96 | 92.21` in [readme](https://github.com/open-mmlab/mmclassification/tree/master/configs/densenet)

Should I use imagenet_bs2048 other than imagenet_bs256 when training with 8 gpus?

**Comment by AwesomePH** [comment]
> Notice that models with * are converted from [pytorch](https://pytorch.org/vision/stable/models.html), guided by [original repo](https://github.com/liuzhuang13/DenseNet). The config files of these models are only for inference. We don't ensure these config files' training accuracy and welcome you to contribute your reproduction results.

8卡schdule配置为 imagenet_bs2048,训练得到 "accuracy_top-1": 74.68401
