### ISSUE TITLE
 ImageNet: The number of subfolders (2) doesn't match the number of specified classes (1000). Please check the data folder.

### ISSUE THREAD

**Issue by FashionXu** [open-mmlab/mmclassification#819]
我跑colab上的例子，在配置dataset的时候，我把里面的

cfg.data.train.classes = 'data/cats_dogs_dataset/classes.txt'

cfg.data.val.ann_file = 'data/cats_dogs_dataset/val.txt'
cfg.data.val.classes = 'data/cats_dogs_dataset/classes.txt'

这些相关的信息去掉了。因为我的理解是mmcls能自动根据cfg.data.train.data_prefix中的子文件夹获取到类别和标签，结果后面运行到：

datasets = [build_dataset(cfg.data.train)]

的时候就出错了。提示信息是：

AssertionError: ImageNet: The number of subfolders (2) doesn't match the number of specified classes (1000). Please check the data folder.

不知道这个算是bug还是我的理解不对。

**Comment by Ezra-Yu** [comment]
Sorry, it is a  mismatch between the tutorial and the update, please refer to [this issue](https://github.com/open-mmlab/mmclassification/issues/806) for help. I will fix this soon.

**Comment by FashionXu** [comment]
> Sorry, it is a mismatch between the tutorial and the latest update, please refer to [this issue](https://github.com/open-mmlab/mmclassification/issues/806) for help. I will fix this soon.

Thank you very much!
