### ISSUE TITLE
Can I do Hierarchical Multi Label Classification using mmclassification ?

### ISSUE THREAD

**Issue by Balakumaran-kandula** [open-mmlab/mmclassification#823]
Lets say i have classes as multiple vectors (e.g) { "object":[cat , dog, hen , horse], "color":[ black , brown, white , grey], "number of animals":[1,2,3,4,5] } , i then wanted to train a single model which give results for all the different hierarchy of inputs ?

For this is it possible to give Classes as a 2d vector like [[horses,cat,dog],[black,white,gray]] and train on them?

**Comment by Ezra-Yu** [comment]
You can try the multi-task classification task,  refer to  #808

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
