### ISSUE TITLE
How Can i use tnt backbone  in mmdetection?

### ISSUE THREAD

**Issue by dsp6414** [open-mmlab/mmclassification#825]
i do not know the output tensor shape of tnt backbone features, How can i use the backbone in mmdet?

**Comment by Ezra-Yu** [comment]
you can refer to this [toturial PR](https://github.com/open-mmlab/mmclassification/pull/765) for help. [temp link](https://mmclassification--765.org.readthedocs.build/zh_CN/765/tutorials/backbone.html)
