### ISSUE TITLE
multi label classification tasks

### ISSUE THREAD

**Issue by Warrior996** [open-mmlab/mmclassification#828]
Is the MMClassification suitable for multi label classification tasks?  eg. ChestX-ray14 dataset

**Comment by mzr1996** [comment]
Yes, we support multi-label tasks, You can implement your dataset by referring to the `VOC` dataset. And the head of model should be `MultiLabelLinearHead`.

**Comment by Ezra-Yu** [comment]
@CompliceU  目前以支持 VOC 数据集，可以直接运行config， 参考[CSRA](https://github.com/open-mmlab/mmclassification/tree/dev/configs/csra)

**Comment by st929** [comment]
请问如何用CSRA跑自己制作的数据集呢？

**Comment by st929** [comment]
请问如何用CSRA训练自己的数据集呢，我制作成VOC架构的数据集格式 会出现 精度为0的现象

**Comment by Kelleg-Xu** [comment]
> 请问如何用CSRA训练自己的数据集呢，我制作成VOC架构的数据集格式 会出现 精度为0的现象

出现了同样的问题，请问你解决了吗？

**Comment by Warrior996** [comment]
没有，已经不做这个方向了。




陈凯
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmpretrain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月7日(星期四) 中午11:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmpretrain] multi label classification tasks (Issue #828)





  
请问如何用CSRA训练自己的数据集呢，我制作成VOC架构的数据集格式 会出现 精度为0的现象
  
出现了同样的问题，请问你解决了吗？
