### ISSUE TITLE
在终端输出中没有mode train只会打印mode val, 怎样设置才能打印mode train

### ISSUE THREAD

**Issue by xiaolifeimianbao** [open-mmlab/mmclassification#830]
举例例子，如下这种mode train 怎样设置终端才打印
{"mode": "train", "epoch": 1, "iter": 100, "lr": 0.01, "memory": 4745, "data_time": 0.42691, "loss": 6.9082, "top-1": 0.15234, "top-5": 0.57031, "time": 0.84829}

**Comment by Ezra-Yu** [comment]
try to modify your head config, for example [resnet50 head](https://github.com/open-mmlab/mmclassification/blob/master/configs/_base_/models/resnest50.py)
```
head=dict(
        type='LinearClsHead',
        num_classes=1000,
        in_channels=2048,
        loss=dict(
            type='LabelSmoothLoss',
            label_smooth_val=0.1,
            num_classes=1000,
            reduction='mean',
            loss_weight=1.0),
        topk=(1, 5),
        cal_acc=True))
```

**Comment by AlenLi817** [comment]
数据集很小batchsize很大就不打印，可以在default_runtime.py里设置interval小一些
log_config = dict(
    interval=100,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
