### ISSUE TITLE
Can i do image regression using mmclassification ?

### ISSUE THREAD

**Issue by Balakumaran-kandula** [open-mmlab/mmclassification#832]
If i want to do age prediction , can i do the regression model here ?

**Comment by Ezra-Yu** [comment]
sure, you can do that, but you have to implement your own [head](https://github.com/open-mmlab/mmclassification/tree/master/mmcls/models/heads), [loss](https://github.com/open-mmlab/mmclassification/tree/master/mmcls/models/losses) and [regressor](https://github.com/open-mmlab/mmclassification/tree/master/mmcls/models/classifiers). Also, the evaluation method needs to be rewrite.
