### ISSUE TITLE
Is there any problem to predict image rotation with image classification?

### ISSUE THREAD

**Issue by lvbohui** [open-mmlab/mmclassification#833]
### Problem
I used the mobilenet-v3 network to train a model to solve a four-category problem, but there is only one category in the prediction result of the final model, correspondingly, the accuracy rate is about 25%. The number of four categories in my data is not much different, about 25% in each category

### Related info
1. `pip list | grep "mmcv\|mmcls\|^torch"` 命令的输出
```
mmcls                             0.22.1    /home/xiaojiu/gitlab-pro/mmclassification
mmcv-full                         1.5.0
torch                             1.10.2
torchvision                       0.11.3
```
2. Related files
What I want to distinguish is the four directions of sink, in other words, my labels are up, down, left, right, so I removed the random flips in train_pipeline and test_pipeline. Is there a problem in predicting the rotation direction of the same object using image classification?
[config_sink200.zip](https://github.com/open-mmlab/mmclassification/files/8667207/config_sink200.zip)
My evaluation metric is:
`evaluation = dict(interval=50, metric='accuracy', metric_options={'topk': 1})`
This can be confirmed at **line 39** of `dataset/sink200_bs32_pil_resize.py` in the above file

And this is the result:[result.txt](https://github.com/open-mmlab/mmclassification/files/8667257/result.txt)

**Comment by Ezra-Yu** [comment]
First, check the annotations of the dataset.  you can use this [tool](https://mmclassification.readthedocs.io/en/latest/tools/visualization.html#pipeline-visualization).

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
