### ISSUE TITLE
输出特征提取结果

### ISSUE THREAD

**Issue by JennieDD** [open-mmlab/mmclassification#836]
以下代码能正常运行
```
python demo/image_demo.py demo/demo.JPEG configs/resnet/resnet34_8xb32_in1k.py /data/dataset_81/jd_result/epoch_100.pth
```
我想咨询一下能否输出backbone或者neck提取特征之后的结果呢，我自己尝试改了一下代码，觉得有些复杂。希望能问问如何输出backbone或者neck提取特征之后的结果

**Comment by JennieDD** [comment]
The following code runs successfully
```
python demo/image_demo.py demo/demo.JPEG configs/resnet/resnet34_8xb32_in1k.py /data/dataset_81/jd_result/epoch_100.pth
```
I would like to ask if it is possible to output the result after extracting features of Backbone or Neck. I have tried to change the code myself, but I think it is a little complicated. How to output the result of backbone or Neck extracting features

**Comment by Ezra-Yu** [comment]
please refer to this PR https://github.com/open-mmlab/mmclassification/pull/593

**Comment by okideal** [comment]
Add your custom output layer name in arg _stage_ of function _extract_feat_ of _Classifier_, and then modify the backbone _forward_ function to process your custome name (return earlier)
