### ISSUE TITLE
[Bug]TensorRT: torch.jit.frontend.NotSupportedError

### ISSUE THREAD

**Issue by yige2018** [open-mmlab/mmclassification#837]
推荐使用英语模板 Bug report，以便你的问题帮助更多人。

### 描述 bug
简单地描述一下遇到了什么 bug
when I tried to run torch_tensorrt through modified image_demo.py, I saw following error
File "/home/.local/lib/python3.8/site-packages/torch/jit/frontend.py", line 326, in build_param_list
raise NotSupportedError(ctx_range, _vararg_kwarg_err)
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:

[填写这里]
Here is the code I modified for image_demo.py
from argparse import ArgumentParser

from mmcls.apis import inference_model, init_model, show_result_pyplot

import time
import torch
from mmcv.runner.fp16_utils import wrap_fp16_model

**import torch_tensorrt**

def main():
    parser = ArgumentParser()
    parser.add_argument('img', help='Image file')
    parser.add_argument('config', help='Config file')
    parser.add_argument('checkpoint', help='Checkpoint file')
    parser.add_argument(
        '--device', default='cuda:0', help='Device used for inference')
    args = parser.parse_args()

    # build the model from a config file and a checkpoint file
    model = init_model(args.config, args.checkpoint, device=args.device)

    **trt_model_fp32 = torch_tensorrt.compile(model, inputs = [torch_tensorrt.Input((1, 3, 224, 224), dtype=torch.float32)],
    enabled_precisions = torch.float32, # Run with FP32
    workspace_size = 1 << 32)**

    warms = 10
    # test a single image
    for i in range(warms):
        result = inference_model(**trt_model_fp32**, args.img)

    start = time.time()
    for i in range(1000):
        result = inference_model(**trt_model_fp32**, args.img)
    end = time.time()

    print('latency is {}'.format(end-start))
    # show the results
    #show_result_pyplot(model, args.img, result)

if __name__ == '__main__':
    main()

here is the log I saw

(open-mmlab) :~/mmclassification/demo$ python image_demo.py demo_224.jpg '../configs/swin_transformer/swin_base_224_b16x64_300e_imagenet.py' '../checkpoints/swin_base_224_b16x64_300e_imagenet_20210616_190742-93230b0d.pth' --device cuda

### 复现流程
在命令行中执行的详细操作

```shell
[填写这里]
```
load checkpoint from local path: ../checkpoints/swin_base_224_b16x64_300e_imagenet_20210616_190742-93230b0d.pth
Traceback (most recent call last):
  File "image_demo.py", line 45, in <module>
    main()
  File "image_demo.py", line 25, in main
    trt_model_fp32 = torch_tensorrt.compile(model, inputs = [torch_tensorrt.Input((1, 3, 224, 224), dtype=torch.float32)],
  File "/home/aslan/.local/lib/python3.8/site-packages/torch_tensorrt/_compile.py", line 96, in compile
    ts_mod = torch.jit.script(module)
  File "/home/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 1257, in script
    return torch.jit._recursive.create_script_module(
  File "/home/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 451, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 463, in create_script_module_impl
    method_stubs = stubs_fn(nn_module)
  File "/home/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 732, in infer_methods_to_compile
    stubs.append(make_stub_from_method(nn_module, method))
  File "/home/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 66, in make_stub_from_method
    return make_stub(func, method_name)
  File "/home/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 51, in make_stub
    ast = get_jit_def(func, name, self_name="RecursiveScriptModule")
  File "/home/.local/lib/python3.8/site-packages/torch/jit/frontend.py", line 264, in get_jit_def
    return build_def(parsed_def.ctx, fn_def, type_line, def_name, self_name=self_name, pdt_arg_types=pdt_arg_types)
  File "/home/.local/lib/python3.8/site-packages/torch/jit/frontend.py", line 302, in build_def
    param_list = build_param_list(ctx, py_def.args, self_name, pdt_arg_types)
  File "/home/.local/lib/python3.8/site-packages/torch/jit/frontend.py", line 326, in build_param_list
    raise NotSupportedError(ctx_range, _vararg_kwarg_err)
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
  File "/home/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 72
    @auto_fp16(apply_to=('img', ))
    def forward(self, img, return_loss=True, ****kwargs**):
                                              **~~~~~~~ <--- HERE**
        """Calls either forward_train or forward_test depending on whether
        return_loss=True.

### 相关信息
1. `pip list | grep "mmcv\|mmcls\|^torch"` 命令的输出
mmcls                     0.23.0       /home/aslan/yige/mmclassification
mmcv-full                 1.5.0

torch                     1.10.0+cu113
torch-tensorrt            1.0.0
torchaudio                0.10.0+cu113
torchinfo                 1.5.3
torchvision               0.11.1+cu113

[填写这里]
3. 如果你修改了，或者使用了新的配置文件，请在这里写明
```python
[填写这里]
```
4. 如果你是在训练过程中遇到的问题，请填写完整的训练日志和报错信息
[填写这里]
5. 如果你对 `mmcls` 文件夹下的代码做了其他相关的修改，请在这里写明
[填写这里]

### 附加内容
任何其他有关该 bug 的信息、截图等

[填写这里]

**Comment by Ezra-Yu** [comment]
some ops of swin are not supported in `torch.jit`. This kind of problem has to wait for the torch update, I will close this issue later.

**Comment by lvhan028** [comment]
Hi, @yige2018 you can try [mmdeploy](https://github.com/open-mmlab/mmdeploy.git) to deploy mmclassification models
