### ISSUE TITLE
puzzled With Mobilenet_v3 out_indices

### ISSUE THREAD

**Issue by dsp6414** [open-mmlab/mmclassification#838]
when out_indices is set None.

arch is small ,out_indices is (12,), while len(arch) is 11.
when arch is large, out_indices is (16,), however len(arch) is 15.

**Comment by dsp6414** [comment]
Does it mean to output classifier layer(12th layer).

**Comment by Ezra-Yu** [comment]
there is a [layer0](https://github.com/open-mmlab/mmclassification/blob/73c056b79f45da6c0ea138f0cd38237c7220f277/mmcls/models/backbones/mobilenet_v3.py#L120) in the start.
