### ISSUE TITLE
difference of the backbones between mmclassification and mmdetection

### ISSUE THREAD

**Issue by ChenCVer** [open-mmlab/mmclassification#84]
hello!
      I am in trouble, i want to merge mmdetection and mmclassification, i note that, there are great simillarity between backbone of the mmclassification and mmdetection. so, i want to use one of these. and then, i decide to use backbone of mmdetection rather than mmcls, but trouble is come, a classification which consist of backbone of mmdetection(for example, ResNet), neck named GAP(comes from mmclassifaction) and a LinearClsHead( comes from mmclassification). Now, this loss of model is not down during  the train, No matter what sample the input of the model is, for example, the samples are [0,0,0,1,1,0,0,0,0] or [1,1,0,0,1,0,0,1, 1], but the output after softmax and argmax of model always are the same number. So, when I replace the backbone with mmclassification. it works normarlly, I look carefully these files and want to find the difference, finally, I don't find the difference. So, I want to know, where is the difference of backbone of mmdet and mmcls? thank you!

**Comment by ChenCVer** [comment]
I got it, the key is: norm_eval

**Comment by ycxioooong** [comment]
Thanks for your information!
