### ISSUE TITLE
[Feature Request] Add segmentation as auxiliary task.

### ISSUE THREAD

**Issue by JayJJChen** [open-mmlab/mmclassification#840]
### Describe the feature
Add segmentation as auxiliary task. I tried to use mmsegmentation repo for my classification-segmentation task, but that's semantic segmentation so it's not as easy to evaluate and tune as classification task.

### Motivation
Empirically, adding salient object segmentation task as auxiliary task usually boosts main classification task performance. 

### Related resources
[DenseSharp](https://github.com/duducheng/DenseSharp)

### Additional context
NA.

**Comment by Ezra-Yu** [comment]
Thank you for your suggestion. We are working on this. And this requires the joint efforts of many parties.
