### ISSUE TITLE
How can I get a confusion_matrix?

### ISSUE THREAD

**Issue by AlenLi817** [open-mmlab/mmclassification#842]
### Checklist
- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

I found that the following code can be added in base_dataset.py to output confusion matrix.
But this confusion matrix is just a tensor. Are there other tools that can output a more beautiful confusion matrix?
```
allowed_metrics = [
            'accuracy', 'precision', 'recall', 'f1_score', 'support', 'calculate_confusion_matrix'
        ]
```

```
        if 'calculate_confusion_matrix' in metrics:
            confusion_matrix = calculate_confusion_matrix(results, gt_labels)
            eval_results['calculate_confusion_matrix'] = confusion_matrix
```

**Comment by Ezra-Yu** [comment]
refer to https://github.com/open-mmlab/mmclassification/issues/598

**Comment by AlenLi817** [comment]
Wow, get it. I should learn how to search related issues.
