### ISSUE TITLE
When using multitask training , the prediction during inference was not quite good 

### ISSUE THREAD

**Issue by Balakumaran-kandula** [open-mmlab/mmclassification#843]
I have tried using multi task for my dataset with 47 classes seperated into four different tasks ( single label classification types) , where each task added with extra class named "others" , for images which doesn't come under any other class in the task it will be assigned to class "others". In my dataset task 1 is like main type ( vegetable , fruits , packages) and task 2,3,4 are subtypes of those main types. so for most of the images atleast two tasks will be assigned to "others" class. Hence in training accuracy cant be improved much ,even if the accuracy is (80 %) which is not pretty good because most of the images will be assigned to others in the datas , is there any way to give more loss value to other classes and less loss value for "others" class in training process. and also in evaluation (e,g) accuracy gives misjudgement ( can we exclude others class there also)

**Comment by mzr1996** [comment]
Our `CrossEntroy` supports `class_weight`, you can specify the weight of each class.
