### ISSUE TITLE
Using official imagenet-1k

### ISSUE THREAD

**Issue by tpoisonooo** [open-mmlab/mmclassification#850]
### Checklist
- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

I have download imagenet-1k and extract it to `ILSVRC`，here is my directory structure :
```bash
├── ILSVRC
│   ├── Annotations
│   │   └── CLS-LOC
│   ├── Data
│   │   └── CLS-LOC
│   └── ImageSets
│       └── CLS-LOC
```
I would like to use `mmlcs/datastes/imagenet.py` to train my model,  it seems that an `data/imagenet/meta/val.txt` is required.

After checking [tutorial](https://mmclassification.readthedocs.io/en/latest/tutorials/new_dataset.html), I guess that `val.txt` should contain these lines:
```bash
ILSVRC2012_val_00000001.JPEG 65
ILSVRC2012_val_00000002.JPEG 970
ILSVRC2012_val_00000003.JPEG 230
ILSVRC2012_val_00000004.JPEG 809
ILSVRC2012_val_00000005.JPEG 516
```

Is there any script to convert it from `ILSVRC` ?

**Comment by tpoisonooo** [comment]
Would you please update it to `README.md` ?

**Comment by Ezra-Yu** [comment]
I will add a link to [this document](https://mmclassification.readthedocs.io/en/master/getting_started.html).
