### ISSUE TITLE
Using CNN-LSTM to classify time series images

### ISSUE THREAD

**Issue by greattBILL** [open-mmlab/mmclassification#859]
Your product is great, but I recently found that  CNN is not effective for classifying images with different periods, so I would like to ask how you can add CNN-LSTM to the library to make it possible to classify images with time series information. This would really be a huge improvement for timing  images! thank you very much.

**Comment by Ezra-Yu** [comment]
Do you deal with video data?

**Comment by greattBILL** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by greattBILL** [comment]
No, I use CNN to classify crop images with different growth periods

**Comment by Ezra-Yu** [comment]
Sorry, we currently have no plans to support such a task.

**Comment by greattBILL** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by greattBILL** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
