### ISSUE TITLE
Can I set different learning rates for different layers of the model?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#86]
for example,
optimizer:
resnet50.layer1.parameters(), lr＝lr/10
resnet50.layer2.parameters(), lr＝lr/5
resnet50.layer3.parameters(), lr＝lr/2
resnet50.layer4.parameters(), lr＝lr

Could you tell me how can I achieve it in mmdet？
thank you！

**Comment by mzr1996** [comment]
Duplicate of #46.
