### ISSUE TITLE
API documentation 打不开

### ISSUE THREAD

**Issue by grapefruitL** [open-mmlab/mmclassification#862]
在查看[使用文档](https://mmclassification.readthedocs.io/en/master/tutorials/finetune.html)时，内容里的[api文档链接](https://mmclassification.readthedocs.io/en/latest/api.html#module-mmcls.models.backbones)打不开

**Comment by mzr1996** [comment]
Please use this link https://mmclassification.readthedocs.io/en/master/api/models.html#backbones
We will fix it later.

**Comment by grapefruitL** [comment]
OK
