### ISSUE TITLE
ValueError: metric {'mAP'} is not supported.

### ISSUE THREAD

**Issue by yuluom** [open-mmlab/mmclassification#864]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

\[here\]

### Post related information

1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
   \[here\]
2. Your config file if you modified it or created a new one.

```python
[here]
```

3. Your train log file if you meet the problem during training.
   \[here\]
4. Other code you modified in the `mmcls` folder.
   \[here\]

**Comment by Ezra-Yu** [comment]
We are refactoring the code in this area and can wait for our subsequent updates

**Comment by Ezra-Yu** [comment]
Please refer to this [setting](https://github.com/open-mmlab/mmclassification/tree/dev/configs/csra). Note that both the dataset and head need to support mutil-label.
