### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (8x131072 and 25088x4096)

### ISSUE THREAD

**Issue by biel-jony** [open-mmlab/mmclassification#867]
Here is my dataset processing config

```
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

train_pipeline = [
    dict(type = 'LoadImageFromFile'),
    dict(type = 'Resize', size = (512, 512)),
    # dict(type = 'RandomFlip', flip_prob = 0.5, direction='horizontal'),
    dict(type = 'Normalize', **img_norm_cfg),
    dict(type = 'ImageToTensor', keys = ['img']),
    dict(type = 'ToTensor', keys = ['gt_label']),
    dict(type = 'Collect', keys = ['img', 'gt_label'])
]
test_pipeline = [
    dict(type = 'LoadImageFromFile'),
    dict(type = 'Resize', size = (512, 512)),
    dict(type = 'Normalize', **img_norm_cfg),
    dict(type = 'ImageToTensor', keys = ['img']),
    dict(type = 'Collect', keys = ['img'])
]

dataset_type = 'DATALOADER'
data = dict( 
            samples_per_gpu = 8, 
            workers_per_gpu = 2,
            train=dict(
                type = dataset_type,
                data_prefix = '/home/jony/workspace/Project/mmclassification/datasets/SRC-S1V2/train', #训练集路径
                pipeline = train_pipeline
            ),
            val=dict(
                type = dataset_type,
                data_prefix = '/home/jony/workspace/Project/mmclassification/datasets/SRC-S1V2/val',
                pipeline = test_pipeline
            ),
            test=dict(
                type = dataset_type,
                data_prefix = '/home/jony/workspace/Project/mmclassification/datasets/SRC-S1V2/test',   
                pipeline = test_pipeline
            )
        )

evaluation = dict(interval=1, 
                  metric='accuracy', 
                  metric_options = {'topk':(1,)},
                  save_best = "auto",)
```

It works ok on resnet50, but fails on Vgg16 unless resize is (224, 224).
I'm confused why is that ? 
Does Vgg16 only run with input sizes (224,224) ?

1. `pip list | grep "mmcv\|mmcls\|^torch"` 命令的输出
   \[填写这里\]
2. 如果你修改了，或者使用了新的配置文件，请在这里写明
```
_base_ = [
    '../_base_/default_runtime.py'
]


img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

train_pipeline = [
    dict(type = 'LoadImageFromFile'),
    dict(type = 'Resize', size = (512, 512)),
    # dict(type = 'RandomFlip', flip_prob = 0.5, direction='horizontal'),
    dict(type = 'Normalize', **img_norm_cfg),
    dict(type = 'ImageToTensor', keys = ['img']),
    dict(type = 'ToTensor', keys = ['gt_label']),
    dict(type = 'Collect', keys = ['img', 'gt_label'])
]
test_pipeline = [
    dict(type = 'LoadImageFromFile'),
    dict(type = 'Resize', size = (512, 512)),
    dict(type = 'Normalize', **img_norm_cfg),
    dict(type = 'ImageToTensor', keys = ['img']),
    dict(type = 'Collect', keys = ['img'])
]

dataset_type = 'DATALOADER'
data = dict( 
            samples_per_gpu = 8, 
            workers_per_gpu = 2,
            train=dict(
                type = dataset_type,
                data_prefix = '/home/jony/workspace/Project/mmclassification/datasets/SRC-S1V2/train', #训练集路径
                pipeline = train_pipeline
            ),
            val=dict(
                type = dataset_type,
                data_prefix = '/home/jony/workspace/Project/mmclassification/datasets/SRC-S1V2/val',
                pipeline = test_pipeline
            ),
            test=dict(
                type = dataset_type,
                data_prefix = '/home/jony/workspace/Project/mmclassification/datasets/SRC-S1V2/test',   
                pipeline = test_pipeline
            )
        )

evaluation = dict(interval=1, 
                  metric='accuracy', 
                  metric_options = {'topk':(1,)},
                  save_best = "auto",)


# model settings
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='VGG', depth=16, norm_cfg=dict(type='BN'), num_classes=2),
    neck=None,
    head=dict(
        type='ClsHead',
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, ),
    ))

# optimizer
optimizer = dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', step=[30, 60, 90])
runner = dict(type='EpochBasedRunner', max_epochs=100)
```

3. 如果你是在训练过程中遇到的问题，请填写完整的训练日志和报错信息
   Traceback (most recent call last):
  File "tools/train.py", line 203, in <module>
    main()
  File "tools/train.py", line 199, in main
    meta=meta)
  File "/home/jony/workspace/Project/mmclassification/mmcls/apis/train.py", line 240, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/home/jony/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jony/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/jony/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/jony/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/jony/workspace/Project/mmclassification/mmcls/models/classifiers/base.py", line 139, in train_step
    losses = self(**data)
  File "/home/jony/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jony/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/home/jony/workspace/Project/mmclassification/mmcls/models/classifiers/base.py", line 83, in forward
    return self.forward_train(img, **kwargs)
  File "/home/jony/workspace/Project/mmclassification/mmcls/models/classifiers/image.py", line 134, in forward_train
    x = self.extract_feat(img)
  File "/home/jony/workspace/Project/mmclassification/mmcls/models/classifiers/image.py", line 104, in extract_feat
    x = self.backbone(img)
  File "/home/jony/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jony/workspace/Project/mmclassification/mmcls/models/backbones/vgg.py", line 162, in forward
    x = self.classifier(x)
  File "/home/jony/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jony/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/jony/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jony/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/jony/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 1849, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (8x131072 and 25088x4096)

4. 如果你对 `mmcls` 文件夹下的代码做了其他相关的修改，请在这里写明
   \[填写这里\]

**Comment by Ezra-Yu** [comment]
If you want to use VGG in your own dataset. it would help if you modified [the classifier](https://github.com/open-mmlab/mmclassification/blob/58b21ee56ff193dced1a02efa81e73bb92347029/mmcls/models/backbones/vgg.py#L141) according to your data.

```
        if self.num_classes > 0:
            self.classifier = nn.Sequential(
                # 7 * 7 get from output of backbone is 224 * 224,  224 / 32, modify to H / 32, W / 32.
                nn.Linear(512 * 7 * 7, 4096),   
                nn.ReLU(True),
                nn.Dropout(),
                nn.Linear(4096, 4096),
                nn.ReLU(True),
                nn.Dropout(),
                nn.Linear(4096, num_classes),
            )
```

I will add this note to the documentation later.

**Comment by biel-jony** [comment]
> If you want to use VGG in your own dataset. it would help if you modified [the classifier](https://github.com/open-mmlab/mmclassification/blob/58b21ee56ff193dced1a02efa81e73bb92347029/mmcls/models/backbones/vgg.py#L141) according to your data.
> 
> ```
>         if self.num_classes > 0:
>             self.classifier = nn.Sequential(
>                 # 7 * 7 get from output of backbone is 224 * 224,  224 / 32, modify to H / 32, W / 32.
>                 nn.Linear(512 * 7 * 7, 4096),   
>                 nn.ReLU(True),
>                 nn.Dropout(),
>                 nn.Linear(4096, 4096),
>                 nn.ReLU(True),
>                 nn.Dropout(),
>                 nn.Linear(4096, num_classes),
>             )
> ```
> 
> I will add this note to the documentation later.

Thanks
