### ISSUE TITLE
How to take numpy arrays as input not image files?

### ISSUE THREAD

**Issue by wolfryu** [open-mmlab/mmclassification#871]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

Image file is value range 0 ~ 254 int type numpy arrays, and can be storaged as ".jpg, .png" image files.
However, I have CT images with value range -2000 ~ 4000, I can not save these into  ".jpg, .png" image files.
But mmclassification only supports image file as input.
Is there any way I can using numpy arrays as input?

**Comment by Ezra-Yu** [comment]
You can do that by implement your own CTDataset refer to [mmcls/datasets/cifar.py](https://github.com/open-mmlab/mmclassification/blob/master/mmcls/datasets/cifar.py),  which put loading image input dataset. the transforms will be a little different, such as https://github.com/open-mmlab/mmclassification/blob/58b21ee56ff193dced1a02efa81e73bb92347029/configs/_base_/datasets/cifar10_bs16.py#L7-L14

**Comment by wolfryu** [comment]
> 

Thank you so much!
