### ISSUE TITLE
There is a problem/bug with the acc calculation logic in swinTransformer

### ISSUE THREAD

**Issue by wangych6** [open-mmlab/mmclassification#874]
**Scenario:** 
```
My configuration file is swin_base_224_b16x64_300e_imagenet.py;
cfg.model.head.num_classes = 20;
cfg.data.samples_per_gpu = 3;
```

**When calculating acc, there will always be a dimension error:**
```
  File "/mmcls/models/losses/accuracy.py", line 116, in accuracy
    res = accuracy_torch(pred, target, topk, thrs)
  File "/mmcls/models/losses/accuracy.py", line 62, in accuracy_torch
    correct = pred_label.eq(target.view(1, -1).expand_as(pred_label))
```

RuntimeError: The expanded size of the tensor (3) must match the existing size (60) at non-singleton dimension 1. Target sizes: [1, 3]. Tensor sizes: [1, 60]

**This 60 is 3x20, I don't know why to use classes*samples, is this a bug, or is there something wrong with my settings?**

**Comment by mzr1996** [comment]
It's because the swin transformer enabled `Mixup` and `CutMix`. As the result, the `target` is transformed to one-hot format, and all these images and targets are mixed. Please disable the `cal_acc` in the head, because it is meaningless to calculate accuracy on these mixed images.
