### ISSUE TITLE
BatchCutMixLayer和BatchMixupLayer中，prob并没有起到作用，所有数据100%被cutmix和mixup

### ISSUE THREAD

**Issue by BokyLiu** [open-mmlab/mmclassification#875]
https://github.com/open-mmlab/mmclassification/blob/d2e505415040bf5329ab218bb6fe3d899f176cd5/mmcls/models/utils/augment/mixup.py#L80

https://github.com/open-mmlab/mmclassification/blob/d2e505415040bf5329ab218bb6fe3d899f176cd5/mmcls/models/utils/augment/cutmix.py#L175

是不是应该有,如:
```
if random<self.prob:
    return img, gt_label
else:
   return self.cutmix(img, gt_label)
```

**Comment by mzr1996** [comment]
是这样的，这里的 prob 只是用作记录概率，随机选取是在 https://github.com/open-mmlab/mmclassification/blob/master/mmcls/models/utils/augment/augments.py 中进行的。
后续我们会对这块的逻辑进行重构

**Comment by BokyLiu** [comment]
了解了，这里的prob代表选择Augments中某一个策略的概率
