### ISSUE TITLE
VOC2007 Train,  RuntimeError: Expected floating point type for target with class probabilities, got Char

### ISSUE THREAD

**Issue by Recialhot** [open-mmlab/mmclassification#880]
when I use the resnet50 to train VOC2007 datasets, it will appear 
![image](https://user-images.githubusercontent.com/64907763/175060907-f72790b9-15bc-4e5a-b983-ed45bfc28330.png)

voc_bs16.py:
![image](https://user-images.githubusercontent.com/64907763/175061194-0d675f24-7237-4d54-8b11-26cc5b0edc6c.png)

_base_ = [
    '../_base_/models/resnet50.py', '../_base_/datasets/voc_bs16.py',
    '../_base_/schedules/cifar10_bs128.py', '../_base_/default_runtime.py'
]

**Comment by Ezra-Yu** [comment]
VOC is a multi_label dataset, if you want to use it, you should use the multi_label head.

**Comment by Ezra-Yu** [comment]
Now, we have provided the mutil_label task config, please refer to [csra](https://github.com/open-mmlab/mmclassification/tree/dev/configs/csra)
