### ISSUE TITLE
How to use the model in another place?

### ISSUE THREAD

**Issue by gl94** [open-mmlab/mmclassification#883]
I've trained my custom cls model, and it works well. But how can I use the model in another palce? It's a part of my whole project which contains several models.
I used the publish_model.py to publish the state_dict and load_state_dict() it. But it doesn't work. The out is wrong.
![image](https://user-images.githubusercontent.com/26252750/175853634-30f028ce-deef-450c-bb51-afc82735f752.png)
![image](https://user-images.githubusercontent.com/26252750/175853777-9db028dc-f826-4fdc-b110-82665d3c5821.png)

**Comment by Ezra-Yu** [comment]
Do you mean using the `mmcls` as a 3rd package?

You can use the code in [demo](https://github.com/open-mmlab/mmclassification/blob/d2e505415040bf5329ab218bb6fe3d899f176cd5/demo/image_demo.py#L23) if you just want to inference in your project. If you want more than inference, you can learn [MMCls API](https://colab.research.google.com/github/open-mmlab/mmclassification/blob/master/docs/en/tutorials/MMClassification_tools.ipynb).

In your own project, fix the version of mmcls

**Comment by gl94** [comment]
> Do you mean using the `mmcls` as a 3rd package?
> 
> You can use the code in [demo](https://github.com/open-mmlab/mmclassification/blob/d2e505415040bf5329ab218bb6fe3d899f176cd5/demo/image_demo.py#L23) if you just want to inference in your project. If you want more than inference, you can learn [MMCls API](https://colab.research.google.com/github/open-mmlab/mmclassification/blob/master/docs/en/tutorials/MMClassification_tools.ipynb).
> 
> In your own project, fix the version of mmcls

Thank you, it works.
