### ISSUE TITLE
how to add custom sampler?

### ISSUE THREAD

**Issue by bmxbmx3** [open-mmlab/mmclassification#886]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

I want to make a custom sampler for my own dataset,is there a tutorial can help me to do this?

**Comment by Ezra-Yu** [comment]
refer to to [this file](https://github.com/open-mmlab/mmclassification/blob/master/mmcls/datasets/samplers/repeat_aug.py)

**Comment by bmxbmx3** [comment]
but I also want to know how to invoke this sampler in the config file?could you please show more details?Thanks.

**Comment by Ezra-Yu** [comment]
here is an [example](https://github.com/open-mmlab/mmclassification/blob/d2e505415040bf5329ab218bb6fe3d899f176cd5/configs/resnet/resnet50_8xb256-rsb-a1-600e_in1k.py#L26)

**Comment by Ezra-Yu** [comment]
> another question,if I want to train on distributed model,should I customize a sampler that inherits from DistributedSampler class or just from torch.utils.data.sampler.Sampler class?

No, we support the Distributed training, users do not need concern about samper.  Related code is [here](https://github.com/open-mmlab/mmclassification/blob/d2e505415040bf5329ab218bb6fe3d899f176cd5/mmcls/datasets/builder.py#L115), `DistributedSampler` have been implemented in `mmcv`.
