### ISSUE TITLE
如何增加RepOptVGG optimizer？

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmclassification#897]
初衷是为model增加一个自定义的optimizer（RepOptVGG）(https://github.com/DingXiaoH/RepOptimizers/blob/fab389c39b1b082fafba7268a3a7f7c10c8ee7b8/repoptvgg.py#L180)
1、该optimizer需要传入一个scales变量（需要读取模型导入），这个如何传入？自定义一个optimizer constructor 是否可以解决这个问题？
2、是否可以配置使得不同的模块匹配不同的optimizer，比如 backbone配置上述提到的自定义optimizer  neck使用sgd？

**Comment by Ezra-Yu** [comment]
1. 这里确实需要添加新的 optimizer, 可以参考 https://github.com/open-mmlab/mmclassification/blob/master/mmcls/core/optimizers/lamb.py
2. 可能只能通过添加新的 optimizer来实现。

**Comment by huoshuai-dot** [comment]
> 1. 这里确实需要添加新的 optimizer, 可以参考 https://github.com/open-mmlab/mmclassification/blob/master/mmcls/core/optimizers/lamb.py
> 2. 可能只能通过添加新的 optimizer来实现。

这里有个问题是 输入的参数不大能在cfg里面写出来的 事实上是从一个pretrained 模型里面取出来的 就需要在build optimizer之前load model，那这种情况的话 是要实现新的optimizer constructor以及optimizer吗？在optimizer constructor里面load model然后 获取scale 传给optimizer？

**Comment by Ezra-Yu** [comment]
可以换一个思路，可以通过前缀去区分组，这样scale可以为一个dict 在配置文件中设置。

在训练前，load checkpoint后的操作也是可以通过写hook来做的。

**Comment by Ezra-Yu** [comment]
如果你想复现RepVGG，可以联系我们，我们近期也有相关计划。

**Comment by huoshuai-dot** [comment]
> 如果你想复现RepVGG，可以联系我们，我们近期也有相关计划。

hello啊 我这边对比训练了下repvgg deploy mode 但是 结果一直是1% 感觉不太对，config文件如下
_base_ = [
    '../_base_/models/repvgg-A0_in1k.py', '../_base_/datasets/cifar100_bs16.py',
    '../_base_/schedules/cifar10_bs128.py', '../_base_/default_runtime.py'
]
model = dict(backbone=dict(arch='B1', deploy=True), head=dict(in_channels=2048, num_classes=100))
runner = dict(max_epochs=200)

optimizer = dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0005)
lr_config = dict(policy='step', step=[60, 120, 160], gamma=0.2)
结果如下：
![image](https://user-images.githubusercontent.com/74335389/178175886-49ae8306-895a-4a80-bf14-78212b39093d.png)
accuracy_top-1: 1.0000, accuracy_top-5: 5.0000
这是什么原因呢？麻烦帮我解答一下。

**Comment by Ezra-Yu** [comment]
deploy mode  是推理时使用的，训练时设置为False，默认为False

**Comment by huoshuai-dot** [comment]
> deploy mode 是推理时使用的，训练时设置为False，默认为False
那我想对照一下deploy这种直筒模型训练的结果 该怎么操作呢？

**Comment by twmht** [comment]
@huoshuai-dot 

請問有複製出論文的結果嗎?對於 detection 有想法嗎?

**Comment by huoshuai-dot** [comment]
> @huoshuai-dot
> 
> 請問有複製出論文的結果嗎?對於 detection 有想法嗎?

目前还没有，，，，
