### ISSUE TITLE
How to plot ROC curve?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#92]
Thank your for your amazing job!
I have a little question about the mmcls.
How to plot ROC curve and get Recall?
Thank you!

**Comment by zhongqiu1245** [comment]
I got it！ Use the test.py

**Comment by silverlining21** [comment]
Hi, I falied to find any piece code related to caculate ROC or AUC?  any hints would be appericated.

**Comment by serser** [comment]
For PR curve, I believe you could generate PR values according to specified thresholds,
```
python tools/test.py your_config.py work_dirs/your_config/best_accuracy_top-1_epoch_*.pth --metrics precision,recall --metric-options average_mode=none thrs='(0.1,0.2,0.3,0.4,0.5,0.65,0.8,0.9,0.95,0.97,0.985,0.99,0.995,0.999)'
```
