### ISSUE TITLE
How to change "in_channels" (input image channel) in config file?

### ISSUE THREAD

**Issue by wolfryu** [open-mmlab/mmclassification#925]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

I have "images" with 5 channels (loader as numpy array), but model default using 3 channels image.
How to change "in_channels" (input image channel) in config file?

### Post related information

1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
   \[here\]
2. Your config file if you modified it or created a new one.

```
_base_ = [
    '../_base_/models/mobilenet_v2_1x.py',
    '../_base_/schedules/imagenet_bs256_epochstep.py',
    '../_base_/default_runtime.py'
]
# ---- Model configs ----
# Here we use init_cfg to load pre-trained model.
# In this way, only the weights of backbone will be loaded.
# And modify the num_classes to match our dataset.

model = dict(
    backbone=dict(
        init_cfg = dict(
            type='Pretrained',
            checkpoint='https://download.openmmlab.com/mmclassification/v0/mobilenet_v2/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth',
            prefix='backbone'),
        # pad_small_map=True
        in_channels=5
    ),
    head=dict(
        num_classes=2,
        topk = (1, )
    ),
)

# ---- Dataset configs ----
# We re-organized the dataset as ImageNet format.
dataset_type = 'CustomDataset'
img_norm_cfg = dict(
     mean=[132.5028, 97.4147, 115.2442, 24.6812, 143.6917],
     std=[40.315, 62.0412, 33.2143, 45.6525, 219.5267],
     to_rgb=False)
```

3. Your train log file if you meet the problem during training.
```
Traceback (most recent call last):
  File "/home/123/anaconda3/envs/mmc/lib/python3.8/site-packages/mmcv/utils/registry.py", line 66, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'in_channels'

```
4. Other code you modified in the `mmcls` folder.
   \[here\]

**Comment by Ezra-Yu** [comment]
you need to modify [this line](https://github.com/open-mmlab/mmclassification/blob/d2e505415040bf5329ab218bb6fe3d899f176cd5/mmcls/models/backbones/mobilenet_v2.py#L168) in src code. We will refactor this place to make inputs dims modifiable.eg.
```
        self.conv1 = ConvModule(
            in_channels=5,
            out_channels=self.in_channels,
            kernel_size=3,
            stride=2,
            padding=1,
            conv_cfg=self.conv_cfg,
            norm_cfg=self.norm_cfg,
            act_cfg=self.act_cfg)

```

**Comment by wolfryu** [comment]
> you need to modify [this line](https://github.com/open-mmlab/mmclassification/blob/d2e505415040bf5329ab218bb6fe3d899f176cd5/mmcls/models/backbones/mobilenet_v2.py#L168) in src code. We will refactor this place to make inputs dims modifiable.eg.
> 
> ```
>         self.conv1 = ConvModule(
>             in_channels=5,
>             out_channels=self.in_channels,
>             kernel_size=3,
>             stride=2,
>             padding=1,
>             conv_cfg=self.conv_cfg,
>             norm_cfg=self.norm_cfg,
>             act_cfg=self.act_cfg)
> ```

Thank you so much!!!
