### ISSUE TITLE
NotImplementedError: This is a project in development

### ISSUE THREAD

**Issue by ke-dev** [open-mmlab/mmclassification#932]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

hi, developers, when I tried to use ```arc_face_head```, 

and I met the following error, 
and I already installed ```mmengine```

 ```
Traceback (most recent call last):
File "tools/train.py", line 6, in <module>
    from mmengine.config import Config, DictAction
  File "/opt/conda/lib/python3.7/site-packages/mmengine/__init__.py", line 1, in <module>
    raise NotImplementedError('This is a project in development')
NotImplementedError: This is a project in development
```

### Post related information

1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
```python
   
mmcls                  1.0.0rc0            /workspace/test_picture/arc_face_head/mmclassification-add-arcface
mmcv-full              1.6.0
torch                  1.8.1
torchelastic           0.2.0
torchtext              0.9.1
torchvision            0.9.1

```
2. The config file is
```
    head=dict(
        type='ArcFaceHead',
        num_classes=4,
        in_channels=768,
        init_cfg=None,  # suppress the default init_cfg of LinearClsHead.
        loss=dict(
            type='LabelSmoothLoss', label_smooth_val=0.1, mode='original'),
        cal_acc=False),
```
what should I do if I want to use  ```arc_face_head```,
looking forward to your reply

**Comment by Ezra-Yu** [comment]
Sorry that all the PRs with the tag `1.0rc`are under development and cannot be used yet. You need to wait for some days if using this version.

We will consider adding this feature to the current master branch as well. This will be seen soon.

**Comment by zzc98** [comment]
I implemented arcface head based on the master branch for image retrieval. The link is [arcface](https://github.com/zzc98/mmclassification/tree/add-arcface-master). I hope it can help you.

**Comment by ke-dev** [comment]
> I implemented arcface head based on the master branch. The link is [arcface](https://github.com/zzc98/mmclassification/tree/add-arcface-master). I hope it can help you.

wow! much appreciation! this is very helpful to me
