### ISSUE TITLE
resize mode question

### ISSUE THREAD

**Issue by dadada101** [open-mmlab/mmclassification#94]
hi：
 @ycxioooong  in the config file of imagenet, as follows:
![image](https://user-images.githubusercontent.com/69999981/100084296-8dd4e580-2e85-11eb-94cf-e8cd9cf4ca5e.png)
one way is use cv2.resize an anther way is the implementation in  pillow library ,I wonder the difference between them and any gap in the classification accuracy ?

**Comment by ycxioooong** [comment]
Hi @dadada101 sorry for my late reply. The only difference is that we use PIL as the backend in `RandomResizedCrop`. It will not affect the performance.

**Comment by ycxioooong** [comment]
Hi @dadada101, one correction: the performance would be affected by resize backend. Using OpenCV as resize backend will decrease the accuracy by 0.1% ~ 0.3% in our experience (R50, ImageNet) than using PIL.
