### ISSUE TITLE
如何给eval hook增加acc 精度的显示呢？

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmclassification#940]
默认的eval hook训练阶段只有loss 验证阶段只有acc，怎么样修改可以在训练中同时显示loss以及acc？

**Comment by Ezra-Yu** [comment]
Most heads have suppled the field of [`cal_acc`](https://github.com/open-mmlab/mmclassification/blob/71ef7bae854a9b85d83864f0e4af72c1e9fc7357/mmcls/models/heads/cls_head.py#L20). But if `cal_acc` is `True`, some train augments can not be used, such as MixUp.

the config should be like:
```
# model settings
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(3, ),
        style='pytorch'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=1000,
        in_channels=2048,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5),
        cal_acc=True.
    ))
```
