### ISSUE TITLE
Failed to load Swin Transformer pretrained model in mmdet v2.25.0

### ISSUE THREAD

**Issue by foolhard** [open-mmlab/mmclassification#945]
Hello, 

Thanks for greate job. 

I try to use Swin-B pretrained model in mmdet. 
If load the Swin-B pretrained model from official repo,  it can work. 
But, I failed to load the pretrained model from mmcls ( [https://download.openmmlab.com/mmclassification/v0/swin-transformer/convert/swin-base_3rdparty_in21k.pth](url) ）.

The error is `KeyError: 'backbone.stages.0.blocks.0.attn.w_msa.relative_position_bias_table'`.

Do you have any suggestion to use mmcls Swin Transformer model in mmdet?

### Post related information

1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
   \[mmcls                   0.23.0
mmcv-full               1.4.2
torch                   1.9.0
torchaudio              0.9.0a0+33b2469
torchvision             0.10.0\]

2. Your train log file if you meet the problem during training.
   \[Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 216, in main
    model.init_weights()
  File "/dfs/data/miniconda/envs/panoptic/lib/python3.7/site-packages/mmcv/runner/base_module.py", line 116, in init_weights
    m.init_weights()
  File "/dfs/data/open_mmlab/mmdet_panoptic/mmdet/models/backbones/swin.py", line 727, in init_weights
    table_current = self.state_dict()[table_key]
KeyError: 'backbone.stages.0.blocks.0.attn.w_msa.relative_position_bias_table'\]

**Comment by mzr1996** [comment]
Could you please provide your config file of model?

**Comment by foolhard** [comment]
Add my config file:

`_base_ = [
    '../_base_/models/mask_rcnn_r50_fpn.py',
    '../_base_/datasets/coco_instance.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]
# pretrained = 'https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth'  # noqa
pretrained = 'ckpts/swin-base_3rdparty_in21k.pth'
model = dict(
    type='MaskRCNN',
    backbone=dict(
        _delete_=True,
        type='SwinTransformer',
        embed_dims=128,
        depths=[2, 2, 18, 2],
        num_heads=[4, 8, 16, 32],
        window_size=7,
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.,
        attn_drop_rate=0.,
        drop_path_rate=0.2,
        patch_norm=True,
        out_indices=(0, 1, 2, 3),
        with_cp=False,
        convert_weights=True,
        init_cfg=dict(type='Pretrained', checkpoint=pretrained)
    ),
    neck=dict(in_channels=[128, 256, 512, 1024]))

optimizer = dict(
    _delete_=True,
    type='AdamW',
    lr=0.0001,
    betas=(0.9, 0.999),
    weight_decay=0.05,
    paramwise_cfg=dict(
        custom_keys={
            'absolute_pos_embed': dict(decay_mult=0.),
            'relative_position_bias_table': dict(decay_mult=0.),
            'norm': dict(decay_mult=0.)
        }))
lr_config = dict(warmup_iters=1000, step=[8, 11])
runner = dict(max_epochs=12)
`

**Comment by foolhard** [comment]
Add my config file as below:

> _base_ = [
    '../_base_/models/mask_rcnn_r50_fpn.py',
    '../_base_/datasets/coco_instance.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]
# pretrained = 'https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth'  # noqa
pretrained = 'ckpts/swin-base_3rdparty_in21k.pth'
model = dict(
    type='MaskRCNN',
    backbone=dict(
        _delete_=True,
        type='SwinTransformer',
        embed_dims=128,
        depths=[2, 2, 18, 2],
        num_heads=[4, 8, 16, 32],
        window_size=7,
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.,
        attn_drop_rate=0.,
        drop_path_rate=0.2,
        patch_norm=True,
        out_indices=(0, 1, 2, 3),
        with_cp=False,
        convert_weights=True,
        init_cfg=dict(type='Pretrained', checkpoint=pretrained)
    ),
    neck=dict(in_channels=[128, 256, 512, 1024]))

optimizer = dict(
    _delete_=True,
    type='AdamW',
    lr=0.0001,
    betas=(0.9, 0.999),
    weight_decay=0.05,
    paramwise_cfg=dict(
        custom_keys={
            'absolute_pos_embed': dict(decay_mult=0.),
            'relative_position_bias_table': dict(decay_mult=0.),
            'norm': dict(decay_mult=0.)
        }))
lr_config = dict(warmup_iters=1000, step=[8, 11])
runner = dict(max_epochs=12)

**Comment by foolhard** [comment]
Add my config file below:
_

> _base_ = [
>     '../_base_/models/mask_rcnn_r50_fpn.py',
>     '../_base_/datasets/coco_instance.py',
>     '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
> ]
> pretrained = 'ckpts/swin-base_3rdparty_in21k.pth'
> model = dict(
>     type='MaskRCNN',
>     backbone=dict(
>         _delete_=True,
>         type='SwinTransformer',
>         embed_dims=128,
>         depths=[2, 2, 18, 2],
>         num_heads=[4, 8, 16, 32],
>         window_size=7,
>         mlp_ratio=4,
>         qkv_bias=True,
>         qk_scale=None,
>         drop_rate=0.,
>         attn_drop_rate=0.,
>         drop_path_rate=0.2,
>         patch_norm=True,
>         out_indices=(0, 1, 2, 3),
>         with_cp=False,
>         convert_weights=True,
>         init_cfg=dict(type='Pretrained', checkpoint=pretrained)
>     ),
>     neck=dict(in_channels=[128, 256, 512, 1024]))
> 
> optimizer = dict(
>     _delete_=True,
>     type='AdamW',
>     lr=0.0001,
>     betas=(0.9, 0.999),
>     weight_decay=0.05,
>     paramwise_cfg=dict(
>         custom_keys={
>             'absolute_pos_embed': dict(decay_mult=0.),
>             'relative_position_bias_table': dict(decay_mult=0.),
>             'norm': dict(decay_mult=0.)
>         }))
> lr_config = dict(warmup_iters=1000, step=[8, 11])
> runner = dict(max_epochs=12)

_

**Comment by foolhard** [comment]
Sorry, my mistake to close the issue.

**Comment by mzr1996** [comment]
Move to #946
