### ISSUE TITLE
训练过程中val acc与 单独测试该模型 结果不一致的问题

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmclassification#948]
问题主要是：
训练阶段打印的val data acc如下图
![image](https://user-images.githubusercontent.com/74335389/182271977-082c35d1-fa12-4bf2-9db7-38bb57385ee9.png)
但是直接load 这个pth 使用dist_test.sh测试同样的数据 ，结果如下：
![image](https://user-images.githubusercontent.com/74335389/182272089-5ac92f55-39f2-479a-8712-68c4172462ba.png)
这两个本该完全一致的结果却完全不一致 这个问题该如何定位 希望社区同学可以提提意见？

**Comment by mzr1996** [comment]
Please provide your config of the dataset
请提供一下数据集相关的配置

**Comment by huoshuai-dot** [comment]
> Please provide your config of the dataset 请提供一下数据集相关的配置

# dataset settings
dataset_type = 'ImageNet'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomResizedCrop', size=224, backend='pillow'),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(256, -1), backend='pillow'),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
data = dict(
    samples_per_gpu=64,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        data_prefix='/data/_KJT_Workspace_HDD/_Data/imagenet/ILSVRC2012_img_train',
        # data_prefix='/data/_KJT_Workspace_HDD/_Data/imagenet/val',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        data_prefix='/data/_KJT_Workspace_HDD/_Data/imagenet/ILSVRC2012_img_val',
        ann_file='/data/_KJT_Workspace_HDD/_Data/imagenet/caffe_ilsvrc12/val.txt',
        pipeline=test_pipeline),
    test=dict(
        # replace `data/val` with `data/test` for standard test
        type=dataset_type,
        data_prefix='/data/_KJT_Workspace_HDD/_Data/imagenet/ILSVRC2012_img_val',
        ann_file='/data/_KJT_Workspace_HDD/_Data/imagenet/caffe_ilsvrc12/val.txt',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='accuracy')

**Comment by mzr1996** [comment]
Do you enable the EMA by `EMAHook`?

**Comment by huoshuai-dot** [comment]
> Do you enable the EMA by `EMAHook`?

···
2022-08-01 06:04:37,872 - mmcls - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) CosineAnnealingLrUpdaterHook
(NORMAL      ) CheckpointHook
(LOW         ) DistEvalHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_train_epoch:
(VERY_HIGH   ) CosineAnnealingLrUpdaterHook
(NORMAL      ) DistSamplerSeedHook
(LOW         ) IterTimerHook
(LOW         ) DistEvalHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_train_iter:
(VERY_HIGH   ) CosineAnnealingLrUpdaterHook
(LOW         ) IterTimerHook
(LOW         ) DistEvalHook
 --------------------
after_train_iter:
(ABOVE_NORMAL) DistOptimizerHook
(NORMAL      ) CheckpointHook
(LOW         ) IterTimerHook
(LOW         ) DistEvalHook
(VERY_LOW    ) TextLoggerHook
 --------------------
after_train_epoch:
(NORMAL      ) CheckpointHook
(LOW         ) DistEvalHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_val_epoch:
(NORMAL      ) DistSamplerSeedHook
(LOW         ) IterTimerHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_val_iter:
(LOW         ) IterTimerHook
 --------------------
after_val_iter:
(LOW         ) IterTimerHook
 --------------------
after_val_epoch:
(VERY_LOW    ) TextLoggerHook
 --------------------
after_run:
(VERY_LOW    ) TextLoggerHook
···
以上是运行时调用的所有的hook，并没有调用EMAHook，

**Comment by mzr1996** [comment]
Ok, please provide your train command and test command, and I will try to reproduce the problem.

**Comment by huoshuai-dot** [comment]
> Ok, please provide your train command and test command, and I will try to reproduce the problem.

我这个主要是在复现RepOptVGG 训练的时候出现的问题，复现中改动了两处处：
1、修改了RepOptVGG的backbone，也是基于repvgg的小改动；
2、增加了RepOptVGG 优化器
我觉得出现这个没对齐的问题大概率是我修改的地方存在某些问题，
如果您这边方便的话 您给我一个联系方式，我可以把我改动过的文件发给您 帮我分析一下

**Comment by mzr1996** [comment]
你可以扫描这个二维码，联系她加 mmcls 的群组
https://github.com/open-mmlab/mmcv/raw/master/docs/en/_static/wechat_qrcode.jpg
