### ISSUE TITLE
Why is the performance of CSPNet much higher than that of the paper？

### ISSUE THREAD

**Issue by ioir123ju** [open-mmlab/mmclassification#951]
![image](https://user-images.githubusercontent.com/14951957/182511488-e8babd85-f082-48b3-9fe5-05451257a471.png)

**Comment by mzr1996** [comment]
These checkpoints are converted from [pytorch-image-models](https://github.com/rwightman/pytorch-image-models), not official checkpoints.
They re-trained these models with new tricks like `RandAugment` and get a higher score. The detailed training recipe maybe like [the Swin-Transformer recipe](https://github.com/open-mmlab/mmclassification/blob/71ef7bae854a9b85d83864f0e4af72c1e9fc7357/configs/swin_transformer/swin-small_16xb64_in1k.py)
