### ISSUE TITLE
how to customize normalization

### ISSUE THREAD

**Issue by MARUIHAN123** [open-mmlab/mmclassification#961]
推荐使用英语模板 Feature request，以便你的问题帮助更多人。

### 描述这个功能

\[填写这里\]

### 动机

请简要说明以下为什么需要添加这个新功能
例 1. 现在进行 xxx 的时候不方便
例 2. 最近的论文中提出了有一个很有帮助的 xx

\[填写这里\]

### 相关资源

是否有相关的官方实现或者第三方实现？这些会很有参考意义。

\[填写这里\]

### 其他相关信息

其他和这个功能相关的信息或者截图，请放在这里。
另外如果你愿意参与实现这个功能并提交 PR，请在这里说明，我们将非常欢迎。

\[填写这里\]

**Comment by Ezra-Yu** [comment]
You can refer to this class to customize your [normailzation](
https://github.com/open-mmlab/mmclassification/blob/90254a845540650bd03bc2b6108251825935c687/mmcls/datasets/pipelines/transforms.py#L880),

If you want to modify the config, just refer to API of this class.
