### ISSUE TITLE
预测类别不对应，但是准确率很高。

### ISSUE THREAD

**Issue by MARUIHAN123** [open-mmlab/mmclassification#962]
预测类别不对应，但是准确率很高
比如 我的数据集有文件类别1，2，3
预测时，类别一中的图片被预测为3，但是准确率很高。

**Comment by MARUIHAN123** [comment]
The prediction categories do not correspond, but the accuracy is very high
for example,  my dataset has file categories 1,2,3
When predicting, the picture in category 1 is predicted to be 3, but with high accuracy.

**Comment by Ezra-Yu** [comment]
you can use this [tool](https://github.com/open-mmlab/mmclassification/blob/master/tools/visualizations/vis_pipeline.py) to check the dataset.

**Comment by mzr1996** [comment]
Please try to calculate the confusion matrix according to the comment https://github.com/open-mmlab/mmclassification/issues/598#issuecomment-992064599

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.

**Comment by batchor** [comment]
Probably your categories are highly unbalanced.
