### ISSUE TITLE
can not reproduce accuracy of the resnest

### ISSUE THREAD

**Issue by lixincn2015** [open-mmlab/mmclassification#97]
Will you release the training config of resnest?
How to reproduce resnset50 with top-1 81.13% (model zoo)?

**Comment by fupingren** [comment]
拭目以待

**Comment by GitHubChrischen** [comment]
resnet 我也无法复现， 
resnet can't reproduce accuracy too

**Comment by mzr1996** [comment]
> Will you release the training config of resnest?
> How to reproduce resnset50 with top-1 81.13% (model zoo)?



> resnet 我也无法复现，
> resnet can't reproduce accuracy too

Please provide your entire train log, thx

**Comment by tonysy** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you still encounter this issue with the latest stable version. You can also contribute directly by creating a PR

Thank you!
