### ISSUE TITLE
[Bug]AttributeError: 'ConfigDict' object has no attribute 'device'

### ISSUE THREAD

**Issue by wuhongsheng** [open-mmlab/mmclassification#974]
推荐使用英语模板 Bug report，以便你的问题帮助更多人。

### 描述 bug

我微调分类模型
import time
import mmcv
import os.path as osp

from mmcls.datasets import build_dataset
from mmcls.models import build_classifier
from mmcls.apis import train_model

# 创建工作目录
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
# 创建分类器
model = build_classifier(cfg.model)
model.init_weights()
# 创建数据集
datasets = [build_dataset(cfg.data.train)]
# 添加类别属性以方便可视化
model.CLASSES = datasets[0].CLASSES
# 开始微调
train_model(
    model,
    datasets,
    cfg,
    distributed=False,
    validate=True,
    timestamp=time.strftime('%Y%m%d_%H%M%S', time.localtime()),
    meta=dict())

### 复现流程

在命令行中执行的详细操作

```shell

```

### 相关信息

1. `pip list | grep "mmcv\|mmcls\|^torch"` 命令的输出
mmcls                         0.23.2                       /content/mmclassification
mmcv                          1.6.1
torch                         1.12.1+cu113
torchaudio                    0.12.1+cu113
torchsummary                  1.5.1
torchtext                     0.13.1
torchvision                   0.13.1+cu113
2. 如果你修改了，或者使用了新的配置文件，请在这里写明

```python
#@title 默认标题文本
# 载入已经存在的配置文件
from mmcv import Config
cfg = Config.fromfile('configs/resnet/resnet18_8xb32_in1k.py')


# 修改模型分类头中的类别数目
cfg.model.head.num_classes = 4
cfg.model.head.topk = (1, )

# 加载预训练权重
cfg.model.backbone.init_cfg = dict(type='Pretrained', checkpoint=checkpoint_file, prefix='backbone')

# 根据你的电脑情况设置 sample size 和 workers 
cfg.data.samples_per_gpu = 32
cfg.data.workers_per_gpu = 2

# 指定训练集路径
cfg.data.train.data_prefix = '/content/drive/MyDrive/datasets/ADE20K_OUTDOORS/images/train'
cfg.data.train.classes = '/content/drive/MyDrive/datasets/ADE20K_OUTDOORS/images/classes.txt'

# 指定验证集路径
cfg.data.val.data_prefix = '/content/drive/MyDrive/datasets/ADE20K_OUTDOORS/images/val'
#cfg.data.val.ann_file = 'data/cats_dogs_dataset/val.txt'
cfg.data.val.classes = '/content/drive/MyDrive/datasets/ADE20K_OUTDOORS/images/classes.txt'

# 指定测试集路径
cfg.data.test.data_prefix = '/content/drive/MyDrive/datasets/ADE20K_OUTDOORS/images/test'
#cfg.data.test.ann_file = 'data/cats_dogs_dataset/test.txt'
cfg.data.test.classes = '/content/drive/MyDrive/datasets/ADE20K_OUTDOORS/images/classes.txt'

# 设定数据集归一化参数
normalize_cfg = dict(type='Normalize', mean=[124.508, 116.050, 106.438], std=[58.577, 57.310, 57.437], to_rgb=True)
cfg.data.train.pipeline[3] = normalize_cfg
cfg.data.val.pipeline[3] = normalize_cfg
cfg.data.test.pipeline[3] = normalize_cfg

# 修改评价指标选项
cfg.evaluation['metric_options']={'topk': (1, )}

# 设置优化器
cfg.optimizer = dict(type='SGD', lr=0.005, momentum=0.9, weight_decay=0.0001)
cfg.optimizer_config = dict(grad_clip=None)

# 设置学习率策略
cfg.lr_config = dict(policy='step', step=1, gamma=0.1)
cfg.runner = dict(type='EpochBasedRunner', max_epochs=2)

# 设置工作目录以保存模型和日志
cfg.work_dir = './work_dirs/orientation_dataset'

# 设置每 10 个训练批次输出一次日志
cfg.log_config.interval = 10

# 设置随机种子，并启用 cudnn 确定性选项以保证结果的可重复性
from mmcls.apis import set_random_seed
cfg.seed = 0
set_random_seed(0, deterministic=True)

cfg.gpu_ids = range(1)
```

3. 如果你是在训练过程中遇到的问题，请填写完整的训练日志和报错信息
   \[填写这里\]
4. 如果你对 `mmcls` 文件夹下的代码做了其他相关的修改，请在这里写明
   \[填写这里\]

### 附加内容

任何其他有关该 bug 的信息、截图等

\[填写这里\]

**Comment by mzr1996** [comment]
Please add the following code before call `train_model`
```python
from mmcls.utils import auto_select_device

cfg.device = auto_select_device()
```

**Comment by wuhongsheng** [comment]
> Please add the following code before call `train_model`
> 
> ```python
> from mmcls.utils import auto_select_device
> 
> cfg.device = auto_select_device()
> ```
thank you

**Comment by zanetsc** [comment]
Could you please update the demo: MMClassification_python.ipynb by adding this:  

from mmcls.utils import auto_select_device
cfg.device = auto_select_device()
