### ISSUE TITLE
Can I get epoch number in head files during training?

### ISSUE THREAD

**Issue by ChengHan111** [open-mmlab/mmclassification#982]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

Can I get epoch number during training in head files? I want to implement some changes during training on specific epoch.

### Post related information

1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
mmcls                        0.18.0         self/mmclassification
mmcv-full                    1.4.1
torch                        1.8.1
torchaudio                   0.8.0a0+e4e171a
torchfile                    0.1.0
torchvision                  0.9.1
2. Your config file if you modified it or created a new one.

No modifications on config, using default settings

3. Your train log file if you meet the problem during training.
-----
4. Other code you modified in the `mmcls` folder.
-----

**Comment by Ezra-Yu** [comment]
> Can I get epoch number during training in head files? I want to implement some changes during training on specific epoch.

what are your changes during the training? change the transforms, the datasets, or the model? If you want to do those kind of jobs, you need to implement your customer hook refer to [this guide](https://mmclassification.readthedocs.io/en/latest/tutorials/runtime.html#customize-self-implemented-hooks).

**Comment by ChengHan111** [comment]
Awesome! Thanks for your reply. I will have a try on that

**Comment by ChengHan111** [comment]
Just an update, I take the epoch from mmcv, store it in a global memory, and applied to the head for solving this problem. It is really a stupid approach but intuitive. Not very sure this will influence the training speed or not. 
Here is the code I applied...
`
def _init():  
    global _global_dict
    _global_dict = {}

def set_value(key, value):
    _global_dict[key] = value

def get_value(key):
    try:
        return _global_dict[key]
    except:
        pass
`
