### ISSUE TITLE
[Bug] LabelSmoothLoss loss_weight is not work.

### ISSUE THREAD

**Issue by 274869388** [open-mmlab/mmclassification#983]
### Describe the bug

LabelSmoothLoss loss_weight is not work. 
https://github.com/open-mmlab/mmclassification/blob/90254a845540650bd03bc2b6108251825935c687/mmcls/models/losses/label_smooth_loss.py#L63

**Comment by tonysy** [comment]
Hi, thanks for your report. While, would you like to describe more details of the bug, like what case you use? Thanks.

**Comment by Ezra-Yu** [comment]
we have fixed it in the https://github.com/open-mmlab/mmclassification/pull/1058 .
