### ISSUE TITLE
How to load an img in gray scale mode

### ISSUE THREAD

**Issue by q671383789** [open-mmlab/mmclassification#995]
Hey, I'm using to classify imgs in grayscale(1 channel) and color(3 channels)
I want to let them all input as grayscale. But I can't find where the code u guys use to read img from file.

**Comment by tonysy** [comment]
Hi,
you can change the color mode in config like:
```
train_pipeline = [
    dict(type='LoadImageFromFile', color='grayscale'),
    dict(type='RandomResizedCrop', size=224, backend='pillow'),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
```

Actually, we use the image reading function of `mmcv` in https://github.com/open-mmlab/mmclassification/blob/90254a845540650bd03bc2b6108251825935c687/mmcls/datasets/pipelines/loading.py#L49

You can also refer 
https://github.com/open-mmlab/mmcv/blob/a08517790d26f8761910cac47ce8098faac7b627/mmcv/image/io.py#L33
for more details.

Thanks for your question, we will add how to change the color type in documentation.

**Comment by q671383789** [comment]
LoadImageFromFile.__init__() got an unexpected keyword argument 'color'
my mmcv_version == 1.47.1 is that the reason?
and I can't run swin_transformer whenever I run it the gt_label become [bs, 1000] and I use the same dataset config resnet can run correct


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmclassification"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月25日(星期四) 下午5:37
***@***.***&gt;;
抄送:&nbsp;"系要听Rock &amp; ***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmclassification] How to load an img in gray scale mode (Issue #995)





 
Hi,
 you can change the color mode in config like:
 train_pipeline = [     dict(type='LoadImageFromFile', color='grayscale'),     dict(type='RandomResizedCrop', size=224, backend='pillow'),     dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),     dict(type='Normalize', **img_norm_cfg),     dict(type='ImageToTensor', keys=['img']),     dict(type='ToTensor', keys=['gt_label']),     dict(type='Collect', keys=['img', 'gt_label']) ]  
Actually, we use the image reading function of mmcv in https://github.com/open-mmlab/mmclassification/blob/90254a845540650bd03bc2b6108251825935c687/mmcls/datasets/pipelines/loading.py#L49
 
You can also refer
 https://github.com/open-mmlab/mmcv/blob/a08517790d26f8761910cac47ce8098faac7b627/mmcv/image/io.py#L33
 for more details.
 
Thanks for your question, we will add how to change the color type in documentation.

**Comment by q671383789** [comment]
@tonysy Hi, actually I have update my mmcv and mmcls again but this still happens
![image](https://user-images.githubusercontent.com/48686306/186797546-f9b62803-a5d9-4583-9008-83e05b12acfd.png)

**Comment by q671383789** [comment]
@tonysy  I have solved this using color_type 
seems like the api has changed but thx!
